game.stored_db.bar_en = [{type:"1",text:"%s, if you're running on flavored beer, you drink. Give out one sip otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, if you're running on a can of beer, drink. Give out one sip otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, if you're running on a pitcher of beer, you drink. Give out one sip otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, go take the worst shot in the bar",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"The last one to have been to a bar, give out 2 sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"The last one to arrive, give out 2 sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"The last one to have been to a bar, drinks",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"The last one to arrive, drinks",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"The player who has paid the least so far, drinks",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"The player who has paid the most so far, give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"%s, if coming here was your idea, give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, if doing a Picolo Bar was your idea, give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, drink as many sips as the number of Picolo challenges you have failed today. None? Drink anyway",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, drink as many sips as the number of successful Picolo challenges today",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, drink as many sips as the number Picolo challenges you have completed today. None? Drink anyway",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, drink as many sips as the number of refused Picolo challenges today",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, drink as many sips as the number of Picolo challenges you have refused today. None? Bravo! Give out one sip",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, if you have a coin, put it in the player's glass who will have to drink $ sips. Drink $ sips if you don't have one",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s and %s compare their glasses: the player with the fullest drink, pours some into the other one",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"1",text:"%s and %s compare their glasses: the player with the fuller glass will drink until the amount in both glasses is even",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"1",text:"%s, go ask for straws for everyone please",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"First one to take a sh*t in the toilets without flushing, can order someone to down their drink!",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"%s, the next person you touch, has to drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, make someone drink if you've been to multiple bars today. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, make someone drink if you've talked to the server today. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, make someone drink if you've paid for something today. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, make someone drink if there are waitresses around. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, make someone drink if you've been to this bar before. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, make someone drink if you've never been to this bar before. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, make someone drink if you know other people in the bar besides the ones playing. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"If there are other people playing Picolo in this bar, you'll have to offer them a drink. Otherwise everyone drinks!",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"%s, make someone drink if you've picked someone up at this bar before. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, choose someone to finish their drink if you've got an ex roaming around. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, drink if you've ever slept with a barman or barmaid. Give out one sip otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, drink if you've ever slept with a waiter or waitress. Give out one sip otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, give out as many sips as there are weirdos in this bar, except your friends",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, give out as many sips as there are hot girls in this bar, except your friends",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, give out as many sips as there are bald men in this bar, except your friends",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, give out as many sips as there are people with glasses in this bar, except your friends",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, choose someone close. At your beep\u0022 if this stranger doesn't speak within 7 seconds you can give out $ sips. Drink otherwise\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, choose someone close. At your beep\u0022 if this stranger stays in the same position within 7 seconds you can give out $ sips. Drink otherwise\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, choose someone close. At your beep\u0022 if this stranger doesn't look towards you within 12 seconds you can give out $ sips. Drink otherwise\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, choose someone close. At your beep\u0022 if this stranger stands up within 15 seconds you can give out $ sips. Drink otherwise\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, choose someone close. At your beep\u0022 if this stranger sits down within 15 seconds you can give out $ sips. Drink otherwise\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, choose someone close. At your beep\u0022 if this stranger laughs within 7 seconds you can give out $ sips. Drink otherwise\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, choose someone close. At your beep\u0022 if this stranger smiles within 4 seconds you can give out $ sips. Drink otherwise\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, choose someone close. At your beep\u0022 if this stranger drinks within 7 seconds you can give out $ sips. Drink otherwise\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, choose someone close. At your beep\u0022 if this stranger does not drink within 10 seconds you can give out $ sips. Drink otherwise\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, choose someone close. At your beep\u0022 if this stranger does not smile within 5 seconds you can give out $ sips. Drink otherwise\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, choose someone close. At your beep\u0022 if this stranger does not laugh within 10 seconds you can give out $ sips. Drink otherwise\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, choose someone close. At your beep\u0022 if this stranger orders within 30 seconds you can give out $ sips. Drink otherwise\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s and %s, may the force be with you. Choose a stranger nearby each, your Padawan. The one whose Padawan talks first, gives out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"1",text:"%s and %s, may the force be with you. Choose a stranger nearby each, your Padawan. The one whose Padawan orders first, gives out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"1",text:"%s and %s, may the force be with you. Choose a stranger nearby each, your Padawan. The one whose Padawan smokes first, gives out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"1",text:"%s and %s, may the force be with you. Choose a stranger nearby each, your Padawan. The one whose Padawan goes to the bathroom first, gives out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"1",text:"%s and %s, may the force be with you. Choose a stranger nearby each, your Padawan. The one whose Padawan smiles first, gives out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"1",text:"%s and %s, may the force be with you. Choose a stranger nearby each, your Padawan. The one whose Padawan laughs first, gives out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"1",text:"The first one who ordered will gently drink 2 sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"The last one to have ordered, it's time to catch up to your buddies, drink 2 sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"%s, if you shook hands or hugged a staff member, you drink. Make someone drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, if you have a coaster, make someone drink, Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, if this is your favorite bar, own up and drink. Otherwise you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, give out $ sips if you've been here more than 3 times. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, give out $ sips if you've been here more than one year ago. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, give out $ sips if you've ever argued with someone here. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, give out $ sips if you've ever been wasted here. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, give out $ sips if you've ever come here with your boyfriend or girlfriend. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, give out $ sips if you've ever come here while single. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, give out $ sips if you've ever talked to the waiters since you're so used to this place. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, if you started the night with a soda, drink you shameful one. Otherwise, make someone drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, make someone drink if you've ever puked after leaving this place. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"First one to find a couple, gives out $ sips. None? Everybody drinks!",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"First one to find a couple that seems bored, gives out $ sips. None? Everybody drinks!",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"First one to find a laughing guy, gives out $ sips. None? Everybody drinks!",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"First one to find a girl wearing a dress, gives out $ sips. None? Everybody drinks!",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"First one to find a shot, gives out $ sips. None? Everybody drinks!",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"First one to find an empty beer, gives out $ sips. None? Everybody drinks!",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"First one to find an animal, gives out $ sips. None? Everybody drinks!",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"First one to find an empty table, gives out $ sips. None? Everybody drinks!",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"First one to find a group of four guys, give out $ sips. None? Everybody drinks!",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"If you're in the outside seating area, %s can give out one sip. If you're inside, %s drinks",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"1",text:"If you all came at the same time, %s you drink. If there were some delayed, it'll be %s",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"1",text:"%s, if you were the first one to arrive you can give out $ sips, otherwise drink. Hope that will teach you",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"%s, either you were the last one to come and you drink $ sips, or you can give out one sip",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"Those who have already said something like I forgot my card -- can someone spot me?\u0022 you drink $ sips\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"Those who've complained about being at this bar, drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"Those who weren't so excited about being a part of this night out tonight, drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"1",text:"%s, if you've ever tried a Picolo Bar\u0022 challenge you can give out $ sips. You'll drink if you failed anyway\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"1",text:"Is it happy-hour time? Yes, %s drinks. No, let's make %s drink instead",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"1",text:"If there isn't music here, %s that's your fault, drink one sip. If there is, drink twice",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, you're Mister Coffee. Go and ask for a coffee. There's no way you're allowed to drink it! Keep it for later...",key:"coffee",parent_key:"",pack_name:"bar",language:"en",nb_players:"3"},
{type:"2",text:"%s can now share the coffee, equally or not, in %s's and %s's glasses",key:"",parent_key:"coffee",pack_name:"bar",language:"en",nb_players:"3"},
{type:"2",text:"%s, choose in which glass you'll pour your cold coffee",key:"",parent_key:"coffee",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, you'll be able to put all of your coffee in your glass... Enjoy!",key:"",parent_key:"coffee",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, Snap the beat of the song! Have $ sips for each new song otherwise",key:"click-finger",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, you can stop snapping your fingers",key:"",parent_key:"click-finger",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, go drink alone at the bar",key:"alone-at-the-bar",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s can come back",key:"",parent_key:"alone-at-the-bar",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, be a weirdo please: let some howls out from time to time, like you're a total idiot. You'll be able to give out one sip for each one",key:"I-assume-mongolito",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, weirdo time is over",key:"",parent_key:"I-assume-mongolito",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, you'll drink with 3 straws from now on, or that'll be one sip for each new rule",key:"3-straws",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, you can stop sucking with you straws",key:"",parent_key:"3-straws",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, choose your favorite waiter. As soon as he serves a drink, let out a fart with your mouth, or drink one sip",key:"choose-waiter",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, stop mouth-farting, it's embarassing",key:"",parent_key:"choose-waiter",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, you're such a social butterfly! Say hi\u0022 to each person who passes by. One sip for each forgotten \u0022hi\u0022\u0022",key:"hypersocial",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, you're done with your social mania",key:"",parent_key:"hypersocial",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, find a tampon and tuck it over your ear. That's so classy!",key:"tampon-ear",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, take off your tampon, you're not bleeding anymore!",key:"",parent_key:"tampon-ear",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, you're punished! Go sulk in the corner. If people talk to you, you're only able to say I AM PUNISHED\u0022\u0022",key:"punition",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s can come back! Or not, you can simply pass the rule ;)",key:"",parent_key:"punition",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, stay under the table. We'll tell when you can come back",key:"under-the-table",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s can join us! (Or we can act like there was a bug and this rule never showed up)",key:"",parent_key:"under-the-table",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, choose a girl nearby. As soon as she drinks, let out a woooo\u0022\u0022",key:"choose-your-partner",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, stop embarrasing the girl next door!",key:"",parent_key:"choose-your-partner",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, choose a nearby stranger. While your chosen one speaks, you must say blah blah blah blah blah\u0022\u0022",key:"speak-when-other-speak",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"2",text:"%s, leave this person alone",key:"",parent_key:"speak-when-other-speak",pack_name:"bar",language:"en",nb_players:"1"},
{type:"4",text:"Coin game from now on! %s, take a coin and drop it in someone's glass. Targeted one will take $ sips, and will be able to drop the coin in any glass, etc.",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"4",text:"Let's put a pack of cigarettes on the edge of the table, each one tries in turn to make it flip one time. Losers drink, winners give out one sip. %s you start",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"4",text:"Let's put a coin on the edge of the table, each person tries in turn to flip the coin to the opposite side in one hit. The closest to the edge, gives out $ sips. %s you start",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"4",text:"Pop quiz! The first one to guess the title of the song, can give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"4",text:"%s, choose a sentence and whisper it once only to the person to your left. No one must hear it but your listener. Continue until the sentence comes backs to you. The players who didn't whisper the correct sentence, drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"4",text:"%s, spin a coin on the table. Taking turns, flick the coin with your finger to keep it spinning. The first one to loose, drinks $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"4",text:"Pop quiz! The first player to name the singer of the current song, gives out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"4",text:"Pop quiz! The first player to name the singer of the previous song, gives out $ sips. No one? Everyone drinks!",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"4",text:"Let's play a game of pick-up sticks with about twenty cigarettes. Each cigarette taken according to the rules, allows a sip to be given! %s starts",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"16",text:"Go around the room and guess who the hottest girl here is according to %s. First one to guess right, gives out $ sips! %s starts",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"16",text:"Go around the room and guess who the most handsome man here is according to %s. First one to guess right, gives out $ sips! %s starts",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"16",text:"Go around the room and guess who the easiest lay here is according to %s. First one to guess right, gives out $ sips! %s starts",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"16",text:"Go around the room and guess who the ugliest girl here is according to %s. First one to guess right, gives out $ sips! %s starts",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"16",text:"Go around the room and guess who the most sex-starved man here is according to %s. First one to guess right, gives out $ sips! %s starts",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"16",text:"Go around the room and guess who the ugliest man here is according to %s. First one to guess right, gives out $ sips! %s starts",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"16",text:"Go around the room and guess what the best alcohol in the bar is according to %s. First one to guess right, gives out $ sips! %s starts",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"16",text:"Go around the room and guess what the best beer here is according to %s. First one to guess right, gives out $ sips! %s starts",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"16",text:"Go around the room and guess who the horniest girl here is according to %s. First one to guess right, gives out $ sips! %s starts",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"16",text:"Go around the room and guess what bar downtown is the best according to %s. First one to guess right, gives out $ sips! %s starts",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"16",text:"Go around the room and guess what club downtown is the best according to %s. First one to guess right, gives out $ sips! %s starts",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"16",text:"Go around the room and guess what place downtown is the best to pick up a girl according to %s. First one to guess right, gives out $ sips! %s starts",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"16",text:"Go around the room and guess what song is currently the best according to %s. First one to guess right, gives out $ sips! %s starts",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"17",text:"%s, you've been chosen to order the next round and you're not allowed to use the verbs have\u0022 \u0022take\u0022 \u0022get\u0022 or \u0022order\u0022\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"17",text:"%s and %s, order at the same time. The first one to be served, will give out $ sips. The loser will drink them",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"17",text:"%s, go ask for an appetizer for everyone please",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"17",text:"%s, take your wallet out... next round's on you!",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"17",text:"%s, make a gift to %s: let them name their favorite cocktail",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"17",text:"Let's get crazy... %s buys a round of shots for everyone!",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"17",text:"Just so you know, last one to finish their drink will buy the next round...",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"17",text:"%s, if someone still has some balls, buy him/her a shot",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"17",text:"%s offers a beer! It'll be for %s or %s, whoever finishes their drink first",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"3"},
{type:"17",text:"%s offers a drink! %s, tell him/her what you want",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"17",text:"%s, buy a drink for a stranger chosen by %s",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"17",text:"Would you rather drink a dozen shots or some mojitos? Vote at the same time. Losing group buys the winning answer for the next round",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"17",text:"Would you rather drink dark or light beers? Vote at the same time. Losing group buys the winning answer for the next round",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"17",text:"Would you rather drink some beers or something else? Vote at the same time. Losing group buys the winning answer for the next round",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"0"},
{type:"17",text:"%s, either you down 6 drinks in a row, or the next round is on you",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"17",text:"%s, you decide who, between %s and %s, will buy next round",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"3"},
{type:"17",text:"%s, you decide who will buy the next round",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"17",text:"%s, you're such a princess! You can choose anyone to buy you a drink. The person and type of drink is up to you",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go bum a condom or drink off someone",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go bum a cigarette or drink off someone",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go ask any stranger if he/she knows Picolo. If that's the case you give out $ sips. Otherwise you drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, try to guess the age of a stranger chosen by %s. Ask him/her. If you win, you give out $ sips. Otherwise you drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"18",text:"%s, try to guess the height of a stranger chosen by %s. Ask him/her. If you win, you give out $ sips. Otherwise you drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"18",text:"%s, try to guess the bra size of a female you don't know, chosen by %s. Ask him/her. If you win, you give out $ sips. Otherwise you drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"18",text:"%s, try to guess the shoe size of a stranger chosen by %s. Ask him/her. If you win, you give out $ sips. Otherwise you drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"18",text:"%s, choose a stranger. If he/she is single, you can give out $ sips. Drink otherwise. And yes, someone has to check",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, let %s choose a stranger. Try to guess at what time she/he arrived at the bar. You can give out $ sips if you win. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"18",text:"%s, go suggest a song to the DJ. A refusal means one sip. You can give out $ sips if they accept",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go ask the DJ to lower the volume or drink $ sips. Challenge successful? You can give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go ask the DJ to turn it up or drink $ times. Challenge successful? You can give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, tell a stranger a joke. Any smile is a victory! You'll be able to give out $ sips. If you refuse or fail, drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, annoy a group of people you don't know by showing them a picture of a fly, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, annoy a group of people you don't know by showing them a picture of a dinosaur, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, annoy a group of people you don't know by showing them a picture of a sauerkraut, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, annoy a group of people you don't know by asking them if they want to buy your slide (find a picture on the Internet), or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, annoy a group of people you don't know by asking them if they want to buy your coat-rack (find a picture on the Internet), or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, annoy a group of people you don't know by asking them if they want to buy your microwave (find a picture on the Internet), or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, declare your love to a stranger or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, ask a group of people you don't know, if you can take a picture of them because you find them so cuuuute! Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, ask a stranger to take a picture of you. Send us the result sometime, it could be fun ;)",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, show this screen to the barman. If he's fun enough to drink, you can give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, show this screen to a man you don't know. If he drinks, you can give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, show this screen to a female you don't know. If she drinks, you can give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, draw an elephant on a napkin and offer it to a stranger chosen by %s, or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"18",text:"%s, draw an apple on a napkin and offer it to a stanger chosen by %s, or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"18",text:"%s, draw a rabbit on a napkin and offer it to a stranger chosen by %s, or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"18",text:"%s, play a thumb war with a stranger chosen by %s. If you win, give out $ sips. In any other cases, you drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"18",text:"%s, play a rock-paper-scissors war with a stranger chosen by %s. If you win, give out $ sips. In any other cases, you drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"18",text:"%s, ask a stranger chosen by %s to guess your age. If it's successful, jackpot! You give out $ sips. Otherwise drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"18",text:"%s, ask a stranger chosen by %s to guess how tall you are. If it's successful, jackpot! You give out $ sips. Otherwise drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"18",text:"%s, ask a stranger chosen by %s to guess your shoe size. If it's successful, jackpot! You give out $ sips. Otherwise drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"18",text:"%s, go get the number of a waiter or waitress, or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, you have 5 minutes to find a married person. If you fail you drink, otherwise you'll be able to give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, find someone who has downloaded Picolo. You have 3 tries, if you win you'll be able to give out $ sips. Drink if you refuse or fail",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, find someone who hasn't downloaded Picolo. If you manage to make them download the app, you can give out $ sips. Drink if you refuse or fail",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, find someone who has already tried Picolo and liked it. If you win you'll be able to give out $ sips. Drink if you refuse or fail",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, wink at a stranger chosen by %s, or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"18",text:"%s, ask the waiter his name. If he gives it to you, you can give out $ sips. Fail and you'll drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, sniff a stranger's butt discreetly... Drink $ times if you refuse",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, ask a stranger if he/she is for or against shrimp abortion. For: you'll give out $ sips. Against: you drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, ask a stranger if he/she is for or against racism against albino monkeys. For: you'll give out $ sips. Against: you drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go get the number of a stranger, or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, give your number to a stranger chosen by the group, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a stranger and try and guess their zodiac sign. Then go find out from them if you're right. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, give your number to a stranger and tell them you sell health products. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, ask someone you don't know if they'd like your number and tell them you're a sports coach. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, ask someone you don't know to take a picture of you. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, ask someone you don't know if they can take a selfie with your phone. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, heads or tails? Flip a coin with a stranger. You win the challenge if you win the game of Heads or Tails. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, ask someone you don't know to guess your zodiac sign. You win if they guess right. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, find someone who's vegan. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, ask a stranger if they'd like to play an imaginary game of table tennis with you. You win if they agree. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, ask a stranger if they'd like to have an imaginary sword fight with you. You win if they agree. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, ask a stranger if they'd like to play an imaginary game of beach volleyball with you. You win if they agree. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, ask a stranger if they'd like to play an imaginary game of hockey with you (you're the goalkeeper). You win if they agree. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, ask a stranger if they'd like a free cuddle. You win if they agree. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, imitate a monkey and make a stranger guess what it is. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, imitate a hippo and make a stranger guess what it is. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, imitate a butterfly and make a stranger guess what it is. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, imitate a rabid dog and make a stranger guess what it is. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, imitate a bear and make a stranger guess what it is. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, act out this sport and make a stranger guess what it is: underwater hockey. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, act out this sport and make a stranger guess what it is: bobsleigh. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, act out this sport and make a stranger guess what it is: 4x100m freestyle relay. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, act out the term photo finish\u0022 and make a stranger guess what it is. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, imitate Lance Armstrong\u0022 and make a stranger guess who it is. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick any question. You must ask a person you don't know the question and predict what they'll say. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a person you don't know and guess their first name, you have 60 secs. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a person you don't know and guess the town where they were born, you have 60 secs. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a person you don't know and guess their date of birth, you have 60 secs. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a person you don't know and guess their age, you have 60 secs. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a person you don't know and guess their height, you have 60 secs. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, throw a round object towards a group of strangers and say GRENADE\u0022. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a stranger and get them to say the word sausage\u0022 without saying the word itself or using any words from the same family. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a stranger and get them say the word whitehead\u0022 without saying the word itself or using any words from the same family. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a stranger and get them to say toilet brush\u0022 without saying the words themselves or using any words from the same family. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a stranger and get them say Hershey highway\u0022 without saying the word itself or using any words from the same family. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a stranger and get them to say jerk the gherkin\u0022 without saying the words themselves or using any words from the same family. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go ask someone something with your mouth full. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go bum some lipstick off a stranger. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go bum a tissue off a stranger, and tell them you're going to use it as toilet paper. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, give a gift to someone you don't know. Whatever you like. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go and shake hands with at least 10 people you don't know, you have 30 secs. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a stranger to play with, then each of you take turns and name characters from Harry Potter. If you name more characters than your opponent, you win the challenge. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a stranger to play with, then each of you take turns and come up with words that rhyme with -art. If you come up with more words than your opponent, you win the challenge. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a stranger to play with, then each of you take turns and come up with words that rhyme with -all. If you come up with more words than your opponent, you win the challenge. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a stranger to play with, then each of you take turns and come up with words people use instead of penis\u0022. If you come up with more words than your opponent you win the challenge. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a stranger to play with, then each of you take turns and name bad guys/gals from movies. If you come up with more names than your opponent, you win the challenge. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, pick a stranger to play with, then each of you take turns and name places where people use napkins. If you come up with more names than your opponent, you win the challenge. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go read a few lines from Harry Potter to some unknown person. You choose what to read. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go read a few lines from a Kendrick Lamar song to some unknown person. You choose what to read. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go read a few lines from a 50 Cent song to some unknown person. You choose what to read. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go read a few lines from an Adam Levine song to some unknown person. You choose what to read. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go read a few lines from a Kehlani song to some unknown person. You choose what to read. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, give someone you don't know money to pay for something. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go ask someone you don't know to write a word of love on your arm. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go ask someone you don't know to draw something on your forehead. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, go ask someone you don't know to write a 10-digit number on your arm. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"18",text:"%s, each player must say a word. You must say one or more sentences containing these words to a person you don't know. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, choose a minion among your friends. If the lad succeeds in the challenge you set, you'll give out $ sips. Otherwise he/she will drink them",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, choose a challenge for %s. $ sips in play, beware that in case of failure you will both drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"19",text:"%s, choose a challenge for %s, who can give out $ sips if they succeed, or drink $ times if they fail",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"19",text:"%s, have a round under the table on all fours, or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, let %s bite your ass or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"19",text:"%s, drop a peanut or something edible in your glass, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, let %s pour some other drinks into yours, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"19",text:"%s, put one of your socks on the table, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, put one of your shoes on the table, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, go barefoot, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, go to the bathroom and come back with your shirt inside out, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, run to the bathroom while having a hand on your butt, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, leave the bathroom with a subsantial water stain in the groin area, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, moonwalk or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, leave the bathroom with 3 visible pieces of toilet paper sticking out of your pants, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, go to the bathroom and tell the first person you see, Good luck to the next one\u0022 or drink\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, go to the bathroom and interrupt a stranger by saying It'll be a massacre in here\u0022 or drink\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, go part your hair in the middle, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, go turn your pants inside out, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, get your butt slapped by %s, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"19",text:"%s, write your phone number and name on a coaster and leave it after the game. Refuse and you'll drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, draw some fake glasses on your face, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, put a booger on a coaster, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, if you manage to get behind the bar, you can give out $ sips. You'll drink $ times otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, ask for an ice bucket and you can make someone drink. Be a p*ssy and you'll drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, put a foot on the table and you can make someone drink, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, find some lipstick, put it on your lips and color outside the lines, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, next time you go pee, go to the bathroom for the oppostite sex and you'll be able to give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, go around the table and smell everyone's hair, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, drink a shot by using a clean tampon: soak it and suck up. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, spit in your drink, or drink twice",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, let %s lick around the rim of your glass, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"19",text:"%s, lick the table or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, let %s slap you in the face, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"19",text:"%s, put your feet up on a chair until a waiter gets annoyed, or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, chew your coaster for 30 secs, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, let %s put some makeup on your face, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"2"},
{type:"19",text:"%s, eat an ice cube, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, let out a howl like Chewbacca (from Star Wars), or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, do some public tap dancing, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, let out a big burp or drink. Yes, it's silly, but that's part of the game",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, put the coaster in your drink, or drink",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, someone must write GONAD on your forehead with a felt-tip pen. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, someone must write ASSHAT on your forehead with a felt-tip pen. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, let someone draw mustaches on you. Leave the work of art as is until the end of the game. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, clap your hands with your arms up in the air for 5 secs. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, sing a song out loud for 10 secs. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, sing a bawdy song out loud for 10 secs. You have 10 seconds to find out the lyrics. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, sing a rap song out loud for 5 secs. You have 10 seconds to find out the lyrics. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, smell the butts of all the players and draw as much attention as possible to yourself. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, free challenge! The group must come up with a challenge for you. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, throw a round object towards a group of strangers and say PIKACHU THUNDERBOLT ATTACK\u0022. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, do some capoeira in front of as many people as possible. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, roll (forwards or backwards). Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, do a 10m sprint. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, stick your arm right out and point to all those people who appeal to you. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, pretend you're shooting imaginary pigeons for 15 secs. Don't forget the gun sound effects. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, go warm up — high steps, butt kicks etc. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, do 10 burpees (1 burpee = one push-up followed by a jump). Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, smear soil all over your face. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, get up and give an imaginary person the finger . Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, climb on your imaginary bike and go for a ride. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, climb into your imaginary canoe and go for a paddle. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, get into your imaginary bus and go for a ride. Don't hesitate to ask passers-by if they want to climb in. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, racewalk as far as possible for 20 secs. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, step away from the group and beat the triple-jump world record. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, step away from the group and beat the imaginary pole-vault world record. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, step away from the group and beat the long-jump world record. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, step away from the group and beat the imaginary hammer-throw world record. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, step away from the group and beat the imaginary javelin-throw world record. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, step away from the group and beat the imaginary discus-throw world record. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, step away from the group and beat the imaginary shot-put world record. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, step away from the group and kick the winning penalty. Don't keep the crowd waiting... Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, move away from the group and beat the imaginary 3-pointer world record in 20 secs. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, you're in Djokovic's shoes. Move away from the group and work on your imaginary serve until time's up. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, move away from the group, lift up one leg and show the public that you're forcing one out, then say that's better\u0022. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, pretend you're really irritated and shout out: BUT I DON'T ONLY GIVE ANIMALS BLOW JOBS\u0022. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, in a fairly loud voice (groups of strangers closest to you must be able to hear you) say: ... And now you know why my vegetables have an anus smell\u0022. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, in a fairly loud voice (groups of strangers closest to you must be able to hear you) say: ... That was the last time I gave a billy goat a rim job\u0022. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, in a fairly loud voice (groups of strangers closest to you must be able to hear you) say: ... Then they walked in on me right in the middle of anal masturbation\u0022. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, in a fairly loud voice (groups of strangers closest to you must be able to hear you) say: ... It reminds me of the piles I had 3 weeks ago\u0022. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, in a fairly loud voice (groups of strangers closest to you must be able to hear you) say: ... I've never put so many things up his anus\u0022. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, in a fairly loud voice (groups of strangers closest to you must be able to hear you) say: ... My cat all but licked the sperm\u0022. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, come closer to the crowd, stick your hand in your underwear, give yourself a scratch and smell your fingers. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, lay down flat on your stomach and shoot passers-by with your imaginary sniper, for 20 secs. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, go round and round while snapping your fingers for 20 secs. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, go duck-walking around (butt as close to the ground as possible) for at least 50m. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, go around swimming. Pick a style. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, step away from the group and beat the imaginary clean-and-jerk world record (weight-lifting). Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, go wet your entire head of hair then come back. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, go make a scarf out of toilet paper then come back. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, imitate a salmon out of water for 10 secs. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, go layer your underwear on top of your clothing. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, you must move away from the group and act like a dog running after its own tail. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, bind both your feet together, in whatever way, and go around like this. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, move away from the group and shoot passers-by with your imaginary bow and arrow. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, leave something on your face until the end of the game. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, leave something on your head until the end of the game. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, spit on the ground. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, bark so that groups of people you don't know, closest to you, are able to hear you. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, moo (like a cow), so that groups of people you don't know, closest to you, are able to hear you. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, grunt (like a pig), so that groups of people you don't know, closest to you, are able to hear you. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, trumpet (like an elephant), so that groups of people you don't know, closest to you, are able to hear you. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, make the sound of the monkey, so that groups of people you don't know, closest to you, are able to hear you. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, make the sound of the whale, so that groups of people you don't know, closest to you, are able to hear you. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, make the sound of the donkey, so that groups of people you don't know, closest to you, are able to hear you. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, quack (like a duck), so that groups of people you don't know, closest to you, are able to hear you. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, bleat (like a sheep), so that groups of people you don't know, closest to you, are able to hear you. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, shout out the first word that comes to mind. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, each player must say a word. You must make up one or more sentences with these words, so that groups of strangers closest to you are able to hear you. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, shout out the first word that comes to mind that rhymes with ERK\u0022. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, shout out the first word that comes to mind that rhymes with ICK\u0022. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, shout out the first word that comes to mind that rhymes with US\u0022. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, shout out the first word that comes to mind that rhymes with ITCH\u0022. Or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"19",text:"%s, throw something over your shoulder, so it lands at least 5m away. Or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a guy called Anthony or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a guy called Ryan or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a guy called Nathan or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a guy called Vincent or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a guy called Charles or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a guy called Damien or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a guy called Liam or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a guy called Steven or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a guy called Alan or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a guy called Jeremy or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a girl called Ethel or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a girl called Betty or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a girl called Alicia or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a girl called Carly or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a girl called Jessica or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a girl called Justine or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a girl called Laura or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a girl called Melissa or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a girl called Martha or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a girl called Melanie or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"20",text:"%s, find a girl called Mary or drink. You've got 3 tries, if you succeed you'll give out $ sips",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write sauerkraut\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write anal plug\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write phallus\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write boil\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, draw a unibrow or drink $ times",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write trumpet\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write vaseline\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write litter\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write viagra\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write diahrrea\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write anal sex\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write virgin\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write tapeworm\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write lube\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write sperm\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write jar of jelly\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write cyst\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write pube\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write oral coitus\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write horny\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write do me\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"21",text:"%s, write pants\u0022 on your forehead or drink $ times\u0022",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a prostitute riding a horse. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a mammoth shitting a lemur. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a lesbian unicorn. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw an earwig gymnast. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a talking French fry. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a farting pan. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a dog having diahrrea. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a head gasket. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a baby psychopath. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a cockroach wearing shorts. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a castrated chippendale. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw Batman playing jump rope. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a hobbit who's running. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a giraffe that's puking. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a baby taking a sh*t. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a female Pikachu. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a monkey caressing himself. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw Iron Man wearing pants. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw Trump's foreskin. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a policeman doing doggy style with a frog. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a cat wearing a condom. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a living chair. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a dancing bear. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw an egg giving a phone call. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a vampire wiping his butt. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a dead mouse. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a crocodile ejaculating. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw Pinocchio commiting suicide. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a drunk fox. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a rabbit on a skateboard. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw Smurfette naked. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a gay lion. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a flying playground slide. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a stuffed turkey. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"},
{type:"22",text:"%s, draw a horse with an erection. Make a stranger chosen by the group guess what it is. If this person succeeds, you'll give out $ sips. Drink otherwise",key:"",parent_key:"",pack_name:"bar",language:"en",nb_players:"1"}];
game.pending_db = game.pending_db.concat(game.stored_db.bar_en);