var db = TAFFY([{cycle_state:"false",type:"1",text:"%s, 맛이 나는 맥주를 마시고 있다면, 네가 마시고 그렇지 않으면 다른 사람에게 한번 마시라고 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 오백 한 잔을 마신다면 네가 마시고, 그렇지 않으면 다른 사람에게 한번 마시라고 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 이백 잔을 마시면 네가 마시고, 그렇지 않으면 다른 사람에게 한번 마시라고 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 이 바의 가장 최악의 슈터 한 잔을 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"이 바에서 제일 늦게 나간 사람은 다른 사람에게 2번 마시라고 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"이 바에 첫 번째로 들어온 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"이 바에 첫 번째로 들어온 사람은 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"이 바에 마지막으로 들어온 사람은 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"지금까지 돈을 가장 조금 낸 사람은 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"지금까지 돈을 가장 많이 낸 사람은 다른 사람에게 $번 마시라고 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, 여기에 오는 게 너의 생각이었다면 다른 사람에게 $번 마시라고 해. 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 피콜로 바 게임을 하는 게 너의 생각이었다면 다른 사람에게 $번 마시라고 해. 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 오늘 네가 실패한 피콜로 대결 게임의 수만큼 마셔. 도전에 실패한 적 없어? 그래도 일단 한번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 오늘 이 그룹이 실행한 피콜로 게임을 수만큼 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 오늘 네가 실행한 피콜로 대결 게임의 수만큼 마셔. 도전에 실행한 게 없어? 그래도 일단 한번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 오늘 모든 사람이 거절한 피콜로 도전의 수만큼 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 오늘 네가 거절한 피콜로 도전의 수만큼 마셔. 거절한 도전이 없어? 브라보! 다른 사람에게 $번 마시라고 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 동전을 가지고 있다면 누군가의 잔에 넣고 그 사람은 $번 마셔. 그렇지 않으면 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s 하고 %s 은/는 잔을 똑같이 만들어 : 가장 많이 채워진 잔을 가진 사람은 다른 사람 잔에 그걸 부어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s 하고 %s 은/는 잔을 똑같이 만들어 : 잔의 양이 더 많은 사람은 그 양의 차이만큼 더 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, 모든 사람에게 줄 빨대를 달라고 하든지 싫으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"제일 먼저 화장실에 가서 똥을 싼 다음 물을 안내리는 사람은 다른 사람에게 원샷 줄 수 있어!",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, 네가 다음에 만지는 사람은 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 오늘 여러 바를 다녔다면 다른 사람을 마시게 할 수 있고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 종업원하고 대화를 했다면 어떤 사람을 마시게 해, 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 어떤 것에 돈을 이미 냈다면 어떤 사람을 마시게 해, 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 여기에 여자종업원들이 있다면 어떤 사람을 마시게 해, 그렇지 않으면 마셔 ",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 지난번에도 이 바에 왔었다면 어떤 사람을 마시게 해, 그렇지 않으면 마셔 ",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 이 바에 처음 와본 거라면 어떤 사람을 마시게 해, 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 이 바안에서 게임을 하고 있는 어떤 사람을 알고 있다면, 어떤 사람을 마시게 해, 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"우리 테이블 말고 다른 사람들의 테이블에서 피콜로 게임을 한다면, 그들에게 한 잔 줄 준비를 해. 그렇지 않다면 모두 건배!",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, 이 바안에서 벌써 데이트해본 적 있으면 어떤 사람을 마시게 해, 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네 전 애인이 이 근처에 산다면 다른 사람에게 원샷을 주고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 남자 또는 여자 바텐더와 데이트를 해봤다면 네가 마시고, 그렇지 않으면 한 잔을 다른 사람에게 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 남자 또는 여자 종업원하고 데이트를 해봤다면 네가 마시고, 그렇지 않으면 한 잔을 다른 사람에게 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네 친구들을 제외하고 이 바에 있는 못생긴 사람의 수만큼 다른 사람에게 마시라고 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네 친구들을 제외하고 이 바에 있는 멋진 사람의 수만큼 다른 사람에게 마시라고 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 이 바에 있는 대머리의 수만큼 다른 사람에게 잔을 나눠주고, 대머리가 없다면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 이 바에 있는 찌질이의 수만큼 다른 사람에게 잔을 나눠주고 (최고 4명), 찌질이가 없다면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 그다지 멀리 있지 않은 사람을 선택해. A ton top\u0022 저 모르는 사람이 7초 동안 말을 하지 않는다면 너는 다른 사람들에게 $번 마시라고 하고 그렇지 않으면 네가 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 그다지 멀리 있지 않은 사람을 선택해. A ton top\u0022 저 모르는 사람이 7초 동안 같은 자세를 한다면 너는 다른 사람들에게 $번 마시라고 하고 그렇지 않으면 네가 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 그다지 멀리 있지 않은 사람을 선택해. A ton top\u0022 저 모르는 사람이 처음 12초 안에 네 쪽으로 쳐다보지 않으면 너는 다른 사람들에게 $번 마시라고 하고 그렇지 않으면 네가 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 그다지 멀리 있지 않은 곳에 앉아있는 사람을 선택해. A ton top\u0022 저 모르는 사람이 15초 안에 일어난다면 너는 다른 사람들에게 $번 마시라고 해! 그렇지 않으면 네가 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 그다지 멀리 있지 않은 곳에서 서있는 사람을 선택해. A ton top\u0022 저 모르는 사람이 15초 안에 앉으면 너는 다른 사람들에게 $번 마시라고 해! 그렇지 않으면 네가 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 그다지 멀리 있지 않은 사람을 선택해. A ton top\u0022 저 모르는 사람이 7초 안에 재밌게 깔깔거리면 너는 다른 사람들에게 $번 마시라고 하고 그렇지 않으면 네가 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 그다지 멀리 있지 않은 사람을 선택해. A ton top\u0022 저 모르는 사람이 4초 안에 미소 지으면 너는 다른 사람들에게 $번 마시라고 할 수 있고 그렇지 않으면 네가 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 그다지 멀리 있지 않은 사람을 선택해. A ton top\u0022 저 모르는 사람이 7초 안에 마시면 너는 다른 사람들에게 $번 마시라고 할 수 있고 그렇지 않으면 네가 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 그다지 멀리 있지 않은 사람을 선택해. A ton top\u0022 저 모르는 사람이 10초 안에 마시지 않으면 너는 다른 사람들에게 $번 마시라고 할 수 있고 그렇지 않으면 네가 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 그다지 멀리 있지 않은 사람을 선택해. A ton top\u0022 저 모르는 사람이 5초 안에 미소 짓지 않으면 너는 다른 사람들에게 $번 마시라고 할 수 있고 그렇지 않으면 네가 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 그다지 멀리 있지 않은 사람을 선택해. A ton top\u0022 저 모르는 사람이 10초 안에 깔깔거리며 웃지 않으면 너는 다른 사람들에게 $번 마시라고 할 수 있고 그렇지 않으면 네가 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 그다지 멀리 있지 않은 사람을 선택해. A ton top\u0022 저 모르는 사람이 30초 안에 주문하면 너는 다른 사람들에게 $번 마시라고 할 수 있고 그렇지 않으면 네가 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s 하고 %s, 각각 선수 한 명씩 선택해 (모르는 사람으로). 첫 번째로 말을 한 사람을 고른 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s 하고 %s, 각각 선수 한 명씩 선택해 (모르는 사람으로). 첫 번째로 주문을 한 사람을 고른 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s 하고 %s, 각각 선수 한 명씩 선택해 (모르는 사람으로). 첫 번째로 담배피는 사람을 고른 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s 하고 %s, 각각 선수 한 명씩 선택해 (모르는 사람으로). 첫 번째로 화장실을 가는 사람을 고른 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s 하고 %s, 각각 선수 한 명씩 선택해 (모르는 사람으로). 첫 번째로 미소 짓는 사람을 고른 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s 하고 %s, 각각 선수 한 명씩 선택해 (모르는 사람으로). 첫 번째로 깔깔거리며 웃는 사람을 고른 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"두 명 중 첫 번째로 주문을 한 사람은 정중히 두 번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"두 명 중 마지막으로 주문을 한 사람은, 두 번 마시면서 따라잡아",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, 여기 스태프 멤버하고 악수를 했거나 볼에 키스를 했다면 넌 마셔. 그렇지 않다면 다른 사람을 마시게 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 잔받침을 가지고 있으면 다른 사람을 마시게 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 이 도시에서 이곳이 네가 가장 선호하는 바라면 마셔, 그렇지 않으면 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 이 바에 3번 이상 온 적이 있다면 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 1년 전에 이 바에 와본 적 있다면 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 이 바에서 누군가와 복잡하게 설켜 본 적 있으면 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 이 바에서 토를 엄청 많이 해봤다면 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 이 바에 커플로 와본 적 있다면 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 이 바에 솔로로 와본 적 있다면 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 여기 도착하면서 종업원들에게 인사를 했고 이곳 구석구석 잘 알고 있다면 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 이 파티의 시작을 세지 않은 술로 시작을 했다면 네가 마시고, 그렇지 않으면 다른 사람에게 술을 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 이 바를 나가면서 토 한적 있다면 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"첫 번째로 커플을 찾아내는 사람은 다른 사람에게 $번 마시라고 해. 아무도 없어? 모두 마셔!",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"첫 번째로 키스를 하고 있는 커플을 찾는 사람은 다른 사람에게 $번 마시라고 해. 아무도 없어? 모두 마셔!",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"첫 번째로 웃는 타입의 사람을 찾아내는 사람은 다른 사람에게 $번 마시라고 해. 아무도 없어? 모두 마셔!",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"첫 번째로 원피스를 입고 있는 여자를 찾는 사람은 다른 사람에게 $번 마시라고 해. 아무도 없어? 모두 마셔!",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"첫 번째로 슈터를 찾아내는 사람은 다른 사람에게 $번 마시라고 해. 아무도 없어? 모두 마셔!",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"첫 번째로 비어있는 오백잔을 찾는 사람은 다른 사람에게 $번 마시라고 해. 아무도 없어? 모두 마셔!",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"첫 번째로 동물을 찾아내는 사람은 다른 사람에게 $번 마시라고 해. 아무도 없어? 모두 마셔!",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"비어있는 테이블을 첫 번째로 찾는 사람은 다른 사람에게 $번 마시라고 해. 아무도 없어? 모두 마셔!",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"4명의 친구로 된 그룹을 첫 번째로 찾아내는 사람은 다른 사람에게 $번 마시라고 해. 아무도 없어? 모두 마셔!",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"너네들이 테라스에 있다면, %s 은/는 다른 사람에게 한번 마시라고 줄 수 있어. 너네들이 실내에 있다면, %s 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"너네들이 모두 같이 도착했다면,  %s 너 마셔. 지각한 사람이 있다면 그건 %s 일 거야",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, 네가 맨 처음으로 도착한 사람이면 너는 다른 사람에게 $번 마시라고 줄 수 있고, 그렇지 않으면 마셔, 고소하다",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 가장 늦게 온 사람이 되어서 $번 마시고, 다른 사람에게 한번 마시게 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"카드를 깜빡했는데 돈 좀 빌려줄래?\u0022라고 말을 해본 적 있는 사람은 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"다른 바에 가서 마시고 싶어서 화를 내본 적 있는 사람은 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"오늘 밤 나가 놀고 싶지 않아서 조금 화를 내본 사람은 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, 피콜로 바\u0022 게임을 사람들에게 도전하라고 부추겼다면 다른 사람에게 한번 마시라고 할 수 있어. 그런데 부추김에 실패했다면 네가 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"해피 아워야? 그렇다면, %s 마셔. 아니면, %s 가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"여기에 음악이 없다면, %s 네 잘못이니까 한번 마셔. 음악이 있다면 네 덕분이야! 2번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 너는 미스터 커피야. 커피 한 잔을 주문해, 절대 그걸 마시지 말고 다음을 위해 보관해",key:"coffee",parent_key:"",pack_name:"bar",language:"ko",nb_players:"3"},
{cycle_state:"false",type:"2",text:"%s, %s 하고 %s 의 잔에 똑같이 따르든지 말든지 네 커피를 나눠 줄 수 있어.",key:"",parent_key:"coffee",pack_name:"bar",language:"ko",nb_players:"3"},
{cycle_state:"false",type:"2",text:"%s, 어느 잔에 너의 찬 커피를 따라 부을 건지 선택해",key:"",parent_key:"coffee",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 너의 잔에 차가운 커피를 부어...건배!",key:"",parent_key:"coffee",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 새로운 규칙이 나올 때까지 손가락을 튕기며 리듬을 타. 또는 새로운 노래가 나올 때마다 $번 마셔",key:"click-finger",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 이제 손가락 그만 튕겨",key:"",parent_key:"click-finger",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 바에 가서 혼자 마셔",key:"alone-at-the-bar",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 이제 다시 돌아와!",key:"",parent_key:"alone-at-the-bar",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 바보같이 행동해 부탁이야 : 가끔씩 네가 할 수 있는 만큼 아주 크게 소리질러. 소리지를때마다 다른 사람에게 한번 마시라고 줄수있어",key:"I-assume-mongolito",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 바보짓 그만해",key:"",parent_key:"I-assume-mongolito",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 지금부터 빨대 3개로 마시든지 아니면 새로운 규칙이 나올 때마다 한 번씩 마셔",key:"3-straws",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 빨대 3개로 그만해도 돼",key:"",parent_key:"3-straws",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 네가 가장 좋아하는 종업원을 선택해. 종업원이 한 잔을 서빙할 때, 네 입으로 방귀 뀌는 소리를 내든지 아니면 한번 마셔",key:"choose-waiter",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 네 입으로 방귀소리 그만 내, 바보 같아",key:"",parent_key:"choose-waiter",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 너는 오늘 파티에서 매우 사교적이야, 네 앞을 지나가는 사람들에게 매번 인사해. 인사를 놓칠 때마다 한번 마셔",key:"hypersocial",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 넌 이제 매우 사교적이 아니야",key:"",parent_key:"hypersocial",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 탐폰을 찾아서 네 귀에다가 보관해, 그게 품위야",key:"tampon-ear",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s,탐폰 빼 이제 피 안 나",key:"",parent_key:"tampon-ear",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 너는 벌받는 사람이야! 바의 구석으로 가. 사람들이 네가 말을 걸면, 나는 벌을 받아\u0022라고 말할 권리가 있어\u0022",key:"punition",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 이제 다시 돌아와! 그렇지 않으면, 그냥 단순히 규칙을 통과해 ;)",key:"",parent_key:"punition",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 테이블 아래에 있어. 네가 언제 테이블에서 나올 건지 우리가 알려줄게",key:"under-the-table",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 우리들 속으로 다시 돌아와! 우리는 이 규칙이 통과되지 않은척할 수 있어",key:"",parent_key:"under-the-table",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 문 옆에 있는 테이블에서 한 여자를 선택해. 그 여자가 마시자마자 잘한다\u0022라고 말해야 해\u0022",key:"choose-your-partner",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 옆 테이블에 있는 여자에게 귀찮게 구는 짓은 그만해!",key:"",parent_key:"choose-your-partner",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 그다지 멀리 있지 않은 곳에 있는 모르는 사람을 선택해. 선발된 사람이 말할 때마다, 너는 어쩌구저쩌구\u0022를 꼭 말해야 해\u0022",key:"speak-when-other-speak",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 이제 그 사람이 뭘 하든 조용히 놔둬",key:"",parent_key:"speak-when-other-speak",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"이 게임이 끝날 때까지 동전 게임하기! %s, 동전 한 개를 가지고 잔에다가 넣어. 그 대상은 $번 마시고, 자신의 차례에 그 동전을 다른 사람에게 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"담배 한 갑의 끝을 테이블의 끝에다 두고, 각자 돌아가며 한 번의 시도로 테이블을 쳐서 떨어지게 만들어. 지는 사람은 마시고, 이긴 사람은 한번 마시라고 다른 사람 주기, %s 네가 먼저 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"동전 하나를 테이블 끝에 두고, 각자 돌아가며 한 번의 시도로 테이블을 쳐서 동전이 반대편 모서리에 최대한 가깝게 가게 하기. 가장 가깝게 만든 사람이 다른 사람에게 3번 마시라고 주기, %s 네가 먼저 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"블라인드 테스트! 현재 들리는 음악의 제목을 제일 먼저 맞추는 사람은 다른 사람에게 $번 마시라고 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"4",text:"신속한 정보 전달! %s 문장 하나를 선택해서 네 왼쪽에 있는 사람에게 그것을 속삭여. 이하 마찬가지로 그것이 너한테 다시 올 때까지 해. 이 게임을 망친 사람들은 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s 테이블 위에 동전 하나를 돌리는 것으로 시작해. 각자 차례에, 손가락으로 그 동전을 쳐서 계속 돌리게 해. 동전 못 살린 사람은 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"블라인드 테스트! 현재 들리는 음악의 연주자를 제일 먼저 맞추는 사람은 다른 사람에게 $번 마시라고 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"4",text:"블라인드 테스트! 이전 음악의 제목을 제일 먼저 맞추는 사람은 다른 사람에게 $번 마시라고 줘. 아무도 없어? 모두 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"4",text:"20개의 담배로 미카도 게임하기. 이 게임의 규칙은 담배 한 개비당 한번 마시는 것으로 인정, %s 시작해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"16",text:"각각 차례로, %s 의 생각에 이 바에서 가장 매력 있고 아름다운 여자가 누군지 맞춰봐. 처음으로 맞춘 사람은 다른 사람에게 $번 마시라고 해! %s 시작해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"16",text:"각각 차례로, %s 의 관점으로 이 바의 트레이드 마크가 뭔지 맞춰봐. 처음으로 맞춘 사람은 다른 사람에게 $번 마시라고 해! %s 시작해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"16",text:"각각 차례로, %s 의 생각에 이 바에서 가장 쉬운 여자가 누군지 맞춰봐. 처음으로 맞춘 사람은 다른 사람에게 $번 마시라고 해! %s 시작해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"16",text:"각각 차례로, %s 의 생각에 이 바에서 가장 못생긴 여자가 누군지 맞춰봐. 처음으로 맞춘 사람은 다른 사람에게 $번 마시라고 해! %s 시작해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"16",text:"각각 차례로, %s 의 관점으로 봐서 이 바에는 없는 이상형을 맞춰봐. 처음으로 맞춘 사람은 다른 사람에게 $번 마시라고 해! %s 시작해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"16",text:"각각 차례로, %s 의 생각에 이 바에서 가장 못생긴 남자가 누군지 맞춰봐. 처음으로 맞춘 사람은 다른 사람에게 $번 마시라고 해! %s 시작해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"16",text:"각각 차례로, %s 의 생각에 이 바의 가장 최고인 술이 뭔지 맞춰봐. 처음으로 맞춘 사람은 다른 사람에게 $번 마시라고 해! %s 시작해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"16",text:"각각 차례로, %s 의 생각에 이 바에서 가장 최고의 맥주가 뭔지 맞춰봐. 처음으로 맞춘 사람은 다른 사람에게 $번 마시라고 해! %s 시작해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"16",text:"각각 차례로, %s 의 생각에 이 바에서 가장 섹시한 여자가 누군지 맞춰봐. 처음으로 맞춘 사람은 다른 사람에게 $번 마시라고 해! %s 시작해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"16",text:"각각 차례로, %s 의 생각에 이 동네에서 가장 최고의 바가 어딘지 뭔지 맞춰봐. 처음으로 맞춘 사람은 다른 사람에게 $번 마시라고 해! %s 시작해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"16",text:"각각 차례로, %s 의 생각에 이 동네에서 가장 최고의 나이트클럽이 어딘지 맞춰봐. 처음으로 맞춘 사람은 다른 사람에게 $번 마시라고 해! %s 시작해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"16",text:"각각 차례로, %s 의 생각에 시내에서 데이트하기 가장 쉬운 장소가 어딘지 맞춰봐. 처음으로 맞춘 사람은 다른 사람에게 $번 마시라고 해! %s 시작해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"16",text:"각각 차례로, %s 의 생각에 가장 좋은 최신 음악이 뭔지 맞춰봐. 처음으로 맞춘 사람은 다른 사람에게 $번 마시라고 해! %s 시작해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"17",text:"%s, 너는 다음 순서에서 주문하기 위해 선택됐어, 가지다\u0022 \u0022먹다\u0022 그리고 \u0022주문할게요\u0022 라는 동사를 사용하면 안 돼\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"17",text:"%s 하고 %s, 동시에 주문해. 첫 번째로 음식을 받은 사람은 늦게 받은 사람이 마실 동안 다른 사람에게 $번 마시라고 해 ",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"17",text:"%s, 모든 사람을 위해 가서 간단히 먹을 것을 찾든지 하기 싫으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"17",text:"%s, 지갑을 꺼내서 다음 게임에 계산해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"17",text:"%s, %s 이/가 원하는 칵테일로 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"17",text:"그거 아주 좋을 거야... %s 슈터 한 바퀴 돈 내!",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"17",text:"정보에 의하면, 가장 늦게 마시는 사람은 다음번에 돈을 내야 해...",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"17",text:"%s, 아직도 배짱이 있는 사람이 있다면, 그 사람에게 슈터 한잔 사줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"17",text:"%s, 네 맥주 오백 돈내! 자신의 잔을 첫 번째로 다 마시는 %s 또는 %s 이/가 오백을 마실 거야.",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"3"},
{cycle_state:"false",type:"17",text:"%s, 네 잔 돈을 내! %s, 네가 원하는 것으로 선택해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"17",text:"%s, %s 이/가 선택한 모르는 남자 또는 여자에게 한 잔 사줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"17",text:"100 센티미터의 슈터야 아니면 차라리 모히토야? 모두 동시에 결정하고, 결과의 소수자들은 다음을 위해 맞는 대답해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"17",text:"페일 에일 맥주야 아니면 차라리 밀맥주야? 모두 동시에 결정하고, 결과의 소수들은 다음을 위해 대답 잘해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"17",text:"맥주야 아니면 차라리 그냥 아무거 나야? 모두 동시에 결정하고, 결과의 소수들은 다음을 위해 대답 잘해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"17",text:"%s, 연달아서 6번 원샷하고, 친절하게 다음번에 낸다고 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"17",text:"%s, %s 하고 %s 중에서 다음번에 누가 계산할 건지 네가 정해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"3"},
{cycle_state:"false",type:"17",text:"%s, 다음번에 누가 계산할 건지 네가 정해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"17",text:"%s,  넌 임금님! 네가 마시고 싶은 한 잔을 선택해서 네가 원하는 사람에게 돈을 내라고 할 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 가서 콘돔 하나를 사 오든지 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 가서 담배 한 개를 사 오든지 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 모르는 사람한테 가서 피콜로 게임 아냐고 물어봐. 안다고 하면 네가 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, %s 이/가 정한 모르는 사람의 나이를 맞춰봐. 그 사람한테 가서 물어보고, 네가 맞다면 다른 사람에게 $번 마시라고 하고, 틀렸다면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"18",text:"%s, %s 이/가 정한 모르는 사람의 사이즈를 맞춰봐. 그 사람한테 가서 물어보고, 네가 맞다면 다른 사람에게 $번 마시라고 하고, 틀렸다면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"18",text:"%s, %s 이/가 정한 모르는 사람의 브래지어 사이즈를 맞춰봐. 그 사람한테 가서 물어보고, 네가 맞다면 다른 사람에게 $번 마시라고 하고, 틀렸다면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"18",text:"%s, %s 이/가 정한 모르는 사람의 발 사이즈를 맞춰봐. 그 사람한테 가서 물어보고, 네가 맞다면 다른 사람에게 $번 마시라고 하고, 틀렸다면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"18",text:"%s, 모르는 사람 한 명을 선택해. 그 여자가 싱글이면 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, %s 이/가 모르는 사람 한 명을 선택하게 해. 그 사람이 몇 시에 도착했는지 맞춰봐. 네가 맞다면 다른 사람에게 $번 마시라고 하고, 틀리면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"18",text:"%s, 바에 노래 한 곡을 부탁해. 어떠한 경우의 거절은 한번 마시는 걸로 하고, 네 부탁을 받아들이면 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 가서 디제이한테 음악소리를 줄여달라고 하든지 아니면 $번 마셔. 성공했어? 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 가서 디제이한테 음악소리를 키워달라고 하든지 아니면 $번 마셔. 성공했어? 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 모르는 사람한테 농담 하나 해. 웃기거나 미소를 짓게 했다면 다른 사람에게 $번 마시라고 할 수 있어. 실패했으면 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 못생긴 사람의 사진 한 장을 보여주면서 모르는 사람들의 그룹에 바짝 다가가든지, 아니면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 공룡 사진 한 장을 보여주면서 모르는 사람들의 그룹에 바짝 다가가든지, 아니면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 양배추 절임 사진 한 장을 보여주면서 모르는 사람들의 그룹에 바짝 다가가든지, 아니면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 모르는 그룹에 가서 그들이 네 미끄럼틀을 좋아하는지 물어봐 (미끄럼틀 사진을 네이버 블로그에서 보여줘), 물어보기 싫으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 모르는 그룹에 가서 그들이 네 옷걸이를 좋아하는지 물어봐 (네 옷걸이 사진을 네이버 블로그에서 보여줘), 물어보기 싫으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 모르는 그룹에 가서 그들이 네 전자레인지를 좋아하는지 물어봐 (전자레인지 사진을 네이버 블로그에서 보여줘), 물어보기 싫으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 모르는 사람한테 사랑 고백하든지 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 네가 생각하기에 잘생겼거나 이쁜 사람하고 사진을 찍을 수 있는지 그룹에 물어보든지, 아니면 그냥 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 모르는 사람에게 너네들의 사진을 찍어달라고 하고, 우리에게 그 사진을 보내달라 해 ;)",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 바텐더에게 이 스크린을 보여줘. 그가 마시면, 너는 다른 사람에게 $번 마시라고 줄 수 있고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 모르는 남자에게 이 스크린을 보여줘. 그가 마시면, 너는 다른 사람에게 $번 마시라고 줄 수 있고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 모르는 여자에게 이 스크린을 보여줘. 그녀가 마시면, 너는 다른 사람에게 $번 마시라고 줄 수 있고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 냅킨에 코끼리를 그려서 %s 이/가 선택한 모르는 사람에게 그것을 줘, 아니면 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"18",text:"%s, 냅킨에 사과를 그려서 %s 이/가 선택한 모르는 사람에게 그것을 줘, 아니면 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"18",text:"%s, 냅킨에 토끼를 그려서 %s 이/가 선택한 모르는 사람에게 그것을 줘, 아니면 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"18",text:"%s, %s 이/가 선택한 모르는 사람하고 엄지손가락 싸움해. 네가 이기면, 다른 사람에게 $번 마시라고 해. 네 상대가 거절하거나 이기면, 넌 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"18",text:"%s, %s 이/가 선택한 모르는 사람하고 가위바위보 해. 네가 이기면, 다른 사람에게 $번 마시라고 해. 네 상대가 거절하거나 이기면, 넌 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"18",text:"%s, %s 이/가 선택한 모르는 사람에게 너의 나이를 맞춰보라고 물어봐. 만약 맞추면, 잭 팟! 다른 사람에게 $번 마시라고 줘. 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"18",text:"%s, %s 이/가 선택한 모르는 사람에게 너의 사이즈를 맞춰보라고 물어봐. 만약 맞추면, 잭 팟! 다른 사람에게 $번 마시라고 줘. 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"18",text:"%s, %s 이/가 선택한 모르는 사람에게 네가 신은 신발이 얼마인지 맞춰보라고 물어봐. 만약 맞추면, 잭 팟! 다른 사람에게 $번 마시라고 줘. 그렇지 않으면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"18",text:"%s, 종업원의 번호를 따오든지, $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 결혼한 사람 한 명 찾는 데까지 5분 남았어. 찾는데 실패하면 네가 마셔, 성공하면 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 피콜로 게임을 다운받은 한 명을 찾아. 너는 3번의 기회가 있어, 찾는데 성공하면 다른 사람에게 $번 마시라고 줄 수 있어. 하기 싫으면 그걸 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 피콜로 게임을 다운받지 않은 한 명을 찾아. 그 사람에게 피콜로 게임을 다운받게 하면, 다른 사람에게 $번 마시라고 할 수 있고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 피콜로 게임을 해봤고 좋아한 한 명을 찾아. 찾는데 성공하면 너는 다른 사람에게 $번 마시라고 주고, 실패하면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, %s 이/가 선택한 사람에게 윙크를 하든지 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"18",text:"%s, 종업원에게 이름을 물어봐. 이름을 말하면 너는 다른 사람에게 한번 마시라고 줘",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 모르는 사람의 엉덩이를 몰래 느껴...거절하면 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 모르는 사람에게 새우가 낙태를 하는 거에 찬성인지 반대인지 물어봐. 찬성 : 다른 사람에게 $번 마시라고 줄 수 있어. 반대 : 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 모르는 사람 한 명에게 알비노 원숭이에 대한 인종 차별주의에 찬성인지 반대인지 물어봐. 찬성 : 다른 사람에게 $번 마시라고 줄 수 있어. 반대 : 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 모르는 사람의 번호를 따오든지 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"18",text:"%s, 이 그룹이 선택한 모르는 사람에게 네 전화번호를 주든지, 아님 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 이 테이블에서 꼬붕 하나 선택해. 네가 꼬붕한테 시킨 일을 꼬붕이 성공하면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 꼬붕은 그걸 마셔야 해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, %s 에게 할 도전을 선택해. 게임에서 $번 마심, 실패할 경우 둘 다 마셔야 하니까 조심해",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"19",text:"%s, %s 에게 할 도전을 선택해, 성공할 경우엔 다른 사람에게 $번 마시라고 주고, 실패할 경우에는 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"19",text:"%s, 테이블 밑을 네발로 기든지 아니면 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, %s 이/가 네 엉덩이를 물게 놔두든지 아니면 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"19",text:"%s, 네 잔 안에 땅콩이나 과자를 넣든지 아니면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, %s 이/가 다른 잔을 네 잔에 조금 붓도록 놔두든지 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"19",text:"%s, 네 양말 한 짝을 테이블 위에 놓든지 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 네 신발 한 짝을 테이블 위에 놓든지 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 맨발로 있든지 아님 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 화장실로 가 그리고 돌아올 때 상의를 뒤집어서 입고 오든지, 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 한 손으로 네 엉덩이를 잡고 화장실로 급하게 가든지, 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 네 거시기 부분에 아주 큰 물에 젖은 얼룩을 만들고 화장실에서 나오든지, 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 모두 앞에서 문워크를 하든지 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 휴지 3칸을 네 엉덩이에 달고 화장실에서 나오든지, 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 화장실에서 나오면서 처음으로 만나는 사람에게 다음 행운을 빌게\u0022 라고 말해 아님 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 화장실로 가서, 모르는 사람에게 나 거기서 완전 엉망으로 만들거야\u0022 라고 말하든지 아님 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 가운데로 가르마를 타든지 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 가서 네 바지를 앞뒤 반대로 입고 오든지 아니면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s,  %s 한테서 네 엉덩이 한쪽을 맞든지 아님 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"19",text:"%s, 잔 밑에 네 전화번호랑 네 이름을 적어 놔 그리고 게임 끝나고도 계속 놔둬. 하기 싫으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 네 얼굴에 가짜 안경을 그리든지 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s,  컵받침에 코딱지를 붙이든지 아님 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 네가 이 바의 뒤쪽을 지나갈 거라면 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 그걸 네가 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 얼음 한 개를 쟁반에 달라고 해서 다른 사람을 마시게 해, 실패하면 그걸 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 테이블 위에 발을 올리고 다른 사람을 마시게 해, 실패하면 넌 한번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 립스틱 한 개를 찾고, 입술 밖에 삐져나오게 막 칠하든지, 아니면 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 다음에 네가 오줌 싸러 갈때, 네가 들어가야 할 화장실을 그 반대로 들어가 그리고 다른 사람에게 $번 마시라고 해 ",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 테이블을 돌면서 모든 사람들의 머리 냄새를 맡든지, 아님 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 깨끗한 탐폰을 사용하면서 슈터를 마셔 : 탐폰을 빨아먹을 수 있는 비스킷처럼 적시고 그걸 좋아해. 또는 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 네 잔에 침 몇 방울을 넣든지 아님 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, %s 이/가 너의 잔 가장자리를 전부 핥게 놔두든지 아님 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"19",text:"%s, 테이블을 핥든지 아님 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, %s 한테서 따귀 한대 맞든지 아님 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"19",text:"%s, 종업원이 짜증 날 때까지 네 다리를 뻗어 네 발을 의자 위에 놓든지 아님 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 30초 동안 컵 받침을 씹든지 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, %s 한테서 화장을 조금 받든지 아님 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"19",text:"%s, 얼음 한 개를 먹든지 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 스타워즈의 츄바카 처럼 소리를 지르든지 아님 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 모두 앞에서 탭댄스를 하든지 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 아주 강하게 트림하든지 마셔. 알아 더러운 거 그래도 게임이야",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"19",text:"%s, 네 잔에 컵 받침을 넣든지 아님 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 영중이라는 이름을 가진 남자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 훈라는 이름을 가진 남자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 인성이라는 이름을 가진 남자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 영호라는 이름을 가진 남자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 준수라는 이름을 가진 남자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 나훈이라는 이름을 가진 남자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 해진이라는 이름을 가진 남자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 재훈이라는 이름을 가진 남자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 나혁이라는 이름을 가진 남자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 중기라는 이름을 가진 남자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 재혁이라는 이름을 가진 남자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 주현이라는 이름을 가진 여자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 민경이라는 이름을 가진 여자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 연희라는 이름을 가진 여자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 민정이라는 이름을 가진 여자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 새라라는 이름을 가진 여자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 선희라는 이름을 가진 여자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 정연이라는 이름을 가진 여자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 연지라는 이름을 가진 여자를 찾든지 마셔.세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 혜나라는 이름을 가진 여자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"20",text:"%s, 정희라는 이름을 가진 여자를 찾든지 마셔. 세 번의 기회가 있어, 만약 성공하면 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 양배추 절임\u0022이라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 항문 섹스토이\u0022라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에  발기된 고추\u0022라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 종기\u0022라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 눈썹을 일자로 붙여 그리든지 $번 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 나팔\u0022이라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 바셀린\u0022이라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 쓰레기\u0022라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 비아그라\u0022라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 위통\u0022이라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 애널섹스\u0022라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 처녀\u0022라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 기생충\u0022이라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 질 분비액\u0022라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 정액\u0022라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 비스킷\u0022이라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 낭종(혹)\u0022이라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 음부 털\u0022이라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 구강 섹스\u0022라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 발정\u0022이라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 토스트\u0022라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"21",text:"%s, 네 이마에 팬티\u0022라고 쓰던지 $번 마셔\u0022",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 말에 올라탄 창녀 한 명을 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 여우원숭이를 똥으로 싸는 맘모스를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 레즈비언 유니콘을 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔.",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 체조선수 집게벌레를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔.",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 말하는 감자튀김을 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔.",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 방구 뀌는 냄비를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔.",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 위통 있는 개를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔.",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 자동차 실린더 헤드 개스킷을 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔.",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 사이코패스 아기를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔.",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 반바지 차림의 바퀴벌레를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔.",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 고추가 없는 남자 스트리퍼를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔.",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 줄넘기하는 배트맨을 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 달리는 호빗을 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 토하는 기린을 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 똥 싸는 아기를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 여자 피카츄 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 자위하는 원숭이를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 팬티 차림인 아이언맨 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 프랑수아 올랑드의 포피(성기의 귀두를 감싸는 피부)를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 개구리하고 후방섹스를 하는 경찰을 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 콘돔을 쓰고 있는 고양이를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 살아있는 의자를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 춤추는 곰을 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 전화하는 달걀을 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 자기의 똥꼬를 닦는 뱀파이어를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 죽은 쥐를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 사정하는 악어를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 자살하는 피노키오를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 술에 취한 여우를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 스케이트보드 타고 있는 토끼를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 나체인 여자 스머프를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 게이 사자를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 날으는 봅슬레이 썰매를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 속을 채운 칠면조를 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"22",text:"%s, 발기된 말을 그려. 그룹이 선택한 모르는 사람에게 이 그림이 뭔지 맞춰보라고 해, 만약 그 사람이 맞추면 너는 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 네가 마셔",key:"",parent_key:"",pack_name:"bar",language:"ko",nb_players:"1"}
]);
retrieveDB();