game.stored_db.bar_fr = [{type:"1",text:"%s, si tu tournes à la bière aromatisée tu bois, autrement tu distribues une gorgée",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, si tu tournes à la pinte tu bois, autrement tu distribues une gorgée",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, si tu tournes au demi (25cl) tu bois, autrement tu distribues une gorgée",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, prends le pire shooter du bar",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"Le dernier joueur à être allé dans un bar distribue 2 gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Le premier joueur à être entré dans le bar distribue $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Le premier joueur à être entré dans le bar boit",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Le dernier joueur à être entré dans le bar boit",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Le joueur ayant payé le moins jusqu'à maintenant boit",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Le joueur ayant payé le plus jusqu'à maintenant distribue $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"%s, si c'était ton idée de venir ici distribue $ gorgées. Sinon bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, si c'était ton idée de faire un Picolo Bar distribue $ gorgées. Sinon bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, bois autant que de défis Picolo que tu as foirés aujourd'hui. Aucun défi foiré ? Bois une gorgée quand même ",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, bois autant que de défis Picolo réalisés par l'équipe aujourd'hui",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, bois autant que de défis Picolo que tu as réalisés aujourd'hui. Aucun défi réalisé ? Bois une gorgée quand même ",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, bois autant que de défis Picolo refusés par tous les joueurs d'aujourd'hui",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, bois autant que de défis Picolo que tu as refusés aujourd'hui. Aucun défi refusé ? Bravo ! Tu distribues $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, si tu as une pièce mets-là dans le verre du joueur qui en boira $. Bois $ gorgées sinon",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s et %s égalisent leur verre : le joueur ayant le verre le plus rempli le verse dans le verre de l'autre",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"1",text:"%s et %s égalisent leur verre : le trop plein du plus grand verre finit dans l'estomac de son propriétaire",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"1",text:"%s, va demander des pailles pour tout le monde ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"Le premier joueur à aller poser un étron aux chiottes sans tirer la chasse pourra distribuer un cul sec !",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"%s, la prochaine personne que tu touches boit",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, fais boire quelqu'un si t'as fait plusieurs bars aujourd'hui, sinon bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, fais boire quelqu'un si t'as parlé au serveur, sinon bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, fais boire quelqu'un si t'as déjà payé quelque chose, sinon bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, fais boire quelqu'un s'il y a des serveuses, sinon bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, fais boire quelqu'un si t'es déjà venu(e) dans ce bar avant aujourd'hui, sinon bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, fais boire quelqu'un si t'es jamais venu(e) dans ce bar avant aujourd'hui, sinon bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, fais boire quelqu'un si tu connais d'autres personnes dans le bar que celles qui sont en train de jouer, sinon bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"S'il y a d'autres joueurs de Picolo Bar autre que votre table, démerdez-vous pour leur offrir un verre. Sinon tout le monde trinque !",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"%s, fais boire quelqu'un si t'as déjà pécho dans ce bar, sinon bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, distribue un cul sec si tu as un ou une ex qui rôde par ici, bois sinon",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, si t'es déjà sorti(e) avec un barman ou une barmaid tu bois, autrement tu donnes une gorgée",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, si t'es déjà sorti(e) avec un serveur ou une serveuse tu bois, autrement tu donnes une gorgée",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, distribue autant de gorgées qu'il y a de thons dans le bar, hormis tes potes",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, distribue autant de gorgées qu'il y a de canons dans le bar, hormis tes potes",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, distribue autant de gorgées qu'il y a de types chauves dans le bar, bois s'il n'y en a pas",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, distribue autant de gorgées qu'il y a de binoclards dans le bar (4 max), tu bois s'il n'y en a pas",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, choisis quelqu'un pas trop loin. A ton top\u0022 si cette personne inconnue ne parle pas dans les 7 secondes tu peux distribuer $ gorgées tu boiras sinon\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, choisis quelqu'un pas trop loin. A ton top\u0022 si cette personne inconnue reste dans la même position 7 secondes tu peux distribuer $ gorgées tu boiras sinon\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, choisis quelqu'un pas trop loin. A ton top\u0022 si cette personne inconnue ne regarde pas dans ta direction dans les 12 premières secondes tu peux distribuer $ gorgées tu boiras sinon\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, choisis quelqu'un d'assis pas trop loin. A ton top\u0022 si cette personne inconnue se lève dans les 15 secondes tu peux distribuer $ gorgées ! Tu boiras sinon\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, choisis une personne inconnue debout pas trop loin. A ton top\u0022 si cette personne s'assoit dans les 15 secondes tu peux distribuer $ gorgées ! Tu boiras sinon\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, choisis quelqu'un pas trop loin. A ton top\u0022 si cette personne inconnue rigole dans les 7 secondes tu peux distribuer $ gorgées tu boiras sinon\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, choisis quelqu'un pas trop loin. A ton top\u0022 si cette personne inconnue sourit dans les 4 secondes tu peux distribuer $ gorgées tu boiras sinon\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, choisis quelqu'un pas trop loin. A ton top\u0022 si cette personne inconnue boit dans les 7 secondes tu peux distribuer $ gorgées tu boiras sinon\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, choisis quelqu'un pas trop loin. A ton top\u0022 si cette personne inconnue ne boit pas dans les 10 secondes tu peux distribuer $ gorgées tu boiras sinon\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, choisis quelqu'un pas trop loin. A ton top\u0022 si cette personne inconnue ne sourit pas dans les 5 secondes tu peux distribuer $ gorgées tu boiras sinon\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, choisis quelqu'un pas trop loin. A ton top\u0022 si cette personne inconnue ne rigole pas dans les 10 secondes tu peux distribuer $ gorgées tu boiras sinon\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, choisis quelqu'un pas trop loin. A ton top\u0022 si cette personne inconnue commande dans les 30 secondes tu peux distribuer $ gorgées tu boiras sinon\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s et %s, choisissez un poulain chacun (un / une inconnue). Celui dont le poulain parlera en premier distribuera $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"1",text:"%s et %s, choisissez un poulain chacun (un / une inconnue). Celui dont le poulain commandera en premier distribuera $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"1",text:"%s et %s, choisissez un poulain chacun (un / une inconnue). Celui dont le poulain fumera en premier distribuera $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"1",text:"%s et %s, choisissez un poulain chacun (un / une inconnue). Celui dont le poulain ira aux chiottes en premier distribuera $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"1",text:"%s et %s, choisissez un poulain chacun (un / une inconnue). Celui dont le poulain sourira en premier distribuera $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"1",text:"%s et %s, choisissez un poulain chacun (un / une inconnue). Celui dont le poulain rigolera en premier distribuera $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"1",text:"Le premier d'entre vous à avoir commandé va gentiment boire 2 gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Le dernier d'entre vous à avoir commandé, rattrape ton retard en buvant 2 gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"%s, si tu as serré la main ou fait la bise à un membre du staff tu bois. Sinon fais boire quelqu'un",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, si tu as un dessous de verre fais boire quelqu'un, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, si ce bar est ton bar préféré dans cette ville assume et bois, autrement tu distribues $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, distribue $ gorgées si t'es déjà venu(e) plus de 3 fois dans ce bar, autrement bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, distribue $ gorgées si t'es déjà venu(e) dans ce bar il y a plus d'un an, autrement bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, distribue $ gorgées si tu t'es déjà embrouillé(e) avec quelqu'un dans ce bar, autrement bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, distribue $ gorgées si tu t'es déjà mis(e) une énorme race dans ce bar, autrement bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, distribue $ gorgées si t'es déjà venu(e) en couple dans ce bar, autrement bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, distribue $ gorgées si t'es déjà venu(e) célibataire dans ce bar, autrement bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, si tu as dit bonjour aux serveurs en arrivant tellement tu connais le coin distribue $ gorgées, autrement bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, si t'as commencé la soirée par un soft tu bois, autrement fais boire quelqu'un",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, si t'as déjà vomi en sortant de ce bar distribue $ gorgées, autrement tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"Le premier joueur à trouver un couple distribue $ gorgées. Personne ? Tout le monde boit !",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Le premier joueur à trouver un couple qui se font iech distribue $ gorgées. Personne ? Tout le monde boit !",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Le premier joueur à trouver un type qui rigole distribue $ gorgées. Personne ? Tout le monde boit !",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Le premier joueur à trouver une fille en robe distribue $ gorgées. Personne ? Tout le monde boit !",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Le premier joueur à trouver un shooter distribue $ gorgées. Personne ? Tout le monde boit !",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Le premier joueur à trouver une pinte vide distribue $ gorgées. Personne ? Tout le monde boit !",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Le premier joueur à trouver un animal distribue $ gorgées. Personne ? Tout le monde boit !",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Le premier joueur à trouver une table vide distribue $ gorgées. Personne ? Tout le monde boit !",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Le premier joueur à trouver un groupe de 4 potes distribue $ gorgées. Personne ? Tout le monde boit !",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Si vous êtes en terrasse, %s peut distribuer une gorgée. Si vous êtes à l'intérieur, %s boit",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"1",text:"Si vous êtes tous arrivés en même temps, %s tu bois. S'il y a eu des retardataires ça sera %s",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"1",text:"%s, si tu es la première personne arrivée tu peux distribuer $ gorgées, sinon bois, ça t'apprendra",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"%s, soit tu es la dernière personne arrivée et tu bois $ gorgées, soit tu distribues une gorgée",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"Ceux qui ont déjà commencé à dire j'ai oublié ma carte tu peux m'avancer ?\u0022 vous buvez $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Ceux qui ont râlé parce qu'ils auraient voulu être dans un autre bar boivent",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"Ceux qui ont quelque peu râlé parce qu'ils voulaient pas sortir ce soir boivent",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"1",text:"%s, si t'as déjà tenté un défi Picolo Bar\u0022 tu peux distribuer une gorgée. Et tu bois s'il a été foiré\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"1",text:"Est-ce les happy hours ? Oui, %s boit. Non, c'est %s qui boit",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"1",text:"S'il n'y a pas de musique ici, %s c'est ta faute tu bois une gorgée. S'il y en a merci à toi ! Bois 2 gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, t'es mister coffee. Tu vas demander un café, surtout ne le bois pas et garde le pour la suite",key:"coffee",parent_key:"",pack_name:"bar",language:"fr",nb_players:"3"},
{type:"2",text:"%s peut dès à présent partager son café, équitablement ou non, dans les verres de %s et %s",key:"",parent_key:"coffee",pack_name:"bar",language:"fr",nb_players:"3"},
{type:"2",text:"%s, choisis dans quel verre tu vas pouvoir mettre ton café froid",key:"",parent_key:"coffee",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, tu vas pouvoir mettre ton café froid dans ton verre... A la tienne !",key:"",parent_key:"coffee",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, joue le rythme de la musique en claquant des doigts jusqu'à nouvel ordre. Ou bois $ gorgées à chaque nouvelle chanson",key:"click-finger",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, tu peux arrêter de claquer des doigts",key:"",parent_key:"click-finger",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, va boire seul(e) au bar",key:"alone-at-the-bar",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s peut revenir !",key:"",parent_key:"alone-at-the-bar",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, aies l'air con s'il te plait : de temps en temps gueule un coup en mode mongolito. Tu pourras distribuer une gorgée pour chaque cri",key:"I-assume-mongolito",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, t'as fini d'être débile",key:"",parent_key:"I-assume-mongolito",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, tu boiras avec 3 pailles à partir de maintenant ou ça sera une gorgée pour chaque nouvelle règle",key:"3-straws",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, tu peux arrêter les 3 pailles",key:"",parent_key:"3-straws",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, choisis ton serveur chouchou. Dès qu'il sert un verre, fais un prout avec ta bouche ou bois une gorgée",key:"choose-waiter",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, arrête de faire des prouts avec ta bouche, c'est ridicule",key:"",parent_key:"choose-waiter",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, t'es l'hypersociable de la soirée, dis bonjour à chaque personne qui passe devant toi. Une gorgée par bonjour loupé",key:"hypersocial",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, t'as fini d'être hyper sociable",key:"",parent_key:"hypersocial",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, trouve un tampon et garde-le sur l'oreille, ça c'est la classe",key:"tampon-ear",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, enlève ton tampon ça saigne plus",key:"",parent_key:"tampon-ear",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, t'es puni(e) ! Va au coin du bar. Si des gens te parlent, t'as que le droit de dire JE SUIS PUNI(E)\u0022\u0022",key:"punition",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s peut revenir ! Ou pas, vous pouvez simplement passer la règle ;)",key:"",parent_key:"punition",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, reste sous la table. On te dira quand revenir",key:"under-the-table",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s peut revenir parmi nous ! On peut aussi faire comme si cette règle n'était jamais passée",key:"",parent_key:"under-the-table",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, choisis une fille à la table d'à côté. Dès qu'elle boit tu devras dire ooooolé\u0022\u0022",key:"choose-your-partner",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, t'as fini d'emmerder la fille d'à côté !",key:"",parent_key:"choose-your-partner",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, choisis une personne inconnue pas trop loin. Dès que ton élu(e) parle, tu dois faire blablablablabla\u0022\u0022",key:"speak-when-other-speak",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"2",text:"%s, laisse donc cette personne tranquille",key:"",parent_key:"speak-when-other-speak",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"4",text:"Jeu de la pièce jusqu'à la fin du jeu ! %s, prends une pièce et mets-la dans un verre. La cible prendra $ gorgées, et pourra à son tour distribuer la pièce ",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"4",text:"Mettez un paquet de clopes sur sa tranche au bord de la table, chacun essaye à son tour de lui faire faire un tour d'un seul coup. Les perdants boivent, les gagnants distribuent une gorgée, %s à toi l'honneur",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"4",text:"Mettez une pièce au bord de la table, chacun essaye à son tour de la rapprocher le plus possible du bord d’en face d'un seul coup. Le plus proche distribue 3 gorgées, %s à toi l'honneur",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"4",text:"Blind test ! Le premier joueur qui donne le titre de la chanson actuelle distribue $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"4",text:"Petit téléphone arabe ! %s tu choisis une phrase et tu la chuchotes à ton voisin de gauche. Ainsi de suite jusqu'à arriver de nouveau à toi. Les joueurs qui auront merdé boivent",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"4",text:"%s commence par faire tourner une pièce sur la table. Chacun votre tour, donnez un coup avec votre doigt pour continuer de la faire tourner. Le perdant boit $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"4",text:"Blind test ! Le premier joueur qui donne l'interprète de la chanson actuelle distribue $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"4",text:"Blind test ! Le premier joueur qui trouve le titre de la chanson d'avant distribue $ gorgées. Personne ? Tout le monde boit",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"4",text:"Faites une partie de Mikado avec une vingtaine de clopes. Chaque cigarette prise dans les règles permet de donner une gorgée, %s commence",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"16",text:"Chacun votre tour, tentez de deviner quelle est la fille la plus canon du bar selon %s. Le premier qui trouve distribue $ gorgées ! %s commence",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"16",text:"Chacun votre tour, tentez de deviner quel est LE type bogoss du bar selon %s. Le premier qui trouve distribue $ gorgées ! %s commence",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"16",text:"Chacun votre tour, tentez de deviner quelle est la fille la plus facile du bar selon %s. Le premier qui trouve distribue $ gorgées ! %s commence",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"16",text:"Chacun votre tour, tentez de deviner quelle est la fille la plus moche du bar selon %s. Le premier qui trouve distribue $ gorgées ! %s commence",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"16",text:"Chacun votre tour, tentez de deviner quel est le type le plus en manque du bar selon %s. Le premier qui trouve distribue $ gorgées ! %s commence",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"16",text:"Chacun votre tour, tentez de deviner quel est le type le plus moche du bar selon %s. Le premier qui trouve distribue $ gorgées ! %s commence",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"16",text:"Chacun votre tour, tentez de deviner quel est le meilleur alcool du bar selon %s. Le premier qui trouve distribue $ gorgées ! %s commence",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"16",text:"Chacun votre tour, tentez de deviner quelle est la meilleure bière du bar selon %s. Le premier qui trouve distribue $ gorgées ! %s commence",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"16",text:"Chacun votre tour, tentez de deviner quelle est la fille la plus chaude du bar selon %s. Le premier qui trouve distribue $ gorgées ! %s commence",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"16",text:"Chacun votre tour, tentez de deviner quel est le meilleur bar de la ville selon %s. Le premier qui trouve distribue $ gorgées ! %s commence",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"16",text:"Chacun votre tour, tentez de deviner quelle est la meilleure boîte de la ville selon %s. Le premier qui trouve distribue $ gorgées ! %s commence",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"16",text:"Chacun votre tour, tentez de deviner quel est le lieu en ville où c'est le plus facile pour pécho selon %s. Le premier qui trouve distribue $ gorgées ! %s commence",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"16",text:"Chacun votre tour, tentez de deviner quelle est la meilleure chanson du moment selon %s. Le premier qui trouve distribue $ gorgées ! %s commence",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"17",text:"%s, t'es désigné(e) pour commander la prochaine tournée, et interdit pour toi d'utiliser les verbes avoir\u0022 \u0022prendre\u0022 et \u0022commander\u0022\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"17",text:"%s et %s, commandez en même temps. Le premier servi distribuera $ gorgées pendant que l'autre les boira",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"17",text:"%s, va chercher un petit amuse-gueule pour tout le monde ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"17",text:"%s, sors le porte-feuille et paye la prochaine tournée",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"17",text:"%s, offre à %s le cocktail de son choix",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"17",text:"Ça va s'enjailler... %s paye sa tournée de shooters !",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"17",text:"Pour info, le dernier à terminer son verre paiera la prochaine tournée...",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"17",text:"%s, s'il y a un joueur à qui il reste une paire de coui***, paye lui donc un shooter",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"17",text:"%s, paye ta pinte ! Elle sera pour %s ou %s, au premier qui finira son verre.",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"3"},
{type:"17",text:"%s, paye ton verre ! %s, choisis ce que tu veux ",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"17",text:"%s, paye un verre à un ou une inconnue choisie par %s",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"17",text:"Plutôt un mètre de shooters ou des mojitos ? Votez en même temps, les perdants payent la bonne réponse pour la prochaine tournée",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"17",text:"Plutôt bières blondes ou blanches ? Votez en même temps, les perdants payent la bonne réponse pour la prochaine tournée",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"17",text:"Plutôt bière ou n'importe quoi d'autre ? Votez en même temps, les perdants payent la bonne réponse pour la prochaine tournée",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"0"},
{type:"17",text:"%s, soit tu bois 6 culs secs d'affilée, soit tu te proposes gentiment pour payer la prochaine tournée",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"17",text:"%s, tu décides qui paye la prochaine tournée entre %s et %s",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"3"},
{type:"17",text:"%s, tu décides qui paye la prochaine tournée",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"17",text:"%s, grande princesse ! T'as le droit de te faire payer un verre par un joueur au choix et tu choisis ce que tu veux",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va taxer une capote ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va taxer une cigarette ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va demander à une personne inconnue si elle connait Picolo. Si c'est le cas tu distribues $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, essaye de deviner l'âge d'une personne inconnue choisie par %s. Va lui demander, si tu gagnes tu distribues $ gorgées, tu bois sinon",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"18",text:"%s, essaye de deviner la taille d'une personne inconnue choisie par %s. Va lui demander, si tu gagnes tu distribues $ gorgées, tu bois sinon",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"18",text:"%s, essaye de deviner la taille de soutif d'une inconnue choisie par %s. Va lui demander, si tu gagnes tu distribues $ gorgées, tu bois sinon",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"18",text:"%s, essaye de deviner la taille de pied d'une personne inconnue choisie par %s. Va lui demander, si tu gagnes tu distribues $ gorgées, tu bois sinon",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"18",text:"%s, choisis une personne inconnue. Si elle est célibataire tu distribues $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, laisse %s choisir une personne inconnue. Essaye de deviner à quelle heure elle est arrivée. Tu gagnes tu distribues $ gorgées, tu perds tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"18",text:"%s, va proposer une chanson au bar. Tout refus sera pénalisé d'une gorgée, tu pourras en distribuer $ s'ils acceptent",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va demander au DJ de baisser le son ou bois $ gorgées. Défi réussi ? Tu peux distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va demander au DJ de monter le son ou bois $ gorgées. Défi réussi ? Tu peux distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, raconte une blague à une personne inconnue. Si tu fais rire ou sourire tu pourras distribuer $ gorgées. Refuse et bois $ gorgées ",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, accoste un groupe d'inconnus en montrant une photo de mouche, ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, accoste un groupe d'inconnus en montrant une photo de dinosaure, ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, accoste un groupe d'inconnus en montrant une photo de choucroute, ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, demande à un groupe d'inconnus si ton toboggan les intéresse (montre une photo leboncoin), ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, demande à un groupe d'inconnus si ton portemanteau les intéresse (montre une photo leboncoin), ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, demande à un groupe d'inconnus si ton micro-ondes les intéresse (montre une photo leboncoin), ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, fais une déclaration d'amour à une personne inconnue ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, demande à un groupe si tu peux les prendre en photo tellement tu les trouves beaux, ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, demande à une personne inconnue de vous prendre en photo, envoie-nous la photo à l'occaz ;)",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, montre cet écran au barman. S'il boit, tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, montre cet écran à un type inconnu. S'il boit, tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, montre cet écran à une inconnue. Si elle boit, tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, dessine un éléphant sur une serviette et offre-la à une personne inconnue choisie par %s, ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"18",text:"%s, dessine une pomme sur une serviette et offre-la à une personne inconnue choisie par %s, ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"18",text:"%s, dessine un lapin sur une serviette et offre-la à une personne inconnue choisie par %s, ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"18",text:"%s, fais une bataille de pouce avec une personne inconnue choisie par %s. Si tu gagnes, distribue $ gorgées. Si ton adversaire refuse ou gagne, tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"18",text:"%s, fais un Chifoumi avec une personne inconnue choisie par %s. Si tu gagnes, distribue $ gorgées. Si ton adversaire refuse ou gagne, tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"18",text:"%s, demande à une personne inconnue choisie par %s de deviner ton âge. Si c'est gagné, jackpot ! Tu distribues $ gorgées. Autrement bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"18",text:"%s, demande à une personne inconnue choisie par %s de deviner ta taille. Si c'est gagné, jackpot ! Tu distribues $ gorgées. Autrement bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"18",text:"%s, demande à une personne inconnue choisie par %s de deviner combien tu chausses. Si c'est gagné, jackpot ! Tu distribues $ gorgées. Autrement bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"18",text:"%s, ramène le numéro d'un serveur ou d'une serveuse, ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu as 5 minutes pour trouver une personne mariée. Si tu échoues tu bois, autrement tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, trouve une personne qui a téléchargé Picolo. Tu as 3 chances, réussis et tu peux distribuer $ gorgées. Si tu refuses tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, trouve une personne qui n'a pas téléchargé Picolo. Si tu réussis à lui faire télécharger, tu pourras distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, trouve une personne qui a testé et kiffé Picolo. Réussis et tu pourras distribuer $ gorgées, échoue et bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, fais un clin d'oeil à une personne choisie par %s ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"18",text:"%s, demande au serveur son prénom. S'il le donne tu pourras distribuer une gorgée",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, sens le cul d'un inconnu discrètement... Bois $ gorgées si tu refuses",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, demande à une personne inconnue si elle est pour ou contre l'avortement chez les crevettes. Pour : tu peux distribuer $ gorgées. Contre : tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, demande à une personne inconnue si elle est pour ou contre le racisme contre les singes albinos. Pour : tu peux distribuer $ gorgées. Contre : tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, ramène le numéro d'une personne inconnue ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, donne ton numéro à une personne inconnue choisie par le groupe, ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tente de deviner le signe astrologique d'une personne inconnue, va lui demander pour valider le défi. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, donne ton numéro à une personne inconnue en disant que tu vends des produits de santé. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va proposer ton numéro à une personne inconnue en disant que t'es coach sportif. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, demande à une personne inconnue de te prendre en photo. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, demande à une personne inconnue si elle peut faire un selfie avec ton téléphone. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, joue à pile ou face avec une personne inconnue. Tu gagnes le défi si tu gagnes le pile ou face. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, demande à une personne inconnue de deviner ton signe astrologique. Tu gagnes si elle tombe juste. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, trouve une personne vegan. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, propose une partie de ping pong imaginaire à une personne inconnue. Tu gagnes si elle accepte. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, propose un combat d'épées imaginaires à une personne inconnue. Tu gagnes si elle accepte. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, propose une partie de beach volley imaginaire à une personne inconnue. Tu gagnes si elle accepte. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, propose une partie de hockey imaginaire à une personne inconnue (tu seras le gardien). Tu gagnes si elle accepte. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, propose un câlin gratuit à une personne inconnue. Tu gagnes si elle accepte. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois imiter et faire deviner un singe à une personne inconnue. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois imiter et faire deviner un hippopotame à une personne inconnue. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois imiter et faire deviner un papillon à une personne inconnue. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois imiter et faire deviner un chien enragé à une personne inconnue. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois imiter et faire deviner un ours à une personne inconnue. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois imiter et faire deviner le sport suivant à une personne inconnue : le hockey subaquatique. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois imiter et faire deviner le sport suivant à une personne inconnue : le bobsleigh. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois imiter et faire deviner l'épreuve suivante à une personne inconnue : le relais 4×100m nage libre. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois imiter et faire deviner le terme photo-finish\u0022 à une personne inconnue. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois imiter et faire deviner Lance Armstrong\u0022 à une personne inconnue. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, choisis la question que tu veux. Tu va devoir la poser à une personne inconnue et prédire sa réponse. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va deviner le prénom d'une personne inconnue, tu as 60 secondes. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va deviner la ville de naissance d'une personne inconnue, tu as 60 secondes. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va deviner la date de naissance d'une personne inconnue, tu as 60 secondes. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va deviner l'âge d'une personne inconnue, tu as 60 secondes. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va deviner la taille d'une personne inconnue, tu as 60 secondes. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, lance un objet rond vers un groupe d'inconnus et dis GRENADE\u0022. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois réussir à faire dire le mot Boudin\u0022 à une personne inconnue sans dire le mot ni un mot de la même famille. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois réussir à faire dire le mot Bouton blanc\u0022 à une personne inconnue sans dire le mot ni un mot de la même famille. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois réussir à faire dire le mot Brosse à chiotte\u0022 à une personne inconnue sans dire le mot ni un mot de la même famille. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois réussir à faire dire le mot Chemin boueux\u0022 à une personne inconnue sans dire le mot ni un mot de la même famille. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, tu dois réussir à faire dire le mot Dégorger le poireau\u0022 à une personne inconnue sans dire le mot ni un mot de la même famille. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va demander quelque chose à quelqu'un la bouche pleine. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va taxer du rouge à lèvres à une personne inconnue. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va taxer un mouchoir à une personne inconnue, dis que tu comptes t'en servir comme PQ. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va offrir un cadeau à une personne inconnue. Ce que tu veux. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va serrer la main d'au moins 10 personnes inconnues, tu as 30 secondes. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, joue avec une personne inconnue : citez à tour de rôle les personnages d'Harry Potter. Si tu en cites plus que ton adversaire, tu gagnes le défi. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, joue avec une personne inconnue : citez à tour de rôle les mots qui riment avec -nar. Si tu en cites plus que ton adversaire, tu gagnes le défi. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, joue avec une personne inconnue : citez à tour de rôle les mots qui riment avec -ouille. Si tu en cites plus que ton adversaire, tu gagnes le défi. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, joue avec une personne inconnue : citez à tour de rôle les mots qu'on utilise à la place de pénis\u0022. Si tu en cites plus que ton adversaire tu gagnes le défi. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, joue avec une personne inconnue : citez à tour de rôle les méchants dans les films. Si tu en cites plus que ton adversaire, tu gagnes le défi. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, joue avec une personne inconnue : citez à tour de rôle les endroits où on se sert d'une serviette. Si tu en cites plus que ton adversaire, tu gagnes le défi. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va lire un passage d'Harry Potter à une personne inconnue. Celui que tu veux. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va lire un passage d'une chanson de Black M à une personne inconnue. Celui que tu veux. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va lire un passage d'une chanson de Maitre Gims à une personne inconnue. Celui que tu veux. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va lire un passage d'une chanson de Matt Pokora à une personne inconnue. Celui que tu veux. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va lire un passage d'une chanson de Sheryfa Luna à une personne inconnue. Celui que tu veux. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va payer quelque chose à une personne inconnue. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va demander à une personne inconnue de t'écrire un mot doux sur le bras. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va demander à une personne inconnue de te faire un dessin sur le front. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, va demander à une personne inconnue de t'écrire des chiffres sur le bras, ça doit commencer par 06. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"18",text:"%s, chaque joueur te dit un mot. Tu dois dire une ou plusieurs phrases qui contient ces mots à une personne inconnue. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, choisis un sous-fifre à cette table. S'il réussit le défi que tu lui proposes tu pourras distribuer $ gorgées, sinon il (elle) les boira",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, choisis un défi pour %s. $ gorgées en jeu, attention en cas d'échec vous boirez tous les deux",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"19",text:"%s, choisis un défi pour %s, qui pourra distribuer $ gorgées en cas de réussite, ou boire $ gorgées en cas d'échec",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"19",text:"%s, passe sous la table à 4 pattes ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, laisse %s te mordre le cul ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"19",text:"%s, mets une cacahuète ou une chips dans ton verre ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, laisse %s mettre un peu d'autres verres dans le tien ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"19",text:"%s, mets une de tes chaussettes sur la table ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, mets une de tes chaussures sur la table ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, mets toi pieds nus ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, va aux toilettes et reviens avec le haut à l'envers, ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, va aux chiottes en courant, en mettant une main sur tes fesses ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, sors des chiottes avec une vilaine tache d'eau dans la zone pubienne, ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, fais un moonwalk devant tout le monde ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, sors des chiottes avec 3 feuilles de PQ qui dépassent du pantalon, ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, sors des chiottes en disant au premier que tu croises Bonne chance au prochain\u0022 ou bois\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, va aux chiottes, interpelle une personne inconnue avant en lui disant Je vais faire un beau bordel\u0022 ou bois\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, va te mettre la raie des cheveux au milieu ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, va mettre ton pantalon à l'envers ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, prends toi une fessée par %s ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"19",text:"%s, laisse ton numéro de téléphone et ton prénom sur un dessous de verre et laisse-le après le jeu. Si tu refuses tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, dessine-toi des fausses lunettes ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, laisse un mickey sur un dessous de verre ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, si tu arrives à passer derrière le bar tu pourras distribuer $ gorgées, tu en bois $ sinon",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, demande un bac à glaçons et tu feras boire quelqu'un, échappe-toi et bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, mets un pied sur la table et tu feras boire quelqu'un, échappe-toi et tu boiras une gorgée",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, trouve du rouge à lèvres, mets-en sur les lèvres en débordant, ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, la prochaine fois que tu vas pisser, va dans le chiotte du sexe opposé et tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, fais le tour de la table et sens les cheveux de tous les joueurs, ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, bois un shooter en utilisant un tampon propre : tu le trempes tel un biscuit suçable et tu aspires. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, mets quelques postillons dans ton verre ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, laisse %s lécher tout le tour de ton verre ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"19",text:"%s, lèche la table ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, prends toi une claque par %s ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"19",text:"%s, allonge tes jambes en posant tes pieds sur une chaise jusqu'à ce qu'un serveur s'agace, ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, mâche ton dessous de verre 30 secondes ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, laisse %s te mettre un petit coup de maquillage ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"2"},
{type:"19",text:"%s, mange un glaçon ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, pousse un énorme cri façon Chewbacca de Star Wars ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, fais des claquettes devant tout le monde ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, rote fort ou bois. Ouais c'est dégueu mais c'est le jeu",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, mets le dessous de verre dans ton verre ou bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, fais-toi écrire ROUBIGNOLE sur le front au feutre. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, fais-toi écrire TROUDUC sur le front au feutre. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, laisse-toi dessiner des moustaches. Garde le chef-d'oeuvre jusqu'à la fin du jeu. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, applaudis les deux bras en l'air 5 bonnes secondes. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, chante une chanson à haute voix 10 bonnes secondes. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, chante une chanson paillarde à haute voix pendant 10 secondes. Tu as 10 secondes pour trouver les paroles. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, chante une chanson de Céline Dion à haute voix pendant 10 secondes. Tu as 10 secondes pour trouver les paroles. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, renifle le cul de tous les joueurs, fais-toi remarquer au maximum. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, défi libre ! Le groupe te propose un défi. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, lance un objet rond vers un groupe d'inconnus et dis PIKACHU ATTAQUE ÉCLAIR\u0022. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, fais de la capoeira devant un maximum d'audience. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, fais une roulade. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, fais un sprint sur 10m. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, montre d'un bras tendu les personnes inconnues qui te plaisent. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, fais semblant de tirer au pistolet les pigeons imaginaires pendant 15 secondes. N'oublie pas les bruits du fusil. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, va faire un échauffement : montée de genoux, talons aux fesses, etc.. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, fais 10 burpees (1 burpee = une pompe enchaînée avec un saut). Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, étale-toi de la terre sur la figure. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, lève-toi et fais un doigt à une personne imaginaire. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, monte sur ta moto imaginaire et va faire un petit tour. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, monte sur ton kayak imaginaire et va faire un tour. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, monte dans ton bus imaginaire et va faire un tour. N'hésite pas à proposer aux passants de monter à bord. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, parcours le plus de distance possible en marche athlétique en 20 secondes. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, écarte-toi du groupe et bats le record du monde du triple saut. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, écarte-toi du groupe et bats le record du monde du saut à la perche imaginaire. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, écarte-toi du groupe et bats le record du monde du saut en longueur. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, écarte-toi du groupe et bats le record du monde du lancer du marteau imaginaire. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, écarte-toi du groupe et bats le record du monde du lancer du javelot imaginaire. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, écarte-toi du groupe et bats le record du monde du lancer du disque imaginaire. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, écarte-toi du groupe et bats le record du monde du lancer du poids imaginaire. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, écarte-toi du groupe, et tape le pénalty de la gagne. La foule attend.... Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, écarte-toi du groupe, et bats le record de panier à 3 points imaginaire en 20 sec. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, dans la peau de Djokovic. Écarte-toi du groupe, et travaille ton service imaginaire jusqu'à la fin du chrono. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, écarte-toi du groupe, lève une jambe, montre au public que tu forces, et dis ça va mieux\u0022. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, fais comme si tu t'énervais, et crie MAIS JE SUCE PAS QUE DES ANIMAUX\u0022. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, dis de façon assez forte (les groupes d'inconnus les plus proches doivent t'entendre) : ... Et maintenant tu sais pourquoi mes légumes sentent l'anus\u0022. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, dis de façon assez forte (les groupes d'inconnus les plus proches doivent t'entendre) : ... C'était la dernière fois que j'ai fait un anulingus à un bouc\u0022. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, dis de façon assez forte (les groupes d'inconnus les plus proches doivent t'entendre) : ... Et là ils m'ont surpris en pleine masturbation anale\u0022. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, dis de façon assez forte (les groupes d'inconnus les plus proches doivent t'entendre) : ... Ça me rappelle mes hémorroïdes y'a 3 semaines\u0022. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, dis de façon assez forte (les groupes d'inconnus les plus proches doivent t'entendre) : ... J'ai rarement mis autant de choses dans son anus\u0022. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, dis de façon assez forte (les groupes d'inconnus les plus proches doivent t'entendre) : ... Un peu plus et mon chat léchait le sperme\u0022. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, rapproche-toi de la foule, gratte-toi à l'intérieur du slip, et sens tes doigts. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, place-toi à plat ventre, et tire sur les passants avec ton sniper imaginaire, pendant 20 secondes. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, tourne en rond en claquant des doigts pendant 20 secondes. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, va faire un tour, minimum 50m, de marche en canard rapide (marcher les fesses le plus près possible du sol). Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, va faire un tour en nageant. Tu peux choisir la nage. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, écarte-toi du groupe et bats le record du monde de l'épaulé-jeté imaginaire (Haltérophilie) . Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, va te mouiller la totalité des cheveux et reviens. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, va te faire une écharpe en papier toilette et reviens. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, imite un saumon sorti de l'eau pendant 10 secondes. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, va mettre tes sous-vêtements par dessus tes vêtements. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, écarte-toi du groupe et fais le chien qui court après sa queue. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, attache tes pieds entre eux comme tu peux et va faire un tour. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, place-toi à l'écart, et tire sur les passants avec ton arc imaginaire. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, garde quelque chose sur le visage jusqu'à la fin de la partie. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, garde quelque chose sur la tête jusqu'à la fin de la partie. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, crache par terre. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, aboie, de sorte que les groupes d'inconnus les plus proches t'entendent. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, meugle (cri de la vache), de sorte que les groupes d'inconnus les plus proches t'entendent. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, grouine (cri du cochon), de sorte que les groupes d'inconnus les plus proches t'entendent. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, barète (fais le cri de l'éléphant), de sorte que les groupes d'inconnus les plus proches t'entendent. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, fais le cri du singe, de sorte que les groupes d'inconnus les plus proches t'entendent. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, fais le cri de la baleine, de sorte que les groupes d'inconnus les plus proches t'entendent. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, fais le cri de l'âne, de sorte que les groupes d'inconnus les plus proches t'entendent. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, cancane (fais le cri du canard), de sorte que les groupes d'inconnus les plus proches t'entendent. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, bêle (cri du mouton), de sorte que les groupes d'inconnus les plus proches t'entendent. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, crie le premier mot qui te vient à l'esprit. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, chaque joueur te dit un mot. Tu dois dire une ou plusieurs phrases qui contient ces mots, de sorte que les groupes d'inconnus les plus proches t'entendent. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, crie le premier mot qui te vient à l'esprit, et qui rime avec NAR\u0022. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, crie le premier mot qui te vient à l'esprit, et qui rime avec ITE\u0022. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, crie le premier mot qui te vient à l'esprit, et qui rime avec NUSSE\u0022. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, crie le premier mot qui te vient à l'esprit, et qui rime avec NASSE\u0022. Ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"19",text:"%s, jette quelque chose à au moins 5m de toi, par dessus ton épaule. Ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve un type qui s'appelle Antoine ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve un type qui s'appelle Romain ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve un type qui s'appelle Nathan ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve un type qui s'appelle Valentin ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve un type qui s'appelle Clément ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve un type qui s'appelle Damien ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve un type qui s'appelle Laurent ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve un type qui s'appelle Stéphane ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve un type qui s'appelle Alan ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve un type qui s'appelle Jérôme ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve un type qui s'appelle Séraphin ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve une fille qui s'appelle Géraldine ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve une fille qui s'appelle Alicia ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve une fille qui s'appelle Camille ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve une fille qui s'appelle Jessica ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve une fille qui s'appelle Justine ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve une fille qui s'appelle Laura ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve une fille qui s'appelle Marine ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve une fille qui s'appelle Mathilde ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve une fille qui s'appelle Margaux ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"20",text:"%s, trouve une fille qui s'appelle Maïlys ou bois. Tu as 3 chances, si tu réussis tu pourras distribuer $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque choucroute\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque plug anal\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque phallus\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque furoncle\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, dessine-toi un mono sourcil ou bois $ gorgées",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque trompette\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque vaseline\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque déchet\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque viagra\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque gastro\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque sexe anal\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque vierge\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque Ténia\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque cyprine\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque sperme\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque biscotte\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque kyste\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque poil pubien\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque coït buccal\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque en chaleur\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque tartine\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"21",text:"%s, marque slip\u0022 sur ton front ou bois $ gorgées\u0022",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine une prostituée sur un cheval. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un mammouth qui chie un lémurien. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine une licorne lesbienne. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un pince-oreille gymnaste. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine une frite qui parle. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine une casserole qui pète. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un chien qui a la gastro. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un joint de culasse. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un bébé psychopathe. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un cafard en short. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un chippendale castré. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine Batman qui fait de la corde à sauter. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un hobbit qui court. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine une girafe qui vomit. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un bébé qui fait caca. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un pikachu femelle. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un singe qui se caresse. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine Iron Man en slip. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine le prépuce de François Hollande. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un CRS qui fait une levrette avec une grenouille. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un chat portant une capote. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine une chaise vivante. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un ours qui danse. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un oeuf qui téléphone. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un vampire qui se torche. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine une souris morte. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un crocodile qui éjacule. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine Pinocchio qui se suicide. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un renard bourré. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un lapin en skateboard. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine la Schtroumpfette à poil. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un lion gay. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un toboggan volant. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine une dinde farcie. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"},
{type:"22",text:"%s, dessine un cheval en érection. Fais deviner le dessin à une personne inconnue choisie par le groupe, si elle trouve tu peux distribuer $ gorgées, sinon tu bois",key:"",parent_key:"",pack_name:"bar",language:"fr",nb_players:"1"}];
game.pending_db = game.pending_db.concat(game.stored_db.bar_fr);