var db = TAFFY([{type:"1",text:"%s, ota huikka, jos juot maustettua olutta. Jos et, anna juomastasi huikka muille",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, ota huikka jos juot olutta tölkistä. Jos et, anna juomastasi huikka muille",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, ota huikka, jos juot olutta tuopista. Jos et, anna juomastasi huikka muille",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, käy tilaamassa baarin pahin shotti",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"Viimeksi baaritiskillä käynyt osallistuja jakaa kaksi huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Viimeisimpänä paikalle saapunut osallistuja jakaa kaksi huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Viimeksi baaritiskillä käynyt osallistuja ottaa huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Viimeisimpänä paikalle saapunut osallistuja ottaa huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Osallistuja, joka on maksanut tähän mennessä vähiten, ottaa huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Osallistuja, joka on maksanut tähän mennessä eniten, jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"%s, jaa $ huikkaa, jos tänne tuleminen oli sinun ideasi. Jos ei, ota itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jaa $ huikkaa, jos Picolo Barin pelaaminen oli sinun ideasi. Jos ei, ota huikka itse",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, juo niin monta huikkaa, kuin olet epäonnistunut suorittamaan Picolo-haasteen tänään. Juo, vaikka epäonnistuneita haasteita ei olisi yhtään",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, juo yhtä monta huikkaa kuin olet onnistunut Picolo-haasteissa tänään",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, juo yhtä monta huikkaa, kuin olet suorittanut Picolo-haasteita tänään. Juo, vaikka niitä ei olisi yhtään",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, juo yhtä monta huikkaa kuin Picolo-haasteita, joita et ole suostunut suorittamaan tänään",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, juo yhtä monta huikkaa kuin Picolo-haasteita, jotka olet kieltäytynyt suorittamasta tänään. Nolla? Bravo! Jaa huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jos sinulla on kolikko, laita se toisen osallistujan lasiin. Hänen tulee juoda $ huikkaa. Juo $ huikkaa, jos sinulla ei ole kolikkoa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s ja %s, vertailkaa lasejanne: se, kenellä on enemmän, kaataa osan toisen lasiin",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"1",text:"%s ja %s, vertailkaa lasejanne, se kenellä on lasissaan enemmän, juo niin paljon, että molemmissa laseissa on saman verran",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"1",text:"%s, käy pyytämässä pillit kaikille osallistujille, kiitos",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"Ensimmäinen, joka käy p*skalla eikä vedä vessaa sen jälkeen, saa määrätä toisen osallistujan juomaan lasinsa tyhjäksi!",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"%s, seuraava henkilö, johon kosket, juo huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jos olet ollut tänään useammassa baarissa, saat määrätä toisen osallistujan juomaan. Jos et, ota itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jos olet puhunut tarjoilijan kanssa illan aikana, saat määrätä toisen osallistujan juomaan. Jos et, juo itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jos olet maksanut jostakin juomasta tänään, saat määrätä toisen osallistujan juomaan. Jos et, ota itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, määrää jonkun osallistujista juomaan, jos baarissa on tarjoilijoita. Jos ei, juo itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jos olet ollut täällä aiemminkin, saat määrätä toisen osallistujan juomaan. Jos et, ota itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jos et ole koskaan aiemmin ollut täällä, saat määrätä toisen osallistujan juomaan. Jos olet, juo itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jos tunnet täältä muita kuin pelin osallistujat, saat määrätä jonkun juomaan. Jos et, ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"Jos paikalla on muita, jotka pelaavat Picoloa, teidän on tarjottava heille juomat. Muuten kaikki juovat!",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"%s, jos olet joskus pokannut jonkun tässä paikassa, saat määrätä toisen osallistujan juomaan. Jos et, juo itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jos joku existäsi käy säännöllisesti täällä, saat määrätä jonkun juomaan. Jos ei, juo itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, ota huikka, jos olet joskus harrastanut seksiä jonkun tämän baarin työntekijän kanssa. Jos et ole, jaa huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, juo huikka, jos olet joskus harrastanut seksiä tarjoilijan kanssa. Jos et, jaa huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jaa yhtä monta huikkaa kuin täällä on outoja tyyppejä (ystäväsi ei lasketa mukaan)",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jaa yhtä monta huikkaa kuin täällä on kuumia mimmejä (ystäviäsi ei lasketa mukaan)",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jaa yhtä monta huikkaa kuin täällä on kaljupäitä (ystäväsi ei lasketa mukaan)",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jaa yhtä monta huikkaa, kun paikalla on rillipäitä (ystäväsi ei lasketa mukaan)",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, valitse tuntematon henkilö läheltäsi. Jos tämä henkilö ei sano mitään 7 sekunnin kuluessa siitä, kun aikaa aletaan laskea, saat jakaa $ huikkaa, muuten joudut itse juomaan yhden huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, valitse tuntematon henkilö läheltäsi. Jos tämä henkilö seisoo/istuu samalla tavalla 7 sekunnin ajan siitä, kun aikaa aletaan laskea, saat jakaa $ huikkaa, muuten joudut itse juomaan yhden huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, valitse tuntematon henkilö läheltäsi. Jos tämä henkilö ei katso sinuun päin 12 sekunnin sisällä siitä, kun aikaa aletaan laskea, saat jakaa $ huikkaa, muuten joudut itse juomaan yhden huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, valitse tuntematon henkilö läheltäsi. Jos tämä henkilö nousee ylös 15 sekunnin sisällä siitä, kun aikaa aletaan laskea, saat jakaa $ huikkaa, muuten joudut itse juomaan huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, valitse tuntematon henkilö läheltäsi. Jos tämä henkilö ei sano mitään 15 sekunnin aikana siitä, kun aikaa aletaan laskea, saat jakaa $ huikkaa, muuten joudut itse ottamaan huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, valitse tuntematon henkilö läheltäsi. Jos tämä henkilö alkaa nauraa 7 sekunnin sisällä siitä, kun aikaa aletaan laskea, saat jakaa $ huikkaa, muuten joudut itse juomaan huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, valitse tuntematon henkilö läheltäsi. Jos tämä henkilö hymyilee 4 sekunnin sisällä siitä, kun aika aletaan laskea, saat jakaa $ huikkaa, muuten joudut itse juomaan huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, valitse tuntematon henkilö läheltäsi. Jos tämä henkilö ei juo 7 sekunnin sisällä siitä, kun aikaa aletaan laskea, saat jakaa $ huikkaa. Muuten joudut itse juomaan huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, valitse tuntematon henkilö läheltäsi. Jos tämä henkilö ei juo 10 sekunnin sisällä siitä, kun aikaa aletaan laskea, saat jakaa $ huikkaa. Muuten joudut itse juomaan huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, valitse tuntematon henkilö läheltäsi. Jos tämä henkilö ei hymyile 5 sekunnin sisällä siitä, kun aikaa aletaan laskea, saat jakaa $ huikkaa. Muuten joudut itse juomaan huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, valitse tuntematon henkilö läheltäsi. Jos tämä henkilö ei naura 10 sekunnin sisällä siitä, kun aikaa aletaan laskea, saat jakaa $ huikkaa. Muuten joudut itse juomaan huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, valitse tuntematon henkilö läheltäsi. Jos tämä henkilö ei tilaa mitään 30 sekunnin sisällä siitä, kun aikaa aletaan laskea, saat jakaa $ huikkaa. Muuten joudut itse juomaan huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s ja %s, olkoon voima kanssanne. Valitkaa molemmat lähettyviltä joku tuntematon henkilö henkilökohtaiseksi padawaniksenne. Se, jonka padawan puhuu ensin, jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"1",text:"%s ja %s, olkoon voima kanssanne. Valitkaa molemmat tuntematon henkilö läheltänne henkilökohtaiseksi padawaniksenne. Se, jonka padawan puhuu ensin, jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"1",text:"%s ja %s, olkoon voima kanssanne. Valitkaa molemmat joku läheltänne henkilökohtaiseksi padawaniksenne. Se, jonka padawan menee ensin käymään vessassa, jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"1",text:"%s ja %s, olkoon voima kanssanne. Valitkaa joku läheltänne henkilökohtaiseksi padawaniksenne. Se, jonka padawan lähtee röökille ensin, jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"1",text:"%s ja %s, olkoon voima kanssanne. Valitkaa molemmat joku läheltänne henkilökohtaiseksi padawaniksenne. Se, jonka padawan nauraa ensin, jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"1",text:"Osallistuja, joka tilasi ensimmäisenä, ottaa 2 varovaista huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Sinä, joka tilasit viimeisimpänä: aika ottaa kaverit kiinni! Juo 2 huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"%s, ota huikka, jos olet kätellyt tai halannut jotakuta henkilökunnan jäsenistä. Jos et ole, saat määrätä jonkun juomaan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, saat määrätä jonkun juomaan, jos sinulla on lasinalunen. Jos ei, ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jos tämä on lempipaikkasi, tunnusta se ja juo. Jos ei, jaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jaa $ huikkaa, jos olet käynyt täällä useammin kuin 3 kertaa. Jos et, ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jaa $ huikkaa, jos olet ollut täällä edellisen kerran yli vuosi sitten. Jos et, ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jaa $ huikkaa, jos olet joskus tapellut täällä jonkun kanssa. Jos et, ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jaa $ huikkaa, jos olet joskus ollut täällä kaatokännissä. Jos et, ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jaa $ huikkaa, jos olet joskus ollut täällä kumppanisi kanssa. Jos et, ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jaa $ huikkaa, jos olet joskus ollut täällä sinkkuna. Jos et, ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jaa $ huikkaa, jos olet joskus jutellut tämän paikan tarjoilijoiden kanssa (vaikuttaa nimittäin, että olet täällä kuin kotonasi). Jos et, ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jos aloitit illan limulla, tulee sinun juoda ja hävetä. Jos et, määrää joku toinen juomaan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, määrää joku juomaan, jos olet joskus oksentanut oltuasi täällä. Jos et, juo itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"Ensimmäinen osallistuja, joka bongaa pariskunnan täällä olijoiden joukosta jakaa $ huikkaa. Mikäli paria ei ole, kaikki juovat!",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Ensimmäinen, joka näkee selvästikin tylsistyneen pariskunnan täällä olijoiden joukosta jakaa $ huikkaa. Mikäli tylsistyneitä pareja ei näy, kaikki juovat!",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Ensimmäinen, joka bongaa nauravan kundin täällä olijoiden joukosta, jakaa $ huikkaa. Mikäli nauravaa jätkää ei näy, kaikki juovat!",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Ensimmäinen, joka bongaa tytön mekko päällä täällä olijoiden joukosta jakaa $ huikkaa. Mikäli mekkotyttöä ei näy, kaikki juovat!",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Ensimmäinen, joka näkee jonkun shotti kädessä, jakaa $ huikkaa. Mikäli shotin tilannutta ei henkilöä löydy, kaikki juovat!",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Ensimmäinen, joka näkee tyhjän olutlasin, jakaa $ huikkaa. Mikäli tyhjää lasia ei näy, kaikki juovat!",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Ensimmäinen, joka bongaa jonkin eläimen, jakaa $ huikkaa. Mikäli eläimiä ei näy, kaikki juovat!",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Ensimmäinen, joka bongaa tyhjän pöydän, jakaa $ huikkaa. Mikäli tyhjää pöytää ei näy, kaikki juovat!",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Ensimmäinen, joka näkee neljän jätkän porukan, jakaa $ huikkaa. Mikäli äijäjengiä ei näy, kaikki juovat!",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Jos istutte terassilla, %s jakaa huikan. Jos istutte sisällä, %s juo huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"1",text:"Jos kaikki saapuivat tänne samaan aikaan, %s sinä juot. Mikäli jotkut tulivat myöhemmin, osuu arpaonni osallistujaan %s",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"1",text:"%s, jos saavuit paikalle ensimmäisenä, jaa $ huikkaa. Jos et, saat juoda itse ja toivomme, että tämä toimii sinulle opetuksena",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"%s, jos saavuit paikalle viimeisenä, juo $ huikkaa. Jos et, jaa huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"Kaikki, jotka ovat joskus kuulleet klassikon Oho taisin unohtaa lompakon kotiin voisiko joku maksaa\u0022 juovat $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Kaikki, jotka ovat valittaneet tässä paikassa olemisesta, ottavat huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"Kaikki, jotka eivät aluksi olleet niin innoissaan tästä illasta, ottavat huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"1",text:"%s, jos olet joskus kokeillut Picolo Bar\u0022-haastetta saat jakaa $ huikkaa. Jos epäonnistuit annetussa haasteessa joudut kuitenkin juomaan myös itse\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"1",text:"Onko 'Happy Hour' edelleen käynnissä? Jos vastaus on kyllä, %s juo ja jos ei, juo %s hänen sijastaan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"1",text:"Jos musiikki ei soi tällä hetkellä, on se sinun syytäsi, %s. Juo siis huikka. Jos musiikki soi, saat hemmotella itseäsi kahdella huikalla",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, olet nyt Herra Kofeinisti. Käy tilaamassa kahvi. Voit kuitenkin vain unelmoida sen juomisesta. Joka säästää saadessaan, sillä on mistä ottaa tarvitessaan...",key:"coffee",parent_key:"",pack_name:"bar",language:"fi",nb_players:"3"},
{type:"2",text:"%s saa nyt kaataa kahviaan haluamansa määrän osallistujien %s ja %s laseihin",key:"",parent_key:"coffee",pack_name:"bar",language:"fi",nb_players:"3"},
{type:"2",text:"%s, valitse kenen lasiin haluat kaataa jäähtyneen kahvisi",key:"",parent_key:"coffee",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, lasissasi on tilaa kahville... Nauti!",key:"",parent_key:"coffee",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, napsuttele sormiasi biisin tahtiin! Jos et, ota $ huikkaa jokaisen uuden biisin alkaessa",key:"click-finger",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, voit lopettaa sormien napsuttelun",key:"",parent_key:"click-finger",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, mene istumaan baaritiskille ja juo yksinäsi",key:"alone-at-the-bar",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s saa tulla takaisin lämpimään",key:"",parent_key:"alone-at-the-bar",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, olet outo: ulvo hieman kuin kunnon weirdo konsanaan. Saat jakaa yhden huikan jokaisesta ulvahduksesta",key:"I-assume-mongolito",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, aikasi weirdona on päättynyt",key:"",parent_key:"I-assume-mongolito",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, sinun on nyt juotava 3 pillillä. Jos et, juot huikan jokaisen uuden tehtävän kohdalla",key:"3-straws",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, voit lopettaa pillillä leikkimisen",key:"",parent_key:"3-straws",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, valitse lempitarjoilijasi. Tee pieruääni suullasi joka kerta, kun hän tarjoilee juoman tai ota huikka",key:"choose-waiter",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, lopeta nuo pieruäänet, olet nolo",key:"",parent_key:"choose-waiter",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, olet ylisosiaalinen bilehile! Tervehdi jokaista ohitsesi kävelevää henkilöä. Juo huikka aina, kun missaat tervehdyksen.",key:"hypersocial",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, sosiaalinen maniasi on tullut päätökseensä",key:"",parent_key:"hypersocial",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, etsi tamponi ja ripusta se korvaasi. Todella tyylikästä",key:"tampon-ear",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, ota tamponi pois. Se aika kuukaudesta on ohi",key:"",parent_key:"tampon-ear",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, sinua rangaistaan! Mene nurkkaan mököttämään. Jos joku puhuu sinulle, saat vastata vain ANSAITSEN RANGAISTUKSEN\u0022\u0022",key:"punition",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s saa tulla takaisin! Tai voitte teeskennellä, ettette nähneet tätä…",key:"",parent_key:"punition",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, mene pöydän alle. Kerromme, kun saat tulla pois",key:"under-the-table",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s saa palata seuraamme! Voimme myös teeskennellä, että kyseessä oli bugi eikä tätä viestiä koskaan näytetty...",key:"",parent_key:"under-the-table",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, valitse lähistöltä tyttö. Puhkea ihailuun ja hihkaise wooow!\u0022 aina kun hän juo\u0022",key:"choose-your-partner",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, lakkaa hämmentämästä naapuripöydän tyttöä",key:"",parent_key:"choose-your-partner",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, valitse tuntematon henkilö lähettyviltä. Kun valitsemasi henkilö puhuu, tulee sinun sanoa bla bla bla bla...\u0022\u0022",key:"speak-when-other-speak",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"2",text:"%s, jätä viaton ihmisparka rauhaan",key:"",parent_key:"speak-when-other-speak",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"4",text:"Pelataan kolikkoleikkiä! %s, ota kolikko ja laita se yhden osallistujista lasiin. Hän juo $ huikkaa ja laittaa kolikon vuorostaan jonkun muun lasiin jne.",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"4",text:"Asettakaa tupakka-aski pöydän reunalle. Jokainen osallistuja saa vuorollaan yrittää askin ympäri flippaamista. Häviäjät juovat, voittajat saavat jakaa huikan eteenpäin. %s, sinä aloitat",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"4",text:"Asettakaa kolikko pöydän reunalle. Jokainen osallistuja saa vuorollaan yhden kerran yrittää heittää kolikon toiselle puolelle yhdellä flippauksella. Se, joka pääsee lähimmäksi pöydän reunaa, jakaa $ huikkaa. %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"4",text:"Pop Quiz! Se, joka arvaa biisin nimen ensimmäisenä, saa jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"4",text:"%s, valitse jokin lause ja kuiskaa se vain kerran vasemmanpuoleiselle vierustoverillesi, niin, että ainoastaan hän kuulee sen. Jatkakaa tätä eteenpäin, kunnes lause tulee takaisin sinulle. Osallistujat, jotka eivät kuiskaa oikeaa lausetta juovat $ huikkaa.",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"4",text:"%s, pyöräytä kolikkoa pöydällä. Antakaa kolikolle vuorotellen vauhtia yhdellä sormella. Ensimmäinen epäonnistuja juo $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"4",text:"Pop Quiz! Ensimmäinen, joka arvaa biisin nimen oikein, saa jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"4",text:"Pop Quiz! Osallistuja, joka sanoo ensimmäisenä edellisen biisin laulajan nimen saa jakaa $ huikkaa. Mikäli kukaan ei tiedä vastausta, kaikki juovat!",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"4",text:"Pelataan Mikado -tikkupeliä noin 20 tupakalla. Jokainen tupakka, joka noukitaan oikeassa järjestyksessä, antaa oikeuden yhden huikan jakamiseen! %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"16",text:"Käykää kaikki baarissa olijat läpi ja arvatkaa, kuka on pelaajan %s mielestä seksikkäin tyttö. Se, joka arvaa ensimmäisenä oikein, jakaa $ huikkaa! %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"16",text:"Kukin osallistuja arvaa vuoron perään järjestyksessä, kuka on pelaajan %s mielestä baarin seksikkäin mies. Se, joka arvaa oikein, jakaa $ huikkaa! %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"16",text:"Arvatkaa vuoron perään järjestyksessä, kuka baarista on pelaajan %s mielestä helpoin iskeä. Se, joka arvaa oikein, jakaa $ huikkaa! %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"16",text:"Arvatkaa vuoron perään järjestyksessä, kuka on pelaajan %s mielestä baarin rumin tyttö. Ensimmäinen, joka arvaa oikein, jakaa $ huikkaa! %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"16",text:"Arvatkaa vuoron perään järjestyksessä, kenen %s uskoo olevan baarin pahiten puutteessa oleva mies. Ensimmäinen, joka arvaa oikein, jakaa $ huikkaa! %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"16",text:"Arvatkaa vuoron perään järjestyksessä, kuka on osallistujan %s mielestä baarin rumin mies. Ensimmäinen oikein arvannut jakaa $ huikkaa! %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"16",text:"Arvatkaa vuoron perään järjestyksessä, mikä baarin viinoista on pelaajan %s mielestä parasta. Ensimmäinen oikein arvannut jakaa $ huikkaa! %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"16",text:"Arvatkaa vuoron perään järjestyksessä, mikä paikan oluista on pelaajan %s mielestä parasta. Ensimmäinen oikein arvannut jakaa $ huikkaa! %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"16",text:"Arvatkaa vuoron perään järjestyksessä, kuka on osallistujan %s mielestä baarin kiimaisin tyttö. Ensimmäinen oikein arvannut jakaa $ huikkaa! %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"16",text:"Arvatkaa järjestyksessä vuoron perään, mikä on osallistujan %s mielestä kaupungin paras baari. Ensimmäinen oikein arvannut jakaa $ huikkaa! %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"16",text:"Arvatkaa järjestyksessä vuoron perään, mikä on osallistujan %s mielestä kaupungin paras klubi. Ensimmäinen oikein arvannut jakaa $ huikkaa! %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"16",text:"Arvatkaa järjestyksessä vuoron perään, mikä keskustan paikoista on osallistujan %s mielestä paras pokailupaikka. Ensimmäinen oikein arvannut jakaa $ huikkaa! %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"16",text:"Arvatkaa järjestyksessä vuoron perään, mikä on osallistujan %s lempibiisi tällä hetkellä. Ensimmäinen oikein arvannut jakaa $ huikkaa! %s aloittaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"17",text:"%s, sinut on valittu tilaamaan seuraava kierros. Et saa käyttää verbejä haluta\u0022 \u0022ottaa\u0022 \u0022valita\u0022 tai \u0022tilata\u0022\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"17",text:"%s ja %s, menkää tilaamaan yhtä aikaa. Se, kumpaa palvellaan ensin, jakaa $ huikkaa. Myös häviäjä juo saman määrän",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"17",text:"%s, olehan kiltti ja mene pyytämään kaikille pientä välipalaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"17",text:"%s, ota lompakkosi esille... Seuraava kierros on sinun!",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"17",text:"%s, anna pelaajalle %s lahja. Hän saa kertoa suosikkidrinkkinsä",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"17",text:"Nostamme hieman tahtia... %s tarjoaa shottikierroksen!",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"17",text:"Ihan vain tiedoksi... Se, joka juo lasinsa tyhjäksi viimeisenä, maksaa seuraavan kierroksen....",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"17",text:"%s, jos jollakulla on vielä munaa, tarjoa asianomaiselle shotti",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"17",text:"%s tarjoaa oluen joko pelaajalle %s tai %s, riippuen siitä kumpi juo lasinsa tyhjäksi ensimmäisenä",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"3"},
{type:"17",text:"%s tarjoaa lasillisen! %s, mitä haluaisit?",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"17",text:"%s tarjoaa jollekin pelaajan %s valitsemalle tuntemattomalle henkilölle lasillisen",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"17",text:"Tusina shotteja vai muutama mojito? Kaikki äänestävät yhtä aikaa ja häviäjät tarjoavat voittajille seuraavan kierroksen voittaneen juoman muodossa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"17",text:"Tumma vai vaalea olut? Kaikki äänestävät yhtä aikaa ja häviäjät tarjoavat voittajille seuraavan kierroksen voittaneen juoman muodossa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"17",text:"Juotko mieluummin muutaman oluen vai jotakin muuta? Kaikki äänestävät yhtä aikaa ja häviäjät tarjoavat voittajille seuraavan kierroksen voittaneen vaihtoehdon muodossa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"0"},
{type:"17",text:"%s tyhjennä 6 lasia putkeen tai tarjoa seuraava kierros",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"17",text:"%s, päätä, tarjoaako seuraavan kierroksen %s vai %s",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"3"},
{type:"17",text:"%s, päätä, kuka tarjoaa seuraavan kierroksen",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"17",text:"%s, olet melkoinen beibi! Valitse, kuka tarjoaa sinulle juoman. Tarjoajan sekä juoman päätät kokonaan itse",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, pyydä kondomia tai ota huikka jonkun juomasta",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, pyydä röökiä tai ota huikka jonkun juomasta",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, kysy joltakin tuntemattomalta, tietääkö hän Picolon. Jos tietää, saat jakaa $ huikkaa, mutta jos ei, juo itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, yritä arvata pelaajan %s valitseman tuntemattoman ikä ja kysy sen jälkeen hänen ikäänsä. Jos olet oikeassa, saat jakaa $ huikkaa. Jos et, ota itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"18",text:"%s, yritä arvata pelaajan %s valitseman tuntemattoman pituus ja kysy sen jälkeen pituuttaan. Mikäli arvaat oikein, jaa $ huikkaa. Jos et, ota itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"18",text:"%s, yritä arvata jonkun tuntemattoman naisen, jonka %s on valinnut, kuppikoko. Kysy sen jälkeen häneltä kokoa. Jos arvasit oikein, saat jakaa $ huikkaa. Muuten ota itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"18",text:"%s, yritä arvata pelaajan %s valitseman tuntemattoman kengänkoko ja kysy sitten kokoa tältä henkilöltä. Jos arvauksesi oli oikein, saat jakaa $ huikkaa ja jos ei, juo itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"18",text:"%s, valitse joku tuntematon henkilö. Jos hän on sinkku, saat jakaa $ huikkaa ja jos ei, saat juoda itse... Ja kyllä, jonkun on otettava asiasta selvää",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, anna pelaajan %s valita joku tuntematon henkilö. Yritä arvata, milloin hän saapui baariin. Jaa $ huikkaa, jos arvasit oikein. Jos et, ota itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"18",text:"%s, mene dj:n luo ja toivo biisiä. Jos hän vastaa myöntävästi, sinä juot huikan. Jos ei, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, pyydä dj:tä laskemaan äänenvoimakkuutta tai juo $ huikkaa. Mikäli onnistut haasteessa, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, pyydä dj:tä nostamaan äänenvoimakkuutta tai juo $ huikkaa. Mikäli onnistut haasteessa, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, kerro vitsi tuntemattomalle. Pieninkin hymy on voitto ja saat jakaa $ huikkaa. Jos kieltäydyt tai epäonnistut, juo $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, ärsytä tuntemattomia henkilöitä näyttämällä heille piirrosta kärpäsestä tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, ärsytä tuntemattomia henkilöitä näyttämällä heille kuvaa dinosauruksesta tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, ärsytä tuntemattomia henkilöitä näyttämällä heille kuvaa hapankaalista tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, ärsytä tuntemattomia henkilöitä kysymällä heiltä, haluaisivatko he ostaa kuvasarjan (etsi kuvia netistä) tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, ärsytä tuntemattomia henkilöitä kysymällä, haluaisivatko he ostaa vaatehenkarin (etsi kuvia netistä) tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, ärsytä tuntemattomia henkilöitä kysymällä, haluaisivatko he ostaa mikroaaltouunin (etsi kuvia netistä) tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, julista rakkauttasi tuntemattomalle tai juo $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, kysy joltakin seurueelta, saisitko ottaa heistä kuvan, kun he ovat niiiiin söpöjä! Jos et, juo $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, pyydä jotakin tuntematonta henkilöä ottamaan sinusta kuva. Lähetä tulos meille tilaisuuden tullen, se olisi hauska nähdä ;)",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, näytä tämä tehtävä baarimikolle. Mikäli hän on tarpeeksi huumorintajuinen ja ottaa huikan, saat jakaa $ huikkaa. Jos ei, juo huikat itse",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, näytä tämä tehtävä jollekin tuntemattomalle henkilölle. Jos hän juo, saat jakaa $ huikkaa. Muuten juo itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, näytä tämä tehtävä jollekin tuntemattomalle naiselle. Jos hän juo, saat jakaa $ huikkaa. Muuten juo itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, piirrä serviettiin elefantin kuva ja anna se pelaajan %s valitsemalle tuntemattomalle henkilölle tai juo $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"18",text:"%s, piirrä serviettiin omenan kuva ja anna se pelaajan %s valitsemalle tuntemattomalle henkilölle tai juo $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"18",text:"%s, piirrä serviettiin jäniksen kuva ja anna se pelaajan %s valitsemalle tuntemattomalle henkilölle tai juo $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"18",text:"%s, haasta pelaajan %s valitsema tuntematon henkilö peukalopainiin. Jaa $ huikkaa, jos voitat. Muussa tapauksessa juo itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"18",text:"%s, haasta pelaajan %s valitsema tuntematon henkilö kivi-paperi-sakset-otteluun. Jaa $ huikkaa, jos voitat. Muussa tapauksessa juo itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"18",text:"%s, pyydä pelaajan %s valitsemaa tuntematonta henkilöä arvaamaan ikäsi. Jaa $ huikkaa, jos hän arvaa oikein. Muussa tapauksessa ota itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"18",text:"%s, pyydä pelaajan %s valitsemaa tuntematonta henkilöä arvaamaan pituutesi. Jaa $ huikkaa, jos hän arvaa oikein. Muussa tapauksessa ota itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"18",text:"%s, pyydä pelaajan %s valitsemaa tuntematonta henkilöä arvaamaan kengänkokosi. Jaa $ huikkaa, jos hän arvaa oikein. Muussa tapauksessa ota itse huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"18",text:"%s, hanki tarjoilijan numero tai juo $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, saat 5 minuuttia aikaa etsiä naimisissa olevan henkilön. Jos epäonnistut, joudut juomaan. Onnistuessasi saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, etsi joku, joka on ladannut Picolon. Sinulla on 3 yritystä. Jos löydät jonkun, saat jakaa $ huikkaa. Juo itse, jos kieltäydyt tehtävästä tai epäonnistut",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, etsi joku, joka ei ole ladannut Picoloa. Jos saat hänen lataamaan sovelluksen, saat jakaa $ huikkaa. Juo, jos kieltäydyt tehtävästä tai epäonnistut",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, etsi joku, joka on jo kokeillut Picoloa ja pitänyt siitä. Sinulla on 3 yritystä. Jos löydät jonkun, saat jakaa $ huikkaa. Juo, jos kieltäydyt tehtävästä tai epäonnistut",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, iske silmää pelaajan %s valitsemalle tuntemattomalle henkilölle tai juo $ kertaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"18",text:"%s, kysy tarjoilijalta hänen nimeään. Jos hän kertoo sen, saat jakaa $ huikkaa. Mikäli epäonnistut, juo $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, haista hienovaraisesti tuntemattoman henkilön takamusta... Juo $ huikkaa, jos kieltäydyt tehtävästä",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, kysy tuntemattomalta, onko hän aborttia vastaan. Jos vastaus on kyllä\u0022 saat jakaa $ huikkaa. Jos \u0022ei\u0022 ota itse huikka\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, kysy joltakin tuntemattomalta, onko hän albiinoapinoihin kohdistuvaa rasismia vastaan. Jos vastaus on kyllä\u0022 saat jakaa $ huikkaa. Jos \u0022ei\u0022 ota itse huikka\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, käy pyytämässä tuntemattoman henkilön numeroa tai juo $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"18",text:"%s, anna numerosi muiden valitsemalle tuntemattomalle henkilölle tai juo",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, valitse ystäviesi joukosta kätyri. Jos hän onnistuu sinun antamassasi haasteessa, saat jakaa $ huikkaa. Muuten hän joutuu juomaan ne",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, valitse haaste pelaajalle %s. Potissa on $ huikkaa. Jos hän ei selviä haasteesta, saatte kumpikin juoda",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"19",text:"%s, valitse haaste pelaajalle %s, joka saa onnistuessaan jakaa $ huikkaa, mutta epäonnistuessaan tulee juoda $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"19",text:"%s, tee konttauskierros pöydän alla tai juo $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, anna pelaajan %s puraista sinua pakarasta tai juo $ kertaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"19",text:"%s, laita lasiisi maapähkinä tai jotain muuta syötävää, tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, anna pelaajan %s kaataa jonkun toisen lasin sisältö sinun lasiisi tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"19",text:"%s, laita toinen sukistasi pöydälle tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, laita toinen kenkäsi pöydälle tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, riisu kengät ja sukat pois tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, mene vessaan kääntämään paitasi nurin päin tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, kulje vessaan yksi käsi pyllylläsi tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, mene vessaan ja tule takaisin suuri märkä läntti haaroissasi tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, tee moonwalk/backslide -liike tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, mene vessaan ja tule takaisin niin, että housuistasi roikkuu 3 selvästi näkyvää vessapaperinpalaa, tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, käy vessassa ja sano ensimmäiselle sen jälkeen näkemällesi ihmiselle: Onnea seuraavalle...\u0022 tai juo\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, mene vessaan ja sano jollekin vieraalle ihmiselle: Tästä on tulossa kunnon verilöyly\u0022 tai juo huikka\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, käy laittamassa hiuksiisi keskijakaus tai juo huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, käännä housusi nurin päin tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, anna pelaajan %s läimäyttää sinua ahteriin tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"19",text:"%s, kirjoita nimesi ja puhelinnumerosi lasinaluseen ja jätä se pöydälle vielä pelin päätyttyä. Jos kieltäydyt, saat juoda huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, piirrä silmälasit naamaasi tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, ota räkäpallo nenästäsi ja laita se lasinaluselle tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, jos onnistut livahtamaan baaritiskin taakse, saat jakaa $ huikkaa. Jos et, juo itse $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, käy pyytämässä ämpärillistä jäitä, niin saat määrätä jonkun juomaan, tai ole pelkuri ja juo itse",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, laita toinen jalkasi pöydälle, niin saat määrätä jonkun juomaan. Muuten juo itse",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, etsi jostain huulipuna ja laita sitä huuliisi niin, että sitä on myös reilusti huulten rajojen ulkopuolella, tai juo huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, mene vastakkaisen sukupuolen vessaan kun käyt pissalla seuraavan kerran, niin saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, kävele pöydän ympäri ja nuuhkaise jokaisen osallistujan hiuksia tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, juo shotti puhdasta tamponia käyttämällä: imeytä juomaa tamponiin ja siitä itseesi, muuten saat juoda $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s sylje juomaasi tai juo kaksi kertaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, anna pelaajan %s nuolla juomalasisi reunaa tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"19",text:"%s, nuole pöytää tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, anna pelaajan %s läimäyttää sinua poskelle tai juo huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"19",text:"%s, laita jalat tuolille ja odota kunnes tarjoilija hermostuu, tai juo $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, pureskele lasinalustasi 30 sekunnin ajan tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, anna pelaajan %s meikata sinua hieman tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"2"},
{type:"19",text:"%s, syö jääpala tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, örise kuin Chewbacca (Star Wars, tiedäthän) tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, esitä julkinen steppausnäytös tai juo huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, röyhtäise kovaan ääneen tai ota huikka. Kyllä, tämä on lapsellista, mutta nämä ovat pelin säännöt",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"19",text:"%s, laita lasillesi lasialunen tai ota huikka",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Antti-niminen mies tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Juho-niminen mies tai juo huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Niklas-niminen mies tai juo huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Pentti-niminen mies tai juo huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Kalle-niminen mies tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Daniel-niminen mies tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Leevi-niminen mies tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Samuli-niminen mies tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Joni-niminen mies tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Toni-niminen mies tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Elina-niminen nainen tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Piia-niminen nainen tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Alina-niminen nainen tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Karoliina-niminen nainen tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Jessika-niminen nainen tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Jenni-niminen nainen tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Liisa-niminen nainen tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Miia-niminen nainen tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Maaret-niminen nainen tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Marjo-niminen nainen tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"20",text:"%s, etsi Maria-niminen nainen tai ota huikka. Sinulla on 3 yritystä ja jos onnistut, saat jakaa $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi hapankaali\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi anustappi\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi penis\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi keitä\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, piirrä itsellesi yhteenkasvaneet kulmakarvat tai juo $ huikkaa",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi torvi\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi vaseliini\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi roska\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi viagra\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi ripuli\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi anaaliseksi\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi neitsyt\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi lapamato\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi liukuvoide\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi siittiö\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi klimppi\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi rakko\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi häpykarva\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi suuseksi\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi kiimassa\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi ota minut\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"21",text:"%s, kirjoita otsaasi housut pois\u0022 tai juo $ huikkaa\u0022",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä hevosella ratsastava prostituoitu. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä mammutti, joka paskoo rengashäntämakin. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä yksisarvinen, joka on lesbo. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä voimisteleva hyönteinen. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä puhuva ranskanperuna. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä piereskelevä paistinpannu. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä ripuloiva koira. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä kannentiiviste. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä psykopaattivauva. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä torakka, jolla on shortsit. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä kastroitu Chippendale-tanssija. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä narua hyppäävä Batman. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä juokseva hobitti. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä oksentava kirahvi. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä kakkaava vauva. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä naispuolinen Pikachu. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä itseään hyväilevä apina. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä Iron Man, jolla on housut. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä Trumpin esinahka. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä poliisi joka nai sammakkoa takaapäin. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä kissa, jolla kondomi. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä elävä tuoli. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä tanssiva karhu. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä puhelimessa puhuva kanamuna. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä vampyyri, joka puree itseään ahteriin. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä kuollut hiiri. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä ejakuloiva krokotiili. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä Pikachu, joka tekee itsemurhan. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä kännissä oleva kettu. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä skeittaava kani. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä alaston smurffi. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä homoseksuaalinen leijona. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä leikkipuiston keinu täydessä vauhdissa. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä täytetty kalkkuna. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"},
{type:"22",text:"%s, piirrä hevonen, jolla seisoo. Ryhmä päättää, kuka ulkopuolinen saa arvata, mitä kuva esittää. Jos henkilö arvaa oikein, saat jakaa $ huikkaa. Jos arvaus on väärä, juot itse huikan",key:"",parent_key:"",pack_name:"bar",language:"fi",nb_players:"1"}]);
retrieveDB();