var db = TAFFY([{cycle_state:"false",type:"1",text:"%s, если ты девушка, эротично облизни свой палец. Если ты парень, эротично облизни свои губы. Или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь занимался сексом в общественном месте, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, имитируй оргазм на протяжении 10 секунд",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь занимался сексом втроем, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Все девушки должны подтянуть свои трусики так, чтобы их было видно ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s и %s должны нежно обняться",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь занимался сексом при включенной камере, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь во время секса представлял другого человека, решают, кому делать $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Тот, кто хотел бы переспать с одним из игроков, делает $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь спал(а) с первой(ым) встречной(ым) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто любят оральные ласки, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь во время секса снимал на камеру своего партнера, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто считают, что %s хорош(а) в постели, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s должен сексуально облизать палец %s или сделать $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь занимался анальным сексом, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто одет в рубашку на пуговицах, расстегивает их и делает столько глотков, сколько пуговиц он расстегнул",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s снимает один предмет одежды с %s или делает $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Те, кого когда-либо застукивали за онанизмом, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто бреют/эпилируют свои интимные зоны, решают, кому делать $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если последний раз ты смотрел порно больше двух недель назад",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто любят использовать похотливые словечки во время секса, решают, кому делать $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, сколько бы тебе понадобилось выпить, что бы переспать с %s ? Отвечай и делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, как ты считаешь, кто из игроков умеет доставлять удовольствие во время оральных ласк? Отвечай и делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь играл в ролевые игры, решает, кому делать $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, ты должен изображать оргазм каждый раз, перед тем, как пьешь ",key:"orgasm-simulation",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, можешь больше не изображать оргазм каждый раз, перед тем, как пьешь ",key:"",parent_key:"orgasm-simulation",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, кого из игроков ты считаешь самым(ой) сексуальным(ой)? Он(она) должен(должна) сделать $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кто не помнят имен всех своих сексуальных партнеров, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь занимался сексом в отеле, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, покажи позу наездницы или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кто никогда не занимался сексом в машине, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, чего ты никогда не пробовал(а) во время секса? Игроки, которые это делали, пьют $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, если ты покажешь свой сосок, %s делает $ глотка(ов). Не покажешь, пей $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s, %s и %s устройте оргию или делайте $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"4"},
{cycle_state:"false",type:"1",text:"%s, выбирай: сделать $ глотка(ов) или поцеловать ноги %s",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, если ты поцелуешь %s, все игроки делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Все должны сделать столько глотков, сколько оргазмов вы испытали на этой неделе. Онанизм тоже считается ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто не занимался сексом на этой неделе, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Если у тебя был секс с человеком, который старше тебя на 5 лет, делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Если у тебя был секс с человеком, который младше тебя на 5 лет, делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Если %s и %s поцелуются в губы, каждый из них может решить, кому пить $ глотка(ов). Если не поцелуются,  все игроки делают по $ глотка(ов)  ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь отправлял или получал сексуальные смс, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Первый игрок, который покажет интимное смс на своем телефоне, решает, кому пить $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Если ты когда-нибудь терпел(а) провал во время секса, делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Если тебе доводилось спать с одним из игроков, делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кого когда-либо застукивали родители во время секса, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, если у тебя не было секса более 4 раз за день, делай $ глотка(ов). Если да, решай, кому пить ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Если ты когда-либо представлял(а) в своих сексуальных фантазиях девушку/парня своего друга/своей подруги, делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Если ты когда-нибудь отправлял(а) сексуальные фотографии, делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Если ты когда-нибудь ел(а) с тела своего партнера, делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто занимался сексом на кровати своих родителей, делают $ глотка(ов)  ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто выкрикивают имя своего партнера во время секса, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь испытывали оргазм после трех минут секса, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь занимался сексом во время менструации, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь занимался сексом на стиральной машинке, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь занимался сексом на кухне, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Девушки, которым было больно во время первого раза, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, если бы ты был(а) не против переспать с %s, решай, кому пить $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, если ты был(а) тайно влюблен(а) в %s, ты делаешь $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, ущипни %s за сосок. Иначе, он/она делает $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь пользовался секс игрушками, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, выбирай игрока, в чьи глаза ты будешь смотреть. Тебе скажут, когда остановиться. ",key:"look-in-the-eyes",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ты можешь перестать смотреть в глаза своему другу(своей подруге) ",key:"",parent_key:"look-in-the-eyes",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Отныне, все должны гладить свою грудь, когда разговаривают",key:"caress-boobs",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Можно перестать себя щупать",key:"",parent_key:"caress-boobs",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто сидят на сайте знакомств, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Если ты когда-нибудь спал с человеком с сайта знакомств, делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь занимался сексом в лесу, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Если ты когда-нибудь притворялся(лась) во время оргазма, делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Если у тебя когда-нибудь оставались синяки или царапины после секса, делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь держал в руке фаллоимитатор, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь чувствовал возбуждение в общественном транспорте, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь чувствовал сексуальное возбуждение на работе делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, лизни нос %s или делай $ глотка(ов) !",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь представлял в эротических фантазиях родителей своего друга/своей подруги, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь наблюдал за сексом животных, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, прошепчи что-то сексуальное на ухо %s или сделай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, потрогай причиндалы %s или сделай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Парни: те, кто когда-либо мерился своими причиндалам, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь засовывал инородный предмет себе в анус/вагину, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, чмокни в нос %s или сделай $ глотка(ов)!",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь обзывал во время секса своего партнера, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, выбери двух игроков, которые должны поцеловаться или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"3"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь подталкивал своего друга/свою подругу на измену, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь встречался с бывшей(бывшим) своего друга(подруги), делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, если последний твой секс был защищенным, решай, кому делать $ глотка(ов), если нет, пей сам",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ты предпочитаешь секс оральный, анальный или вагинальный? Отвечай и делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кого когда-нибудь оскорбляли во время секса, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, встань на четвереньки и выгни хорошенько спину, тебе скажут, когда можно будет встать",key:"doggy-style-way",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, можешь вернуться к нормальной позе",key:"",parent_key:"doggy-style-way",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ты мент ! Можешь обыскать любого игрока. Если тот откажет, он делает $ глотка(ов)  ",key:"body-search",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ты больше не мент. Хватит распускать руки и делай-ка $ глотка(ов) ",key:"",parent_key:"body-search",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ты Купидон! Выбери того, кто сможет обнимать и целовать кого хочет, когда хочет. Или делай $ глотка(ов) ",key:"cupidon",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ты больше не Купидон!",key:"",parent_key:"cupidon",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты любишь, когда на тебя смотрят во время секса",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь занимался сексом при просмотре порно",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты любишь заниматься сексом при включенном порно",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты любишь спонтанный секс",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты людишь, когда во время секса ласкают твой анус",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты любишь забавляться с анусом твоего партнера(твоей партнерши) во время секса ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты любишь, когда тебя шлепают",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Развратники, у кого был секс с двумя партнерами, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Девушки, которые испытывали оргазм, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если испытывал(а) больше трех оргазмов подряд",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь спал с человеком другой расы, решай, кому делать $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь переодевался(лась), что бы придать пикантности сексу ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь наблюдал(а), как другие занимаются сексом",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если последний твой секс был анальным ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если когда-нибудь массаж, который ты делал(а), доводил до секса",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь занимался(лась) сексом по телефону",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, оближи губы одного из игроков или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, оближи ухо одного из игроков или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Все игроки делают $ глотка(ов) кроме %s, который(ая) целует всех в щечку",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, поцелуй %s и делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, выбирай: поцеловать любого игрока или сделать $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s сними один предмет одежды с %s или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s передай кусочек льда изо рта в рот %s или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, если ты парень, опиши минет своей мечты. Если ты девушка, расскажи, как ты его делаешь. Во время рассказала пей $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, если ты девушка, опиши куни своей мечты. Если ты парень, расскажи, как ты его делаешь. Во время рассказала пей $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты считаешь себя ГУРУ СЕКСА",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s должен(должна) целовать другого игрока каждый раз перед тем, как пьет",key:"kiss-before-drink",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, угомони свою страсть к поцелуям ",key:"",parent_key:"kiss-before-drink",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s нежно держи за руку %s, пока не будет задания перестать ",key:"hold-hand",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, можете больше не держаться за руки",key:"",parent_key:"hold-hand",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s выбери игрока, который будет тебе массировать руку, пока ему не будет велено прекратить",key:"hand-massage",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, массаж окончен",key:"",parent_key:"hand-massage",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ты неотразим! Ты можешь просить любого игрока поцеловать тебя (в щечку, губы или еще куда..) Игрок не имеет права отказать!",key:"irresistible",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ты больше не неотразимый!",key:"",parent_key:"irresistible",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s и %s, тритесь друг об друга ногами, пока не будет задания прекратить",key:"naughty-feet",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, можете перестать тереться друг об друга ",key:"",parent_key:"naughty-feet",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, выбери того, кто должен не переставая трогать свою попу ",key:"hand-under-ass",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, скажи, чтобы перестал(а) трогать свою попу!",key:"",parent_key:"hand-under-ass",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, оближи любую часть тела того игрока, которого выберет %s ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, реши, кто из игроков оближет какую-либо часть твоего тела. $ глотка(ов), если он откажется",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s должен пощупать соски одного из игроков. $ глотка(ов), если он откажется",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s выбери игрока, который потрогает тебя за соски. $ глотка(ов), если он откажется",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, поцелуй голый торс одного из игроков или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери, кто поцелует твою голую грудь/торс. $ глотка(ов), если он откажется",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, если ты парень, подойди сзади к одной из девушки, принимающей участие в игре Picolo, и нежно погладь ее грудь. Если ты девушка, выбери парня, который погладит твою грудь. $ глотка(ов), если он откажется",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s выбери игрока, который сможет решить, кто станцует эротический танец у него на коленках. $ глотка(ов), если он/она откажется",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты когда-нибудь занимался сексом перед другими людьми",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты когда-нибудь участвовал в свингер пати ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Реши, кому делать $ глотка(ов), если ты когда-нибудь масту*бировал(а), пока твой партнер наблюдал за тобой",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, гладь попу одного из игроков на протяжении 5 секунд. $ глотка(ов), если он/она откажется",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Реши, кому делать $ глотка(ов), если ты масту*бировал(а), представляя своего(свою) коллегу по работе",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь масту*бировал(а) при просмотре обычного фильма (не порно)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, выбери игрока, который будет поглаживать твою попу на протяжении 5 секунд. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, посмотри в глаза тому игроку, с кем бы ты мог(могла) переспать этой ночью. $ глотка(ов) делает тот игрок, в чьи глаза ты посмотришь",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери игрока, который будет пить, пока ты гладишь его интимные части тела",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, покажи свою фотографию топлес или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, укуси одного из игроков за ушко или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кто после секса ласкал своего партнера так, что это приводило снова к сексу, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, выбери двух игроков, которые должны поцеловаться с языком. Тот, кто откажется, делает $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери того, кто должен показать свой сосок... $ глотка(ов) в случае отказа ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, покажи одну из интимных частей своего тела или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери игрока, который должен показать интимную часть своего тела. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, покажи секс позицию с одним из игроков или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери двоих игроков, которые должны показать секс позицию и выпить после этого $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, прильни головой к интимной части тела одного из игроков. $ глотка(ов) в случае отказа ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери игрока, который должен прильнуть своей головой к интимной части твоего тела. $ глотка(ов) в случае отказа ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери игрока, который должен уткнуться лицом в грудь одной из девушек. $ глотка(ов) в случае отказа ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, лизни интимную часть тела одного из игроков. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери игрока, который должен облизать интимную часть твоего тела. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, погладь интимную часть тела одного из игроков или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери игрока, который должен погладить интимную часть твоего тела. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери того, кто должен залезть рукой под твое нижнее белье. $ глотка(ов) в случае отказа ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ты должен(должна) провести своей рукой под нижнем бельем одного из игроков. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, передай изо рта в рот другому игроку какой-либо предмет. $ глотка(ов) в случае отказа ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери двух игроков, которые должны передать друг другу предмет изо рта в рот. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, пощупай грудь одной из девушек. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Все пьют и снимают один предмет одежды! ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто не умеют танцевать twerk делают $ глотка(ов)!",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, выбери, кто снимет один элемент одежды. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если у тебя были эротические фантазии с участием одного из игроков",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, выбери игрока, который должен расстегнуть лифчик одной из девушек. Если он не справится за 5 секунд, он делает $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Тот, у кого недавно был секс, снимает один элемент одежды",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, выбери того, кто ущипнет тебя за соски или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ущипни за попу одного из игроков. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери того, кто ущипнет тебя за попу или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, оближи губы одного из игроков. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери того, кто оближет твои губы или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, покажи интимную часть своего тела или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, оближи соски одного из игроков. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери игрока, который должен облизать твои соски или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Парни, снимите один элемент одежды или делайте $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Девушки, снимите один элемент одежды или делайте $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Парни, вы должны сидеть с голым торсом или делайте $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Девушки, вы должны снять верх и остаться в лифчике или делайте $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты занимался(лась) сексом в кровати друга без его ведома",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Реши, кому делать $ глотка(ов), если ты использовал лед во время предварительных ласк",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Реши, кому делать $ глотка(ов), если во время предварительных ласк во рту у тебя была ментоловая жвачка",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если тебя фотографировали голым(голой) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если на тебе нет нижнего белья ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если предварительные ласки тебе нравятся больше, чем секс ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка, если ты любишь жесткий секс",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты считаешь, что предварительные ласки необходимы ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, сними свое нижнее белье или допивай свой бокал до дна ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, если ты впервые ты занимался(лась) сексом, когда тебе было меньше 17 лет, реши, кому делать $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, положи свою руку на попу одного из игроков, пока не будет команды прекратить ",key:"put-your-hand-on-legs",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ты можешь убрать свою руку с попы игрока ",key:"",parent_key:"put-your-hand-on-legs",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Каждый раз, когда %s дотрагивается до бокала, %s должен(должна) имитировать оргазм. $ глотка(ов), если не сделает ",key:"touch-glass-and-cum",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, заканчивайте, можно больше не стонать",key:"",parent_key:"touch-glass-and-cum",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, в любой момент ты можешь выбрать двух игроков, один из которых сядет на колени другому. $ глотка(ов) в случае отказа",key:"on-sby-knees",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ты больше не выбираешь, кому садиться на колени ",key:"",parent_key:"on-sby-knees",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Отныне все глотки превращаются в поцелуи. Вместо того, что бы пить, крутите бутылочку и целуйте того, на кого укажет горлышко. Если кто-либо откажется, делает вдвое больше глотков. ",key:"spin-the-bottle",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Игра в бутылочку закончена",key:"",parent_key:"spin-the-bottle",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Ты бы переспал(а) со своим боссом, если бы он(она) был(а) сексуальный(ной), для продвижения по карьерной лестнице? Отвечайте по кругу и делайте по 2 глотка. %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Переспал(а) ли ты с противным старикашкой за 150 000 USD. Отвечают все игроки и делают по $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, назови букву. Те игроки, кто спал с человеком, чье имя начинается на выбранную букву, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Каждый игрок по очереди должен назвать эрогенную зону %s. Тот, кто не сможет ответить или повторится, делает $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, назови про себя секс позицию. Все игроки по очереди должны угадать, что это за позиция. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, назови про себя место, где ты бы хотел заняться сексом. Все игроки по очереди должны угадать, что это за место. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, назови про себя вещь, которую можно использовать во время секса. Все игроки по очереди должны угадать, что это за вещь. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, подумай про себя, кого из игроков ты считаешь самым горячим в постели. Все игроки по очереди должны угадать, кто это. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Какую часть своего тела вы любите больше всего? Отвечайте по кругу и делайте по 2 глотка. %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"В чем вы спите? Отвечайте по кругу и делайте по 2 глотка. %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Что вас возбуждает в вашем партнере? Тот, кто не ответит или повторится, делает $ глотка(ов). %s начинает ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Какие фразы возбуждают во время секса? Тот, кто не ответит или повторится, делает $ глотка(ов). %s начинает ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Что вы думаете о предварительных ласках? Отвечают все игроки и делают по $ глотка(ов). %s начинает ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Новая тема и $ глотка(ов), кто проиграл: места где %s занимался(лась) сексом\u0022 %s начинает\u0022",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Новая тема и $ глотка(ов), кто проиграл : знаменитости которые засветились в домашнем порно\u0022 %s начинает\u0022",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Новая тема и $ глотка(ов), кто проиграл: порно актрисы\u0022 %s начинает\u0022",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Новая тема и $ глотка(ов), кто проиграл: секс позиции\u0022 %s начинает\u0022",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Каждый игрок должен назвать самое необычное место, где он(она) занимался(лась) сексом и сделать $ глотка(ов), %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"По очереди каждый игрок должен показать свою татуировку или пирсинг. Те, у кого их нет, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"7",text:"%s, допей свой бокал и расстегни зубами ширинку одного из игроков на твой выбор",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, допей свой бокал и укуси или облизни ухо того человека, который тебя привлекает ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, допей свой бокал и поцелуй в губы любого из игроков ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, станцуй сексуальных танец для %s и допей свой бокал",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s поставь засос %s и сделай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, допей свой бокал и изобрази минет(куни) для %s",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, оближи ухо %s или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, оближи щеку %s или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, выбери игрока, который будет тебя ласкать, пока ты допиваешь свой бокал",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, сними 3 элемента одежды и допивай свой бокал ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, выбери игрока, с которым вы будете целоваться после каждого сделанного вами глотка. Продолжайте, пока ваши бокалы не опустеют",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, выбери игрока, чья рука будет находиться у тебя между ног, пока ты допиваешь свой бока до дна. Рука должны быть под нижним бельем...",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, выбери игроков, которые должны допить свои бокалы до дна и поцеловаться с языком",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, допей до дна бокал игрока, с кем бы ты мог/могла переспать этой ночью",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, выбери игрока, который будет тебя ласкать, пока ты допиваешь свой бокал. Если ты девушка, ласкать будут твою грудь. Если парень - член ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Девушки, в мужчине вас больше привлекает накачанный пресс или накачанная грудь? Парни: грудь или попа? Отвечают все игроки и делают по $ глотка(ов). %s начинает ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Вы за или против секса на одну ночь? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Вы за или против незащищенного секса? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Секс с сильно пьяным партнером: отвратительно или занимательно? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что ты предпочитаешь: актив или пассив? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Что ты предпочитаешь: орал или анал? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Что ты предпочитаешь: легкую интрижку или серьезные отношения? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Что ты выберешь: секс с любимой порно звездой или с любимым(ой) актером(актрисой)? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Что ты предпочитаешь: стринги или шортики? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Что ты выберешь: сняться в порно или снять порно? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Ты бы предпочел(предпочла) поцеловать %s или %s ? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"3"},
{cycle_state:"false",type:"14",text:"Ты бы предпочел(предпочла) секс с %s или %s ? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"3"},
{cycle_state:"false",type:"14",text:"Что ты предпочитаешь: секс с 3 партнерами или с 15? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что предпочитаешь: оральный секс или вагинальный? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что бы ты выбрал(а): вдеть сквозь одежду или быть невидимкой? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что ты выберешь: секс со знаменитостью или самым сексуальным человеком в твоем окружении? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Выбирай: Меган Фокс или Скарлетт Йоханссон ? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что ты выберешь: идеальные отношения и скучный секс или ужасные отношения и невероятный секс? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что ты выберешь: никогда не испытать любовь или никогда не заниматься сексом? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что бы ты выбрал(а): пенис 9 см или 36 см? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Предпочитаешь заниматься сексом утром или вечером? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Костюм медсестры или полицейской, что сексуальней? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ты бы предпочел(предпочла) поцеловать игрока справа или слева? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ты бы предпочел(предпочла) заняться сексом с игроком справа или слева? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Костюм полицейского или пожарника? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Чего вы больше всего боитесь? Отвечайте друг за другом и делайте по 2 глотка. %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Опишите того игрока, которому не хватает сексуальности и нажмите на экран ",key:"horny",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Тот, кого описали, делает $ глотка(ов)",key:"",parent_key:"horny",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Все, кроме описанного игрока, делают $ глотка(ов)",key:"",parent_key:"horny",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Тот, кого описали другие игроки, утоляет свою печаль в алкоголе и делает $ глотка(ов) (сегодня вечером тебе уже ничего не светит...) ",key:"",parent_key:"horny",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Идеальная продолжительность полового акта? %s начинает",key:"sex-duration",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, если твоя идеальная продолжительность\u0022 больше 15 минут делай столько глотков сколько минут было названо\u0022",key:"",parent_key:"sex-duration",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Те, кто сказал быстрый перепихон тоже сойдет\u0022 делают $ глотка(ов)\u0022",key:"",parent_key:"sex-duration",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Те, кто ответил больше 20 минут, делают $ глотка(ов) ",key:"",parent_key:"sex-duration",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Сколько у вас было сексуальных партнеров? Отвечает каждый игрок, продолжение следует... %s начинает",key:"number-partner-sex",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Те, у кого было меньше 4 партнеров, решают, кому делать $ глотка(ов)",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Те, у кого было более 9 партнеров, решают, кому делать $ глотка(ов)",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Тот, у кого самое больше количество, делают $ глотка(ов) ",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Самая странная твоя эротическая фантазия? Отвечают все игроки и делают по $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Ваше самое длительное время воздержания? Отвечают все игроки и делают по $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Сколько раз в неделю тебе кажется идеальным заниматься сексом? Отвечают все игроки и делают по $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Ваш самый худший сексуальный опыт. Отвечают все игроки и делают по $ глотка(ов). %s начинает ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Ваша любимая позиция в сексе? Отвечают все игроки и делают по $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Самая несексуальная фраза, который ваш партнер может сказать во время секса. Отвечают все игроки и делают по $ глотка(ов). %s начинает ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Вы устали, а ваш партнер хочет секса, ваши действия? Отвечают все игроки и делают по $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Представьте: перед смертью у вас есть 5 минут на секс (с кем хотите и где хотите). Отвечают все игроки и делают по $ глотка(ов). %s начинает ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Каждый игрок делает $ глотка(ов) и говорит, с кем бы он переспал из присутствующих",key:"who-u-wanna-fuck",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Если кто-нибудь указал на %s , он(она) может поцеловать того игрока, который назвал его(ее) имя. Или сделать $ глотка(ов)",key:"",parent_key:"who-u-wanna-fuck",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Все по очереди должны поцеловать одного из игроков. Тот, кто откажется, делает $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Каждый игрок выбирает того, что потрогает его гениталии. Тот, кто откажется, делает $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Каждый игрок выбирает того, кто должен снять с себя один из предметов одежды. Тот, кто откажется, делает $ глотка(ов). %s начинает ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"По очереди каждый игрок крутит бутылочку и целует того игрока, на кого покажет горлышко. $ глотка(ов) в случае отказа. %s начинает ",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Конкурс трусов! Чьи трусы самые крутые? Девушки выбирают победителя, проигравший делает $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Конкурс лифчиков! Чей лифчик самый крутой? Парни выбирают победителя, проигравший делает $ глотка(ов)",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"По очереди каждый игрок должен поцеловать соседа слева или сделать $ глотка(ов), %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"По очереди каждый игрок должен потрогать своего соседа/свою соседку слева между ног или сделать $ глотка(ов), %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"По очереди каждый игрок должен потрогать своего соседа/свою соседку справа между ног или сделать $ глотка(ов), %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"По очереди каждый игрок должен потрогать грудь своего соседа/своей соседки справа или сделать $ глотка(ов), %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"По очереди каждый игрок должен потрогать грудь своего соседа/своей соседки слева или сделать $ глотка(ов), %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"По очереди каждый игрок должен показать пигментное пятно на теле и решить, кому делать $ глотка(ов). Если такого пятна нет, делайте $ глотка(ов), %s начинает",key:"",parent_key:"",pack_name:"hot",language:"ru",nb_players:"1"}]);
retrieveDB();