var db = TAFFY([{cycle_state:"false",type:"1",text:"%s, als je een meisje bent, lik dan op een verleidelijke manier aan je vinger. Als je een man bent, doe je een bef-imitatie met 2 vingers van je hand. En/of je drinkt $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, doe 10 seconden lang net of je een orgasme hebt",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Alle meisjes moeten hun string boven hun broek uittrekken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s en %s geven elkaar een knuffel en drinken allebei een slok",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s laat zijn vinger zuigen door %s of neemt $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"De mensen die een overhemd aan hebben knopen het los en nemen een slok per knoop",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s doet een kledingstuk uit van %s of neemt $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, hoeveel glazen moet je drinken om met %s naar bed te gaan? Antwoord en neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, wie is van alle deelneemsters kan volgens jou het beste pijp**? Antwoord en neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s geeft $ slokken aan degene die het meest sexy is",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s doet 5 seconden lang op zijn hondjes na of neemt $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, noem iets geils dat je nog nooit hebt gedaan, degenen die het al eens gedaan hebben, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, als je ons een van je tepels laat zien, moet %s $ slokken nemen, anders neem je er zelf $",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s, %s en %s hebben groepsseks of nemen allemaal $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"4"},
{cycle_state:"false",type:"1",text:"%s kies tussen $ slokken nemen of de voeten van %s kussen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, als je %s een zoen geeft, moet iedereen $ slokken nemen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Drink net zo veel slokken als het aantal orgasmen dat je deze week hebt gehad. Aftrekken telt ook mee.",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Als %s en %s elkaar op de mond zoenen, delen ze allebei $ slokken uit, anders neemt iedereen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"De speler die als eerste een geile app laat zien, deelt $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, als je het helemaal niet vervelend vindt om met %s naar bed te gaan, deel je $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, knijp in de tepels van %s of hij/zij moet $ slokken nemen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s likt de neus van %s of neemt $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, masseer het hoofd van %s of neem $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s laat zijn/haar kruis betasten door %s of neemt $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, geef een zoen op de neus van %s of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s kiest twee mensen die elkaar gaan zoenen of moet $ slokken moeten drinken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"3"},
{cycle_state:"false",type:"1",text:"%s, heb je liever orale, anale of vaginale seks? Antwoord en neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Zij die zich al eens hebben laten uitschelden bij het vrijen, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, lik de mond van een van de spelers of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lik de tong van een van de spelers of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Iedereen neemt $ slokken. Behalve %s, die iedereen een kusje gaat geven",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, zoen %s of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, je kunt kiezen tussen iemand van jouw keuze zoenen of $ slokken nemen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s geeft %s van mond tot mond een ijsblokje door of neemt $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, begin $ slokken te drinken. Als je een man bent, beschrijf dan hoe je het lekkerst gepijpt wordt. Als je een vrouw bent, beschrijf dan hoe je pijpt",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, begin $ slokken te drinken. Als je een vrouw bent, beschrijf je hoe je het lekkerst gebeft wordt Als je een man bent, vertel dan hoe je het doet",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kies de persoon die een lichaamsdeel van je mag likken. $ slokken als je weigert",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s moet de tepels van een speler licht aanraken, $ slokken als je weigert",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s moet zijn/haar tepels kort laten aanraken door een speler naar keuze. $ slokken als je weigert",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kus de torso van een speler of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, laat je borst / torso zoenen door een speler naar keuze. $ slokken als je weigert",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, als je een jongen bent, ga dan achter een vrouwelijke speler staan en streel haar over de borsten, kies een man die jou over je borsten streelt als je een meisje bent... $ slokken als je weigert",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s kies een speler van je keuze om een lap dance voor je te geven, $ slokken als hij of zij weigert",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, streel de billen van een speler 5 seconden lang, $ slokken als hij of zij weigert!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, laat je door een speler van je keuze 5 seconden lang over je billen strelen. $ slokken als je weigert",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kijk in de ogen van de persoon met wie je vanavond zou willen vrijen, deze persoon moet $ slokken drinken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kies iemand die moet drinken terwijl jij hem/haar over zijn/haar edele delen streelt",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, laat een topless foto van jezelf zien of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, knabbel aan het oor van een speler of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kies 2 mensen die elkaar gaan tongzoenen, degene die weigert, neemt $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kies wie een van zijn/haar tepels laat zien.. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, laat een intiem deel van je lichaam zien of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kies een speler die een intiem deel van zijn/haar lichaam moet laten zien. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, doe een standje na met een van de andere spelers of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kies twee spelers die een standje moeten nadoen en tegelijkertijd $ slokken nemen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, wrijf je hoofd tegen de intieme delen van iemand. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kies iemand die zijn hoofd tegen de jouw intieme delen moet wrijven. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kies een speler die zijn hoofd moet schudden tussen de borsten van een van de vrouwelijke spelers. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lik de intieme delen van iemand. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kies iemand die je intieme delen moet likken. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, streel de intieme delen van iemand of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kies iemand die je intieme delen moet strelen. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kies iemand die zijn/haar hand onder je ondergoed moet steken. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, je moet je hand onder het ondergoed van iemand steken. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, breng iets van eten van jouw mond in de mond van een ander. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kies twee spelers die iets van eten van een mond naar de andere moeten brengen. $ slokken voor allebei bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, raakt de borsten van een meisje aan. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Iedereen drinkt en trekt een kledingstuk uit!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, kies iemand die een kledingstuk moet uitdoen. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, daag een speler uit om de bh van een van de vrouwelijke spelers los te maken. Als de aangewezen persoon er binnen 5 seconden niet in slaagt, moet hij $ slokken nemen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, laat je door een speler naar keuze in je tepel knijpen of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, knijp in de billen van een speler naar keuze. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, laat je in je billen knijpen door een speler naar keuze of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lik de lippen van een speler naar keuze. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, laat je lippen likken door een speler naar keuze of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lik de tepels van een speler naar keuze. $ slokken bij weigering",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, laat je tepels likken door een speler naar keuze of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Mannen, trek een kledingstuk uit of drink $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Meiden, trek een kledingstuk uit of drink $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Mannen, ontbloot je bovenlijf of drink $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Meiden, ga in je BH zitten of drink $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ga je ondergoed uittrekken en kom terug. Of als je niet wilt, drink dan je glas leeg",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kies een letter. Alle spelers die naar bed gegaan zijn met iemand van wie de voornaam met deze letter begint, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, masseer 2 minuten lang de voeten van de speler van je keuze of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, laat 2 minuten lang het lichaamsdeel van je keuze masseren door de speler die je wilt. Elke weigering betekent $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lik rond de navel van een speler van je keuze of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, laat je rond je navel likken door de speler van je keuze. Elke weigering betekent $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, geef de persoon van je keuze een zuigzoen of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, laat je door de persoon van je keuze een zuigzoen geven, die persoon mag weigeren voor $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Als jij de grootste borsten hebt, wijs dan een gast aan om je borsten te likken of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, laat je billen zien of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kies een deel van je lichaam. De speler die dat lichaamsdeel als eerste aanraakt, deelt $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, laat je tieten zien of neem $ slokken. Als je een man bent, mag je er $ uitdelen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Benoem samen wie het meest lenig is en diegene moet dat laten zien en $ slokken drinken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, geef een zoentje in de hals van de persoon van je keuze of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"We doen het nog eens over! Zij die al eens met elkaar naar bed zijn geweest, zoenen elkaar weer of drinken alle bei $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, laat de persoon van je keuze jou een zoen in je hals geven of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, stuur een geile app naar iemand die is uitgekozen door de groep. Als deze persoon erop ingaat, mag je iemand zijn glas in een keer laten leegdrinken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deelt $ slokken uit aan degene met wie %s best eens naar bed zou willen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, drink net zoveel slokken als er mensen zijn met wie je de afgelopen zes maanden seks hebt gehad",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"1",text:"De eerste speler, %s of %s, die het geslachtsdeel van een andere speler aanraakt, deelt $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Als je graag je buurman/-vrouw links van je een zoen wilt geven, moet je je vinger opsteken. De anderen nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s en %s, lees de eerste app die naar voren komt als je in de zoekbalk “seks” intypt. Als je weigert moet je $ slokken nemen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s en %s, lees de eerste app die naar voren komt als je in de zoekbalk “pik” intypt. Als je weigert moet je $ slokken nemen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s en %s, lees de eerste app die naar voren komt als je in de zoekbalk “pijpen” intypt. Als je weigert moet je $ slokken nemen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s moet nu net doen of hij/zij klaarkomt vóór elke slok",key:"orgasm-simulation",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s hoeft niet meer te doen of hij/zij klaarkomt vóór elke slok",key:"",parent_key:"orgasm-simulation",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, kies iemand die je in de ogen kijkt, je hoort wel als je daar weer mee kan stoppen",key:"look-in-the-eyes",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s je hoeft je vriend(in) niet langer in de ogen te kijken!",key:"",parent_key:"look-in-the-eyes",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s ga met een holle rug op handen en voeten zitten, je hoort wel als je weer mag opstaan",key:"doggy-style-way",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s mag weer in een gemakkelijke houding gaan zitten",key:"",parent_key:"doggy-style-way",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s werkt bij de recherche! Je mag wie je wilt op elk moment fouilleren, degene die gefouilleerd wordt, kan weigeren voor $ slokken",key:"body-search",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s werkt niet meer bij de recherche en deze viezerik moet nu $ slokken nemen",key:"",parent_key:"body-search",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s is Cupido! Hij/zij kiest wie elkaar een zoen geven en elkaar strelen, als hij/zij dat wil, anders $ slokken",key:"cupidon",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s is niet langer Cupido",key:"",parent_key:"cupidon",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s smacht naar seks... Hij of zij moet iemand zoenen voordat hij/zij mag drinken",key:"kiss-before-drink",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s heeft nu genoeg gezoend!",key:"",parent_key:"kiss-before-drink",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s houdt tot nader order verliefd de hand van %s vast",key:"hold-hand",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s en %s mogen elkaar loslaten",key:"",parent_key:"hold-hand",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s kies iemand die hem/haar een handmassage geeft! Hij/zij hoort wel als hij/zij mag stoppen",key:"hand-massage",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s stopt met het masseren van de hand",key:"",parent_key:"hand-massage",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s is onweerstaanbaar! Telkens als je een zoentje vraagt (op de mond of ergens anders), moet de uitverkorene dat doen of drinken",key:"irresistible",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s is weer lelijk",key:"",parent_key:"irresistible",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s en %s, jullie gaan tot nader order voetje vrijen",key:"naughty-feet",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s en %s kunnen stoppen met voetje vrijen",key:"",parent_key:"naughty-feet",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s moet iemand kiezen die zijn/haar hand tot nader order onder zijn/haar billen legt",key:"hand-under-ass",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s kan deze grijpgrage gast of meid weer bevrijden!",key:"",parent_key:"hand-under-ass",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s moet tot nader order zijn/haar hand op de dij van een speler leggen",key:"put-your-hand-on-legs",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s mag zijn hand terug!",key:"",parent_key:"put-your-hand-on-legs",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"Spelletje! Telkens als %s een glas aanraakt, moet %s extreem genot nadoen $ slokken als het niet gebeurt!",key:"touch-glass-and-cum",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s en %s stoppen met dit grappige spelletje",key:"",parent_key:"touch-glass-and-cum",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, kies op een willekeurig moment 2 spelers, de een gaat bij de ander op schoot zitten. $ slokken voor elke weigering",key:"on-sby-knees",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, je mag niet langer kiezen wie op schoot bij wie gaat zitten",key:"",parent_key:"on-sby-knees",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, je lippen zijn besmettelijk! Als je erin slaagt een speler een zoen te geven zonder diegene te dwingen voordat het virus over is, moet deze speler zijn glas leegdrinken!",key:"kiss-poison",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, je lippen zijn niet langer besmettelijk! Als je er niet in bent geslaagd, neem je $ slokken",key:"",parent_key:"kiss-poison",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, je handen zijn besmettelijk! Als je erin slaagt een speler een aai te geven zonder dat diegene het in de gaten heeft voordat het virus over is, moet deze speler zijn glas leegdrinken!",key:"caddle-poison",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, je handen zijn niet langer besmettelijk! Als je er niet in bent geslaagd, neem je $ slokken",key:"",parent_key:"caddle-poison",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"3",text:"Nu moeten je je borst strelen, als je praat!",key:"caress-boobs",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"We hoeven niet langer te strelen, als we praten!",key:"",parent_key:"caress-boobs",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Het is nu mogelijk met flesje draaien om je slokken te gaan spelen! In plaats van te drinken, moeten jullie de fles laten draaien en de aangewezen speler een zoen geven, als je weigert moet je het dubbele drinken!",key:"spin-the-bottle",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Flesje draaien is nu afgelopen!",key:"",parent_key:"spin-the-bottle",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Vanaf nu moet iemand die krachtterm gebruikt een kledingsstuk uittrekken of $ slokken nemen!",key:"cross-word-clothe",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Je kunt nu weer krachttermen gebruiken zonder een kledingstuk kwijt te raken",key:"",parent_key:"cross-word-clothe",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nu moeten we duim zuigen of die van een ander, als we spreken",key:"fingers-mouth",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Je hoeft niet langer duim te zuigen",key:"",parent_key:"fingers-mouth",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Vanaf nu moet iedereen drinken, zodra een meisje haar borsten laat zien!",key:"show-your-boobs",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Meiden, jullie hoeven je borsten niet meer te laten zien",key:"",parent_key:"show-your-boobs",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Een rondje maken! Als je wilt kun je een rondje maken met je duim en je wijsvinger tussen je schouder en je middel, de spelers die kijken moeten een kledingstuk uittrekken of $ slokken nemen",key:"round-game-hot",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Stoppen met een rondje maken!",key:"",parent_key:"round-game-hot",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nieuwe regel, we spelen Duim omhoog (iemand laat een boer, degene die als laatste zijn duim op zijn voorhoofd zet, verliest)! Telkens trekt de verliezer een kledingstuk uit of neemt een slok",key:"gofio-game-hot",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Duim omhoog is afgelopen!",key:"",parent_key:"gofio-game-hot",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nieuwe regel: Als je de blik van een andere speler kruist, terwijl je op je vinger zuigt, moet die drinken",key:"suck-your-finger",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Stop met stoute gebaren naar elkaar maken",key:"",parent_key:"suck-your-finger",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nieuwe regel! Telkens als je gedronken hebt, moet je je tepels strelen. Anders moet je weer drinken",key:"caddle-tities",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Je hoeft niet langer je tepels te strelen",key:"",parent_key:"caddle-tities",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"4",text:"De erogene zones van %s\u0022 de speler die het niet raadt of in herhaling treedt neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, denk aan een standje. Alle spelers doen om de beurt een standje voor, de eerste die het raadt, deelt $ slokken uit. %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, denk aan een andere seksuele activiteit dan de penetratie. Alle spelers doen om de beurt een standje voor, de eerste die het raadt, deelt $ slokken uit. %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, neem de aanwezige speler in gedachten die volgens jou het geilst in bed is. Alle spelers moeten om beurten iemand noemen, de eerste die het raadt, deelt $ slokken uit. %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, denk aan een sextoy. Alle spelers moeten om beurten iets noemen, de eerste die het raadt, deelt $ slokken uit. %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"4",text:"De lichaamsdelen van %s die hij of zij mooi vindt\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken! %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"4",text:"De outfit waarin %s al heeft geslapen\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken! %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Wat je opwindend vindt bij je partner\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken! %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"De zinnen die opwindend zijn tijdens seks\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken! %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Je ex sekspartners, als je een voornaam geeft die al genoemd is of als je het niet meer weet, moet je $ slokken nemen. %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Nieuw thema en $ slokken in het spel: beroemde mensen die een sextape hebben gemaakt\u0022 %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Themagame en $ slokken op het spel: de plaatsen waar %s seks heeft gehad\u0022 %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Themagame en $ slokken op het spel: de gemeenschappelijke fantasieën\u0022 %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Nieuw thema en $ slokken in het spel: de seksuele activiteiten\u0022 (penetratie ...) %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Laat om de beurt je tattoos en piercings zien, als je er geen hebt, neem je $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"4",text:"Laat om de beurt een van je moedervlekken zien en deel $ slokken uit. Als je geen moedervlekken hebt, moet je $ slokken nemen, %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"De seksbommen die al reality-tv hebben gedaan\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sextoys\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Redenen om met een onbekende naar bed te gaan\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"De dingen die je moet doen voordat je uitgaat als je single bent\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"TV-zenders die erotische films uitzenden\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"De plaatsen waar je je handen moet houden tijdens de penetratie\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Soorten voorspel\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Excuses om niet te blijven slapen na een vrijpartij\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"De meest voorkomende plaatsen uit seksuele fantasieën\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"De meest voorkomende outfits in seksuele fantasieën\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Beroepen in verband met erotiek of seks\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Geuren van condooms\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Eten waarvan je zin in seks krijgt als het op een speciale manier wordt gegeten\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Synoniemen van een orgasme krijgen\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"De plaatsen waarop je zachtjes kan bijten om je partner op te winden\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Voorwerpen die gebruikt worden in een sado-masochistische relatie\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"De lichaamsdelen die lekker zijn om te likken bij het vrijen\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"De dingen die vaak gedaan worden vlak nadat je seks gehad hebt\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"De dingen die een seksfetish kunnen zijn\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"De seksuele handelingen die je met je tong kan doen\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"4",text:"De manieren om een vrouw te laten klaarkomen\u0022 de speler die in herhaling treedt of niets meer weet neemt $ slokken. %s begint\u0022",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, drink je glas leeg en ga met je tanden de rits naar beneden doen van de persoon van je keuze",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, drink je glas leeg en ga zachtjes in het oor bijten of likken van degene die je het meest aantrekkelijk vindt",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, drink je glas leeg en ga de persoon van je keuze zoenen (op de lippen)",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, maak een sexy dans voor %s nadat je je glas hebt leeg gedronken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s geef %s een zuigzoen of jullie drinken allebei $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s drink je glas leeg en doe alsof je %s pijpt of likt",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s geef elke speler een zoen en drinkt een glas leeg (je mag zelf weten welk)!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, heef %s een tongzoen of neem $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, kies iemand die je moet strelen terwijl jij je glas leeg drinkt...",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, trek 3 kledingstukken uit en drink je glas leeg...",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, iemand met wie je gaat spelen. Jullie nemen een slok en zoenen elkaar daarna. Totdat jullie allebei je glas leeg hebben...",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, kies een speler die zijn/haar hand op je kruis legt, terwijl jij je glas leegdrinkt. Hand in je ondergoed...",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, kies twee spelers die hun glas leegdrinken en elkaar daarna tongzoenen...",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, je drinkt het glas leeg van de speler met wie je vanavond naar bed wilt...",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, je drinkt je glas leeg, terwijl een een speler naar keuze je streelt. Als je een meisje bent, zijn het je borsten, als je een gast bent je kruis.",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Wie van %s of %s is de beste partner voor voorspel volgens jou? Stem allemaal, degene die de meeste stemmen krijgt, deelt $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"14",text:"Liever borstpartij (borsten voor mannen) of buikspieren (billen voor mannen) Stem allemaal tegelijk, de verliezers nemen $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Voor of tegen one-night-stands? Stem allemaal tegelijk met opgeheven hand, zij die in de minderheid zijn, nemen $ slokken !",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Tieten, liever te groot of te klein? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever onderworpen of dominant? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Liever pijpen of anaal? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Liever een avontuurtje of een serieuze relatie? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Liever rimmen of orgy? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Liever brazilian wax of helemaal kaalgeschoren? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Liever string of shorty? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Liever bukka** of anaal? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Liever 30 keer op een dag neuken of een maand lang niet neuken? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Liever %s of %s zoenen? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"14",text:"Liever met %s of %s neuken? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"14",text:"Liever een trio of met zijn achten? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever cunni of fellati**? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever doorzichtige kleding of onzichtbaar zijn? Stem om de beurt, zij die in de minderheid zijn nemen $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever met een beroemdheid naar bed of met de meest sexy persoon die je kent? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever Megan Fox of Scarlett Johansson? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever een perfecte maar seksueel saaie relatie of een slechte maar seksueel fantastische relatie? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever nooit de liefde vinden of nooit meer een seksuele relatie hebben? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever een van 9cm of 36cm? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Stoute dingen liever 's morgens of 's avonds? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever als verpleegster of politieagente? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever je linker- of rechterbuurvrouw zoenen? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever naar bed met je linker- of rechterbuurvrouw? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever als brandweerman of marinier? Stem allemaal tegelijk, zij die in de minderheid zijn, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Als je met je vingers knipt liever een broek of een top uit? Stem tegelijk, de verliezers nemen $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever een week lang een grenzeloze droom beleven of de macht hebben dat wie dan ook je je hele leven seksueel aantrekkelijk vindt? Stem tegelijk, de verliezers nemen $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever een abonnement op een parenclub of op een seksclub? Stem tegelijk, de verliezers nemen $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Voor of tegen in een pornofilm spelen? Stem tegelijk, de verliezers nemen $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Voor of tegen nudisme? Stem tegelijk, de verliezers nemen $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Voor of tegen swingers? Stem tegelijk, de verliezers nemen $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Heb je liever dat een chick bij het vrijen bovenop of onderop ligt? Stem tegelijk, de verliezers nemen $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever seks met iemand aan deze tafel of een willekeurige onbekende elke dag een week lang? Stem tegelijk, de verliezers nemen $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Liever voorspel met een van de spelers hier of 500 euro winnen? Stem tegelijk, de verliezers nemen $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Overtuig de jury! %s en %s vertellen een van hun fantasieën, de andere spelers stemmen wat het meest opwindend is! De winnaar deelt $ slokken uit, de ander drinkt zoveel slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Wijs degene aan die het meest smacht naar seks, klik daarna op het scherm",key:"horny",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"De aangewezen persoon deelt $ slokken uit",key:"",parent_key:"horny",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Iedereen neemt $ slokken behalve de aangewezen persoon",key:"",parent_key:"horny",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"De aangewezen persoon kan zijn verdriet verdrinken en neemt $ slokken (Vanavond ga je met niemand daten)",key:"",parent_key:"horny",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"De ideale duur van een date. %s begint (de anderen volgen...)",key:"sex-duration",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"De 3 spelers met de kortste duur, nemen $ slokken!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"De 3 spelers met de langste duur, nemen $ slokken!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, deelt $ slokken uit aan de spelers met de langste duur. Als je de langste tijdsduur hebt, neem je $ slokken",key:"",parent_key:"sex-duration",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, deelt $ slokken uit aan de spelers die een kortere duur hebben gekozen. Als jij de kortste duur hebt, neem je $ slokken",key:"",parent_key:"sex-duration",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Hoeveel sekspartners heb je gehad? Iedereen antwoordt, de rest volgt... %s begint",key:"number-partner-sex",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s en %s delen net zo veel slokken uit als ze sekspartners hebben gehad!",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s en %s nemen net zoveel slokken als ze sekspartners hebben gehad!",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"De speler die er het meeste heeft gehad, neemt $ slokken",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"De speler die er het minste heeft gehad, neemt $ slokken",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Overtuig de jury! %s en %s vertellen een vreemde seksdroom die ze hebben gehad, de andere spelers stemmen wat het meest bizarre is! De winnaar deelt $ slokken uit, de ander drinkt zoveel slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"De langste periode dat je geen seks hebt gehad na de eerste keer. Iedereen antwoordt, de rest volgt... %s begint",key:"abstinence-time",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"De speler met de langste periode, neemt $ slokken!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"De speler met de langste periode, deelt $ slokken uit!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s en %s delen net zoveel slokken uit als maanden van onthouding!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s en %s nemen net zoveel slokken als maanden van onthouding!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Het ideale aantal beurten per week volgens jou. Iedereen antwoordt, de rest volgt... %s begint",key:"nb-sexual-rel",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Degenen die meer dan 2 keer kiezen nemen $ slokken, de anderen nemen een kleintje",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Degenen van minder dan 3 nemen $ slokken. De andere nemen een kleintje",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s en %s delen zoveel slokken uit als seksuele contacten!",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s en %s nemen net zoveel slokken als seksuele contacten!",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Overtuig de jury! %s en %s vertellen over een van hun ergste seksuele ervaringen, de andere spelers stemmen over wat de ergste ervaring is! De winnaar deelt $ slokken uit, de ander drinkt zoveel slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Wat is je favoriete standje? Iedereen antwoordt, zij die dezelfde standjes kiezen, nemen samen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Overtuig de jury! %s en %s zeggen waarop je het meeste afknapt tijdens seks, de andere spelers stemmen wat het ergste is! De winnaar deelt $ slokken uit, de ander drinkt zoveel slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Overtuig de jury! %s en %s zeggen waar je partner het meest opgewonden van raakt, de andere spelers stemmen op wat het geilste is! De winnaar deelt $ slokken uit, de ander drinkt zoveel slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Je hebt recht op 5 minuten seks voor je doodgaat met een willekeurig persoon op een willekeurige plaats. %s en %s maken een keuze, de anderen stemmen wat het beste is! De winnaar deelt $ slokken uit, de ander drinkt zoveel slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Overtuig de jury! %s en %s over een van de beste veroveringen van hun leven, de andere spelers stemmen over wat het meest opwindend was! De winnaar deelt $ slokken uit, de ander drinkt zoveel slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Overtuig de jury! %s en %s vertellen wat de gekste plekken waren waar ze seks hebben gehad, de andere spelers stemmen over wat het meest bizarre is! De winnaar deelt $ slokken uit, de ander drinkt zoveel slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Neem om de beurt $ slokken en zeg met wie je in deze ruimte naar bed wilt.",key:"who-u-wanna-fuck",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, als je genoemd wordt, geef je de persoon die je genoemd hebt een zoen. Neem anders $ slokken",key:"",parent_key:"who-u-wanna-fuck",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Ga om beurten iemand zoenen. Degenen die weigeren, nemen $ slokken. %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Kies om beurten iemand die je kruis moet aanraken. Als hij of zij weigert, moet die $ slokken nemen. %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Kies om beurten iemand die een kledingstuk moet uittrekken. Als hij of zij weigert, moet die $ slokken nemen. %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Flesje draaien! Elke speler laat de fles draaien en zoent de aangewezen persoon, $ slokken voor een weigering. %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Wedstrijd boxershorts! De meisjes vormen de jury, de verliezer neemt $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Wedstrijd bh's! De mannen vormen jury, de verliezer neemt $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Kiss party! Zoen om de beurt je linkerbuurman of -buurvrouw of drink $ slokken, %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Raak de kut van je buurvrouw aan! Raak om de beurt het kruis van je rechterbuurman of -buurvrouw aan of drink $ slokken, %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Raak de kut van je buurvrouw aan! Raak om de beurt het kruis van je linkerbuurman of -buurvrouw aan of drink $ slokken, %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Raak de kut van je buurvrouw aan! Streel om de beurt de borst van je rechterbuurman of -buurvrouw of drink $ slokken, %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Raak de kut van je buurvrouw aan! Streel om de beurt de borst van je linkerbuurman of -buurvrouw of drink $ slokken, %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"De strikvraag! Stel om de beurt een stoute vraag aan een willekeurig persoon. Als diegene niet wil antwoorden, moet die $ slokken nemen. %s begint",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Wedstrijd billen: mannen defileer! Meiden jullie zijn de jury, de winnaar mag $ slokken uitdelen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, je krijgt een blinddoek voor en 2 spelers geven je een zoen, doet er niet toe waar. Als je een van de twee spelers herkent, deelt $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, je krijgt een blinddoek voor, een speler legt eten op zijn/haar buik en jij moet het opeten. Als je raadt wat het is, deel je $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Wedstrijd haargeur! De meisjes spelen, de jongens zitten in de jury. De winnares mag $ slokken uitdelen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degene die al eens seks heeft gehad op een openbare plaats, moet $ slokken drinken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degenen die al eens een triootje hebben gedaan, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degenen die al eens aan camsex hebben gedaan, delen $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degenen die al eens aan iemand anders hebben gedacht toen ze seks hadden, delen $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degenen die naar bed willen met iemand die hier aanwezig is, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je al eens op de eerste avond met iemand naar bed bent geweest",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Mensen die fellati** leuk vinden, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degenen die zich al eens hebben laten filmen toen ze de liefde bedreven, delen $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"De mensen die denken dat %s goed in bed is, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Degenen die al eens gerimd hebben, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degenen die al eens betrapt zijn, terwijl ze aan het masturberen waren, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degenen die hun schaamhaar afscheren, delen $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je langer dan twee weken niet op een pornosite geweest bent",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degenen die van geile woordjes houden bij het vrijen, delen $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"De mensen die al eens rollenspellen bij het vrijen hebben gedaan, delen $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degenen die met mensen naar bed zijn geweest van wie ze de voornaam niet meer weten, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degenen die al eens seks in een hotel hebben gehad, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degenen die nog nooit in een auto seks hebben gehad, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die deze week geen seks hebben gehad, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"De spelers die met iemand van 5 jaar ouder naar bed zijn geweest, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"De spelers die met iemand van 5 jaar jonger naar bed zijn geweest, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degenen die al eens geile apps hebben gestuurd of ontvangen, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"De spelers bij wie het al eens helemaal niet lukte, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"De mensen die al eens een avontuurtje hebben gehad met een andere speler, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die al eens door hun ouders zijn betrapt toen ze seks hadden, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, als je nooit meer dan 4 keer op één dag seks hebt gehad, neem anders $ slokken, anders deel je ze uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Zij die al eens fantasieën hebben over de partner van een vriend(in) hebben gehad, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die al eens erotische foto's hebben verstuurd, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die al eens eten van het lichaam van hun partner hebben gelikt of gegeten, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die al eens de voornaam van hun partner hebben uitgeschreeuwd bij het vrijen, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die na minder dan 3 minuten neuken al eens een orgasme hebben gehad, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die al eens seks hebben gehad toen zij of hun partner ongesteld waren, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Wie het beste is in bed van %s of %s, neemt $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Voor wie de eerste keer een one-night-stand was, neemt $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"De meisjes bij wie de eerste keer pijn deed, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, als je al eens stiekem verliefd bent geweest op %s, neem je $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Zij die al eens voorwerpen in hun partner hebben geduwd, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die ingeschreven zijn bij een datingsite, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die al eens iemand ontmoet hebben via een datingsite, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degene die het laatst op een pornosite geweest is, deelt $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degene die al vaker mensen ontmoet heeft via een datingsite, deelt $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die hun sekspartner al eens hebben gekrabd of zijn gekrabd door hun sekspartner, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die al eens een dildo in hun hand hebben gehad, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die al eens hulpmiddelen hebben gebruikt bij het vrijen, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Wie al eens seksueel opgewonden is geraakt van een professionele massage, neemt $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Wie al eens gespuugd heeft op het geslacht van de ander, neemt $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Wie minder dan een maand geleden iemand heeft gepijpt, neemt $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die minder dan een week geleden gepijpt hebben, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die al eens een voorwerp in anus of vagina hebben gestopt, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die hun partner tijdens het vrijen al eens hebben uitgescholden, jullie nemen $ slokken stelletje gekken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die een keer gezien hebben dat een vriend(in) zijn/haar partner bedroog, jullie nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die al eens zijn uitgegaan met de ex van een vriend(in), jullie nemen $ slokken stelletje debielen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, als je laatste seksueel contact beschermd was, deel je $ slokken uit, anders neem je zoveel slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je het geil vindt bekeken te worden bij het vrijen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je al eens geneukt hebt bij een pornofilm",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je het leuk vindt bij een pornofilm te neuken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je nu meteen zin hebt",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je het lekker vindt dat je anus wordt aangeraakt bij het vrijen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je het lekker vindt met de anus van je partner te spelen bij de penetratie",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je van billenkoek houdt",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"De stouteriken die al eens een seksuele ervaring hebben gehad met beide seksen, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"De meisjes die al eens een vaginaal orgasme hebben gehad, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je al eens een anaal orgasme hebt gehad",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Etnische mix! Als je al eens keer seks hebt gehad met iemand met een andere huidskleur, deel je $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je een keer een sexy outfit hebt aan gehad om het geiler te maken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je een keer hebt gekeken, terwijl anderen een wip maakten",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je drie eerste keren een one-night-stand waren.",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je een keer een massage gegeven hebt die uit de hand liep...",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je een keer een massage hebt ondergaan die uit de hand liep...",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je denkt dat je niks nieuws kunt ontdekken op seksueel gebied",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, lik een lichaamsdeel (je mag zelf kiezen welk) van de speler die door %s gekozen is",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je een keer geneukt hebben waar anderen bij waren",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je een keer bij een swingeravond bent geweest",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Deel $ slokken uit als je je een keer hebt gemast*urbeerd in bijzijn van je partner",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Deel $ slokken uit als je een keer gemast*urbeerd hebt denkend aan een collega",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je een keer gemast*urbeerd hebt bij een film, geen pornofilm",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Zij die het voorspel hebben gedaan tussen twee penetraties in, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"De meisjes die de twerk niet kunnen dansen, nemen $ slokken!",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je fantasieën hebt over een van de andere spelers",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degene die het laatste seks heeft gehad, trekt een kledingstuk uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je in het bed van een vriend(in) seks hebt gehad zonder dat die het wist",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Deel $ slokken uit als je een keer voorspel hebt gedaan met een ijsblokje",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Deel $ slokken uit als je eens een voorspel met chlorofyl kauwgum in je mond gedaan hebt...",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je je naakt hebt laten fotograferen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je geen ondergoed aan hebt",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je het voorspel lekkerder vindt dan het neuken zelf",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je van hard houdt in bed",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je niet zonder voorspel kan",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, als je voor het eerst seks gehad hebt voor je zeventiende, deel je $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, zou je met je baas naar bed gaan om je carrièremogelijkheden te vergroten? Ja: neem $ slokken, Nee: deel ze uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, zou je met een vieze oude man of vrouw naar bed gaan voor € 150.000? JA: deelt $ slokken uit, Nee: drink ze op",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je al eens in een parenclub bent geweest of hebt geprobeerd er binnen te komen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"De meiden die al eens net als of gedaan hebben, nemen $ slokken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degene die het laatst gepijpt heeft, deelt $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Degene die het laatst gebeft heeft, deelt $ slokken uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je minder dan een maand geleden gebeft hebt",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je minder dan een week geleden gebeft hebt",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je je vriend pijpend hebt wakker gemaakt. Voor gasten, zij die zijn gepijpt bij het wakker worden.",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je het kruis van iemand hebt gestreeld met je voeten",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, deelt $ slokken uit als je je partner kan vergeven als hij/zij vreemd gaat. Zo niet, drink ze dan zelf op",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je sextoys hebt",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je meerdere mensen op een avond hebt getongzoend",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je het geil zou vinden als je partner seks heeft met een ander",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je vaker seks hebt gehad in het donker dan overdag",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je al eens iets in een seksshop hebt gekocht",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, deel $ slokken uit als je jezelf aantrekkelijk vindt. Als je lelijk bent, moet je zelf drinken",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je al met iemand seks hebt gehad en diegene je voornaam niet kent",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, neem $ slokken als onbekenden je hebben zien vrijen. Zo niet, deel ze dan uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je seks hebt gehad terwijl je dronken was",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, neem $ slokken als je iemand gezoend hebt die je walgelijk vond. Zo niet, deel ze dan uit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je denkt dat je degene rechts van je in minder dan 10 minuten kan laten klaarkomen",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je denkt dat degene die links van je zit vandaag nog met een van de spelers naar bed gaat",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je eerste keer niet geweldig was",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je een keer versierd bent door iemand van hetzelfde geslacht",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je een keer een erotische droom hebt gehad over iemand die aan deze tafel zit",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je het lekker vindt als je er aan je tepels geknabbeld wordt",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, als je denkt dat je de meeste veroveringen aan deze tafel hebt, deel dan $ slokken uit. Zo niet, drink ze dan zelf op",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je meer dan een spelers aan deze tafel aantrekkelijk vindt.",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Neem $ slokken als je al eens met iemand gesekst hebt die je ontmoet hebt via een dating-app",key:"",parent_key:"",pack_name:"hot",language:"nl",nb_players:"0"}])