var db = TAFFY([{cycle_state:"false",type:"1",text:"%s, se sei una ragazza leccati il dito in maniera erotica. Se sei un uomo fai un cunnilingus con 2 dita della mano. E/o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, fai come se stessi avendo un orgasmo per 10 secondi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Tutte le ragazze devono lasciare in vista il perizoma",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s e %s si danno un abbraccio, e tutti e due bevono un sorso",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s si fa succhiare il dito da %s o beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Le persone che indossano una camicia la sbottonano e bevono un sorso per ogni bottone",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s toglie un indumento a %s o beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, di quanti bicchieri avresti bisogno per andare a letto con %s? Rispondi e bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, fra tutte le persone del gioco, secondo te chi è quella che lo suc**ia meglio? Rispondi e bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s dà $ sorsi alla persona più sexy",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s mima una pecorina per 5 secondi o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, di’ una cosa sessuale che non hai mai fatto, quelli/quelle che l’hanno già fatta bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, se ci fai vedere una tetta %s beve $ sorsi, altrimenti tu ne bevi $",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s, %s e %s fanno un'orgia oppure bevono tutti $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"4"},
{cycle_state:"false",type:"1",text:"%s sceglie fra bere $ sorsi o baciare i piedi di %s",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, se dai un bacio a %s, tutti bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Bevete il numero di orgasmi che avete avuto questa settimana; il numero di orgasmi corrisponde ai sorsi. Contano anche le seghe.",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Se %s e %s si baciano sulla bocca, ognuno distribuisce $ sorsi, altrimenti tutti bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Il primo giocatore che mostra un messaggino a sfondo sessuale distribuisce $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, se andare a letto con %s non ti darebbe fastidio distribuisci $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, pizzica le tette di %s oppure lui/lei beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s lecca il naso di %s o beve $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, fai un massaggio alla testa a %s o bevi $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s si fa palpare l’organo sessuale da %s o beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, dai un bacio sul naso a %s o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s sceglie due persone che si daranno un bacio oppure beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"3"},
{cycle_state:"false",type:"1",text:"%s, preferisci un rapporto orale, anale o vaginale? Rispondi e bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Quelle e quelli che si sono già fatti insultare durante un atto sessuale bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, lecca la bocca di uno dei giocatori o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lecca la lingua di uno dei giocatori o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Tutti bevono $ sorsi. Eccetto %s, che darà un bacio a tutti",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, bacia %s o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, scegli fra baciare la persona che vuoi o bere $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s passa un cubetto di ghiaccio a %s di bocca in bocca oppure beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, inizia bevendo $ sorsi. Se sei un uomo, descrivi il tuo pompino ideale. Se sei una donna, raccontaci come li fai",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, inizia bevendo $ sorsi. Se sei una donna, descrivi il tuo cunnilingus ideale. Se sei un uomo, raccontaci come li fai",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli la persona che dovrà leccare una parte del tuo corpo. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s deve sfiorare le tette di un giocatore, $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s deve farsi sfiorare le tette da un giocatore a scelta. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, bacia il torso di un giocatore o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, fatti baciare il petto / il torso da un giocatore a scelta. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, se sei un ragazzo mettiti dietro a una giocatrice e accarezzale i seni, scegli il ragazzo che ti accarezza i seni se sei una ragazza... $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s sceglie di farsi fare una lap dance da un giocatore di sua scelta, $ sorsi se lui o lei rifiuta",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, accarezza le natiche di un giocatore per 5 secondi, $ sorsi se lui o lei rifiuta!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, fatti accarezzare le natiche da un giocatore a scelta, per 5 secondi. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, guarda negli occhi la persona con cui potresti andare a letto stasera, questa persona berrà $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli chi berrà mentre tu gli(le) accarezzi le parti intime",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, mostra una tua foto in topless o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, mordicchia l’orecchio di un giocatore o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli 2 persone che si baceranno con la lingua; la persona che rifiuta berrà $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli chi dovrà far vedere una delle sue tette.. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, mostra una parte intima del tuo corpo o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli un giocatore che dovrà mostrare una parte intima del suo corpo. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, mima una posizione sessuale con uno dei giocatori o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli due giocatori che dovranno mimare una posizione sessuale e contemporaneamente bere $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, sfrega la testa sulla parte intima di qualcuno. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli qualcuno che dovrà sfregarsi la testa contro le tue parti intime. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli un giocatore che dovrà scrollare la testa fra i seni di una giocatrice. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, dai una leccata alle parti intime di qualcuno. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli qualcuno che dovrà darti una leccata sulle parti intime. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, accarezza la parte intime di qualcuno o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli qualcuno che dovrà accarezzarti le parti intime. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli qualcuno che dovrà metterti la mano sotto agli indumenti intimi. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, devi mettere la mano sotto agli indumenti intimi di qualcuno. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, passa un alimento dalla tua bocca a un’altra bocca. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli due giocatori che dovranno passarsi un alimento da una bocca all’altra. $ sorsi per tutti e due in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, tocca i seni di una ragazza. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Tutti bevono e si tolgono un indumento!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, scegli chi dovrà togliersi un vestito. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, sfida un giocatore ad aprire il reggiseno di una giocatrice. Se non ce la fa in 5 secondi, la persona designata prende $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, fatti pizzicare le tette da un giocatore a scelta oppure bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, pizzica le natiche di un giocatore a scelta. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, fatti pizzicare le natiche da un giocatore a scelta o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lecca le labbra di un giocatore a scelta. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, fatti leccare le labbra da un giocatore a scelta o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli il giocatore che dovrà mostrarti una parte intima del suo corpo. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lecca le tette di un giocatore a scelta. $ sorsi in caso di rifiuto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, fatti leccare le tette da un giocatore a scelta o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Ragazzi, toglietevi un indumento o bevete $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Ragazze, toglietevi un indumento o bevete $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Ragazzi, mettetevi a torso nudo o bevete $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Ragazze, mettetevi in reggiseno o bevete $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vatti a togliere la biancheria intima e torna qui. Oppure scappa e finisci il tuo bicchiere",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli una lettera. Tutti i giocatori che sono andati a letto con una persona il cui nome comincia con questa lettera bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, massaggia i piedi del giocatore che vuoi per 2 minuti, oppure bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, fatti massaggiare la parte del corpo che vuoi, dal giocatore che vuoi per 2 minuti. Ogni rifiuto implica $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lecca intorno all’ombelico del giocatore che vuoi, oppure bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, fatti leccare intorno all’ombelico dal giocatore che vuoi. Ogni rifiuto implica $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, fai un succhiotto alla persona che vuoi oppure bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, fatti fare un succhiotto dove vuoi dalla persona che vuoi; questa persona può rifiutare per $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Tu che hai le tette più grandi, nomina un ragazzo che ti lecchi i seni oppure bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, mostra le natiche o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, scegli una parte del corpo. Il primo giocatore che toccherà questa parte distribuirà $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, mostra i tuoi seni o bevi $ sorsi. Se sei un uomo ne puoi distribuire $",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Nominate tutti insieme la persona più agile, che dovrà dare prova della sua agilità, e berrà $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, dai un bacio sul collo alla persona che vuoi o bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Facciamo il secondo giro! Quelli che si sono già baciati si baciano di nuovo o bevono tutti due $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, lasciati dare un bacio sul collo dalla persona che vuoi oppure bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, manda un messaggino a sfondo sessuale a qualcuno scelto dalla squadra. Se questa persona rientra nel tuo gioco puoi distribuire uno shottino!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, distribuisci $ sorsi alla persona con la quale %s è più propenso(a) ad andare a letto",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, bevi tanti sorsi quante sono le persone con le quali sei andato(a) letto nel corso degli ultimi mesi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Il primo giocatore, fra %s e %s, che tocca l’organo sessuale di un altro giocatore distribuisce $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Se baceresti volentieri il tuo vicino o la tua vicina di sinistra alza la mano. Gli altri bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s e %s, leggete il primo SMS che viene visualizzato quando si digita la parola sesso\u0022 nella barra di ricerca. Rifiutate per $ sorsi\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s e %s, leggete il primo SMS che viene visualizzato quando si digita la parola cazzo\u0022 nella barra di ricerca. Rifiutate per $ sorsi\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s e %s, leggete il primo SMS che viene visualizzato quando si digita la parola pompino\u0022 nella barra di ricerca. Rifiutate per $ sorsi\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s ora deve godere prima di ogni sorso",key:"orgasm-simulation",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s non è più obbligato(a) a godere prima di ogni sorso",key:"",parent_key:"orgasm-simulation",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, scegli qualcuno da guardare negli occhi, ti diremo noi quando smettere",key:"look-in-the-eyes",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s puoi smettere di fissare il tuo amico(la tua amica) negli occhi!",key:"",parent_key:"look-in-the-eyes",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s si mette a 4 zampe, ben inarcato(a) - ti diremo quando rialzarti",key:"doggy-style-way",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s può sistemarsi in una posizione comoda",key:"",parent_key:"doggy-style-way",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s lavora alla Brigata Anti-Criminalità! Puoi fare una perquisizione di chi vuoi, quando vuoi; la persona perquisita può rifiutare per $ sorsi",key:"body-search",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s non lavora più alla Brigata Anti-Criminalità e questa persona ignobile, una vera maiala, prenderà $ sorsi",key:"",parent_key:"body-search",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s è Cupido! Lui/Lei sceglie chi baciare e chi abbracciarsi quando vuole, $ sorsi altrimenti",key:"cupidon",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s non è più Cupido",key:"",parent_key:"cupidon",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s è veramente in astinenza... Lui o lei è obbligato(a) a baciare una persona prima di bere",key:"kiss-before-drink",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s ha curato la sua ossessione per i baci!",key:"",parent_key:"kiss-before-drink",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s tiene amorevolmente la mano di %s fino a un nuovo ordine",key:"hold-hand",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s e %s possono lasciarsi",key:"",parent_key:"hold-hand",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s sceglie una persona che gli farà il massaggio della mano! Gli verrà detto quando fermarsi",key:"hand-massage",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s smette di farsi massaggiare la mano",key:"",parent_key:"hand-massage",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s è irresistibile! Ogni volta che chiede un bacio (sulla bocca o da altre parti), l'eletto(a) deve eseguire o bere",key:"irresistible",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s è di nuovo brutto(a)",key:"",parent_key:"irresistible",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s e %s, fatevi piedino fino a nuovo ordine",key:"naughty-feet",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s e %s possono smettere il loro intrallazzo",key:"",parent_key:"naughty-feet",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s è obbligato a scegliere qualcuno che gli terrà la mano sotto alle natiche fino a nuovo ordine",key:"hand-under-ass",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s può liberare l’intrallazzatore(intrallazzatrice)!",key:"",parent_key:"hand-under-ass",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s deve avere la mano appoggiata sulla coscia di un giocatore fino a nuovo ordine",key:"put-your-hand-on-legs",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s può togliere la mano!",key:"",parent_key:"put-your-hand-on-legs",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"Giochino! Ogni volta che %s tocca un bicchiere, %s deve mimare un godimento estremo. $ sorsi a ogni carenza!",key:"touch-glass-and-cum",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s e %s smettono il loro giochino stupido",key:"",parent_key:"touch-glass-and-cum",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, scegli in qualsiasi momento 2 giocatori, uno si metterà sulle ginocchia dell’altro. $ sorsi per ogni rifiuto",key:"on-sby-knees",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, non puoi più scegliere chi si siede su chi",key:"",parent_key:"on-sby-knees",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, hai le labbra avvelenate! Se riesci a dare un bacio a un giocatore senza obbligarlo prima della fine del virus, questo giocatore finirà il suo bicchiere!",key:"kiss-poison",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, non hai più il tuo bacio avvelenato! Se non ci sei riuscito(a), bevi $ sorsi",key:"",parent_key:"kiss-poison",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, hai le mani avvelenate! Se riesci a fare una carezza a un giocatore senza che lui(lei) se ne accorga prima della fine del virus, questo giocatore finirà il suo bicchiere!",key:"caddle-poison",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, non hai più la tua carezza avvelenata! Se non ci sei riuscito(a), bevi $ sorsi",key:"",parent_key:"caddle-poison",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"3",text:"Ora siamo obbligati ad accarezzarci il petto quando parliamo!",key:"caress-boobs",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Possiamo smettere di palparci quando parliamo!",key:"",parent_key:"caress-boobs",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ora è possibile ri-mettere in gioco i propri sorsi col gioco della bottiglia! Anziché bere, fate girare la bottiglia e baciate il giocatore designato; se vi rifiutate bevete il doppio!",key:"spin-the-bottle",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Il gioco della bottiglia è finito!",key:"",parent_key:"spin-the-bottle",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"A partire da questo momento ogni volta che qualcuno dice una parolaccia si toglie un vestito o beve $ sorsi!",key:"cross-word-clothe",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Potete imprecare di nuovo senza aver paura di perdere un indumento",key:"",parent_key:"cross-word-clothe",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ora siamo obbligati a succhiarci il pollice, il nostro o quello di qualcun altro, quando non parliamo",key:"fingers-mouth",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Potete smetterla di succhiarvi i pollici",key:"",parent_key:"fingers-mouth",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"A partire da questo momento, ogni volta che una ragazza mostra i seni tutti bevono!",key:"show-your-boobs",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ragazze, non fate più vedere i seni",key:"",parent_key:"show-your-boobs",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Gioco del cerchio! Quando volete, fare un cerchio col pollice e l’indice, a un’altezza compresa fra la cintura e la spalla: i giocatori che guardano si tolgono un indumento o bevono $ sorsi",key:"round-game-hot",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Gioco del cerchio abolito!",key:"",parent_key:"round-game-hot",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nuova regola, gioco dello shulz\u0022 sul posto (qualcuno rutta l’ultimo a dire \u0022shulz\u0022 perde)! Ogni volta chi perde si toglie un indumento o beve un sorso\u0022",key:"gofio-game-hot",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Gioco dello shulz abolito!",key:"",parent_key:"gofio-game-hot",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nuova regola: Se incrociate lo sguardo di un altro giocatore succhiandovi il pollice, questo giocatore beve",key:"suck-your-finger",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Smettete di farvi dei gesti porci fra di voi",key:"",parent_key:"suck-your-finger",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nuova regola! Ogni volta che si finisce di bere ci si deve accarezzare le tette. Altrimenti si beve di nuovo",key:"caddle-tities",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Non siete più obbligati ad accarezzarvi le tette",key:"",parent_key:"caddle-tities",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"4",text:"Le zone erogene di %s\u0022 il giocatore che non le trova o che ripete beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, pensa a una posizione sessuale. Tutti i giocatori a turno ne dicono una, il primo che indovina distribuisce $ sorsi. %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, pensa a una pratica sessuale che non sia la penetrazione. Tutti i giocatori a turno ne dicono una, il primo che indovina distribuisce $ sorsi. %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, pensa a un giocatore presente, il più abile a letto, secondo te. Tutti i giocatori a turno ne diranno uno, il primo che indovina distribuisce $ sorsi. %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, pensa a un sex toy. Tutti i giocatori a turno ne diranno uno, il primo che indovina distribuisce $ sorsi. %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Le parti del corpo di %s che a lui o lei piacciono\u0022 il giocatore che ripete o non ne trova beve $ sorsi! %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Gli outfit con i quali %s ha già dormito\u0022 il giocatore che ripete o non ne trova beve $ sorsi! %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Quello che vi eccita nel vostro partner\u0022 la persona che ripete o che non trova elementi beve $ sorsi! %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Le frasi che eccitano a letto\u0022 la persona che ripete o che non ne trova beve $ sorsi! %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"I vostri ex-partner sessuali, se dici un nome già detto o se hai finito bevi $ sorsi. %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Nuovo tema e $ sorsi in gioco: le persone famose che hanno fatto un sex tape\u0022 %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Gioco dei temi e $ sorsi in gioco: i luoghi dove %s ha scop**o\u0022 %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Gioco dei temi e $ sorsi in gioco: le fantasie comuni\u0022 %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Nuovo tema e $ sorsi in gioco: le pratiche sessuali\u0022 (penetrazione ...) %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Uno per volta, mostrate tutti i vostri tatuaggi e i piercing, quelle e quelli che non ne hanno bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"4",text:"A turno mostrate una delle vostre voglie della nascita e distribuite $ sorsi. Se non ne avete bevete $ sorsi, %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Le bombe sexy che hanno fatto dei reality-show\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"I sex toy\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"I motivi per andare a letto con uno sconosciuto\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Le cose da fare prima di iniziare una serata quando si è single\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"I canali TV che trasmettono film erotici\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"I punti dove mettere le mani durante la penetrazione\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"I preliminari\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Le scuse per non restare a dormire dopo una scop**a da una botta e via\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"I luoghi comuni delle fantasie\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"I travestimenti più comuni nelle fantasie\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Le professioni legate all’erotismo o al sesso\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Gli aromi dei preservativi\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Gli alimenti che possono far venire voglia di fare sesso se mangiati in un determinato modo\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"I sinonimi di \u0022orgasmare\u0022 \u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"I punti da mordicchiare per eccitare il proprio partner\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Gli oggetti che servono in una relazione sado-maso\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Le parti del corpo che è bello leccare durante un rapporto sessuale\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Le cose che si fanno di solito subito dopo aver fatto l’amore\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Le cose delle quali si può essere feticisti sessuali\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Le pratiche sessuali che si fanno con la lingua\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"4",text:"I metodi per far godere una donna\u0022 il giocatore che ripete o non ne trova beve $ sorsi. %s inizia\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, finisci il tuo bicchiere e vai ad abbassare la zip della persona di tua scelta con i denti",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, finisci il tuo bicchiere e vai a mordicchiare/leccare l’orecchio della persona che ti attira di più",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, finisci il tuo bicchiere e vai a baciare la persona che vuoi (sulle labbra)",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, fai una danza sexy a %s dopo aver finito il tuo bicchiere",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s fa un succhiotto a %s oppure tutti e due bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s finisce il suo bicchiere e fa finta di succhiare/leccare %s",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s dà un bacio a ogni giocatore e finisce il bicchiere che preferisce!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, bacia sulla bocca %s o beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, scegli la persona che ti accarezzerà mentre finisci il tuo bicchiere...",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, togliti 3 indumenti e finisci il tuo bicchiere...",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, scegli una persona con cui giocare. Berrete un sorso e poi vi bacerete. Fino a che tutti e due non avrete finito i rispettivi bicchieri...",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, scegli un giocatore che avrà la mano appoggiata sul tuo organo sessuale mentre finisci il tuo bicchiere. Le mani nella biancheria intima...",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, scegli due giocatori che finiranno il loro bicchiere e poi si baceranno con la lingua...",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, finisci il bicchiere del giocatore con cui potrai andare a letto stasera...",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, finirai il tuo bicchiere mentre un giocatore a scelta di accarezza. Se sei una ragazza saranno i seni, se sei un ragazzo, sarà il membro.",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Chi fra %s o %s è il partner migliore per fare dei preliminari secondo voi? Votate tutti insieme, chi ottiene più voti distribuisce $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"14",text:"Meglio i pettorali (seni per i ragazzi) o gli addominali (natiche per i ragazzi) ? Votate tutti contemporaneamente: chi perde, prende $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Sei a favore o contro l’amore senza futuro? Votate tutti insieme per alzata di mano, quelli che sono in minoranza bevono $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Le tette, meglio troppo grandi o troppo piccole? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio sottomesso(a) o dominato(a)? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Meglio un pompino o la sodom**? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Meglio un trombamico o una storia seria? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Meglio aniling*s o orgia? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Meglio una depilazione con taglio dei peli a forma di una sottile striscetta centrale o senza peli del tutto? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Meglio perizoma o mutandine? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Meglio bukka** o sodom**? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Meglio trombare 30 volte nella stessa giornata o non trombare per un mese? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Meglio baciare %s o %s? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"14",text:"Meglio scop**e con %s o %s? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"14",text:"Meglio fare un triangolo o sesso a 8? Votate tutti insieme, chi è in minoranza beve $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio fare un cunnilingus o una fellat**? Votate tutti insieme, chi è in minoranza beve $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio vedere attraverso i vestiti o rendersi invisibili? Votate uno alla volta, chi è in minoranza beve $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio andare a letto con una star o con la persona più sexy che conoscete? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio Megan Fox o Scarlett Johansson? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio avere una relazione perfetta e sessualmente povera o una relazione marcia e sessualmente incredibile? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio non trovare mai l’amore o non avere mai più una relazione sessuale? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio avere (o avere a che fare con) un pene da 9 cm o 36 cm? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Le maialate, meglio farle la mattina o la sera? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Per fare sesso, meglio mascherarsi da infermiera o da poliziotta? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio baciare il vicino o la vicina di destra o di sinistra? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio scop**e col vicino o la vicina di destra o di sinistra? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Per fare sesso, meglio mascherarsi da pompiere o da poliziotto? Votate tutti contemporaneamente, chi è in minoranza beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio schioccare le dita per far sparire i pantaloni o la maglia? Votate contemporaneamente: chi perde, prende $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio poter vivere un sogno da svegli e avere zero limiti per una settimana o poter fare sempre tutto quello che si desidera, a livello sessuale, a vita? Votate contemporaneamente: chi perde, prende $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio avere un abbonamento per un club di scambisti o per un salone dell’erotismo? Votate contemporaneamente: chi perde, prende $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Sei a favore o contro il fatto di recitare in un film porno? Votate contemporaneamente: chi perde, prende $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Sei a favore o contro il nudismo? Votate contemporaneamente: chi perde, prende $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Sei a favore o contro lo scambismo? Votate contemporaneamente: chi perde, prende $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Durante l’atto sessuale preferisci che la ragazza sia sopra o sotto? Votate contemporaneamente: chi perde, prende $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio andare a letto con qualcuno seduto a questo tavolo o con una persona sconosciuta a caso ogni giorno per una settimana? Votate contemporaneamente: chi perde, beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Meglio fare dei preliminari con uno dei giocatori qui presenti o vincere 500 euro? Votate contemporaneamente: chi perde, beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Convincete la giuria! %s e %s raccontano una delle loro fantasie, gli altri giocatori votano la più passionale! Il vincitore distribuisce $ sorsi, l’altro li beve",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Nominate la persona a cui manca di più fare sesso, quindi fate clic sullo schermo",key:"horny",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"La persona nominata distribuisce $ sorsi",key:"",parent_key:"horny",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Tutti bevono $ sorsi a parte la persona nominata",key:"",parent_key:"horny",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"La persona nominata può affogare i propri dispiaceri nell’alcol e beve $ sorsi (Stasera vai in bianco)",key:"",parent_key:"horny",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"La durata ideale per una partita di gambe all'aria. %s inizia (arriva il seguito...)",key:"sex-duration",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"I 3 giocatori più bassi bevono $ sorsi!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"I 3 giocatori più alti bevono $ sorsi!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, distribuisci $ sorsi ai giocatori che hanno dato una durata superiore. Se sei stato tu a dare la durata più lunga bevi $ sorsi",key:"",parent_key:"sex-duration",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, distribuisci $ sorsi ai giocatori che hanno dato una durata più ridotta. Se hai dato la durata più ridotta bevi $ sorsi",key:"",parent_key:"sex-duration",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Quanti partner sessuali avete avuto? Ognuno risponde, arriva il seguito... %s inizia",key:"number-partner-sex",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s e %s distribuiscono tanti sorsi quanti partner sessuali!",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s e %s bevono tanti sorsi quanti partner sessuali!",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Il giocatore che ne ha avuti di più beve $ sorsi",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Il giocatore che ne ha avuti di meno beve $ sorsi",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Convincete la giuria! %s e %s raccontano un sogno erotico strano che hanno fatto, gli altri giocatori votano il più improbabile! Il vincitore distribuisce $ sorsi, l’altro li beve",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Il vostro periodo di astinenza più lungo dopo il primo rapporto. Ognuno risponde, arriva il seguito... %s inizia",key:"abstinence-time",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Il giocatore col periodo più lungo beve $ sorsi!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Il giocatore col periodo più lungo distribuisce $ sorsi!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s e %s distribuiscono tanti sorsi quanti i mesi di astinenza!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s e %s bevono tanti sorsi quanti i mesi di astinenza!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Il numero ideale di rapporti sessuali a settimana, secondo voi. Ognuno risponde, arriva il seguito... %s inizia",key:"nb-sexual-rel",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Le persone a più di 2 berranno $ sorsi, gli altri, fate solo un sorso piccolo",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Le persone con meno di 3 ne bevono $ sorsi. Gli altri, fate un sorso piccolo",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s e %s distribuiscono tanti sorsi quanti rapporti sessuali!",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s e %s bevono tanti sorsi quanti rapporti sessuali!",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Convincete la giuria! %s e %s raccontano uno dei loro peggiori rapporti sessuali, gli altri giocatori votano il più disastrato! Il vincitore distribuisce $ sorsi, l’altro li beve",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Qual è la vostra posizione sessuale preferita? Ognuno risponde, tutti quelli che hanno delle posizioni in comune bevono $ sorsi insieme",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Convincete la giuria! %s e %s ci dicono qual è la cosa meno sexy da sentire durante un rapporto sessuale, gli altri giocatori votano la peggiore! Il vincitore distribuisce $ sorsi, l’altro li beve",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Convincete la giuria! %s e %s raccontano il miglior trucco per far eccitare il proprio partner, gli altri giocatori votano quello più hot\u0022! Il vincitore distribuisce $ sorsi l’altro li beve\u0022",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Avete diritto a 5 minuti di sesso prima di morire, con chi volete e dove volete. %s e %s propongono una scelta, gli altri votano l’opzione migliore! Il vincitore distribuisce $ sorsi, l’altro li beve",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Convincete la giuria! %s e %s di raccontano una delle migliori volte della loro vita, gli altri giocatori votano la più eccitante! Il vincitore distribuisce $ sorsi, l’altro li beve",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Convincete la giuria! %s e %s ci raccontano di uno dei luoghi più strani dove hanno scop**o, gli altri giocatori votano il più improbabile! Il vincitore distribuisce $ sorsi, l’altro li beve",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Uno per volta, bevete $ sorsi e dite con chi preferireste andare a letto scegliendo fra le persone presenti in questa stanza.",key:"who-u-wanna-fuck",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, se sei stato(a) citato(a), vai a baciare la persona che ti ha citato(a). Altrimenti bevi $ sorsi",key:"",parent_key:"who-u-wanna-fuck",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Uno per volta, andate a baciare una persona. Quelli che si rifiutano bevono $ sorsi. %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Uno per volta, scegliete qualcuno che dovrà toccare il vostro organo sessuale. Se lui o lei rifiuta, $ sorsi per la sua bella faccia. %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Uno per volta, scegliete qualcuno che si dovrà togliere un indumento. Se lui o lei rifiuta, $ sorsi per la sua bella faccia. %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Un giro di bottiglia! Ogni giocatore fa girare la bottiglia e bacia la persona indicata, $ sorsi per rifiutare. %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Concorso di boxer! Le ragazze sono la giuria, chi perde si becca $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Concorso di reggiseno! I ragazzi sono la giuria, chi perde si becca $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Kiss party! Uno alla volta baciate il vostro vicino o la vostra vicina di sinistra oppure bevete $ sorsi, %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Toccare la passera alla vicinaaaa! Uno alla volta toccate l’organo sessuale del vostro vicino o della vostra vicina di destra o bevete $ sorsi, %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Toccare la passera alla vicinaaaa! Uno alla volta toccate l’organo sessuale del vostro vicino o della vostra vicina di sinistra o bevete $ sorsi, %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Toccare la passera alla vicinaaaa! Uno alla volta accarezzate il petto del vostro vicino o della vostra vicina di destra, oppure bevete $ sorsi, %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Toccare la passera alla vicinaaaa! Uno alla volta accarezzate il petto del vostro vicino o della vostra vicina di sinistra, oppure bevete $ sorsi, %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"La domanda-trabocchetto! Uno alla volta, fate una domanda maiala a una persona qualsiasi. Se la persona interrogata non vuole rispondere, si beccherà $ sorsi. %s inizia",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Concorso di culi: ragazzi, in passerella! Ragazze, voi siete la giuria, chi vince può distribuire $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, fatti bendare e 2 giocatori ti daranno un bacio dove vogliono loro. Se indovini uno dei due giocatori, distribuisci $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, fatti bendare, un giocatore si metterà del cibo sullo stomaco e tu dovrai mangiarlo. Se indovini di che cibo si tratta, distribuisci $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Concorso: l’odore dei capelli! Le ragazze giocano, voi ragazzi invece siete la giuria. Chi vince può distribuire $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelli e quelle che hanno già fatto l’amore in un luogo pubblico bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelli/quelle che hanno già fatto un triangolo bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Le persone che hanno già fatto una sexcam distribuiscono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelli e quelle che hanno già pensato a un’altra persona durante l’atto distribuiscono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelli/quelle che vorrebbero andare a letto con una persona presente nella stanza bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se sei già andato(a) a letto con qualcuno la prima sera",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Le persone che amano la fellati* bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelli/quelle che si sono già filmati mentre fanno l’amore distribuiscono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Le persone che pensano che %s sia una bomba a letto bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Quelli/quelle che hanno già praticato un aniling*s bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelli/quelle che sono già stati beccati mentre si stavano mastur*ando bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Le persone che si radono le parti intime distribuiscono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se non consulti siti porno da più di 2 settimane",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelli/quelle a cui piacciono le parolacce a letto distribuiscono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Le persone che hanno già partecipato a dei giochi di ruolo a letto distribuiscono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelli/quelle che sono andati a letto con persone di cui non si ricordano il nome bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelli/quelle che hanno già scop**o in un hotel bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Le persone che non hanno mai scop**o in macchina bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelli e quelle che questa settimana non hanno avuto un rapporto sessuale bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"I giocatori che sono andati a letto con una persona più vecchia di loro di 5 anni bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"I giocatori che sono andati a letto con una persona più giovane di loro di 5 anni bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Le persone che hanno già inviato o ricevuto dei messaggini a sfondo sessuale bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"I giocatori che hanno già avuto una defaillance sessuale bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Le persone che hanno già avuto un'avventura sessuale con un altro giocatore bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che sono già stati beccati da un genitore nel bel mezzo di un atto sessuale bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, se non hai mai fatto l’amore più di 4 volte nella stessa giornata bevi $ sorsi, altrimenti distribuiscili",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno già fantasticato sul(sulla) partner di un amico(un'amica) bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno già inviato delle foto erotiche bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno già leccato o mangiato del cibo su un partner bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno già urlato il nome del proprio partner mentre facevano l’amore bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno già avuto un orgasmo in meno di 3 minuti di penetrazione bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno già fatto l’amore durante il periodo del ciclo bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Il(la) più dotato(a) a letto fra %s e %s beve $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che l’hanno già fatto una volta con un trombamico(a) bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Le ragazze a cui la prima volta ha fatto male bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, se sei già stato(a) segretamente innamorato(a) di %s bevi $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno già infilato degli oggetti nel membro sessuale del proprio partner bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che si sono già iscritti a un sito di incontri bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno già rimorchiato su un sito di incontri bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"L’ultima persona ad essere stata su un sito porno distribuisce $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quello o quella che ha rimorchiato di più sui dei siti di incontri distribuisce $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno già graffiato o sono state(i) graffiate(i) dal proprio partner sessuale bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno già avuto un fallo artificiale fra le mani bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che si sono già serviti di accessori per un atto sessuale bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che si sono già sentiti(e) eccitati(e) in seguito a un massaggio professionale bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno già sputato su un organo sessuale bevono $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno fatto un pompino meno di un mese fa bevono $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno fatto un pompino meno di una settimana fa bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno già avuto un oggetto nell’ano o nella vagina bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno già insultato il loro partner durante un momento di sesso, bevete $ sorsi, banda di maiali",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno già visto un amico(un’amica) tradire il proprio partner, bevete $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che sono già usciti con l'ex di un amico(un'amica), bevete $ sorsi, banda di stronzi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, se il tuo ultimo rapporto sessuale era protetto distribuisci $ sorsi, altrimenti bevili tu",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ti piace essere guardato quando fai l’amore",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai già scop**o davanti a un porno",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ti interessa scop**e o ri-scop**e davanti a un porno",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se vuoi scop**e adesso, qui, subito",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ti piace farti accarezzare l’ano mentre fai l’amore",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ti piace giocherellare con l’ano del tuo(della tua) partner durante la penetrazione",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ti piacciono le sculacciate",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"I maiali e le maiale che hanno già avuto un'esperienza sessuale con i due sessi bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Le ragazze, quelle che hanno già avuto un orgasmo vaginale bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai già avuto un orgasmo anale",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Per i mix inter-razziali! Se sei già andato(a) a letto con una persona di colore diverso dal tuo distribuisci $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ti sei già mascherato(a) per rendere il sesso più piccante",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai già guardato delle persone mentre facevano zin-zin",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se le tue ultime 3 volte sono state con un trombamico(a)",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai già fatto un massaggio che è sconfinato in qualcos’altro...",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai già ricevuto un massaggio che è sconfinato in qualcos’altro...",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se pensi di non scoprire altre cose sessualmente parlando",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, lecca una parte del corpo (quella che vuoi), del giocatore che %s sceglie",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai già scop**o davanti ad altre persone",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai già partecipato a una serata di scambisti",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Distribuisci $ sorsi se ti sei già mastur*ato(a) davanti al tuo(alla tua) partner",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Distribuisci $ sorsi se ti sei già mastur*ato(a) pensando a un(una) collega di lavoro",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ti sei già mastur*ato(a) davanti a un film che non fosse un porno",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle e quelli che hanno praticato i preliminari fra due momenti di penetrazione bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle che non sanno fare il twerk bevono $ sorsi!",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai già fantasticato su uno dei giocatori",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"L’ultima persona che ha avuto una relazione sessuale si toglie un indumento",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai scop**o sul letto di un amico(un’amica) a sua insaputa",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Distribuisci $ sorsi se hai già fatto dei preliminari con un cubetto di ghiaccio",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Distribuisci $ sorsi e se hai già fatto dei preliminari dove bisognava tenere un chewing gum alla clorofilla in bocca...",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ti sei già fatto(a) fotografare nudo(a)",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se non hai la biancheria intima",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se preferisci i preliminari alla penetrazione",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ti piace quando a letto le cose si fanno hard",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ritieni che i preliminari siano indispensabili",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, se hai fatto l’amore per la prima volta prima dei 17 anni distribuisci $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, andresti a letto col tuo capo o con la tua capa per un avanzamento di carriera? Sì: bevi $ sorsi, No: distribuiscili",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, andresti a letto con un vecchio zozzo o una vecchia zozza per 150.000€? Sì: distribuisci $ sorsi, No: li puoi bere",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se sei già entrato(a) in un locale di scambisti oppure se hai provato ad entrarci",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Quelle che hanno già simulato bevono $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"L’ultima persona che ha fatto un bel pompino distribuisce $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"L’ultima persona che ha praticato un cunnilingus appassionato distribuisce $ sorsi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai fatto un cunnilingus meno di un mese fa",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai fatto un cunnilingus meno di una settimana fa",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai già spompinato il tuo compagno per svegliarlo. Per i ragazzi, quelli che hanno già ricevuto una fellatio al risveglio",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai già accarezzato un organo sessuale con i piedi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, distribuisci $ sorsi se puoi perdonare un tradimento al tuo(alla tua) partner. In caso contrario... bevili",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai degli accessori erotici",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ha già baciato, con la lingua, più persone nella stessa serata",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ti piacerebbe vedere il tuo o la tua partner fare l’amore con qualcun altro",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se, nella tua vita, ha fatto l’amore più al buio che in pieno giorno",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai già acquistato qualcosa in un sex shop",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, distribuisci $ sorsi se ritieni di essere attraente. Se sei brutto, bevili",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai già scop**o senza che l’altra persona sapesse come ti chiamavi",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, bevi $ sorsi se degli sconosciuti ti hanno già visto(a) fare l’amore. In caso contrario distribuiscili",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai già avuto dei rapporti sessuali da ubriaco(a)",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, bevi $ sorsi se hai già baciato qualcuno che trovavi ripugnante. In caso contrario distribuiscili",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se pensi che potresti far godere la persona alla tua destra in meno di 10 minuti",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se pensi che la persona alla tua sinistra andrà a letto con un giocatore prima di domani",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se la tua prima volta non è stata del tutto eccezionale",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ti sei già fatto(a) rimorchiare da una persona dello stesso sesso",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se hai già fatto un sogno erotico con una persona seduta a questo tavolo",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ti piace farti mordicchiare le tette",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, se pensi di essere la persona che fa più conquiste a questo tavolo, distribuisci $ sorsi. In caso contrario... bevili",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se ci sono diversi giocatori a questo tavolo che ti attirano fisicamente",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bevi $ sorsi se sei già stato(a) a letto con una persona incontrata tramite un’applicazione di incontri",key:"",parent_key:"",pack_name:"hot",language:"it",nb_players:"0"}]);
retrieveDB();