var db = TAFFY([{cycle_state:"false",type:"1",text:"%s, hvis du er en pige, så slik fingrene på en sexet måde. Hvis du er en dreng, så lav cunnilingus med tungen mellem to fingre. Tøm glasset, hvis du nægter",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, fake en orgasme i 10 sekunder, eller tøm glasset",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Piger, træk op i trusserne",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s og %s, kæl med hinanden de næste fem minutter",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, lad %s sutte kælent på din finger, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Alle knapper deres skjorter/bluser op og drikker en slurk for hver knap",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, tag et stykke tøj af %s, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, hvor mange drinks vil det kræve, før du vil have sex med %s? Svar, og drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, hvem af de tilstedeværende giver det bedste blowjob, tror du? Svar, og drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, giv $ slurke til den mest sexede person i rummet. (Ja, du er vældig sexet, men vælg en anden end dig selv)",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, imitér doggy style-sex i fem sekunder eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, nævn en sexakt, du ikke har prøvet. Alle, som har prøvet den, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, hvis du viser dit ene bryst, skal %s drikke $ slurke. Hvis du nægter, skal du drikke $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s, %s og %s - lad som om I har gruppesex med %s, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"5"},
{cycle_state:"false",type:"1",text:"%s, enten kysser du %ss fødder, eller drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, hvis du kysser %s på kinden, skal alle drikke $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Alle tilstedeværende skal drikke lige så mange slurke som antallet af orgasmer, de har fået i denne uge (inkl. selvfremkaldte orgasmer)",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Hvis %s og %s kysser hinanden, må alle deltagere uddele $ slurke. Ellers skal I to selv drikke $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Den første, der kan vise en sexrelateret besked, må uddele $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, uddel $ slurke, hvis du ikke ville have noget imod at have sex med %s",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, niv %s i brystvorterne, ellers skal vedkommende drikke $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, slik %ss næse, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, giv %s en hovedbundsmassage, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, lad %s kærtegne dine kønsdele, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, kys %s på næsen, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, vælg to deltagere, som skal kysse hinanden. Hvis nogen af dem afslår, skal de drikke $ slurke hver",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"3"},
{cycle_state:"false",type:"1",text:"%s, foretrækker du oral-, anal- eller vaginalsex? Svar, og drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Alle, der er blevet fornærmet under sex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, slik nogen på munden, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slik nogens tunge, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Alle drikker $ slurke, bortset fra %s, som giver alle andre et kys",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kys %s, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, vælg mellem at kysse nogen eller drikke $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, overfør en isterning fra din egen mund til %ss mund, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, tag først $ slurke. Fortæl så, hvordan dit drømme-blowjob vil foregå, eller hvordan du vil give det.",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, tag først $ slurke. Fortæl så, hvordan din drømme-cunnilingus vil foregå, eller hvordan du vil give den.",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg en deltager, som skal slikke én af dine kropsdele. Straffen er $ slurke, hvis deltageren afslår",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, gnid en anden deltagers brystvorter. Straffen er $ slurke, hvis du afslår",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, bed en anden deltager gnide dine brystvorter. Straffen er $ slurke, hvis vedkommende afslår",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kys en anden deltagers bryst, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, bed en anden deltager kysse dit bryst. Straffen er $ slurke, hvis vedkommende afslår",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, stil dig bag en deltager af modsatte køn, og kærtegn vedkommendes bryst(er). Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg en deltager af modsatte køn, som skal give dig en lap dance\u0022. Straffen for at afslå er $ slurke\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kærtegn en valgfri deltagers røv i fem sekunder. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, bed en valgfri deltager kærtegne din røv i fem sekunder. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kig nogen, som du kunne have sex med i nat, i øjnene. Vedkommende skal drikke $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg en deltager, der skal drikke, mens du masserer vedkommendes intime dele",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vis et topløst foto af dig selv på din smartphone, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, bid en valgfri deltager blidt i øret, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg to personer, som skal tungekysse. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg en deltager, der skal vise en brystvorte. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vis lidt af dine intime dele, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg en deltager, der skal vise lidt af sine intime dele. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, indtag en sexstilling med en valgfri deltager. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg to deltagere, som skal indtage en sexstilling og samtidig drikke $ slurke hver.",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, gnid dit ansigt mod en valgfri deltagers intime dele. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg en deltager, som skal gnide sit ansigt mod dine intime dele. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg to deltagere af forskelligt køn, som skal foregive at brystkn*lde. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slik en valgfri deltagers intime dele. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg en deltager, som skal slikke dine intime dele. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kærtegn en valgfri deltagers intime dele, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg en deltager, som skal kærtegne dine intime dele. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg en deltager, som skal stikke hånden ned i dine trusser/underbukser. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, stik hånden ned i en valgfri deltagers trusser/underbukser. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, overfør noget mad fra din mund til en anden deltagers. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg to deltagere, der skal overføre mad fra mund til mund. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, tag en valgfri deltager på brystet. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Alle tager et stykke tøj af!",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, vælg en deltager, som skal tage et stykke tøj af. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, bed en mandlig deltager knappe en kvindelig deltagers bh op. Hvis det ikke lykkes inden for fem sekunder, skal vedkommende drikke $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lad nogen nive dig i brystvorterne, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, niv en valgfri deltager i røven. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lad nogen nive dig i røven, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slik en valgfri deltagers læber. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, bed en valgfri deltager slikke dine læber, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg en deltager, som skal vise lidt af sine intime dele. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slik en valgfri deltagers brystvorter. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, bed en valgfri deltager slikke dine brystvorter, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Drenge, tag et stykke tøj af, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Piger, tag et stykke tøj af, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Drenge, klæd jer topløse, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Piger, tag blusen af, så I kun har bh på, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, gå på toilettet, tag trusserne af, og kom så tilbage med dem. Hvis du ikke vil, skal du tømme dit glas",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg et bogstav. Alle, som har været i seng med en person, hvis fornavn begynder med dette bogstav, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, giv to minutters fodmassage til en valgfri deltager, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg en deltager, som skal give dig to minutters fodmassage. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slik en valgfri deltager rundt om navlen, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg en deltager, som skal slikke din navle. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, giv en valgfri deltager et sugemærke, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, bed en valgfri deltager give dig et sugemærke et valgfrit sted. Straffen for at afslå er $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Pigen med de største kasser vælger en deltager, som skal slikke hendes bryster eller drikke $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, vis din numse, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vælg en kropsdel. Den første deltager, som rører ved kropsdelen, uddeler $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vis dine bryster, eller drik $ slurke. Uddel $ slurke, hvis du er en mand",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Udvælg den mest fleksible deltager, som må bevise dette og drikke $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, kys en valgfri deltager på halsen, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Vi gør det igen! Alle, som har kysset hinanden, skal kysse hinanden igen, ellers skal de begge drikke $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, vælg en deltager, som skal slikke dig på halsen, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, sext (send en sex-besked) til nogen, som holdet vælger. Hvis vedkommende leger med, kan du beordre en deltager at tømme sit glas",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, giv $ slurke til den person, som %s har størst chance for at havne i seng med i nat",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, drik lige så mange slurke som det antal sexpartnere, du har haft det sidste halve år",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Dén af %s og %s, som først rører en anden deltagers kønsdele, uddeler $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Ræk hånden op, hvis du kunne kysse en af dine sidemænd. Resten af selskabet drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s og %s, læs det første resultat, der vises, når man skriver sex\u0022 i søgefeltet på jeres smartphone. Alle som det passer på drikker $ slurke\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s og %s, læs det første resultat, der vises, når man skriver penis\u0022 i søgefeltet på jeres smartphone. Alle som det passer på drikker $ slurke\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s og %s, læs det første resultat, der vises, når man skriver blowjob\u0022 i søgefeltet på jeres smartphone. Alle som det passer på drikker $ slurke\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, simulér en orgasme før hver slurk, indtil du får andre instrukser",key:"orgasm-simulation",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du kan holde op med at simulere en orgasme før hver slurk",key:"",parent_key:"orgasm-simulation",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, udvælg en deltager, og stir vedkommende i øjnene, indtil du får besked på at holde op!",key:"look-in-the-eyes",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du kan holde op med at stirre din ven dybt i øjnene!",key:"",parent_key:"look-in-the-eyes",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, stå på alle fire, og skyd ryg, indtil du får andre instrukser!",key:"doggy-style-way",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du kan igen indtage en lidt behageligere stilling",key:"",parent_key:"doggy-style-way",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er politiet! Du kan kropsvisitere hvem som helst, hvor som helst! Enhver, der afslår at blive kropsvisiteret, straffes med $ slurke!",key:"body-search",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er ikke politi længere. Drik $ slurke, din gamle gris!",key:"",parent_key:"body-search",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er kærlighedsguden Cupido! Vælg to deltagere, som skal kramme eller kysse hinanden. Hvis nogen af dem afslår, skal de drikke $ slurke hver",key:"cupidon",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er ikke Cupido længere",key:"",parent_key:"cupidon",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er rigtig kåd...du bliver nødt til at kysse nogen før hver slurk",key:"kiss-before-drink",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er kureret for din nye sexafhængighed",key:"",parent_key:"kiss-before-drink",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, tag %s kærligt i hånden, indtil du får andre instrukser!",key:"hold-hand",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s og %s, I kan slippe hinandens hænder!",key:"",parent_key:"hold-hand",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, vælg en deltager, som skal give en anden deltager håndmassage! I får besked, når massagen kan afsluttes",key:"hand-massage",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ikke mere håndmassage til dig",key:"",parent_key:"hand-massage",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er helt uimodståelig! Hver gang du vil have nogen til at give dig et kys hvor som helst, skal den udvalgte person opfylde dit ønske eller drikke $ slurke",key:"irresistible",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er ikke længere uimodståelig!",key:"",parent_key:"irresistible",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s og %s, massér hinandens fødder, indtil I får lov til at holde op!",key:"naughty-feet",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s og %s, I kan holde op med at massere hinanden",key:"",parent_key:"naughty-feet",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, udvælg nogen, som skal lægge hånden på din røv",key:"hand-under-ass",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, din røv genvinder sin frihed",key:"",parent_key:"hand-under-ass",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, læg din hånd på en anden deltagers hofte, indtil du får andre instrukser",key:"put-your-hand-on-legs",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du kan fjerne din hånd",key:"",parent_key:"put-your-hand-on-legs",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"Orgasmeleg! Hver gang %s rører et glas, skal %s fake en orgasme. Hver forglemmelse straffes med $ slurke",key:"touch-glass-and-cum",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s og %s, I kan afslutte orgasmelegen",key:"",parent_key:"touch-glass-and-cum",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"2",text:"Skødehundeleg! %s, vælg to deltagere når som helst. Den ene skal sidde på skødet af den anden. Straffen for at afslå er $ slurke",key:"on-sby-knees",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du må ikke længere vælge, hvem der skal sidde på skødet af hinanden",key:"",parent_key:"on-sby-knees",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er Poison Ivy! Enhver deltager, som det lykkes dig at kysse uden tvang, inden virusset bliver helbredt, skal tømme sit glas",key:"kiss-poison",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er ikke længere Poison Ivy! Drik $ slurke, hvis du ikke havde heldet med dig",key:"",parent_key:"kiss-poison",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du har magiske hænder! Enhver deltager, som det lykkes dig at kærtegne uden tvang, inden virusset bliver helbredt, skal tømme sit glas",key:"caddle-poison",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du har ikke længere magiske hænder! Drik $ slurke, hvis du ikke havde heldet med dig",key:"",parent_key:"caddle-poison",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"3",text:"Hver gang I siger noget, skal I kærtegne jeres bryst(er)!",key:"caress-boobs",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"I kan alle holde op med at kærtegne jeres bryst(er)! (Hvis I har lyst, kan I begynde at kærtegne en andens, men det er bare et lille forslag...)",key:"",parent_key:"caress-boobs",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Flaskehalsen peger på\u0022-leg! Drej flasken og kys den deltager den peger på. Antallet af slurke fordobles hvis man afslår!\u0022",key:"spin-the-bottle",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Flaskehalsen peger på\u0022-legen er forbi!\u0022",key:"",parent_key:"spin-the-bottle",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nu skal enhver spiller, som siger et bandeord, enten tage et stykke tøj af eller drikke $ slurke",key:"cross-word-clothe",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Du kan bande igen uden at risikere at miste et stykke tøj",key:"",parent_key:"cross-word-clothe",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nu skal I alle sutte på jeres egen eller en andens tommelfinger, når I ikke snakker. Ellers skal I drikke",key:"fingers-mouth",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nu kan I stoppe med at sutte på tommelen",key:"",parent_key:"fingers-mouth",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nu skal alle drikke, hver gang en pige viser sine bryster! Alle undtagen hun drikker!",key:"show-your-boobs",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Piger, stop med at vise bryster!",key:"",parent_key:"show-your-boobs",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Bulls Eye-legen går i gang! Lav en cirkel med tommelfinger og pegefinger når som helst. Enhver, der kigger på den, skal drikke $ slurke",key:"round-game-hot",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Bulls Eye-legen er færdig!",key:"",parent_key:"round-game-hot",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Farvespillet begynder! Hver gang nogen bøvser, skal den, som sidst nævner en farve, drikke $ slurke eller tage et stykke tøj af",key:"gofio-game-hot",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Farvespillet er forbi!",key:"",parent_key:"gofio-game-hot",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ny regel! Hvis du kan fange en anden deltagers blik, mens du sutter på en finger, skal vedkommende drikke en slurk",key:"suck-your-finger",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Stop med at slikke på fingrene!",key:"",parent_key:"suck-your-finger",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ny regel! Hver gang I drikker ud, skal I røre jeres brystvorter, ellers skal I drikke en slurk mere",key:"caddle-tities",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Stop hellere med at tage jer på brystvorterne, inden I bliver alt for ophidsede",key:"",parent_key:"caddle-tities",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"4",text:"%ss erogene zoner\u0022. Den første der gentager en zone eller ikke kan komme på en ny skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, tænk på en sexstilling uden at sige hvilken. Hver deltager skal efter tur gætte på en stilling, og den, der først gætter rigtigt, må dele $ slurke ud. %s, du begynder",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, tænk på en sexstilling uden at sige hvilken. Hver deltager skal efter tur gætte på et navn, og den, der først gætter rigtigt, må dele $ slurke ud. %s, du begynder",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, tænk på den deltager, som du synes er mest sexet, uden at nævne vedkommendes navn. Hver deltager skal efter tur gætte på et navn, og den, der først gætter rigtigt, må dele $ slurke ud. %s, du begynder",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, tænk på et sexlegetøj uden at nævne hvilket. Hver deltager skal efter tur gætte på et legetøj, og den, der først gætter rigtigt, må dele $ slurke ud. %s, du begynder",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"4",text:"En af %ss kropsdele som vedkommende kan lide\u0022. Den første der gentager en kropsdel eller ikke kan komme på en ny skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Tøj som %s har haft på i sengen\u0022. Den første der gentager et stykke tøj eller ikke kan finde på et nyt skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Ting som ophidser ens partner\u0022. Den første der gentager en ting eller ikke kan finde en ny skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ting som din partner skal sige for at gøre dig liderlig\u0022. Den første der gentager en replik eller ikke kan finde på en ny skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Gå bordet rundt, og nævn en ekskæreste ad gangen. Den første, der løber tør for navne, skal drikke $ slurke. %s, du begynder",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Gå bordet rundt, og nævn en berømthed i en lækket sexvideo. Den første, der løber tør for forslag, skal drikke $ slurke. %s, du begynder",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Gå bordet rundt, og nævn steder, hvor %s har haft sex. Den første, der løber tør for forslag, skal drikke $ slurke. %s, du begynder",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Gå bordet rundt, og nævn en almindelig fantasi. Den første, der løber tør for forslag, skal drikke $ slurke. %s, du begynder",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexakter som ikke er vaginal sex\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Gå bordet rundt, og vis jeres tatoveringer og piercinger. De, der ikke har nogen, skal drikke $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"4",text:"Gå bordet rundt, og vis et modermærke. Hvis nogen afslår, eller ikke har et modermærke at vise, skal de drikke $ slurke. %s, du begynder",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexbomber der har deres eget realityshow\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexlegetøj\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Grunde til at gå i seng med en fremmed\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ting man skal gøre som single før man går ud\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Tv-kanaler som sender erotiske film\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Steder at have sine hænder under samleje\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Forskellige former for forspil\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Undskyldninger for ikke at sove hos et engangsknald\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Typiske steder at udleve fantasier\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Typisk tøj at have på i fantasier\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Job som medfører erotik eller sex\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Kondommærker\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Forskellige slags mad der kan ophidse en person hvis den spises rigtigt\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Synonymer for orgasme\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Steder man kan bide for at tænde en partner\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ting som bruges til S&M\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Kropsdele som man ofte slikker på under sex\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ting man normalt gør efter sex\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexfetisher som folk kan have\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexhandlinger med tungen\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Forskellige måder at få en kvinde til at komme på\u0022. Den første der løber tør for forslag skal drikke $ slurke. %s du begynder\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, tøm dit glas, og åbn lynlåsen/knapperne i en anden deltagers bukser med tænderne",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, tøm dit glas, og kys/slik den lækreste deltager på øret",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, tøm dit glas, og brug glasset til en omgang flaskehalsen peger på\u0022. Kys den deltager som glassets åbne ende peger på på munden\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, tøm %ss glas, og lav en fræk dans for vedkommende",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, giv %s et sugemærke, ellers skal I begge drikke $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, tøm dit glas, og få %s til at kysse dig på munden",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, tøm dit glas, og gnid dig op af %s",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, kys alle deltagere, og drik en valgfri drink",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, giv %s et tungekys, eller drik $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, vælg en person, der skal kærtegne dig på et valgfrit sted, mens du tømmer dit glas...",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, tag tre stykker tøj af, og tøm dit glas...",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, vælg en deltager at spille med. Kys hinanden, og tag begge en slurk. Fortsæt, indtil én af jer har tømt sit glas...",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, vælg en deltager, der skal have hånden i dit skridt, mens du drikker ud - og ja, hånden skal være under dit tøj...",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, vælg to deltagere, som skal tømme deres glas og tungekysse...",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, vælg den deltager, som du helst vil være sammen med senere i aften, og tøm vedkommendes glas...",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, tøm dit glas, mens en valgfri person kærtegner dig. Hvis du er en pige, skal brysterne kærtegnes. Er du en dreng så...dérnede...",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Hvem er bedst til forspil af %s og %s? Der skal stemmes! Vinderen uddeler $ slurke, taberen drikker to slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"14",text:"Piger, er I til biceps eller sixpack? Drenge, er I til babser eller røv? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"14",text:"For eller imod engangsknald? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Er du underdanig eller dominerende? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Morgensex eller aftensex? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Blowjob eller analsex? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Bollevenner eller et seriøst forhold? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Rim job\u0022 eller gruppesex? Alle stemmer samtidig taberne drikker $ slurke\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Barberet eller ubarberet? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"14",text:"G-streng eller trusser? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Gang bang eller homosex? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Vil du helst have sex 30 gange om dagen eller undvære sex i 30 dage? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Vil du helst kysse %s eller %s? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"3"},
{cycle_state:"false",type:"14",text:"Vil du helst have sex med %s eller %s? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"3"},
{cycle_state:"false",type:"14",text:"Vil du helst have en trekant eller en femtenkant? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Vil du helst spise en mus eller sutte p*k? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Vil du helst kunne se igennem tøj eller være usynlig? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Vil du helst have sex med en berømthed eller den mest sexede person, du kender? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Vil du helst have sex med Megan Fox eller Scarlett Johansson? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Vil du helst have et perfekt forhold med dårlig sex eller et dårligt forhold med fantastisk sex? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Vil du helst aldrig finde ægte kærlighed eller aldrig have sex igen? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Brysterne...skal de hellere være for store end for små? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"P*kken...skal den hellere være 10 end 35 cm lang? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Nu bliver det lidt kinky! Vil du helst møde en sygeplejerske eller en kvindelig politibetjent? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Vil du helst kysse deltageren til højre eller venstre for dig? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Vil du helst have sex med deltageren til højre eller venstre for dig? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Nu bliver det lidt kinky! Vil du helst møde en brandmand eller en soldat? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Vil du helst kunne trylle trusserne eller toppen af med et fingerknips? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Vil du helst udleve en drøm uden begrænsninger i en uge eller være i stand til at gøre nogen liderlig når som helst? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Vil du helst have et gratis årskort til en swingerklub eller til et erotikshow? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"For eller imod at have en rolle i en pornofilm? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"For eller imod nudisme? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"For eller imod swingere? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Foretrækker du at være øverst eller nederst under sex? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Vil du helst have sex med en af deltagerne eller en tilfældig fremmed hver dag i en uge? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Vil du helst have forspil med en fremmed eller få 5.000 kr.? Alle stemmer samtidig, taberne drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Lad os overbevise juryen! %s og %s, fortæl om én af jeres fantasier, de andre deltagere stemmer om den mest ophidsende! Vinderen uddeler $ slurke, taberen drikker to slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Alle stemmer om, hvem der får mindst sex. Den uheldige taber skal efterfølgende omtales som Frk./Hr. Sexlysten\u0022\u0022",key:"horny",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Frk./Hr. Sexlysten uddeler $ slurke",key:"",parent_key:"horny",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Alle undtagen Frk./Hr. Sexlysten drikker $ slurke",key:"",parent_key:"horny",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Frk./Hr. Sexlysten, drik dine sorger bort! Drik $ slurke...",key:"",parent_key:"horny",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Det ideelle tidsrum for et samleje\u0022. Alle svarer og trykker på skærmen. %s du begynder\u0022",key:"sex-duration",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"De tre deltagere med de korteste tider drikker $ slurke!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"De tre deltagere med de længste tider drikker $ slurke!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, uddel $ slurke til deltageren med den længste tid. Hvis du havde den længste tid, drikker du $ slurke",key:"",parent_key:"sex-duration",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, uddel $ slurke til deltageren med den korteste tid. Hvis du havde den korteste tid, drikker du $ slurke",key:"",parent_key:"sex-duration",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Hvor mange ekspartnere har du? Alle svarer, og trykker på skærmen. %s, du begynder",key:"number-partner-sex",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s og %s, uddel lige så mange slurke, som I har ekspartnere",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s og %s, drik lige så mange slurke, som I har ekspartnere",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Deltageren med det højeste antal ekspartnere drikker $ slurke",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Deltageren med det laveste antal ekspartnere drikker $ slurke",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Lad os overbevise juryen! %s og %s, fortæl om jeres underligste drøm, de andre deltagere stemmer om den mest usandsynlige! Vinderen uddeler $ slurke, taberen drikker to slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Hvor længe varede din længste tørkeperiode uden sex? Alle svarer, og trykker på skærmen. %s, du begynder",key:"abstinence-time",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Deltageren med den længste tørkeperiode drikker $ slurke",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Deltageren med den korteste tørkeperiode drikker $ slurke",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s og %s, uddel lige så mange slurke som antallet af måneder i jeres tørkeperiode",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s og %s, drik lige så mange slurke som antallet af måneder i jeres tørkeperiode",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Hvad er det ideelle antal samlejer om ugen? Alle svarer, og trykker på skærmen. %s, du begynder",key:"nb-sexual-rel",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"De deltagere, der svarede flere end to gange om ugen, drikker $ slurke. Alle andre kan tage en lille en...",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"De deltagere, der svarede færre end tre gange om ugen, drikker $ slurke. Alle andre kan tage en lille en...",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s og %s, uddel lige så mange slurke som det antal samlejer, I gerne vil have på en uge",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s og %s, drik lige så mange slurke som det antal samlejer, I gerne vil have på en uge",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Lad os overbevise juryen! %s og %s, fortæl om jeres værste sexoplevelse, de andre deltagere stemmer om den værste af dem! Vinderen uddeler $ slurke, taberen drikker to slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Hvad er din foretrukne sexstilling? Alle svarer, og hvis nogen svarer det samme, drikker de $ slurke hver",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Lad os overbevise juryen! %s og %s, fortæl om det mindst sexede, en partner kan sige under sex, så stemmer de andre deltagere om den værste replik! Vinderen uddeler $ slurke, taberen drikker to slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Lad os overbevise juryen! %s og %s, fortæl om det, som bedst kan tænde jeres partner, så stemmer de andre deltagere om det mest ophidsende! Vinderen uddeler $ slurke, taberen drikker to slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Du kan have sex i fem minutter med hvem som helst hvor som helst, inden du dør. %s og %s, giv hver jeres forslag, de andre deltagere stemmer om det mest tiltalende af dem! Vinderen uddeler $ slurke, taberen drikker to slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Lad os overbevise juryen! %s og %s, fortæl om jeres bedste sexoplevelse, de andre deltagere stemmer om den cooleste af dem! Vinderen uddeler $ slurke, taberen drikker to slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Lad os overbevise juryen! %s og %s, fortæl om et usædvanligt sted, I har haft sex, så stemmer de andre deltagere om det cooleste sted! Vinderen uddeler $ slurke, taberen drikker to slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Gå bordet rundt, drik $ gange, og fortæl, hvem du vil have sex med i aften",key:"who-u-wanna-fuck",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, hvis du blev nævnt, skal du kysse enhver deltager, der nævnte dig, på munden. Ellers skal du drikke $ slurke",key:"",parent_key:"who-u-wanna-fuck",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Gå bordet rundt, og kys alle på munden. Enhver, der afslår, skal drikke $ slurke. %s, du begynder!",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Gå bordet rundt, og vælg en person, der skal røre dig i skridtet. Enhver, der afslår, skal drikke $ slurke. %s, du begynder!",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Gå bordet rundt, og vælg en, der skal tage et stykke tøj af. Enhver, der afslår, skal drikke $ slurke. %s, du begynder!",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Spil en runde flaskehalsen peger på\u0022! Hver deltager drejer flasken og kysser den deltager den peger på. Enhver der afslår skal drikke $ slurke. %s du begynder!\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Underbuksekonkurrence! Piger, I er jury, taberen skal drikke $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Bh-konkurrence! Drenge, I er jury, vinderen uddeler $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Kyssefest! Gå bordet rundt, og kys din højre eller venstre nabo. Enhver, der afslår, skal drikke $ slurke. %s, du begynder!",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Lad os være sensuelle! Gå bordet rundt, og tag personen til højre i skridtet. Enhver, der afslår, skal drikke $ slurke. %s, du begynder!",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Lad os være sensuelle! Gå bordet rundt, og tag personen til venstre i skridtet. Enhver, der afslår, skal drikke $ slurke. %s, du begynder!",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Lad os være sensuelle! Gå bordet rundt, og tag personen til venstre på brystet. Enhver, der afslår, skal drikke $ slurke. %s, du begynder!",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Lad os være sensuelle! Gå bordet rundt, og tag personen til højre på brystet. Enhver, der afslår, skal drikke $ slurke. %s, du begynder!",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Svært spørgsmål! Stil efter tur en af de andre deltagere et intimt spørgsmål. Afslag på at svare straffes med $ slurke. %s, du begynder!",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Drengerøvskonkurrence! Drenge, gå catwalk. Piger, I er balle-jury. Vinderen uddeler $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, tag bind for øjnene, og lad to deltagere kysse dig hvor som helst. Hvis du gætter én af de to deltagere, må du uddele $ slurke. Du får kun én chance!",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, tag bind for øjnene. En deltager lægger noget spiseligt på sin mave, og du skal så spise det. Hvis du gætter, hvad det er, må du uddele $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Hårsnusningskonkurrence. Piger, I er deltagere. Drenge, I er dufte-jury. Vinderen uddeler $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har haft sex på et offentligt sted, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har haft en trekant, drikker $ slurke. Drik dobbelt op, hvis alle tre partnere desuden befinder sig i rummet lige nu!",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har haft Skype-sex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har tænkt på en anden end partneren under sex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som kunne gå i seng med en anden tilstedeværende, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har haft sex på første date, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som elsker oralsex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har filmet sig selv under sex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der synes/tror, at %s er god i sengen, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle, som har givet nogen et rim job\u0022 drikker $ slurke\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har prøvet at blive grebet i at onanere, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som intimbarberer sig, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har været inde på en pornoside i de sidste to uger, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som elsker dirty talk, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der nogensinde har anvendt rollespil som sexhjælpemiddel, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har været i seng med nogen uden at kende vedkommendes navn, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har haft sex på et hotel, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som ikke har haft bilsex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som ikke har haft sex i denne uge, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har haft sex med en mindst fem år ældre person, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har haft sex med en mindst fem år yngre person, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har sextet (sendt sex-beskeder) med nogen, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der nogensinde har oplevet ikke at kunne få den op at stå under et samleje, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har haft sex med en anden i rummet, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, uddel $ slurke, hvis du har haft sex mere end fire gange på en dag. Hvis ikke, skal du drikke $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har fantaseret om en vens partner, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har sendt et sexfoto til nogen, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har slikket/spist nogen slags mad fra en anden persons krop, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har skreget sin partners navn under sex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har fået en orgasme på under tre minutter, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Enhver, som nogensinde har haft sex under sin eller sin partners menstruation, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Hvem af %s og %s er bedst i sengen? Vinderen drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Alle, som har en bolleven, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som synes, at første gang gjorde ondt ad h... til, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, hvis du nogensinde har været hemmeligt forelsket i %s, drikker I begge to $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har stukket en genstand ind i sin partners krop under sex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har brugt en datingtjeneste, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har været i seng med nogen takket være en datingtjeneste, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltager, der sidst besøgte en pornohjemmeside, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltager, der har fået mest sex takket være en datingtjeneste, uddeler $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der er blevet kradset under sex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der nogensinde har holdt et sexlegetøj, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der nogensinde har brugt nogen form for genstand/ting under sex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der nogensinde er blevet tændt af professionel massage, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der nogensinde har spyttet under oralsex med deres partner, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der har givet et blowjob i den seneste måned, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der har givet et blowjob i denne uge, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har haft et sexlegetøj i sin anus eller vagina, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle de frækkerter, der har fornærmet deres partner under sex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der nogensinde har set deres ven være utro med deres partner, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der nogensinde har datet en vens eks, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, uddel $ slurke, hvis du brugte kondom, sidste gang du havde sex. Hvis ikke, skal du selv drikke dem",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle, der kan lide at have sex, mens nogen ser på, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der har haft sex til en pornofilm, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der tænder på tanken om (måske endnu en gang) at kn*lde til en pornofilm, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har lyst til sex lige nu, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der kan lide at få anus stimuleret under sex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der kan lide at lege med deres partners anus under sex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der kan lide at give eller få smæk i numsen, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle de frækkerter, der har haft sex med både piger og drenge, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Liderlige damer! Drik $ slurke, hvis I nogensinde har fået en sprøjteorgasme",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Drik $ slurke, hvis du nogensinde har fået en anal orgasme...",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, der har krydret sex med udklædning, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har kigget på, mens andre havde sex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som de tre seneste gange har haft sex med bollevenner, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har givet en massage, der udviklede sig til noget meget mere interessant, drikker $ slurke...",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har fået en massage, der udviklede sig til noget meget mere interessant, drikker $ slurke...",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som tror, at de aldrig kommer til at opleve noget afgørende nyt rent seksuelt, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, slik en valgfri kropsdel på en deltager, som %s udvælger",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har kn*ldet foran andre mennesker, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har deltaget i en partnerbytte-/swingerfest, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har onaneret foran deres partner, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har onaneret med en kollega i tankerne, deler $ slurke ud",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har onaneret, mens de har tænkt på en ikke-pornografisk film, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har haft forspil mellem penetreringer, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle piger, som ikke kan twerke, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har fantaseret om en anden deltager, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltager, der sidst havde sex, skal tage et stykke tøj af",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har knaldet i en vens seng, uden at vennen fandt ud af det, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har haft forspil med isterninger, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har haft forspil med tyggegummi i munden, uddeler $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde er blevet fotograferet nøgen, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som ikke har trusser på nu, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som foretrækker forspil frem for fuldbyrdet samleje, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som godt kan lide hård sex, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som mener, at forspil er obligatorisk, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, uddel $ slurke, hvis du havde din seksuelle debut, inden du fyldte 17 år",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, hvis du havde en sexet chef, ville du så gå i seng med vedkommende for at gavne din karriere? Drik $ slurke for ja\u0022 uddel $ slurke for \u0022nej\u0022\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, ville du gå i seng med en grim, ældre person for 1,5 mio. kr.? Uddel $ slurke for ja\u0022 drik $ slurke for \u0022nej\u0022\u0022",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har været på swingerklub, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har faket en orgasme, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltager, som sidst gav et godt blowjob, uddeler $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltager, som sidst udførte passioneret cunnilingus, uddeler $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har slikket f*sse for mindre end en måned siden, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har slikket f*sse for mindre end en uge siden, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle piger, som nogensinde har givet deres kæreste et blowjob for at vække ham, drikker $ slurke. Det samme gælder alle drenge, som nogensinde er blevet vækket med et blowjob",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har kærtegnet en intim kropsdel med fødderne, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, uddel $ slurke, hvis du villle forlade din partner pga. ét tilfælde af utroskab. Hvis ikke, så drik dem selv",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle, som har erotisk legetøj, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har tungekysset med to personer på samme aften, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som kunne tænke sig at se sin partner have sex med en anden, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som sammenlagt har haft mere sex i mørke end i dagslys, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har købt noget i en sexbutik, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, uddel $ slurke, hvis du mener, at du er lækker. Drik dem selv, hvis du er grim",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle, som har været i seng med nogen, som ikke kendte deres navn, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, drik $ slurke, hvis fremmede mennesker nogensinde har set dig have sex. Hvis ikke, så uddel $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle, som har haft sex i en brandert, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, drik $ slurke, hvis du nogensinde har kysset én, som du syntes var utiltalende. Ellers uddel $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle, som tror, at de kunne få sidemanden til højre til at komme inden for 10 minutter, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Drik $ slurke, hvis du tror, at din nabo til venstre får sex med en anden deltager inden i morgen",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som ikke havde en god første gang, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som har oplevet at blive flirtet med af en person af samme køn, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har haft erotiske drømme om en anden deltager, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som kan lide at blive bidt i brysterne, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, uddel $ slurke, hvis du tror, du har gjort flest erotiske erobringer af alle i selskabet. Hvis ikke, så drik dem selv",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle, som synes, at flere af de andre deltagere er lækre, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle, som nogensinde har haft sex med nogen på grund af en dating-app, drikker $ slurke",key:"",parent_key:"",pack_name:"hot",language:"da",nb_players:"0"}]);
retrieveDB();