var db = TAFFY([{cycle_state:"false",type:"1",text:"%s, om du er jente, slikk fingrene dine på en sexy måte. Om du er gutt, gjør munnsex*bevegelser med tungen mellom fingrene. Drikk opp glasset om du ikke tørr",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lat som du har en orgasme i 10 sekunder eller drikk opp hele glasset",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Jenter, dra opp stringtrusene",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s og %s, kos med hverandre de neste 5 minuttene",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, la %s suge fingeren din eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Alle knepper opp skjortene/blusene sine og tar en slurk for hver knapp",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, ta av et av %ss klesplagg eller drikk $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, hvor mange drinker ville kreves for at du skulle hatt sex med %s? Svar og drikk $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, hvem i rommet tror du ville gitt den beste bl*wjoben? Svar og drikk $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, del ut $ slurker til den mest sexy personen i rommet. (Ja, du er veldig sexy, men velg noen andre enn deg selv)",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, simuler sex på alle fire i 5 sekunder eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, nevn en sexstilling du ikke har prøvd. Alle som har prøvd den tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, om du viser det ene brystet må %s drikke $ slurker. Om du ikke tør må du drikke $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s, %s, og %s - simuler gruppes*ex med %s eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"5"},
{cycle_state:"false",type:"1",text:"%s, enten kysser du %ss føtter eller drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, hvis du kysser %s på kinnet må alle ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Alle i rommet må ta like mange slurker som antallet orgasmer de har hatt denne uken, inkludert de selvproduserte",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Hvis %s og %s kysser hverandre får alle dele ut $ slurker. Hvis ikke må dere ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Den første som kan vise en sexrelatert tekstmelding deler ut $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, del ut $ slurker om du ikke ville hatt noe imot å ha sex med %s",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, klyp %s i brystvortene, ellers må denne drikke $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s slikker %s på nesen eller tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, gi %s hodemassasje eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, la %s stryke deg varsomt i skrittet eller drikk $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, kyss %s på nesen eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s velger to deltakere som skal kysse hverandre, hvis én av dem ikke vil skal de ta $ slurker hver",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"3"},
{cycle_state:"false",type:"1",text:"%s, liker du best oral-, anal- eller vaginalsex? Svar og ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Alle som er blitt fornærmet under sexakten drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, slikk noen på munnen eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slikk på noens tunge eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Alle tar $ slurker, bortsett fra %s som gir alle et kyss",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kyss %s eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, velg mellom å kysse noen eller å ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ta av %s et klesplagg eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, overfør en isbit fra din egen munn til %ss munn, eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, ta først $ slurker. Fortell hvordan din drømme-bl*wjob skulle vært, eller hvordan du ville utført den.",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ta først $ slurker. Fortell hvordan din drømme-cunnilingus skulle foregått, eller hvordan du skulle utført den.",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s velg en deltaker som skal slikke på en av dine kroppsdeler. Straffen er $ slurker hvis deltakeren ikke vil",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s skal gni på noen andres brystvorter, straffen er $ slurker hvis vedkommende ikke vil",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, la en annen deltaker gni på brystvortene dine. Straffen er $ slurker til den som ikke vil",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kyss en annen deltaker på brystet eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, la noen du selv velger kysse brystene dine, den som ikke vil tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, hvis du er mann, still deg bak en dame og kos med brystene hennes, hvis du er dame, velg en mann å kose med... straffen for å ikke ville er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg noen som skal gi deg en lap dance\u0022. Vil ikke personen gjøre det skal vedkommende ta $ slurker\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kjæl med noens rumpe i 5 sekunder, om den utvalgte deltakeren ikke vil blir det $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, la en deltaker du velger ta på rumpa di i fem sekunder. Straffen ved å ikke ville er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, se noen du kunne ligget med i øynene. Personen skal ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg noen som skal drikke mens du masserer personens intime område",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vis et barbrystet/toppløst bilde du har, eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ta på noens øre eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg to personer som skal tungekysse, straffen for å ikke ville gjøre det er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg noen som skal vise en brystvorte, straffen for å ikke gjøre det er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vis noen av dine intime deler eller drikk $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg noen som skal vise frem sine intime deler. Straffen ved å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, innta en sexstilling med en utvalgt deltaker. Straffen for å ikke gjøre det er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg ut to deltakere som skal innta en sexstilling og samtidig drikke $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, gni ansiktet mot noens intime deler. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg ut noen som skal gni ansiktet sitt mot ditt intime område. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg en deltaker som skal brystkn*lle en annen deltakers bryst. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slikk noens intime deler. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg ut noen som skal slikke dine intime deler. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kos med noens intime område eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg noen som skal stryke dine intime deler. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg noen som skal stikke hånden innenfor trusa di. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, stikk hånda innenfor noens truse. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, overfør noe spiselig fra din munn til en annens. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg to deltakere som skal overføre mat til hverandres munner. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ta på noens bryst. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Alle tar av seg et klesplagg!",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, velg ut noen som skal ta av seg et klesplagg. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, utfordre en annen deltaker til å kneppe opp en kvinnelig deltakers bh. Om personen ikke klarer det på fem sekunder må vedkommende ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, la noen klype deg i brystvortene eller drikke $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, klyp noen i rumpa. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, la noen klype deg i rumpa eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slikk noens lepper. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, la noen slikke leppene dine eller drikk $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg noen som skal vise deg noen av sine intime deler. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vis noen dine intime deler eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slikk noens brystvorter. Straffen for å nekte er $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, la noen slikke brystvortene dine eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Gutter, ta av et klesplagg eller drikk $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Jenter, ta av et klesplagg eller drikk $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Gutter, kle av dere så dere er barbrystet eller drikk $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Jenter, ta av trøyene så dere bare sitter i bh eller drikk $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, gå og ta av deg trusene/boxerne og kom tilbake. Om du ikke vil, tømmer du glasset",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg en bokstav. Alle som har ligget med en person hvis navn begynner på denne bokstaven tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, gi en fotmassasje til hvem du vil i 2 minutter, eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg noen som skal gi deg fotmassasje i 2 minutter. All nekt gir $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slikk rundt navlen på en valgfri person eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg noen som skal slikke navlen din. All slags nekting gir $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, gi noen du velger ut et sugemerke eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, la noen du velger gi deg et sugemerke på valgfri plass. All slags nekting gir $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Jenta med de største brystene velger noen som skal slikke dem eller drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, vis rumpen eller drikk $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, velg en kroppsdel. Den første deltakeren som tar på denne kroppsdelen gir ut $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vis brystene dine eller ta $ slurker. Del ut $ om du er mann",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Pek ut den mest vågale deltakeren, som må bevise dette og ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, kyss noen du velger på halsen eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Vi tar det en gang til! Alle som har kysset hverandre må kysse hverandre igjen ellers må begge ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, velg ut noen som skal kysse deg på halsen, eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, sext (send en sexmelding) til noen som resten av gjengen velger ut. Hvis personen du sender melding til blir kåt kan du beordre noen til å tømme glasset",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, del ut $ slurker til den personen som %s har størst sjanse for å havne til køys med i natt",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, ta like mange slurker som antall sexpartnere du har hatt det siste halve året",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Den av %s og %s som først rører en annens kjønnsdeler gir ut $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Rekk opp hånden hvis du ville kysset noen av spillerne. Resten drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s og %s leser opp den første meldingen som vises hvis dere skriver sex\u0022 i søkefeltet på telefonen din. Alle som nekter tar $ slurker\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s og %s, les opp den første meldingen som vises om dere skriver penis\u0022 i søkefeltet på telefonen din. Alle som sier pass tar $ slurker\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s og %s, les opp den første meldingen som vises om dere skriver bl*wjob\u0022 på telefonen. Alle som sier pass tar $ slurker\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, simuler orgasme før hver slurk frem til du blir fortalt annet",key:"orgasm-simulation",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du kan slutte å simulere orgasme før hver slurk",key:"",parent_key:"orgasm-simulation",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, velg ut noen og stirr inn i øynene til personen helt til du får beskjed om å slutte!",key:"look-in-the-eyes",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du kan slutte å stirre vennen din dypt inn i øynene!",key:"",parent_key:"look-in-the-eyes",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, still deg på alle fire og svai med ryggen til du får andre instruksjoner!",key:"doggy-style-way",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s kan innta en behagelig stilling igjen",key:"",parent_key:"doggy-style-way",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s er politi! Du kan kroppsvisitere hvem som helst, hvor som helst! Den som ikke vil, straffes med $ slurker!",key:"body-search",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s du er ikke politi lenger. Ta $ slurker, din pervo!",key:"",parent_key:"body-search",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s er kjærlighetsguden Cupido! Velg en deltaker som skal klemme eller kysse en annen. Den som ikke vil straffes med $ slurker",key:"cupidon",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er ikke Cupido lenger",key:"",parent_key:"cupidon",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s er riktig kåt...og må kysse noen før hver slurk",key:"kiss-before-drink",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er kurert mot ditt nye sexbehov",key:"",parent_key:"kiss-before-drink",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s tar tak i %ss hånd og holder den kjærlig til nye instruksjoner gis!",key:"hold-hand",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s og %s kan slippe hverandre!",key:"",parent_key:"hold-hand",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s velger ut noen som skal gi han/henne en håndmassasje! Vi sier ifra når massasjen kan avsluttes",key:"hand-massage",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ikke mer håndmassasje for din del",key:"",parent_key:"hand-massage",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er helt uimotståelig! Hver gang du vil ha et kyss på munnen eller hvor som helst, må den utvalgte personen oppfylle dine ønsker eller ta $ slurker",key:"irresistible",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s er ikke uimotståelig lenger!",key:"",parent_key:"irresistible",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s og %s, masser hverandres føtter helt til dere får lov til å slutte!",key:"naughty-feet",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s og %s kan slutte å massere hverandre",key:"",parent_key:"naughty-feet",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, velg noen som skal kjærtegne rumpa di med hånden sin",key:"hand-under-ass",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%ss rumpe får friheten tilbake",key:"",parent_key:"hand-under-ass",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, skal legge en hånd på en annen deltakers hofte helt til en annen instruksjon blir gitt",key:"put-your-hand-on-legs",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s kan ta vekk hånden",key:"",parent_key:"put-your-hand-on-legs",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"Orgasmelek! Hver gang %s rører et glass må %s simulere en orgasme. Hvis det ikke skjer straffes det med $ slurker",key:"touch-glass-and-cum",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s og %s kan slutte med orgasmeleken",key:"",parent_key:"touch-glass-and-cum",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, velg 2 deltakere når du vil. Den ene skal sitte på den andres fang. Straffen ved å nekte er $ slurker",key:"on-sby-knees",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du får ikke velge hvem som skal sitte på hvem sitt fang",key:"",parent_key:"on-sby-knees",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er Poison Ivy! Hvis du kysser noen, uten tvang, før viruset er over, skal denne spilleren drikke opp drinken sin",key:"kiss-poison",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du er ikke lenger Poison Ivy! Ta $ slurker hvis du feilet",key:"",parent_key:"kiss-poison",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du har magiske hender! Hvis du lykkes med å kjærtegne en annen spiller uten at det merkes før viruset forsvinner, skal denne spilleren drikke opp drinken sin!",key:"caddle-poison",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du har ikke lenger magiske hender! Drikk $ slurker om du mislyktes med oppdraget",key:"",parent_key:"caddle-poison",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"3",text:"Hver gang dere sier noe må dere kose med brystet deres!",key:"caress-boobs",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Dere kan alle slutte å kose med brystene! (om dere vil, kan dere begynne å kose med noen annens, men det er bare et lite forslag...)",key:"",parent_key:"caress-boobs",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Dere kan nå leke flasketuten peker på. Istedenfor å drikke, snurrer dere flasken og kysser deltakeren tuten peker på. Antallet slurker dobles om dere nekter!",key:"spin-the-bottle",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Flasketuten peker på er over!",key:"",parent_key:"spin-the-bottle",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nå skal hver spiller som sier et banneord enten ta av et klesplagg eller ta $ slurker!",key:"cross-word-clothe",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Dere kan nå banne igjen uten å risikere å miste et klesplagg",key:"",parent_key:"cross-word-clothe",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nå skal vi alle suge på vår egen eller en annens tommel, når vi ikke snakker. Ellers må vi drikke",key:"fingers-mouth",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Dere kan slutte å suge på tommelen",key:"",parent_key:"fingers-mouth",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nå skal alle drikke hver gang en jente viser brystene sine! Alle utenom henne drikker!",key:"show-your-boobs",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Jenter, slutt å vise puppene!",key:"",parent_key:"show-your-boobs",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Bulls Eye-leken begynner! Gjør som du vil med tommel og pekefinger mellom skuldre og hofte. Deltagere som ser på må ta av et klesplagg, eller drikker $ slurker",key:"round-game-hot",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Bulls Eye-leken er ferdig!",key:"",parent_key:"round-game-hot",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Fargespillet starter! Noen raper, og den siste som sier en farge drikker $ slurker eller tar av et klesplagg",key:"gofio-game-hot",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Fargeleken er over!",key:"",parent_key:"gofio-game-hot",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ny regel: hvis man lykkes med å fange en annen spillers blikk samtidig som man suger på en finger, skal denne deltakeren drikke",key:"suck-your-finger",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Slutt å suge på fingrene!",key:"",parent_key:"suck-your-finger",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ny regel! Hver gang vi drikker tomt må vi kose med brystvortene, ellers må vi drikke mer",key:"caddle-tities",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Dere kan slutte å ta på brystvortene",key:"",parent_key:"caddle-tities",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"4",text:"%ss erogene soner, den første som glemmer seg eller ikke kommer på noe å si tar $ slurker. %s starter",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, tenk på en sexposisjon uten å si hvilken. Alle deltakere skal så i tur og orden nevne en, den første som gjetter riktig deler ut $ slurker. %s starter",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, tenk på den deltakeren du tror er mest kåt uten å nevne denne med navn. Alle deltakere skal så i tur og orden nevne en, den første som gjetter riktig deler ut $ slurker. %s starter",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, tenk på et sexleketøy uten å nevne hvilket. Alle deltakere skal så i tur og orden nevne en, den første som gjetter riktig deler ut $ slurker. %s starter",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"4",text:"En av %ss kroppsdeler som denne liker\u0022 den første som gjentar seg eller ikke kommer på noe å si tar $ slurker. %s starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Klær som %s har hatt på seg i sengen\u0022 den første som gjentar seg eller ikke kommer på noe å si tar $ slurker. %s starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Ting som hisser opp partneren\u0022 den første som gjentar seg eller ikke kommer på noe å si tar $ slurker. %s starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ting en partner skal si for å gjøre deg kåt\u0022 den første som gjentar seg eller ikke kommer på noe å si tar $ slurker. %s starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ta runden, alle nevner en eks/partner av gangen. Den som først går tom for navn tar $ slurker. %s, du starter",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ta runden og nevn en kjendis med en lekket sexvideo. Den som først går tom for forslag tar $ slurker. %s, du starter",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ta runden og fortell om steder hvor %s har hatt sex. Den som først går tom for forslag tar $ slurker. %s, du starter",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Gå gjengen rundt, hver person forteller en vanlig fantasi. Den som først går tom for forslag tar $ slurker. %s, du starter",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexakter som ikke er penetreringssex\u0022. Den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Gå laget rundt og vis frem tatoveringene deres, de som ikke har noen tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"4",text:"Gå rundt bordet og vis frem et fødselsmerke. Om du ikke har et eller nekter må du drikke $ slurker. %s starter",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexbomber som har egen dokusåpe\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexleketøy, den som først går tom for forslag tar $ slurker. %s, du starter",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Grunner til å ligge med en fremmed\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ting man skal gjøre som singel før man går ut\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"TV-kanaler som viser erotiske filmer\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Steder å ha hendene på under penetreringssex\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ulike former for vorspiel\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Grunner til ikke å sove over etter et engangsligg\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Typiske steder for fantasier\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Typiske klær i fantasier\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Arbeid som innebærer erotikk eller sex\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Kondomdufter\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ulike sorter mat som kan hisse opp en person om den spises på rett måte\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Synonymer til orgasme\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Steder man kan bite for å hisse opp en partner\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ting som brukes i S&M\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Kroppsdeler som vanligvis slikkes under sex\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ting vi vanligvis gjør etter sex\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexfetisjer folk kan ha\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexhandlinger med tungen\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ulike måter å få en kvinne til å komme på\u0022 den som først går tom for forslag tar $ slurker. %s du starter\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, drikk opp drinken din og bruk tennene til å kneppe opp/dra ned glidelåsen på noens bukser",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, drikk opp drinken din og kos med/slikk på øret til den mest attraktive personen i gjengen",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, drikk opp drinken din og bruk glasset ditt til flasketuten peker på\u0022. Kyss den heldige utvalgte på leppene\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, drikk opp %ss drink og utfør en sexdans for denne deltakeren",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, gi %s et sugemerke, ellers må begge ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, drikk opp drinken din og lat som du får %s til å komme ved å bruke munnen din",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, drikk opp drinken din og gni deg inntil %s",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s kysser samtlige deltakere og drikker opp en valgfri drink",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, gi %s et tungekyss eller ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, velg noen som skal kose deg på valgfritt sted mens du drikker opp drinken din...",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, ta av 3 klesplagg og drikk opp drinken din...",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, velg noen å leke med. Få et kyss og ta en slurk annenhver gang til du har drukket opp denne personens drink...",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, velg noen som skal ha hånden i skrittet ditt mens du drikker opp drinken din, og ja, hånden skal befinne seg innenfor klærne dine...",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, velg 2 deltakere som skal drikke opp drinken sin og tungekysse...",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, tøm glasset til den deltakeren du gjerne skulle tatt med hjem i kveld...",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, tøm glasset ditt mens noen du velger kjæler med deg. Hvis du er jente, skal brystene koses, er du gutt så...der nede...",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Hvem tror dere er best på forspill av %s og %s? Vi stemmer! Vinneren deler ut $ slurker, taperen drikker to ganger",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"14",text:"Jenter, er bryst- eller magemusklene (pupper og rumpe for guttene) viktigst? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"14",text:"For eller imot å ha et engangsligg? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Er du underdanig eller dominant? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Morgensex eller kveldssex? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Bl*wjob eller analsex? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Kn*llekompiser eller seriøst forhold? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Rimjob\u0022 eller gruppesex? ? Alle stemmer samtidig taperne drikker $ slurker\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Barbert eller ubarbert? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"14",text:"G-string eller truser? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Bukkake eller sodomi? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Ville du helst hatt sex 30 ganger på en dag eller ikke hatt sex på en måned? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Ville du helst kysset %s eller %s? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"3"},
{cycle_state:"false",type:"14",text:"Ville du helst hatt sex med %s eller %s? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"3"},
{cycle_state:"false",type:"14",text:"Ville du helst hatt tre*kant eller femten*kant? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ville du helst slikke mus eller suge kuk? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ville du helst sett gjennom klær eller vært usynlig? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ville du helst hatt sex med en kjendis eller den mest sexy personen du kjenner? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ville du helst hatt sex med Megan Fox eller Scarlett Johansson? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ville du helst hatt et perfekt forhold med dårlig sex eller et dårlig forhold med super sex? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ville du helst aldri funnet den ekte kjærligheten eller aldri mer ha sex igjen? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"La oss prate om pupper. Skal de være store eller små? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ville du helst blitt penetrert av en 10 cm eller 35 cm lang k*kk? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Vi øker romtemperaturen litt...sykepleier eller kvinnelig politi? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst kysset personen til høyre eller personen til venstre for deg? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ville du helst hatt sex med personen til høyre eller personen til venstre for deg? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Det tetner til...skal det være brannmann eller soldat? ? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ville du helst tryllet bort truser eller BHer med et knips? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ville du helst levd i en drøm, uten begrensninger i en uke, eller kunne gjøre hvem som helst kåt når som helst? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ville du helst hatt gratis inngang på en swingers-klubb eller et erotisk show? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"For eller imot en rolle i en pornofilm? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"For eller imot nudisme? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Foretrekker du å ligge øverst eller nederst når du har sex? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ville du helst hatt sex med noen i gjengen eller en fremmed person hver dag i en uke? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Ville du helst hatt vors med en fremmed eller få 500 spenn? Alle stemmer samtidig, taperne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"La oss overbevise juryen! %s og %s forteller om en av sine fantasier, de andre deltakerne stemmer det som er mest opphissende! Vinneren deler ut $ slurker, taperen drikker 2 slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Alle stemmer om hvem som får minst sex. Den ulykkelige utvalgte skal heretter kalles Sexsulten\u0022\u0022",key:"horny",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Sexsulten\u0022 del ut $ slurker\u0022",key:"",parent_key:"horny",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Alle tar $ slurker bortsett fra Sexsulten\u0022\u0022",key:"",parent_key:"horny",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Sexsulten\u0022 drukne dine sorger i sprit! Ta $ slurker...\u0022",key:"",parent_key:"horny",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Den ideelle tiden på en runde i senga. Hver person svarer og trykker på skjermen. %s, du starter",key:"sex-duration",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"De tre deltakerne med kortest tid tar $ slurker!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"De tre deltakerne med lengst til drikker $ slurker!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, del ut $ slurker til deltakerne med lengst tid. Hvis du hadde lengst tid drikker du $ slurker",key:"",parent_key:"sex-duration",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, del ut $ slurker til deltakerne med kortest tid. Hvis du hadde kortest tid drikker du $ slurker",key:"",parent_key:"sex-duration",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Hvor mange personer har du hatt sex med? Alle svarer og trykker så på skjermen. %s, du starter",key:"number-partner-sex",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s og %s, del ut like mange slurker som dere har hatt ekspartnere",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s og %s, drikke like mange slurker som dere har hatt ekspartnere",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Den deltakeren som har hatt flest partnere drikker $ slurker",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Den deltakeren som har hatt færrest partnere drikker $ slurker",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"La oss overbevise juryen! %s og %s, fortell om de rareste drømmene dere har hatt, de andre deltakerne stemmer på den rareste! Vinneren deler ut $ slurker, taperen drikker 2 ganger",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Hvor lenge varte din lengste tørkeperiode uten sex? Hver deltaker svarer og trykker på skjermen. %s, du starter",key:"abstinence-time",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Deltakeren med den lengste tørre perioden tar $ slurker",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Deltakeren med den korteste perioden tar $ slurker",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s og %s, del ut like mange slurker som antall måneder dere hadde tørkeperiode",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s og %s drikk like mange slurker som antall måneder dere hadde tørkeperiode",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Hvor mange ganger i uka vil du ha sex? Hver deltaker svarer og trykker på skjermen. %s, du starter",key:"nb-sexual-rel",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Deltakerne som mener mer enn 2 ganger per uke drikker $ slurker, de andre kan ta 1 liten slurk...",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Deltakerne som mener mer enn 3 ganger i uka drikker $ slurker, de andre kan ta 1 liten slurk...",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s og %s deler ut like mange slurker som dere ville hatt sex per uke",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s og %s drikker like mange slurker som antallet ganger dere ville hatt sex på 1 uke",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"La oss overbevise juryen! %s og %s, forteller om sine verste sexopplevelser, deretter stemmer de andre på den verste! Vinneren deler ut $ slurker, taperen drikker 2 ganger",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Hva er favorittposisjonen din? Alle svarer og hvis noen svarer likt, drikker de $ slurker hver",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"La oss overbevise juryen! %s og %s hva er minst sexy å høre når du har sex? Resten stemmer på den verste av dem! Vinneren deler ut $ slurker, taperen drikker 2 slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"La oss overbevise juryen! %s og %s, hva er den beste måten å gjøre partneren kåt på? Resten stemmer på den beste av dem! Vinneren deler ut $ slurker, taperen drikker 2 slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Du kan ha sex i 5 minutter med hvem du vil og hvor du vil før du dør. %s og %s sier sine forslag. Resten stemmer på den mest fristende av dem! Vinneren deler ut $ slurker, taperen drikker 2 slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"La oss overbevise juryen! %s og %s forteller om sine beste sexopplevelser. Resten stemmer på den kuleste av dem! Vinneren deler ut $ slurker, taperen drikker 2 slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"La oss overbevise juryen! %s og %s forteller om en uvanlig plass de har hatt sex på, så stemmer de andre om den tøffeste plassen! Vinneren deler ut $ slurker, taperen drikker to ganger",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Gå gjengen rundt, drikk $ slurker og fortell hvem du vil ha sex med i natt",key:"who-u-wanna-fuck",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Hvis %s blir nevnt, kan hun/han kysse en av deltakerne som sier navnet på munnen. Hvis ikke drikk $ slurker",key:"",parent_key:"who-u-wanna-fuck",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Gå rundt bordet og kyss alle på munnen. De som nekter drikker $ slurker. %s starter!",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Gå rundt bordet og velg noen som må ta deg i skrittet. $ slurker hver for den som nekter. %s, du starter!",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Gå rundt bordet og velg noen som må ta av seg et klesplagg. $ slurker til alle som nekter. %s starter!",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"La oss spille Flasketuten peker på! Hver spiller snurrer flasken og kysser deltakeren tuten peker på. $ slurker til den som nekter. %s starter!",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Underbuksekonkurranse! Jenter; dere er juryen, taperen må ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"BH-konkurranse! Gutter; dere er juryen, vinneren deler ut $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Kysseparty! Gå rundt bordet og kyss personen til høyre eller venstre; eller drikk $ slurker. %s starter!",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"La oss være litt frekke! Gå rundt bordet og ta personen til høyre i skrittet, eller drikk $ slurker. %s starter!",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"La oss være litt frekke! Gå rundt bordet og ta personen til venstre i skrittet, eller ta $ slurker. %s starter!",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"La oss være litt frekke! Gå rundt bordet og ta personen til venstre på brystet, eller ta $ slurker. %s starter!",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"La oss være litt frekke! Gå rundt bordet og ta personen til høyre på brystet, eller ta $ slurker. %s starter!",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Tid for vanskelige spørsmål! Bytt på å spørre om noe dirty. Hvis personen ikke vil svare drikker de $ slurker. %s starter!",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Rumpekonkurranse! Gutter, gå på rekke. Jenter, dere er jury. Vinneren deler ut $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, ta bind over øynene og la 2 deltakere kysse deg hvor som helst. Hvis du gjetter hvem de 2 deltakerne er kan du dele ut $ slurker. Du får bare 1 sjanse!",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, ta bind for øynene, 1 deltaker legger noe spiselig på magen sin og du må spise. Hvis du gjetter hva det er kan du dele ut $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Hårluktekonkurranse. Jentene konkurrerer og guttene er jury. Vinneren deler ut $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt sex offentlig tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt trekant drikker $ slurker. Drikk det dobbelte hvis alle tre deltakerne i trekanten befinner seg i rommet akkurat nå!",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt Skype-sex drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt sex mens de tenkte på noen andre tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som kunne ligget med noen andre i rommet akkurat nå drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt sex på første date drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som elsker oralsex drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har laget en sexvideo tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som tror %s er et bra ligg drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle som har gitt noen en rim job\u0022 drikker $ slurker\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som er blitt overrasket når de har onanert drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som barberer intimområdet drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har vært inne på en pornoside i løpet av de siste to ukene drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som liker dirty talk drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har brukt rollespill som sexhjelpemiddel tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som noen gang har ligget med noen og ikke husker denne personens navn drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt sex på et hotell tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som ikke har hatt bilsex drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som ikke har hatt sex denne uken tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt sex med en minst 5 år eldre person tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt sex med en minst 5 år yngre person tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har sextet\u0022 (sendt sex-tekstmeldinger) med noen tar $ slurker\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som en gang ikke har fått den opp under samleie tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt sex med en annen i rommet tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, del ut $ slurker hvis du har hatt sex mer enn 4 ganger i løpet av en dag. Hvis ikke må du ta $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle som har fantasert om en venns partner drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har sendt sexbilder til noen tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har slikket eller spist mat fra en annen persons kropp drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har skreket ut partneren sitt navn under sexakten tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har fått en orgasme i løpet av 3 minutter tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt sex mens partneren har hatt mensen tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Hvem er best i senga av %s og %s? Vinneren tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Alle som har hatt et utelukkende seksuelt forhold med en venn/venninne tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som syntes første gang gjorde vondt som fa*n tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, hvis du noen gang har vært hemmelig forelsket i %s tar dere begge $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Alle som har stukket et objekt inn i sin partners kropp under sexakten tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har brukt en datingside tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt sex takket være en datingside tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltakeren som sist var inne på en pornoside drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltakeren som har hatt mest sex takket være en datingside deler ut $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har blitt klort under sexakten tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har holdt i et sexleketøy drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har brukt objekter under sexakten drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har blitt opphisset av profesjonell massasje tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har brukt spytt når de har gitt oralsex med sin partner drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har gitt en bl*wjobb den siste måneden tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har sugd noen denne uken tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt et objekt i sin anus eller vagina tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle drittsekker som har fornærmet sin partner mens de hadde sex drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har sett en venn være utro mot sin partner drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har datet en venns eks drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, del ut $ slurker hvis dere brukte kondom sist du hadde sex, ellers må du ta slurkene selv",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle som liker at noen ser på under sexakten drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har kn*llet til en pornofilm drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som liker tanken på å (kanskje enda en gang) kn*lle til en pornofilm tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har lyst på sex akkurat nå tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som liker å bli fingra i anus under sexakten tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som liker å leke med sin partners anus under penetreringen drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som liker å daske eller få dask på rumpa tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle luringer som har hatt sex med både jenter og gutter tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Hør nå, jenter! Ta $ slurker om dere noen gang har hatt sprutorgasme",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Ta $ slurker om dere har fått en analorgasme...",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har krydret sexen ved å kle seg ut drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har sett på nå andre har hatt sex drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som de tre siste gangene hadde sex med kn*llekompiser tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har gitt massasje som videreutviklet seg til noe mye mer interessant drikker $ slurker...",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har fått en massasje som videreutviklet seg til noe mye mer interessant tar $ slurker...",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som tror at de aldri kommer til å prøve noe helt nytt, rent seksuelt, tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, slikk på en kroppsdel på den deltakeren som %s velger ut",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Alle som har kn*llet foran andre mennesker drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har vært med på partnerbytte/swingersfest tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har onanert foran partneren drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som noen gang har onanert med en kollega i tankene deler ut $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som noen gang har onanert mens man har tenkt på en ikke-pornografisk film tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt vorspiel mellom penetreringer drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle jenter som ikke kan twerke\u0022 drikker $ slurker\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har fantasert om en annen deltaker tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltakeren som sist hadde sex tar av et klesplagg",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har kn*llet i sengen til en venn uten at personen har fått vite det tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt forspill med en isbit drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt forspill med en tyggegummi i munnen deler ut $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som er blitt fotografert nakne drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som går truseløse nå drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som foretrekker forspill fremfor penetreringssex tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som liker harde tak drikker $ slurker...",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som mener forspill er obligatorisk drikker $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, del ut $ slurker om du lå med noen før du var 17 år",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, om du hadde en sexy sjef; ville du ha ligget med vedkommende for å fremme karrieren din? Ta $ slurker ved ja\u0022 del ut $ slurker ved \u0022nei\u0022\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, kunne du ligget med en stygg, eldre person for 1,5 millioner kroner? Del ut $ slurker ved ja\u0022 ta $ slurker ved \u0022nei\u0022\u0022",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle som noen gang har prøvd å gå på swingers-klubb tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som noen gang har løyet om at de har fått en orgasme tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltakeren som sist ga en deilig bl*wjob deler ut $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltakeren som sist utførte lidenskapelig munnsex deler ut $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har slikket mus den siste måneden tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har slikket mus for mindre enn en uke siden tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som noen gang har gitt typen en bl*wjob for å vekke han tar $ slurker. Det samme gjelder menn som har blitt vekket av en bl*wjob",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har kost med en intim del med føttene sine tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, del ut $ slurker hvis du ville tilgitt partneren din for å ha vært utro. Hvis ikke drikker du selv",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle som har erotisk tilbehør tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har tungekysset med to personer samme kveld tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som ville ha sett partneren sin ha sex med noen andre tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som tilsammen har hatt sex mer i mørket enn med lyset på tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har kjøpt noe i en sexbutikk tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, del ut $ slurker hvis du synes du er attraktiv. Drikk dem selv hvis du er stygg",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle som har ligget med noen uten å vite navnet deres tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, ta $ slurker hvis fremmede mennesker har sett deg ha sex. Hvis ikke, del ut $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle som har hatt fyllesex tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, ta $ slurker hvis du har kysset noen du synes er motbydelig. Hvis ikke, del ut $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle som tror de kunne få personen ved siden av til å komme i løpet av 10 minutter tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Ta $ slurker om du tror personen til venstre for deg kommer til å ha sex med en annen spiller innen i morgen",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som ikke hadde en bra første sexopplevelse tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har opplevd flørting fra en person av samme kjønn tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt erotiske drømmer om en person ved bordet tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som liker å bli bitt i brystet tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, del ut $ slurker hvis du mener at du har mest sexerfaring i gjengen. Hvis ikke, ta dem selv",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alle som synes flere andre spillere er attraktive tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alle som har hatt sex med noen på grunn av en dating-app tar $ slurker",key:"",parent_key:"",pack_name:"hot",language:"nb",nb_players:"0"}])