var db = TAFFY([{cycle_state:"false",type:"1",text:"%s, 네가 여자라면 네 손가락을 에로틱한 방법으로 핥아. 네가 남자라면 너의 두 손가락으로 여자에게 오랄섹스해줘. 그리고/또는  $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 10초 동안 네가 오르가즘을 느끼는 것처럼 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"모든 여자들은 너네들의 끈 팬티가 보이도록 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s 하고 %s 은/는 아양을 떨고, 두 번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s 은/는 %s 한테 손가락을 빨게 하거나 아니면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"셔츠를 입고 있는 사람은 단추를 풀고, 단추의 수만큼 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, %s 의 옷 한 개를 벗기든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s 하고 자기 위해서는 몇 잔의 잔이 필요해? 대답해 그리고 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, 여기서 게임을 하는 여자들 중, 누가 제일 잘 빠는 것 같아? 대답해 그리고 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s 제일 섹시한 사람에게 $번 마시라고 줘",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 5초 동안 후방 섹스하는 것을 흉내 내든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 한 번도 해본 적 없는 성적인 것을 말해, 그리고 그것을 한 사람들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 우리에게 한쪽의 찌찌를 보여주면 %s 은/는 $번 마셔, 그렇지 않으면 네가 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s, %s 하고 %s 은/는 그룹섹스를 하든지 아니면 모두 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"4"},
{cycle_state:"false",type:"1",text:"%s $번 마실 건지 %s의 발에 키스를 할 건지 정해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s 에게 볼에 뽀뽀를 하면, 모두가 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"이번주에 가진 오르가즘의 수만큼 마셔. 자위 포함.",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"만약 %s 하고 %s 이/가 서로의 입에다 키스를 할 경우, 각각 다른 사람에게 $번 마시라고 하고, 그렇지 않으면 모두 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"첫 번째로 자신의 섹스팅을 보여주는 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, %s 랑 자는 것이 싫지 않으면 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s의 젖꼭지를 꼬집든지 아니면 그/그녀가 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s의 코를 핧든지 아니면 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s에게 머리 마사지를 해주든지 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s 은/는 %s 한테 네 성기를 만지작거리게 놔둬 아니면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s의 코에 뽀뽀를 하든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s 두 명을 선택해서 서로 키스하라고 하든지 아니면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"3"},
{cycle_state:"false",type:"1",text:"%s, 오럴섹스, 애널섹스가 더 좋아 아님 그냥 평범한 섹스가 더 좋아? 대답해 그리고 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"섹스 도중에 모욕을 당한 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, 여기 있는 사람 중 한 사람의 입을 핥든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 여기 있는 사람 중 한 사람의 혀를 핥든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"모두들 $번 마셔. %s 빼고, 모든 사람에게 키스해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, %s 에게 키스를 하든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, 네가 좋아하는 사람에게 키스를 하든지 아니면 $번 마실지 선택해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, %s 의 옷 한개를 벗기든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s 얼음을 %s 에게 입에서 입으로 전달하든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, $번 마시는 것으로 시작해. 네가 남자면, 너의 이상적인 구강 섹스를 묘사해. 네가 여자면 네가 어떻게 그걸 할 건지 이야기해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, $번 마시는 것으로 시작해. 네가 여자면, 너의 이상적인 오럴섹스를 묘사해. 네가 남자면 네가 그걸 어떻게 할 건지 이야기해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네 몸의 일부를 핥을 사람을 선택해. 거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s 은/는 여기 게임하는 사람 중의 찌찌를 반드시 가볍게 건드려야 해, 거절당하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s 선택당한 사람이 너의 찌찌를 살짝 건드리게 놔둬야 해. 거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 여기 게임하고 있는 사람의 가슴에 키스를 하든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 선택당한 사람이 너의 가슴에 키스하게 내버려 둬. 거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 남자라면 네 뒤에 있는 여자에게 네 가슴을 애무하게 나둬, 네가 여자라면 네 가슴을 애무할 남자를 선택해...거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s 너를 위해 랩 댄스를 출 사람을 선택하고, 그 사람이 거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 5초 동안 여기 게임하는 사람의 엉덩이를 애무해, 그/그녀가 거절하면 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 5초 동안 선택된 사람이 네 엉덩이를 애무하게 놔둬. 거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 오늘 밤 잘 사람의 눈을 바라봐, 그 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 그 사람의 은밀한 곳을 애무하는 동안 누가 마실지 선택해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 우리에게 상반신 노출 사진 하나를 보여주든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 여기 게임하고 있는 사람의 귀를 살짝 깨물든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 고른 2명은 서로 혀를 넣어서 키스를 해, 거절하는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 찌찌 한쪽 보여줄 사람을 골라..거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 우리에게 네 신체의 은밀한 부분을 보여주든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 신체의 은밀한 부분을 보여줄 사람 한 명을 선택해. 거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 여기 있는 사람 중 한 사람하고 섹스 동작 한 개를 흉내 내든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 섹스 동작을 흉내 내면서 동시에 $번 마실 사람 2명을 선택해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 어떤 사람의 은밀한 신체 부분에 네 머리를 문질러. 거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 머리를 너의 은밀한 신체에 문질러야 할 사람을 한명 선택해. 거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 게임하고있는 여자의 가슴에 대고 머리를 흔들 한사람을 선택해. 거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 어떤 사람의 은밀한 신체 부위를 핥아. 거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네 신체의 은밀한 부위를 핥을 어떤 사람을 선택해. 거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 어떤 사람의 은밀한 신체 부위를 애무하든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네 신체의 은밀한 부위를 애무할 어떤 사람을 선택해. 거절할 경우에는 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네 속옷 속에 손을 넣을 사람을 선택해. 거절할 경우에는 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 누군가의 속옷 속에 네 손을 반드시 넣어야 해. 거절할 경우에는 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네 입에서 다른 사람의 입으로 음식 옮겨. 거절할 경우에는 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 입에서 입으로 음식 전달할 사람 두 명을 선택해. 거절할 경우에는 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 한 명의 여자 가슴 만져. 거절할 경우에는 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"모두들 마시고 옷 한개 벗어!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, 옷 하나 벗을 사람 선택해. 거절할 경우에는 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 여기 있는 사람 한 명이랑 여자 한 명의 브라자 훅 벗기기 대결해. 5초 안에 못하면, 지명된 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 선택된 사람의 손가락으로 네 찌찌를 꼬집게 하거나 $ 번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 선택된 사람의 엉덩이를 꼬집어. 거절할 경우에는 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 선택된 사람의 손가락으로 네 엉덩이를 꼬집게 하거나 $ 번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 선택된 사람의 입술을 핥아. 거절할 경우에는 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 선택된 사람이 네 입술을 핥게 하든지 아니면 $ 번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 자신의 신체 은밀한 부분을 너에게 보여줄 한 사람을 선택해. 거절할 경우에는 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네 신체의 은밀한 부분을 보여주든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 선택된 사람의 찌찌를 핥아. 거절할 경우에는 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 선택된 사람이 네 찌찌를 핥게 하든지 아니면 $ 번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"남자들, 옷 한 개를 벗든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"여자들, 옷 한 개를 벗든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"남자들, 상의를 벗든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"여자들, 브라자를 입든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 가서 네 속옷을 벗고 와. 하기 싫으면 네 잔을 다 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 글자 하나를 선택해. 저 글자의 이름으로 시작하는 사람하고 잔 모든 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 원하는 사람에게 2분 동안 발 마사지를 해, 아니면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 좋아하는 사람에게서 2분 동안 네가 원하는 신체 부위를 마사지 받아. 두 명 다 거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 원하는 사람의 배꼽을 핥든지 아니면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 좋아하는 사람에게 너의 배꼽을 핥게 해. 두 명 다 거절하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 좋아하는 사람에게 키스 자국을 내든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네가 좋아하는 곳에서, 좋아하는 사람에게 너에게 키스 자국을 내게 해, $번 마시는 걸로 그녀는 거절할 수 있어",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"네가 제일 큰 가슴을 가지고 있어, 남자 하나를 지정해서 네 가슴을 핥게 하든지 아니면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, 너의 엉덩이를 보여주든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 네 신체 한 부분을 선택해. 첫 번째로 그 부분을 만지는 사람은 다른 사람에게 술을 $번 줄 수 있음",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 너의 가슴을 보여주든지 $번 마셔. 네가 남자면, 너는 그걸 다른 사람에게 $번 마시라고 할 수 있어",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"모두 다 같이 가장 유연한 사람을 지정해, 그리고 그 사람이 유연한 것을 증명하고 $번 마셔 ",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, 네가 선택한 사람의 목에다 뽀뽀하든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"시트를 새 걸로 바꿔! 여기서 이미 잔 사람은 다시 키스를 하든지 아니면 두 사람 모두 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, 네가 선택한 사람이 너의 목에다 뽀뽀하게 놔두든지 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, 이 그룹에서 정한 사람에게 화끈한 문자를 보내. 그 사람한테서 답장이 오면 너는 다른 사람에게 원샷을 줘!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, %s 이/가 자고 싶어 할 것 같은 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, 네가 지난 6개월 동안 잔 사람의 수만큼 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s 하고 %s 둘 중에 첫 번째로 다른 사람의 성기를 만지는 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"네 옆에 앉은 사람하고 자발적으로 키스 하고 싶다면 손을 들어. 다른 사람들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"1",text:" %s 하고 %s, 카톡 검색창에서 성기\u0022 라는 단어를 치고 그 단어가 포함된 첫 번째 카톡을 찾아서 읽어. 거절하는 사람은 $번 마셔\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s 하고 %s, 카톡 검색창에서 자지\u0022 라는 단어를 치고 그 단어가 포함된 첫 번째 카톡을 찾아서 읽어. 거절하는 사람은 $번 마셔\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s 하고 %s, 카톡 검색창에서 오럴 섹스\u0022 라는 단어를 치고 그 단어가 포함된 첫 번째 카톡을 찾아서 읽어. 거절하는 사람은 $번 마셔\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s 매번 마실 때마다 지금 즐겨",key:"orgasm-simulation",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 매번 마실 때마다 즐기지 않아도 돼",key:"",parent_key:"orgasm-simulation",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 우리가 그만하라고 할 때까지, 네가 두 눈으로 바라볼 사람을 선택해",key:"look-in-the-eyes",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 네 친구 그만 쳐다봐! ",key:"",parent_key:"look-in-the-eyes",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 네 개의 발 다리로 뒤로 젖혀있어, 네가 언제 일어날지 말해줄게",key:"doggy-style-way",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 이제 그만 편한 자세로 돌아와",key:"",parent_key:"doggy-style-way",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 공항 수색대에서 일해! 네가 원할 때 그 누구의 몸을 수색할 수 있어, 수색을 거절하는 사람은 $번 마셔",key:"body-search",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 은/는 더 이상 공항 수색대에서 일하지 않고 이 더러운 돼지는 $번 마셔",key:"",parent_key:"body-search",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 은/는 큐피트! 그/그녀가 원할 때 애교를 부리는 사람과 키스를 할 사람을 선택해, 그렇지 않으면 $번 마셔",key:"cupidon",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 더 이상 큐피트 아님",key:"",parent_key:"cupidon",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 은/는 정말로 잊어버렸어...그 또는 그녀는 술 마시기 전에 반드시 한 사람하고 키스를 해",key:"kiss-before-drink",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 더 이상 키스 매니아가 아니야!",key:"",parent_key:"kiss-before-drink",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 은/는 새로운 규칙이 나올 때까지 애정을 갖고 %s 의 손을 잡고 있어",key:"hold-hand",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s 하고 %s 은/는 이제 손 놔도 돼",key:"",parent_key:"hold-hand",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s 네 손 마사지를 해줄 한 사람을 선택해! 언제 마사지 그만할지 말해줄게",key:"hand-massage",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 손 마사지 그만해",key:"",parent_key:"hand-massage",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 은/는 매력적이야! 매번 네가 키스를 요구할 때 (입에다 아니면 다른데), 뽑힌 사람은 반드시 해야 하고 싫으면 마셔",key:"irresistible",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 은/는 다시 못생김",key:"",parent_key:"irresistible",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 하고 %s, 새 규칙이 나올 때까지 서로 발 장난해",key:"naughty-feet",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s 하고 %s 발 장난 그만해",key:"",parent_key:"naughty-feet",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s 은/는 새로운 규칙이 나올 때까지 손을 엉덩이 안에 넣을 사람 한 명을 반드시 선택해",key:"hand-under-ass",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 이제 그만 만지작거려!",key:"",parent_key:"hand-under-ass",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 새로운 규칙이 나올 때까지 네 손을 여기 있는 사람의 허벅지에 반드시 대고 있어",key:"put-your-hand-on-legs",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s 이제 손 떼!",key:"",parent_key:"put-your-hand-on-legs",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"작은 게임! %s 이/가 잔을 만질 때마다, %s 은/는 극도의 성적 쾌락을 반드시 흉내 내. 놓칠 때마다 $번 마셔!",key:"touch-glass-and-cum",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s 하고 %s 은/는 너네의 자그만 웃긴 게임 그만해",key:"",parent_key:"touch-glass-and-cum",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, 아무 때나 2명의 사람을 선택해, 그 한 사람은 다른 한 사람의 무릎 위에 앉아. 모두가 거절하면 $번 마셔",key:"on-sby-knees",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 너는 더 이상 그 사람 위에 누가 앉는지 선택할 수 없어",key:"",parent_key:"on-sby-knees",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 너는 독이 든 입술을 가졌어! 바이러스가 끝나기 전에 강요받지 않고 다른 사람에게 키스를 한다면, 그 사람은 그의 잔을 다 마시기! ",key:"kiss-poison",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 네 키스에 더 이상 독이 없어! 실패한다면, $번 마셔",key:"",parent_key:"kiss-poison",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 너는 독이 든 손을 가졌어! 바이러스가 끝나기 전에 다른 사람이 알지 못하게 가볍게 어루만지면, 그 사람은 그의 잔을 다 마시기!",key:"caddle-poison",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, 네 손에 더 이상 독이 없어! 실패한다면, $번 마셔",key:"",parent_key:"caddle-poison",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"3",text:"우리가 말할 때 지금 반드시 서로의 가슴을 애무해야 해!",key:"caress-boobs",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"말하기 위해 우리 이제 그만 서로 만지작거리자!",key:"",parent_key:"caress-boobs",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"병으로 마시는 게임 다시 시작할 수 있어! 마시는 대신에, 병을 돌려서 선택된 사람에게 키스해, 만약 거절하면 두 배로 마셔!",key:"spin-the-bottle",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"병으로 하는 게임은 이제 끝!",key:"",parent_key:"spin-the-bottle",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"지금부터, 어떤 사람이 욕을 할 때마다 그 사람은 옷 한 개 벗든지 $번 마시기!",key:"cross-word-clothe",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"이제 옷 벗을 걱정하지 말고 맘껏 욕해",key:"",parent_key:"cross-word-clothe",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"지금 자신의 엄지손가락을 빨기, 아니면 말을 안 할 때 다른 사람의 엄지손가락을 빨기",key:"fingers-mouth",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"자신의 엄지손가락 이제 그만 빨아도 돼",key:"",parent_key:"fingers-mouth",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"지금부터, 여자가 가슴을 보여줄 때마다 모두들 마셔!",key:"show-your-boobs",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"여자들, 자신의 가슴은 이제 그만 보여줘",key:"",parent_key:"show-your-boobs",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"동그라미 게임! 너희들이 원할 때, 어깨와 허리 사이에 엄지와 검지로 동그랗게 만들고, 그것을 본 사람들은 옷 한 개를 벗든지 $번 마셔",key:"round-game-hot",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"동그라미 게임 끝!",key:"",parent_key:"round-game-hot",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"새로운 규칙, 고리오 게임으로 대체 (어떤 사람이 트림할 때, 가장 늦게 고피오를 외치는 사람이 지는 것)! 매번 질 때마다 옷 한 개를 벗든지 한번 마셔",key:"gofio-game-hot",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"고피오 게임 끝!",key:"",parent_key:"gofio-game-hot",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"새로운 규칙 : 네가 손가락을 빨다가 다른 사람과 눈이 마주쳤다면, 그 사람은 마셔",key:"suck-your-finger",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"다른 사람하고 그런 행동은 이제 그만해",key:"",parent_key:"suck-your-finger",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"새로운 규칙! 우리가 술을 다 마실 때마다 우리는 찌찌를 어루만져. 그렇지 않으면 새로 마셔",key:"caddle-tities",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"3",text:"더 이상 찌찌 만지지 않아도 돼",key:"",parent_key:"caddle-tities",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"4",text:"%s 의 성감대\u0022 를 각자 돌아가며 말할 때 생각이 안 나거나 이미 했던 말을 하는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, 성적인 자세 하나를 생각해. 모든 사람은 각자 순서대로 말하고, 첫 번째로 알아맞힌 사람은 다른 사람에게 $번 마시라고 줘. %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, 일반적으로 질에 하는 삽입 말고 다른 성적인 포즈를 생각해. 모든 사람은 각자 순서대로 말하고, 첫 번째로 알아맞힌 사람은 다른 사람에게 $번 마시라고 줘. %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, 여기 있는 사람 중, 네 생각에 침대에서 가장 뜨거운 사람 한 명을 생각해. 모든 사람은 각자 순서대로 말하고, 첫 번째로 알아맞힌 사람은 다른 사람에게 $번 마시라고 줘. %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, 섹스토이 하나를 생각해. 모든 사람은 각자 순서대로 말하고, 첫 번째로 알아맞힌 사람은 다른 사람에게 $번 마시라고 줘. %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"4",text:"그/그녀가 좋아하는 %s 의 신체 부위\u0022 를 각자 돌아가며 말하고 이미 했던 말을 했거나 생각이 나지 않으면 $번 마셔! %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s 이/가 입고 잔 옷들\u0022 을 각자 돌아가며 말하고 이미 했던 말을 했거나 생각이 나지 않으면 $번 마셔! %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"4",text:"너의 파트너 집에서 널 흥분하게 만드는 것\u0022 를 돌아가며 말할 때 이미 했던 말을 하거나 생각이 안 나는 사람은 $번 마셔! %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"침대에서 널 흥분하게 만드는 말\u0022 을 돌아가며 말할 때 이미 했던 말을 하거나 생각이 안 나는 사람은 $번 마셔! %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"돌아가면서 전 애인의 이름을 말하고, 이미 말했거나 더 이상 없으면 $번 마셔. %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"새로운 주제,그리고 벌칙으로 $번 마시기 : 섹스 테이프가 있는 유명 연예인\u0022 %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"테마게임, 그리고 벌칙으로 $번 마시기 : %s 가 섹스한 장소들\u0022 %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"4",text:"테마게임, 그리고 벌칙으로 $번 마시기 : 일반적인 환상들\u0022 %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"새로운 주제,그리고 벌칙으로 $번 마시기 : 섹스 방식들\u0022 (질 삽입...) %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"차례로, 자신들의 문신 그리고 피어싱들을 보여줘, 이것들이 없는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"4",text:"차례로, 자신들의 몽고반점을 보여주고 다른 사람에게 $번 마시라고 해. 몽고반점 없는 사람은 $번 마셔, %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"리얼리티 방송에 나오는 완전 개섹시한 사람들\u0022 을 각자 돌아가며 말하고 이미 했던 말을 했거나 모르겠는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"섹스 토이들\u0022 을 각자 돌아가며 말하고 이미 했던 말을 했거나 생각이 안나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"모르는 사람들하고 자는 이유들\u0022 을 각자 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"우리가 싱글일 때 파티에 가기 전 꼭 하는 것들 \u0022 을 각자 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은  $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"야한 영화를 틀어주는 티비 채널\u0022 을 각자 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"성관계할 때 네 손을 대는 곳\u0022 을 각자 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"여러가지 전희 \u0022 를 각자 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"하룻밤의 섹스 후 자고 가지 않기 위해 하는 변명들\u0022 을 각자 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"환상 속에서 나오는 장소들\u0022 을 각자 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"환상 속에 나오는 코스튬\u0022 을 각자 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"성행위나 성기에 관련된 직업들\u0022 을 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"콘돔의 냄새\u0022 를 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"특별한 방식으로 먹거나 섹스를 하고 싶어지는 음식 을 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"오르가즘의 동의어\u0022 를 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"네 상대를 흥분시키기 위해 살짝 깨물수있는 장소\u0022 를 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"가학적 변태성욕 중 이용하는 물건들\u0022 을 각자 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"섹스 도중에 기분 좋게 핥을 수 있는 신체 부위 \u0022 를 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"사랑을 나누고 나서 그냥 일반적으로 하는 일들\u0022 을 각자 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"성적으로 집착할 수 있는 것들\u0022 을 각자 돌아가며 말하고 이미 했던 말을 했거나 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"혀를 이용한 성적 행위\u0022 를 각자 돌아가며 말하고 이미 했던 말을 했거나 모르겠는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"4",text:"여자에게 성적 쾌락을 주는 방법들\u0022 을 돌아가며 말하고 이미 했던 말을 했거나 더 이상 생각이 안 나는 사람은 $번 마셔. %s 시작해\u0022",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, 네 잔을 다 마시고 네가 선택한 사람의 바지의 지퍼를 네 이빨로 내려",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, 네 잔을 다 마시고 가서 네가 가장 끌리는 사람의 귀를 살짝 깨물거나/핥아",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, 네 잔을 다 마시고 가서 네가 선택한 사람에게 키스를 해 (입술 에다가)",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, 네 잔을 다 마신 후에 %s 에게 섹시 댄스를 춰",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s %s 에게 키스 자국을 내거나 아님 둘 다 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s 네 잔을 다 마시고 %s 의 얼굴을 빨거나/ 핥아",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s 각각의 사람들에게 뽀뽀를 하고 그걸 좋아한 사람의 잔을 다 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, %s 을/를 껴안고 키스하거나 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, 네가 네 잔을 다 마실 때 너를 애무할 사람을 선택해...",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, 옷 3개를 벗고 네 잔을 다 마셔...",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, 너와 같이 게임을 할 사람을 선택하고 너희는 한번 마시고 키스를 해. 그리고 그 두 명이 잔을 다 마실 때까지 게임해.",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, 네가 네 잔을 다 마시는 동안에 네 성기에다가 손을 갖다 댈 사람 한 명을 선택해. 속옷 안에다 손을 넣어...",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, 잔을 다 마시고 나서 서로 혀로 키스할 두 명을 선택해...",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, 네가 오늘 같이 잘 사람의 잔을 모두 마셔...",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, 네가 선택한 사람이 너를 애무할 동안 너는 네 잔을 다 마셔. 네가 여자라면, 애무 받을 곳은 가슴이고, 네가 남자라면, 애무 받을 곳은 성기야.",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"14",text:"네 생각에 %s 하고 %s 중에 누가 더 전희를 더 잘할 것 같아? 모두들 동시에 결정하고, 표를 더 많이 받은 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"14",text:"남자들 가슴 또는 엉덩이 둘 중에 뭐가 더 좋아? 여자들 가슴 근육 또는 식스팩 둘 중에 뭐가 더 좋아? 모두들 동시에 결정하고, 표가 적은 사람들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"14",text:"원나잇스탠드에 찬성이야 반대야? 모두들 동시에 손을 들어 결정하고, 결과의 소수인 사람들은 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"가슴에 대해, 아주 큰 게 나아 아니면 차라리 아주 작은 게 나아? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"복종하는 게 나아 아님 차라리 지배하는 게 나아? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"14",text:"구강 섹스야 아님 차라리 애널섹스야? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"14",text:"친구랑 잠자는 사이가 나아 아님 차라리 진중한 연인 사이가 나아? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"14",text:"애널섹스야 아님 차라리 섹스 파티야? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"14",text:"지하철 표야 아님 차라리 수염 없는 얼굴이야? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"14",text:"끈 팬티야 아님 그냥 팬티야....? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"14",text:"사정 분출이야 아님 차라리 애널섹스야? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"14",text:"같은 날에 30번 섹스할래 아님 차라리 한 달 동안 섹스 안 할래? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"14",text:"%s 하고 %s 중에 차라리 누구랑 키스할래? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"14",text:"%s 하고 %s 중에 차라리 누구랑 잘래? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"14",text:"3명하고 섹스할래 아님 차라리 8명하고 할래? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"여자에게 오럴섹스를 해줄래 아님 차라리 남자에게 오럴섹스를 해줄래? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"옷을 투과해서 볼래 아님 차라리 투명인간이 될래? 각자 차례로 결정하고, 그 결과의 소수자들은 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"유명인하고 잘래 아님 차라리 네가 아는 가장 섹시한 사람하고 잘래? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"메간 폭스야 아님 차라리 스칼렛 요한슨이야? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"완벽한 관계지만 섹스 궁합은 최악일래 아님 차라리 소홀한 관계지만 끝장나는 섹스 궁합 일래? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"사랑을 절대 찾지 못할래 아님 차라리 성관계를 전혀 하지 못할래? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"9cm 이거나 아님 36cm 의 성기를 가질래 (아님 상대할래) ? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"야한짓은 아침에 하는 게 나아 아님 차라리 밤이야? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"섹스할 때, 간호사로 변장할래 아님 차라리 경찰로 변장할래? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"너의 오른쪽에 있는 사람하고 키스할래 아님 차라리 왼쪽에 있는 사람하고 할래? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"너의 오른쪽에 있는 사람하고 잘래 아님 차라리 왼쪽에 있는 사람하고 잘래? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"섹스할 때, 소방관으로 변장할래 아님 차라리 군인으로 변장할래? 모두 동시에 결정하고, 그 결과의 소수자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"손가락을 튕겨서 바지를 벗기게 할 수 있는 능력을 가질래 아님 웃옷을 벗기게 할래? 모두 동시에 결정하고, 표가 적은 사람들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"한 주 동안 백일몽 하고 무궁한 전지전능의 힘을 가질래 아님 차라리 네가 원하는 아무나 하고 일생 동안 섹스를 할 수 있는 힘을 가질래? 모두 동시에 결정하고, 표가 적은 사람들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"스윙어 클럽의 회원권을 가질래 아님 차라리 에로틱 모임 회원권을 가질래? 모두 동시에 결정하고, 표가 적은 사람들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"포르노 영화에서 연기하는 것에 대해 찬성이야 반대야? 모두 동시에 결정하고, 표가 적은 사람들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"나체주의에 대해 찬성이야 반대야? 모두 동시에 결정하고, 표가 적은 사람들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"스윙어에 찬성이야 반대야? 모두 동시에 결정하고, 표가 적은 사람들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"섹스할 때, 여자가 네 위에 올라타는 게 더 좋아, 아님 네 밑에 있는 게 더 좋아? 모두 동시에 결정하고, 표가 적은 사람들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"이 테이블에 있는 어떤 사람과 잘래 아님 차라리 일주일 동안 모르는 사람과 매일 잘래? 모두 동시에 결정하고, 표가 적은 사람들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"14",text:"여기 있는 사람들 중 한 명과 전희를 가질래 아님 차라리 67만 원을 가질래? 모두 동시에 결정하고, 표가 적은 사람들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"배심원을 설득시켜! %s 하고 %s 은/는 자신들의 환상 중 한 가지를 말하고, 배심원들은 가장 뜨거운 환상을 뽑아! 이긴 사람은 다른 사람에게 $번 마시라고 하고, 진 사람은 그걸 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"섹스를 가장 안 한 것 같은 사람을 지명하고, 스크린을 터치해",key:"horny",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"지명당한 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"horny",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"지명당한 사람을 제외하고 모두 $번 마셔",key:"",parent_key:"horny",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"지명당한 사람은 술로 아픔을 달래고 $번 마셔 (오늘 저녁은 데이트하지 않아)",key:"",parent_key:"horny",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"이상적인 섹스 지속기간. %s 시작해 (다음은 바로...)",key:"sex-duration",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"가장 적은 지속기간을 가진 3명은 $번 마셔!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"가장 긴 지속기간을 가진 3명은 $번 마셔!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, 가장 긴 지속기간을 가진 한 사람에게 $번 줘. 네가 가장 긴 지속기간을 가졌다면 $번 마셔",key:"",parent_key:"sex-duration",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, 가장 적은 지속기간을 가진 사람에게 $번 줘. 네가 가장 적은 지속기간을 가졌다면 $번 마셔",key:"",parent_key:"sex-duration",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"당신이 가졌던 섹스 파트너의 수는 몇 명? 각자 대답을 해, 다음은 바로... %s 시작해",key:"number-partner-sex",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s 하고 %s 은/는 섹스 파트너의 수만큼 다른 사람에게 마시라고 하기!",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s 하고 %s 은/는 섹스 파트너의 수만큼 마셔!",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"섹스 파트너를 가장 많이 가졌던 사람은 $번 마셔",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"섹스 파트너를 가장 적게 가졌던 사람은 $번 마셔",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"배심원을 설득시켜! %s 하고 %s 은/는 자신이 꿔봤던 이상하면서 야한 꿈을 말해! 다른 사람들은 제일 사실 같지 않은 꿈을 뽑아! 뽑힌 사람은 다른 사람에게 $번 마시라고 하고, 진 사람은 그걸 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"첫 성관계 후 당신의 가장 긴 금욕의 시간. 각자 대답을 해, 다음은 바로...%s 시작해",key:"abstinence-time",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"가장 긴 금욕의 시간을 가진 사람은 $번 마셔!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"가장 긴 금욕의 시간을 가진 사람은 다른 사람에게 $번 마시라고 해!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s 하고 %s 은/는 그 금욕의 수가 적은 사람의 수만큼 다른 사람에게 마시라고 해!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s 하고 %s 은/는 그 금욕의 수가 적은 사람의 수만큼 마셔!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"당신이 생각하는 일주일간의 이상적인 성관계의 횟수. 각자 대답을 해, 그 다음은 바로...%s 시작해",key:"nb-sexual-rel",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"2번 이상의 사람들은 $번 마시고, 다른 사람들은 조금만 마셔",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"3번 이하의 사람들은 $번 마셔. 그 외의 나머지 사람들은, 아주 조금만 마셔",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s 하고 %s 은/는 성관계의 횟수만큼 다른 사람에게 마시라고 하기!",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s 하고 %s 은/는 성관계의 횟수만큼 마셔!",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"배심원을 설득시켜! %s 하고 %s 은/는 자신들의 최악의 성관계 중 한 가지를 말하고, 배심원들은 가장 불쌍한 애를 뽑아! 이긴 사람은 다른 사람에게 $번 마시라고 하고, 진 사람은 그걸 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"네가 가장 좋아하는 섹스 자세은? 각자 대답하고, 가장 흔한 자세를 말한 사람들은 $번 같이 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"배심원을 설득시켜! %s 하고 %s 은/는 섹스 도중, 가장 섹시하지 않은 것들을 말하고 다른 사람들은 최악을 뽑아! 이긴 사람은 다른 사람에게 $번 마시라고 하고, 진 사람은 그걸 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"배심원을 설득시켜! %s 하고 %s 은/는 자신의 파트너를 흥분시키는 가장 좋은 것을 말하고, 다른 사람들은 가장 핫한 걸 뽑아! 이긴 사람은 다른 사람에게 $번 마시라고 하고, 진 사람은 그걸 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"언제 어디서든 그 누구와 죽기 전에 5분 동안 섹스를 해야 하는 의무가 있어. %s 하고 %s 은/는 선택을 제안하고, 다른 사람들은 최고인 것을 뽑아! 이긴 사람은 다른 사람에게 $번 마시라고 하고, 진 사람은 그걸 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"배심원을 설득시켜! %s 하고 %s 은/는 너네들의 인생 최고의 섹스를 말하고, 다른 사람들은 가장 흥분되는 것을 뽑아! 이긴 사람은 다른 사람에게 $번 마시라고 하고, 진 사람은 그걸 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"배심원을 설득시켜! %s 하고 %s 은/는 너네가 섹스를 한 색다른 장소를 말하고, 다른 사람들은 가장 사실 같지 않은 것을 뽑아! 이긴 사람은 다른 사람에게 $번 마시라고 하고, 진 사람은 그걸 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"23",text:"각자 차례로, $번 마시고 여기에 있는 어떤 사람과 자고 싶은지 말해.",key:"who-u-wanna-fuck",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, 누군가 너에 대해 이야기했다면, 가서 너에 대해 이야기 한 사람에게 키스해. 그렇지 않으면 $번 마셔",key:"",parent_key:"who-u-wanna-fuck",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"각자 차례로, 한 사람에게 키스해. 거절하는 사람은 $번 마셔. %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"각자 차례로, 자신의 성기를 만질 사람을 선택해. 그 혹은 그녀가 거절하면, 자신을 위해 $번 마셔. %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"각자 차례로, 옷 한 개 벗을 사람을 선택해. 그 혹은 그녀가 거절하면, 자신을 위해 $번 마셔. %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"병 돌리기 게임! 각각 병을 돌리고 병이 가리키는 사람에게 키스하기, 거절하면 $번 마셔. %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"사각팬티의 선발! 여자들이 심사 위원단이고, 지는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"브라자의 선발! 남자들이 심사 위원단이고, 지는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"키스 파티! 각자 차례로 자신의 왼쪽에 있는 사람에게 키스해 하기 싫으면 $번 마시기, %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"옆 사람의 보지 만지기! 각자 차례로, 자신의 오른쪽에 있는 사람의 성기를 만지기 하기 싫으면 $번 마시기, %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"옆 사람의 보지 만지기! 각자 차례로, 자신의 왼쪽에 있는 사람의 성기를 만지기 하기 싫으면 $번 마시기, %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"옆 사람의 보지 만지기! 각자 차례로, 자신의 오른쪽에 있는 사람의 가슴을 애무하고 하기 싫으면 $번 마시기, %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"옆 사람의 보지 만지기! 각자 차례로, 자신의 왼쪽에 있는 사람의 가슴을 애무하고 하기 싫으면 $번 마시기, %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"함정이 있는 질문! 각자 차례로, 아무에게나 심술적인 질문 한 개 하기. 응답자가 대답하기 싫다면, 그 사람은 $번 마셔. %s 시작해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"엉덩이 선발대회 : 남자들, 행진! 여자들은 심사위원, 이긴 사람은 다른 사람에게 $번 마시라고 할 수 있음",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, 네 두 눈을 가려 그리고 2명이 아무 데나 네게 키스할 거야. 네가 그 두 명이 누군지 맞춘다면, 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, 네 두 눈을 가려, 한 명이 네 배 위에 음식을 놓으면 너는 그 음식을 먹을 거야. 그게 무엇인지 맞춘다면, 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"23",text:"머리 냄새 선발대회! 여자들이 하고, 남자들은 심사위원. 이긴 사람은 다른 사람에게 $번 마시라고 줄 수 있어",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"공공장소에서 사랑을 나눠본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"쓰리썸을 한적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"섹스 캠을 해본 적 있는 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"섹스하고 있는 도중에 다른 사람을 생각해본 적 있는 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"지금 여기 있는 사람과 방에서 자는 것이 좋은 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"데이트 첫날 저녁에 자봤으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"오럴섹스를 좋아하는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"사랑을 나누고 있는 동안에 영상을 찍어본 적 있는 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s 이/가 침대에서 끝내준다고 생각하는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"25",text:"똥꼬를 핥아본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"자위를 하는 동안 놀라본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"은밀한 부분을 면도한 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"2주 이상 포르노 사이트에 가지 않은 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"침대에서 더러운 욕 같은 단어 쓰는 것을 좋아하는 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"침대에서 역할극을 해본 적 있는 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"같이 잔 사람들의 이름이 기억나지 않은 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"호텔에서 섹스를 한적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"자동차 안에서 한 번도 섹스해본 적 없는 사람들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"이번 주에 성관계를 가지지 않은 사람들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"자신보다 5살 보다 더 많은 사람과 잔 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"자신보다 5살 보다 더 어린 사람과 잔 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"섹스팅을 보낸 적이 있거나 받아본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"발기부전을 겪어 본 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"여기 있는 사람이랑 정사가 나본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"섹스를 하고 있는 중에 부모 중 한 명이 들어와서 놀랜 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, 같은 날 4번 이상 사랑을 나눠본 적이 한 번도 없으면 $번 마시고, 그렇지 않으면 그걸 다른 사람에게 줘",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"25",text:"친구의 애인에게 환상을 가져본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"에로틱한 사진을 전송해본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"애인의 몸 위에서 음식을 먹어본 적 있거나 핥아본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"사랑을 나누면서 애인의 이름을 외쳐본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"삽입하고 3분도 안 돼서 오르가즘을 느껴본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"생리 중에 사랑을 나눠본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s 하고 %s 중에 침대에서 제일 재능 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"25",text:"첫 성관계가 섹스 파트너랑 한 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"첫 경험 때 아팠던 여자들은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, %s을/를 몰래 사랑했었다면, 너는  $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"25",text:"자신들의 애인의 성기에 물건을 넣어본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"소개팅 사이트에 가입해본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"소개팅 사이트에서 만난 사람하고 섹스한 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"최근에 포르노 사이트 간 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"소개팅 사이트에서 만난 사람들 하고 가장 많이 섹스를 한 사람은 다른 사람에게 $번 마시라고 줘",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"섹스 파트너를 할퀴거나 할퀸 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"가짜 고추를 손에 쥐어본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"섹스할 때 액세서리를 이용해본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"전문적인 문자를 받고 흥분해본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"성기에 침을 뱉어본 적 있는 사람은 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"구강 섹스를 한지 한 달 안된 사람은 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"구강 섹스를 한지 일주일도 안된 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"똥꼬나 보지 안에 물건을 넣어본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"섹스하는 동안에 상대에게 모욕을 준적 있으면 $번 마셔 이 병신들아",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"친한 친구가 그 친구의 애인을 두고 바람피운 것을 본적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"친구의 전 애인이랑 데이트해본 적 있는 사람은 $번 마셔 나쁜 새끼들아",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, 네가 최근에 피임을 하고 섹스를 했다면 다른 사람에게 $번 마시라고 해, 아니면 네가 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"25",text:"네가 사랑을 나눌 때 남들이 쳐다보는 게 좋다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"포르노를 보는 도중에 섹스를 했다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"포르노를 보면서 섹스를 하는 게 흥미롭다고 생각하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"여기서 지금 당장 자고 싶다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"네가 사랑을 나눌 때 네 똥꼬를 애무해주는 게 좋다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"섹스할 때 네 애인의 똥구멍을 가지고 장난을 치는 게 좋으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"엉덩이 때리는 걸 좋아하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"이성, 동성하고 섹스를 해본 적 있는 더러운 새끼는 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"여자들, 질로 오르가즘을 가져본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"항문으로 오르가즘을 가져본 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"민족 혼합을 위하여! 피부 색깔이 다른 사람하고 자 본적 있으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"짜릿한 섹스를 위해 변장을 해본 적 있으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"사람들이 사랑을 나누는 것을 본적 있으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"최근에 한 3번의 섹스가 섹스 파트너와 한 거면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"누군가에게 마사지를 주는데 그게 점점 야해진 적이 있으면 $번 마셔...",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"마사지를 받았는데 그게 야해졌다면 $번 마셔...",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"네가 섹스에 대해 모든 걸 다 해봤다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, %s 이/가 선택한 사람의 몸의 한 일부를 핥아 (네가 원하는 부분)",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"2"},
{cycle_state:"false",type:"25",text:"다른 사람 앞에서 섹스해본 적 있으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"스윙어 파티에 가본적 있으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"너의 애인 앞에서 자위해본 적 있으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"직장 동료를 생각하면서 자위를 해본 적 있으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"포르노를 제외하고 다른 영화를 보면서 자위해본 적 있으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"2분 동안 애무를 하고 섹스를 한적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"트워크 춤을 어떻게 추는지 모르는 사람은 $번 마셔!",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"여기 있는 사람들 중 한 명에게 환상을 품고 있어봤으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"최근 성관계를 한 사람은 옷 한 개 벗어",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"네 친구 모르게 그 친구의 침대 위에서 섹스한 적 있으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"얼음으로 전희를 해봤으면 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"입안에 있는 풍선껌으로 전희를 해본 적 있다면 다른 사람에게 $번 마시라고 해...",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"자신의 누드 사진을 찍어봤으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"속옷을 입지 않았으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"질에 애무 받는 걸 좋아하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"침대에서 세게 하는 걸 좋아하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"전희가 필수라고 생각하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, 17살 전에 첫 경험을 했다면 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, 네 커리어를 위해서 너의 직장 상사하고 잘 수 있어? 그렇다 : $번 마셔, 아니다 : 다른 사람에게 그걸 마시라고 줘",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, 2억을 위해 역겨운 늙은이랑 잘 수 있어? 그렇다 : 다른 사람에게 $번 마시라고 해, 아니다 : 넌 그걸 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"25",text:"스윙어 클럽에 들어간 적이 있거나, 들어가려고 시도해봤다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"가짜로 오르가즘 연기를 한 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"최근 아주 좋은 구강 섹스를 남자에게 해준 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"최근 열정적으로 여자에게 구강 섹스를 해준 사람은 다른 사람에게 $번 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"한 달 안 돼서 여자에게 오랄 섹스를 해줬다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"일주일 안 돼서 여자에게 오랄 섹스를 해줬다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"네 애인을 깨우기 위해서 빨아봤다면 $번 마시고. 일어날 때 오럴 섹스를 받아본 남자들은 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"발로 성기를 애무한 적 있으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, 너의 애인의 배신을 용서할 수 있다면 다른 사람에게 $번 마시라고 해. 아니면 네가 그걸 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"25",text:"에로틱한 소품을 가지고 있다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"같은 날 저녁에 여러 사람과 혀로, 키스를 해본 적 있다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"너의 애인이 다른 사람과 사랑을 나누는 것을 보고 싶다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"네 인생에서, 낮보다는 밤에 더 많이 사랑을 나눠봤다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"섹스 샵에서 무언가를 사본적 있으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, 네가 매력적이라고 생각하면 다른 사람에게 $번 마시라고 해. 만약 네가 못생겼다면, 네가 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"25",text:"네 이름을 모르는 사람하고 잔 적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, 모르는 사람이 네가 사랑을 나누는 것을 본적 있다면 $번 마셔. 그렇지 않으면 그걸 다른 사람에게 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"25",text:"네가 취한 채 섹스를 해본 적 있으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, 네 생각에 역겨운 사람하고 키스해본 적 있으면 $번 마셔. 그렇지 않으면 그걸 다른 사람에게 마시라고 해",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"25",text:"네 생각에 네 오른쪽에 앉은 사람과 10분 내로 즐길 수 있다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"네 왼쪽에 앉은 사람이 여기 있는 한 사람과 오늘 잘 거라고 생각하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"너의 첫 경험이 좋지 않았다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"동성에게서 유혹을 당해본 적 있으면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"이 테이블에 있는 사람이 너의 에로틱한 꿈에 나와본 적 있다면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"사람들이 네 찌찌를 깨무는 걸 좋아하면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, 이 테이블에서 네가 가장 많이 잤다고 생각하면, 다른 사람에게 $번 마시라고 해. 아니면 네가 그걸 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"1"},
{cycle_state:"false",type:"25",text:"이 테이블에 있는 여러사람이 육체적으로 널 매혹시키면 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"},
{cycle_state:"false",type:"25",text:"미팅 앱에서 만난 사람하고 자본적 있는 사람은 $번 마셔",key:"",parent_key:"",pack_name:"hot",language:"ko",nb_players:"0"}])