var db = TAFFY([{cycle_state:"false",type:"1",text:"%s, slicka fingrarna lite upphetsande om du är en tjej. Gör cunnilingu*s med tungan slafsande mellan två fingrar om du är kille. Drick upp ditt glas om du vägrar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, fejka en orgasm under 10 sekunder eller drick botten upp",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Tjejer, dra upp stringtrosorna",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s och %s, gosa med varann under de följande 5 minuterna",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, låt %s suga av ditt finger eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Alla knäpper upp sina skjortor/blusar och dricker en klunk för varje uppknäppt knapp",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, ta av ett av %ss klädesplagg eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, hur många drinkar skulle du behöva för att ha sex med %s? Svara och drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, vem av de närvarande personerna tror du skulle kunna ge bästa avsugningen? Svara och drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s dela ut $ klunkar till den sexigaste personen i rummet. (Ja, du är väldigt sexig, men välj någon annan än dig själv)",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, låtsas ha doggy style-sex i 5 sekunder eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, nämn en sexakt du inte har prövat på. Alla som har prövat på den dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, om du visar ena bröstet måste %s dricka $ klunkar. Om du vägrar ska du dricka $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s, %s, och %s ska fejka grupps*ex med %s eller dricka $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"5"},
{cycle_state:"false",type:"1",text:"%s, antingen kysser du %ss fötter eller dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, om du kysser %s på kinden måste alla dricka $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Alla närvarande personer ska dricka lika många klunkar som antalet orgasmer de har fått denna vecka, inklusive självframkallade sådana",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Om %s och %s kysser varandra får samtliga deltagare dela ut $ klunkar. I annat fall får ni dricka $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Den som först kan visa upp ett sexrelaterat textmeddelande får dela ut $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, dela ut $ klunkar om du inte skulle ha något emot att ha sex med %s",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, nyp %s i bröstvårtorna, annars får hen dricka $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s slickar %ss näsa eller dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, ge %s huvudmassage eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, låt %s smeka ditt skrev sensuellt eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, pussa %s på näsan eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s väljer ut två deltagare som ska kyssa varann, om någon av dem vägrar ska hen dricka $ klunkar vardera",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"3"},
{cycle_state:"false",type:"1",text:"%s, föredrar du oral-, anal- eller vaginalsex? Svara och drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Alla som har blivit förolämpade under sexakten dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, slicka någon på munnen eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slicka någons tunga eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Alla tar $ klunkar förutom %s som ger alla en kyss",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kyss %s eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, välj mellan att kyssa någon eller att dricka $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ta av %s ett klädesplagg eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s överför en isbit från din egen mun till %ss mun, eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, ta först $ klunkar. Berätta om hur dina drömmars avsugning skulle gå till, eller hur du skulle göra den.",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ta först $ klunkar. Berätta om hur dina drömmars cunnilingus skulle gå till, eller hur du skulle ge den.",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj ut en deltagare som ska slicka en av dina kroppsdelar. Straffet är $ klunkar om deltagaren vägrar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s ska gnida någon annans bröstvårtor, straffet är $ klunkar om personen vägrar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, låt en annan deltagare gnida dina bröstvårtor. Straffet är $ klunkar för den som vägrar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, kyss en annan deltagares bröst eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, låt någon du själv väljer ut kyssa dina bröst. Den som vägrar dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, om du är man, ställ dig bakom en kvinna och smek hennes bröst. Om du är kvinna, välj ut en man att smeka... straffet för vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj ut någon som ska ge dig en lap dance\u0022. Vägrar personen ska hen dricka $ klunkar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, smek någons stjärt i 5 hela sekunder, om den utvalda deltagaren vägrar blir det $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, låt en deltagare du väljer ut smeka din stjärt under 5 sekunder. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, se någon potentiell sexpartner för natten i ögonen. Den personen ska dricka $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj någon som ska dricka medan du masserar hens intima delar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, visa ett barbröstat/topless foto du har, eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, nafsa på någons öra eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj ut 2 personer som ska tungkyssas, straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj ut någon som ska visa en bröstvårta, straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, visa någon av dina intima delar eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj ut någon som ska visa någon av sina intima delar. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, inta en sexställning med en utvald deltagare. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj ut 2 deltagare som ska inta en sexställning och samtidigt dricka $ klunkar.",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, gnid ditt ansikte mot någons intima delar. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj ut någon som ska gnida sitt ansikte mot dina intima delar. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj en deltagare som ska bröstknulla en annan deltagare bröst. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slicka någons intima delar. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj ut någon som ska slicka dina intima delar. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, smek någons intima delar eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj ut någon som ska smeka dina intima delar. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj någon som ska stoppa handen innanför dina trosor. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, stoppa in din hand innanför någon trosor. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, överför något i matväg från din mun till någon annandeltagares mun. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj 2 deltagare som ska överföra mat mellan sina munnar. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ta på någons bröst. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Alla tar av sig ett klädesplagg!",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, välj ut någon som ska ta av ett klädesplagg. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, utmana en annan deltagare att knäppa upp en kvinnlig deltagares bh. Om personen inte kan klara av det på 5 sekunder dricker hen $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, låt någon nypa dig i bröstvårtorna eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, nyp någon i stjärten. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, låt någon nypa dig i stjärten eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slicka någons läppar. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, låt någon slicka dina läppar eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slicka någons bröstvårtor. Straffet vid vägran är $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, låt någon slicka dina bröstvårtor eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Grabbar, ta av ett klädesplagg eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Tjejer, ta av ett klädesplagg eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Grabbar, ta av er barbröstade eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Tjejer, ta av blusen så ni bara har behå eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, gå och ta av dig trosorna/kalsongerna och kom sedan tillbaka. Om du inte vill, töm glaset",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj en bokstav. Alla som har legat med en person vars namn börjar på denna bokstav dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ge en fotmassage till vem du vill i 2 minuter, eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj ut någon som ska ge dig fotmassage i 2 minuter. All slags vägran genererar $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, slicka runt navel på en valfri person eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj någon som ska slicka din navel. All slags vägran genererar $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ge någon du väljer ut ett sugmärke eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, låt någon du väljer ut ge dig ett sugmärke på valfri plats. All slags vägran genererar $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Tjejen med störst hylla väljer ut någon som ska slicka hens tuttar eller så dricker hen $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, visa rumpan eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, välj ut en kroppsdel. Den deltagare som först rör vid kroppsdelen delar ut $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, visa dina bröst eller drick $ klunkar. Dela ut $ klunkar om du är en man",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Utse den mest viga deltagaren, som måste bevisa detta och dricka $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, kyss någon du väljer ut på halsen eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"En gång till! Alla som har kysst varandra måste kyssa varann igen eller så får båda dricka $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, välj ut någon som ska kyssa dig på halsen, eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, sexta (skicka ett sexmeddelande) till någon laget väljer ut. Om personen ifråga blir kåt kan du beordrar någon att tömma glaset",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, dela ut $ klunkar till den person som %s har störst chans att hamna i säng med inatt",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, drick lika många klunkar som antalet samlagspartners du har haft senaste halvåret",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Den av %s och %s som först rör vid en annan deltagares könsorgan delar ut $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Räck upp handen om du skulle kunna tänka dig att kyssa någon av din grannar. De övriga dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s och %s läs upp det första meddelande som visas om man skriver in sex\u0022 i sökfältet på er telefon. Alla som avstår dricker $ klunkar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s och %s läs upp det första meddelande som visas om man skriver in penis\u0022 i sökfältet på er telefon. Alla som avstår dricker $ klunkar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s och %s läs upp det första meddelande som visas om man skriver in avsugning\u0022 i sökfältet på er telefon. Alla som avstår dricker $ klunkar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, simulera en orgasm inför varje klunk fram tills du får en ny instruktion",key:"orgasm-simulation",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du kan sluta simulera en orgasm inför varje klunk",key:"",parent_key:"orgasm-simulation",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, välj ut någon och stirra in i hens ögon tills du får instruktion om att sluta!",key:"look-in-the-eyes",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du kan sluta stirra djupt in i din kamrats ögon!",key:"",parent_key:"look-in-the-eyes",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ställ dig på alla fyra i doggy-style och svanka med ryggen fram tills du får andra instruktioner!",key:"doggy-style-way",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s kan åter inta en mer behaglig ställning",key:"",parent_key:"doggy-style-way",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s är polis! Du kan kroppsvisitera vem som helst, var som helst! Den som vägrar bestraffas med $ klunkar!",key:"body-search",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s du är inte polis längre. Drick $ klunkar, gamla pervo!",key:"",parent_key:"body-search",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s är kärleksguden Cupido! Välja en deltagare som ska krama eller kyssa någon annan. Den som vägrar bestraffas med $ klunkar",key:"cupidon",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du är inte Cupido längre",key:"",parent_key:"cupidon",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s är riktigt kåt... hen måste kyssa någon innan varje klunk",key:"kiss-before-drink",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du är botad mot ditt nya sexberoende",key:"",parent_key:"kiss-before-drink",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ta tag i %ss hand och håll den kärleksfullt fram tills ny instruktioner ges!",key:"hold-hand",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s och %s kan släppa taget om varandras händer!",key:"",parent_key:"hold-hand",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s väljer ut någon som ska ge hen handmassage! Vi säger till när massagen kan ta slut",key:"hand-massage",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ingen mer handmassage för din del",key:"",parent_key:"hand-massage",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du är helt oemotståndlig! Varje gång du vill ha en kyss på munnen eller varhelst, måste den utvalda personen uppfylla din önskan eller dricka $ klunkar",key:"irresistible",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s är inte längre oemotståndlig!",key:"",parent_key:"irresistible",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s och %s, massera varandras fötter fram tills ni får lov att sluta!",key:"naughty-feet",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s och %s kan sluta massera varann",key:"",parent_key:"naughty-feet",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, välj ut någon som ska kupa om din stjärt med sin hand",key:"hand-under-ass",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%ss stjärt återfår sin frihet",key:"",parent_key:"hand-under-ass",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s ska lägga en hand på någon annan deltagares höft fram tills hen får annan instruktion",key:"put-your-hand-on-legs",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s kan ta bort sin hand",key:"",parent_key:"put-your-hand-on-legs",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"Orgasmlek! Varje gång %s rör ett glas måste %s fejka en orgasm. Varje försummelse straffas med $ klunkar",key:"touch-glass-and-cum",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s och %s kan sluta med sin orgasmlek",key:"",parent_key:"touch-glass-and-cum",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, välj 2 deltagare när du vill. Den ene ska sitta i den andras knä. Straffet vid vägran är $ klunkar",key:"on-sby-knees",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du får inte längre välja vem som ska sitta i vems knä",key:"",parent_key:"on-sby-knees",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du är Poison Ivy! Om du lyckas kyssa någon, utan tvång, innan viruset tar slut, ska den spelaren avsluta sin drink",key:"kiss-poison",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du är inte längre Poison Ivy! Drick $ klunkar om du misslyckades",key:"",parent_key:"kiss-poison",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du har magiska händer! Om du innan viruset tar slut lyckas smeka en deltagare utan att det märks ska spelaren avsluta sin drink!",key:"caddle-poison",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, du har inte längre magiska händer! Drick $ klunkar om du misslyckades med ditt uppdrag",key:"",parent_key:"caddle-poison",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"3",text:"Varje gång ni säger något måste ni smeka er över bröstet!",key:"caress-boobs",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"NI kan alla sluta smeka era bröst! (om ni vill kan ni börja smeka någon annans, men det är bara ett litet förslag...)",key:"",parent_key:"caress-boobs",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ni kan nu leka snurra flaskan-leken igen. Istället för att dricka, snurrar ni flaskan och kysser deltagaren den pekar på. Antalet klunkar fördubblas om man vägrar!",key:"spin-the-bottle",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Snurra flaskan-leken är över!",key:"",parent_key:"spin-the-bottle",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nu ska varje spelare som yttrar ett svärord antingen ta av ett klädesplagg eller dricka $ klunkar!",key:"cross-word-clothe",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ni kan svära igen utan att riskera att förlora ett klädesplagg",key:"",parent_key:"cross-word-clothe",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nu ska vi alla suga på vår egen, eller någons tumme, när vi inte pratar. I annat fall får vi dricka",key:"fingers-mouth",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ni kan sluta suga på tummen",key:"",parent_key:"fingers-mouth",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nu ska alla dricka varje gång en tjej visar sina bröst! Alla utom hon själv dricker!",key:"show-your-boobs",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Tjejer, sluta flasha pattarna!",key:"",parent_key:"show-your-boobs",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Bulls Eye-leken börjar! Gör vid valfri tidpunkt en cirkel med tumme och pekfinger mellan axlar och höft. Deltagare som tittar på den ska ta av ett klädesplagg eller dricka $ klunkar",key:"round-game-hot",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Bulls Eye-leken är slut!",key:"",parent_key:"round-game-hot",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Färgspelet börjar! Någon rapar, och den som sist nämner en färg dricker $ klunkar, eller tar av ett klädesplagg",key:"gofio-game-hot",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Färgleken är över!",key:"",parent_key:"gofio-game-hot",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ny regel: om man lyckas fånga en annans persons blick samtidigt som man suger på ett finger ska den deltagaren dricka",key:"suck-your-finger",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Sluta suga på fingrarna!",key:"",parent_key:"suck-your-finger",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ny regel! Varje gång vi dricker upp måste vi smeka bröstvårtorna, annars får vi dricka en gång till",key:"caddle-tities",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ni kan sluta ta er på bröstvårtorna",key:"",parent_key:"caddle-tities",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"4",text:"%ss erogena zoner\u0022. Den som först upprepar sig eller inte kommer på något att säga dricker $ klunkar. %s börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, tänk på en sexställning utan att säga vilken. Alla deltagare ska sedan i turordning nämna en. Den som först gissar rätt delar ut $ klunkar. %s börjar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, tänkt på den deltagare i sällskapet du tror är kåtast utan att nämna hen vid namn. Alla deltagare ska sedan i turordning nämna en. Den som först gissar rätt delar ut $ klunkar. %s börjar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, tänk på en sexleksak utan att nämna vilken. Alla deltagare ska sedan i turordning nämna en. Den som först gissar rätt delar ut $ klunkar. %s börjar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"4",text:"En av %ss kroppsdelar som hen gillar\u0022. Den som först upprepar sig eller inte kan komma på något att säga dricker $ klunkar. %s börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Kläder %s har haft på sig i sängen\u0022. Den som först upprepar sig eller inte kan komma på något att säga dricker $ klunkar. %s börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Saker som upphetsar ens partner\u0022. Den som först upprepar sig eller inte kan komma på något att säga dricker $ klunkar. %s börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Saker din partner ska säga för att göra dig kåt\u0022. Den som först upprepar sig eller inte kan komma på något att säga dricker $ klunkar. %s börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Gå laget runt. Alla nämner ett ex/ett gammalt ragg i taget. Den som först får slut på namn dricker $ klunkar. %s, du börjar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Gå laget runt och nämn en kändis med en läckt sexvideo. Den som först får slut på förslag dricker $ klunkar. %s du börjar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Gå laget runt och berätta om platser där %s har haft sex. Den som först får slut på förslag dricker $ klunkar. %s, du börjar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Gå laget runt. Varje person berättar en vanlig fantasi. Den som först får slut på förslag dricker $ klunkar. %s, du börjar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexakter som inte är penetreringssex\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Gå laget runt och visa upp era tatueringar och piercingar, de som inte har några dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"4",text:"Gå laget runt och visa upp ett födelsemärke. Om du inte har något eller vägrar får du dricka $ klunkar. %s börjar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexbomber som har sin egen dokusåpa\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexleksaker\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Starka skäl till att ligga med en främling\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Saker man ska göra som singel innan man går ut\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"TV-kanaler som sänder erotiska filmer\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ställen att ha händerna på under penetreringssex\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Olika slags förspel\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ursäkter till att inte sova kvar hos ett engångsligg\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Typiska platser för fantasier\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Typiska kläder i fantasier\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Arbeten som inbegriper erotik eller sex\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Kondomsmaker\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Olika slags mat som kan hetsa upp en person om den äts på rätt sätt\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Synonymer till \u0022orgasm\u0022\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Ställen man kan bita på för att kåta upp en partner\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Saker som används i S&M\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Kroppsdelar som vanligtvis slickas under sex\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Saker vi vanligtvis gör efter sex\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexfetischer människor kan ha\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Sexhandlingar med tungan\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Olika sätt att få en kvinna att komma\u0022. Den som först får slut på förslag dricker $ klunkar. %s du börjar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, drick upp din drink och använd tänderna till att knäppa upp/dra ned blixtlåset på någons byxor",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, drick upp din drink och nafsa/slicka örat på den mest attraktiva personen i sällskapet",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, drick upp din drink och använd glaset till snurra flaskan\u0022. Pussa den som utpekas på läpparna\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, drick upp %ss drink och gör en sexdans för hen",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, ge %s ett sugmärke, annars måste båda två dricka $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, drick upp din drink och låtsas få %s komma med din mun",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, drick upp din drink och gnid dig mot %s",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s kysser samtliga deltagare och dricker upp valfri drink",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, ge %s en tungkyss eller drick $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, välj någon som ska smeka dig på valfritt ställe medan du avslutar din drink...",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, ta av 3 klädesplagg och drick upp din drink...",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, välj någon att leka med. Få en kyss och ta en klunk om vartannat tills du avslutat personens drink...",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, välj någon som ska ha handen i ditt skrev medan du dricker botten upp, och ja, handen ska befinna sig innanför dina kläder...",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, välj 2 deltagare som ska dricka upp sin drink och tungkyssas...",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, töm glaset för den deltagare du skulle kunna hooka upp med i kväll...",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, töm ditt glas medan någon du väljer smeker dig. Om du är tjej ska brösten smekas, är du kille så... där nedtill...",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Vilken tror ni är bäst på förspel av %s och %s? Vi röstar!. Vinnaren delar ut $ klunkar, förloraren dricker två gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"14",text:"Tjejer, är bröst- eller magmuskler (tuttar och stjärt för killarna) viktigast? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Är du för eller emot att ha engångsligg? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Är du underdånig eller dominant? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Morgonsex eller kvällssex? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Avsugning eller analsex? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Knullkompisar eller seriös relation? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"14",text:"R*im jo*b\u0022 eller grupp*sex? Alla röstar samtidigt förlorarna dricker $ gånger\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Rakat eller orakat? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Stringisar eller trosor? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Bukka*ki eller homosex? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Skulle du helst ha sex 30 ggr på en dag eller inte ha sex under en hel månad? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Skulle du helst kyssa %s eller %s? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"3"},
{cycle_state:"false",type:"14",text:"Skulle du helst ha sex med %s eller %s? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"3"},
{cycle_state:"false",type:"14",text:"Skulle du helst ha en tre*kant eller en femton*kant? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst lapa mus eller suga kuk? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst kunna se igenom kläder, eller vara osynlig? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst ha sex med en kändis eller med den sexigaste person du vet om? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst ha sex med Megan Fox eller Scarlett Johansson? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst ha en perfekt relation med dåligt sex eller en dålig relation med superbt sex? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst aldrig finna den sanna kärleken eller aldrig mer ha sex igen? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Låt oss snacka bröst... Ska de vara stora eller små? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst penetreras av en 10 cm eller en 35 cm lång kuk? Alla röstar samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Nu kryddar vi steken lite... Ska det vara sjuksköterska eller kvinnlig polis? Rösta samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst kyssa din högra eller vänstra granne? Rösta samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst ha sex med din högra eller vänstra granne? Rösta samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Nu kryddar vi steken lite... ska det vara brandman eller soldat? Rösta samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst kunna trolla bort trosor eller topp med en fingerknäppning? Rösta samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst leva en dröm utan några begränsningar under en vecka, eller kunna kåta upp vem som helst när som helst? Rösta samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst ha frikort till en swingerklubb eller till en årlig erotisk show? Rösta samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Är du Är du för eller emot en roll i en porrfilm? Rösta samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Är du för eller emot nudism? Rösta samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Föredrar du att ligga överst eller underst under sexakten? Rösta samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst ha sex med någon i sällskapet eller med en helt okänd främling varje dag under en veckas tid? Rösta samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Skulle du helst ha förspel med en främling eller få 5000 spänn? Rösta samtidigt, förlorarna dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Låt oss övertyga juryn! %s och %s berättar om en av sina fantasier, de andra deltagarna röstar för det mest upphetsande bidraget! Vinnaren delar ut $ klunkar, förloraren dricker två klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Alla röstar om vem som får ligga minst. Den olyckligt lottade ska hädanefter kallas den sexsvultna/sexsvultne\u0022\u0022",key:"horny",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Den sexsvultna/sexsvultne\u0022 du kan dela ut $ klunkar\u0022",key:"",parent_key:"horny",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Alla dricker $ klunkar förutom Sexsvälten\u0022\u0022",key:"",parent_key:"horny",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Den sexsvultna/sexsvultne\u0022 dränk dina sorger i sprit! Drick $ klunkar...\u0022",key:"",parent_key:"horny",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Den idealiska tidslängden för ett ligg. Varje person svarar och trycker på skärmen. %s, du börjar",key:"sex-duration",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"De 3 deltagarna med kortast tidsangivelse dricker $ klunkar!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"De 3 deltagarna med längst tidsangivelse dricker $ klunkar!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, dela ut $ klunkar till deltagarna med längst tidsangivelse. Om du hade det längsta alternativet dricker du $ klunkar",key:"",parent_key:"sex-duration",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, dela ut $ klunkar till deltagarna med kortast tidsangeivelse. Om du hade det kortaste alternativet dricker du $ klunkar",key:"",parent_key:"sex-duration",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Hur många personer har du haft sex med? Varje person svarar och trycker sedan på skärmen. %s, du börjar",key:"number-partner-sex",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s och %s dela ut lika många klunkar som ni har haft ex-partners",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s och %s drick lika många klunkar som ni har haft ex-partners",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Den deltagare som har haft högst antal partners dricker $ klunkar",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Den deltagare som har haft minst antal partners dricker $ klunkar",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Låt oss övertyga juryn! %s och %s berätta om era underligaste drömmar. De andra deltagarna röstar för den mest bisarra drömmen! Vinnaren delar ut $ klunkar, förloraren dricker två gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Hur länge varade din längsta sextorka? Varje deltagare svarar och trycker sedan på skärmen %s, du börjar",key:"abstinence-time",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Deltagaren med den längsta torkan dricker $ klunkar",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Deltagaren med den kortaste torkan dricker $ klunkar",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s och %s dela ut lika många klunkar som antalet månader den varade",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s och %s drick lika många klunkar som antalet månader den varade",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Vad är det mest idealiska antalet sextillfällen per vecka? Varje deltagare svarar och trycker sedan på skärmen %s, du börjar",key:"nb-sexual-rel",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Deltagare som ligger på över 2 gånger tillfällen/vecka dricker $ klunkar, de andra får ta en liten en...",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Deltagare som ligger över 3 tillfällen/vecka dricker $ klunkar, de andra får ta en liten en...",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s och %s delar ut lika många klunkar som de skulle vilja ha sex under en veckas tid",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s och %s dricker lika många klunkar som antalet gånger de skulle vilja ligga under en veckas tid",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Låt oss övertyga juryn! %s och %s berättar om sina värsta sexupplevelser, sedan röstar de övriga för den värsta av dem! Vinnaren delar ut $ klunkar, förloraren dricker två gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Vilken är din favoritställning? Alla svarar, och om några svarar samma sak dricker de $ gånger vardera",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Låt oss övertyga juryn! %s och %s berätta om den minst sexiga sak en partner skulle kunna yttra under sexakten, sedan röstar de övriga för det värsta alternativet! Vinnaren delar ut $ klunkar, förloraren dricker två gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Låt oss övertyga juryn! %s och %s säg den bästa saken man kan säga för att kåta upp ens partner, sedan röstar de övriga för den bästa av dem! Vinnaren delar ut $ klunkar, förloraren dricker två gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Ni får ha sex i 5 minuter med vem som helst och var man vill innan man dör. %s och %s ger varsitt förslag, sedan röstar de övriga för det mest lockande förslaget! Vinnaren delar ut $ klunkar, förloraren dricker två gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Låt oss övertyga juryn! %s och %s berättar om sina bästa sexupplevelser, sedan röstar de övriga för den coolaste av dem! Vinnaren delar ut $ klunkar, förloraren dricker två gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Låt oss övertyga juryn! %s och %s berättar om en ovanlig plats de har haft sex på, sedan röstar de övriga för den coolaste platsen! Vinnaren delar ut $ klunkar, förloraren dricker två gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Gå laget runt, drink $ gånger och berätta om vem du vill ha sex med i natt",key:"who-u-wanna-fuck",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Ifall %s omnämndes, kan hen kyssa en av de deltagare som nämnde hens namn på munnen. Drick i annat fall $ gånger",key:"",parent_key:"who-u-wanna-fuck",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Gå laget runt och kyss samtliga på munnen. De som vägrar dricker $ gånger. %s börjar!",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Gå laget runt och välj någon som måste ta dig i skrevet. $ klunkar för varje som vägrar. %s, du börjar!",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Gå laget runt och välj någon som måste ta av ett klädesplagg. $ för varje som vägrar. %s börjar!",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Låt oss spela en runda snurra flaskan\u0022! Varje spelare snurrar flaskan och kysser deltagaren den pekar på. $ klunkar för varje som vägrar. %s börjar!\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Kalsongtävling! Tjejer ni är jury, förloraren får $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Bh-tävling! Grabbar ni är juryn, vinnaren delar ut $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Kyssparty! Gå laget runt och kyss höger eller vänster granne, eller drick $ klunkar. %s börjar!",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Sensuell stund! Gå laget runt och ta personen till höger i skrevet, eller drick $ klunkar, %s börjar!",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Sensuell stund! Gå laget runt och ta personen till vänster i skrevet, eller drick $ klunkar, %s börjar!",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Sensuell stund! Gå laget runt och ta personen till vänster på bröstet, eller drick $ klunkar, %s börjar!",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Sensuell stund! Gå laget runt och ta personen till höger på bröstet, eller drick $ klunkar, %s börjar!",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Svår fråga! Turas om och fråga någon om någon snuskig sak. Om personen inte vill svara dricker hen $ gånger. %s börjar!",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Stjärttävling: Grabbar, gå i parad. Tjejer, ni är jury. Segraren delar ut $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, lägg en blindkavle över ögonen och låt 2 deltagare kyssa dig var de vill. Om du gissar vilken en av de två deltagarna är får du dela ut $ klunkar. Du får bara en chans!",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, lägg en blindkavle över ögonenm och ät upp vad nu någon deltagare placerar på sin mage. Om du gissar rätt på vad det är får du dela ut $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Hårdoftningstävling! Tjejer är tävlande och killarna jury. Segrarinnan delar ut $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Drick $ klunkar om du någon gång har haft sex på offentlig plats",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har haft en trekant dricker $ klunkar. Drick dubbelt upp om alla tre deltagarna dessutom befinner sig i rummet just nu!",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har haft Skype-sex dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har haft sex med någon annan i tankarna dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som skulle kunna ligga med någon annan som är närvarande just nu dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har haft sex på första dejten dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som älskar oralsex dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har spelat in ett sexvideoklipp dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som tror %s är ett bra ligg dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alla som har gett någon ett r*im j*ob\u0022 dricker $ klunkar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har blivit påkomna när de har onanerat dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som rakar sina intima områden dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har varit inne på en porrsajt under de senaste två veckorna dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som gillar snuskprat dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har använt rollspel som sexhjälpmedel dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har legat med någon utan att komma ihåg personens namn dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"All som någon gång har haft sex på ett hotell dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som inte har haft bilsex dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som inte har haft sex denna vecka dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har haft sex med en minst 5 år äldre person dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har haft sex med en minst 5 år yngre person dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har sextat\u0022 (skickat sex-textmeddelanden) med någon dricker $ klunkar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång inte har fått upp den under ett samlagstillfälle dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har haft sex med någon annan i rummet dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, dela ut $ klunkar om du har haft sex fler än 4 ggr under en dag. I annat fall får du dricka $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har fantiserat om en väns partner dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har skickat sexfoton till någon dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har slickat, eller ätit någon slags mat från en annan persons kropp, dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har skrikit ut sin partners namn under sexakten dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har fått en orgasm på mindre än 3 minuter dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har haft sex under sin eller sin partners menstruation dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Vem är bäst i sängen av %s och %s? Segraren tar $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Alla som har haft en uteslutande sexuell relation med en vän/väninna dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som tyckte första gången gjorde ont som satan dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, om du någon gång har varit hemligt förälskad i %s dricker ni båda två $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har stuckit in ett föremål i sin partners kropp under sexakten dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har använt en dejtingsajt dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har fått ligga tack vare en dejtingsajt dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltagare som sist besökte en porrsajt dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltagare som har fått ligga mest tack vare en dejtingsajt delar ut $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har blivit klösta under sexakten dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har hållit i en sexleksak dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har använt föremål under sexakten dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har blivit upphetsade av professionell massage dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har använt saliv för oralsex med sin partner dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har sugit av någon under den senaste månaden dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har sugit av någon denna vecka dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har haft något föremål i sitt anus eller i sin vagina dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla snuskhumrar som har förolämpat sin partner under sexakten dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har sett en vän vara otrogen mot sin partner dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har dejtat en kompis ex dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, dela ut $ klunkar om ni använde kondom sista gången du hade sex, annars får du dricka dem själv",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alla som gillar att någon tittar på under sexakten dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har kn*ullat till en porrfilm dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som gillar tanken på att (kanske ännu en gång) kn*ulla till en porrfilm dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som är sugna på att sex just i detta nu dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som tycker om att få sitt anus smekt under sexakten dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som tycker om att leka med sin partners anus under penetreringen dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som tycker om att smiska eller få smisk på stjärten dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla snuskhumrar som har haft sex med både tjejer och killar dricker $ klunkar N",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Hörni brudar! Drick $ klunkar om ni någon gång har fått fontänorgasmer",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Drick $ klunkar om ni har fått anal orgasm...",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har kryddat sex med att klä ut sig dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har tittat på när andra haft sex dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som de tre senaste gånger hade sex med knu*llkompisar dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någonsin gett en massage som vidareutvecklades till något mycket mer angenämt dricker $ klunkar...",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någonsin har fått en massage som vidareutvecklades till något mycket mer angenämt dricker $ klunkar...",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som tror att de aldrig kommer att pröva nåt verkligen nytt på det sexuella området, dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, slicka en kroppsdel på den deltagare som %s väljer ut",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har kn*ullat inför andra människor dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har deltagit i en partnerbyte-/swingerfest dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har onanerat inför sin partner dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har onanerat med en kollega i tankarna delar ut $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har onanerat medan hen har tänkt på en icke-pornografisk film dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har haft förspel mellan penetreringar dricker $ gånger",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla tjejer som inte kan twerka\u0022 dricker $ klunkar\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har fantiserat om en annan närvarande speldeltagare dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltagare som sist hade sex tar av ett klädesplagg",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har kn*ullat i en kompis säng utan att de har fått reda på det dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har haft förspel med en isbit inblandad dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har haft förspel med ett tuggummi i munnen delar ut $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har blivit fotade nakna dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som inte har trosor på sig nu dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som föredrar förspel framför penetreringssex dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som gillar hårda tag dricker $ klunkar...",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som tycker förspel är obligatoriskt dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, dela ut $ klunkar om du låg med någon för första gången innan du var 17 år",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, om du hade en sexig chef; skulle du då ligga med hen för att främja din karriär? Drick $ klunkar vid ja\u0022 dela ut $ klunkar vid \u0022nej\u0022\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, skulle du ligga med en ful, äldre person för 1,5 miljoner kronor? Drick $ klunkar vid ja\u0022 dela ut $ klunkar vid \u0022nej\u0022\u0022",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har testat att gå till en swingerklubb dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har fejkat en orgasm dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltagare som sist gav en skön avsugning delar ut $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Den deltagare som sist utförde en passionerad cunnilingus delar ut $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har slickat mus för mindre än en månad sedan dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som har slickat mus för mindre än en vecka sedan dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har sugit av sin pojkvän för att väcka honom dricker $ klunkar. Samma gäller för män som någon gång har blivit väckta av en avsugning",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har smekt en intim del med fötterna dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, dela ut $ klunkar om du skulle förlåta dina partner för att ha varit otrogen en gång. Drick dem annars själv",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alla som har erotiska tillbehör dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har tungkyssts med två olika personer under samma kväll dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som skulle vilja se sina partner ha sex med någon annan dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som sammantaget har haft mer sex i mörker än i ljus dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har köpt något från en sexbutik dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, delat ut $ klunkar om du tycker att du är attraktiv. Drick dem om du är ful",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alla som har legat med någon som inte har känt till ens namn dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, drick $ klunkar om främmande människor har sett dig ha sex. Dela i annat fall ut $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alla som har haft fyllesex dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, drick $ klunkar om du någon gång har kysst någon du tyckt varit motbjudande. Dela i annat fall ut $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alla som tror sig kunna få bordsgrannen till höger att komma inom 10 minuter dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Drick $ klunkar om du tror att din vänstra granne kommer att ha sex med en annan deltagare innan nästa dag gryr",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som inte hade en bra första sexupplevelse dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som en person av samma kön har flörtat med dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har haft erotiska drömmar om en person i sällskapet dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som tycker om att bli bitna i brösten dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, dela ut $ klunkar om du tror dig ha mest sexerövringar i sällskapet. Drick dem i annat fall",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Alla som tycker ett antal andra deltagare är attraktiva dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Alla som någon gång har haft sex med någon på grund av en dejting-app dricker $ klunkar",key:"",parent_key:"",pack_name:"hot",language:"sv",nb_players:"0"}])