var db = TAFFY([{cycle_state:"false",type:"1",text:"%s, se és uma rapariga, lambe o dedo de maneira erótica. Se és um homem, faz um cunilíngua com 2 dedos. E/ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, simula um orgasmo durante 10 segundos",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Todas as raparigas devem puxar para fora o seu fio dental",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s e %s fazem carícias um ao outro e bebem ambos um gole",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s deixa que %s te chupe o dedo ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"As pessoas que têm uma camisa vestida, desabotoam-na e bebem um gole por botão",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s tira uma peça de roupa a %s ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, de quantos copos precisas para ir para a cama com %s? Responde e bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, de entre todas as pessoas do jogo, quem é, na tua opinião, a que chu** melhor? Responde e bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s dá $ goles à pessoa mais sexy",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s simula sexo de quatro durante 5 segundos ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, diz algo sexual que nunca fizeste, aqueles/aquelas que já o fizeram bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, se mostrares um mamilo, %s bebe $ goles, caso contrário, bebes tu $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s, %s e %s fazem sexo em grupo ou bebem todos $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"4"},
{cycle_state:"false",type:"1",text:"%s escolhe entre beber $ goles ou beijar os pés de %s",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, se deres um beijo a %s, toda a gente bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Bebam o número de orgasmos que tiveram esta semana, em número de goles. A masturbação conta.",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Se %s e %s derem um beijo na boca, cada um distribui $ goles, caso contrário, toda a gente bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"O primeiro jogador a mostrar um sexting distribui $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, se ir para a cama com %s não é para ti um problema, distribui $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, belisca os mamilos de %s ou, então, ele/ela bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s lambe o nariz de %s ou bebe $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, faz uma massagem craniana a %s ou bebe $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, deixa %s apalpar-te o sexo ou, então, bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, dá um beijo no nariz de %s ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s escolhe duas pessoas que se vão beijar ou beber $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"3"},
{cycle_state:"false",type:"1",text:"%s, preferes sexo oral, anal ou vaginal? Responde e bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Aquelas e aqueles que já foram insultados durante o ato sexual bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, lambe a boca de um dos jogadores ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lambe a língua de um dos jogadores ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Toda a gente bebe $ goles. Exceto %s, que vai dar um beijo a toda a gente",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, dá um beijo a %s ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, escolhe entre dar um beijo a uma pessoa à tua escolha e beber $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, despe uma peça de roupa a %s ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, faz passar uma pedra de gelo a %s, de boca em boca, ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, começa por beber $ goles. Se és um homem, descreve o broche ideal para ti. Se és uma mulher, conta-nos como os fazes",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, começa por beber $ goles. Se és uma mulher, descreve o cunilíngua ideal para ti. Se és um homem, conta-nos como os fazes",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe a pessoa que terá de lamber uma parte do teu corpo. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s deve tocar levemente nos mamilos de um jogador. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s deve deixar que um jogador à escolha lhe toque levemente nos mamilos. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, beija o torso de um jogador ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deixa um jogador à escolha beijar-te o peito/o torso. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, se és um rapaz, coloca-te por trás de uma jogadora e acaricia-lhe os seios; escolhe o rapaz que te vai acariciar os seios se és uma rapariga… $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe o jogador que te fará uma lap dance. $ goles se ele ou ela recusar",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, acaricia o rabo de um jogador durante 5 segundos, $ goles se ele ou ela recusar!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deixa um jogador à escolha acariciar-te o rabo durante 5 segundos. Bebe $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, olha nos olhos a pessoa com a qual serias capaz de ir para a cama esta noite, essa pessoa deve beber $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe quem vai beber enquanto lhe acaricias as partes íntimas",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, mostra uma fotografia tua em topless ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, mordisca a orelha de um jogador ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe 2 pessoas que devem beijar-se com a língua, a pessoa que recusar bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe quem deve mostrar um mamilo… $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, mostra uma parte íntima do teu corpo ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe um jogador que terá de mostrar uma parte íntima do seu corpo. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, mima uma posição sexual com um dos jogadores ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe dois jogadores, os quais terão de mimar uma posição sexual e beber ao mesmo tempo $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, esfrega a cabeça nas partes íntimas de alguém. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe um jogador que terá de esfregar a cabeça contra as tuas partes íntimas. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe um jogador que terá de abanar a cabeça nos seios de uma jogadora. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lambe lentamente as partes íntimas de alguém. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe alguém que terá de te lamber lentamente as partes íntimas. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, acaricia as partes íntimas de alguém ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe alguém que terá de te acariciar as partes íntimas. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe alguém que terá de passar a mão por baixo da tua roupa interior. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deves passar a mão por baixo da roupa interior de alguém. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, faz passar um alimento da tua boca para a boca de outra pessoa. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe dois jogadores, os quais terão de trocar um alimento boca a boca. $ goles para ambos em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, toca nos seios de uma rapariga. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Toda a gente bebe e despe uma peça de roupa!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, escolhe quem deve despir uma peça de roupa. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, desafia um jogador a desapertar o sutiã de uma jogadora. Se não conseguir fazê-lo em 5 segundos, o jogador designado bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deixa um jogador à escolha beliscar-te os mamilos ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, belisca o rabo de um jogador à escolha. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deixa um jogador à escolha beliscar-te o rabo ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lambe os lábios de um jogador à escolha. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deixa um jogador à escolha lamber-te os lábios. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe o jogador que terá de te mostrar uma das suas partes íntimas. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, mostra uma das tuas partes íntimas ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lambe os mamilos de um jogador à escolha. $ goles em caso de recusa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deixa um jogador à escolha lamber-te os mamilos ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Para os homens, dispam uma peça de roupa ou bebam $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Para as miúdas, dispam uma peça de roupa ou bebam $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Para os homens, fiquem em tronco nu ou bebam $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Para as miúdas, fiquem de sutiã ou bebam $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, vai despir a roupa interior e volta. Ou escapa e acaba o teu copo",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe uma letra. Todos os jogadores que já foram para a cama com uma pessoa cujo nome começa por essa letra bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, massaja os pés de um jogador à tua escolha durante 2 minutos, ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deixa o jogador que quiseres massajar-te uma parte do corpo à tua escolha durante 2 minutos. Qualquer recusa acarreta $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lambe à volta do umbigo de um jogador à tua escolha, ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deixa o jogador que quiseres lamber-te à volta do umbigo. Qualquer recusa acarreta $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, faz um chupão à quem quiseres ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deixa quem quiseres fazer-te um chupão onde preferires, essa pessoa pode recusar em troca de $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Quem tiver o peito maior designa um rapaz para lhe lamber os seios, ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, mostra o rabo ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, escolhe uma parte do teu corpo. O primeiro jogador a tocar nela distribui $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, mostra os seios ou bebe $ goles. Se és um homem, podes distribuir $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Designem em conjunto a pessoa mais flexível, a qual deverá comprová-lo e beber $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, dá um beijo no pescoço de quem quiseres ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Vamos lá pôr as coisas em prato limpo! Aqueles que já curtiram juntos beijam-se novamente ou bebem ambos $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, deixa uma pessoa à tua escolha dar-te um beijo no pescoço ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, envia um sexting a uma pessoa escolhida pela equipa. Se esta pessoa entrar no jogo, podes distribuir um shot!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, distribui $ goles à pessoa com quem %s tem mais probabilidade de ir para a cama",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, bebe tantos goles quantas pessoas com quem foste para a cama nos últimos 6 meses",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"1",text:"O primeiro jogador, de entre %s e %s, a tocar no sexo de outro jogador distribui $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Se gostavas de beijar o teu vizinho ou a tua vizinha da esquerda levanta a mão. Os outros bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s e %s, leiam o primeiro SMS que aparece ao introduzir sexo\u0022 na barra de pesquisa. Podem recusar em troca de $ goles\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s e %s, leiam o primeiro SMS que aparece ao introduzir gaita\u0022 na barra de pesquisa. Podem recusar em troca de $ goles\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s e %s, leiam o primeiro SMS que aparece ao introduzir broche\u0022 na barra de pesquisa. Podem recusar em troca de $ goles\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s deve agora ter um orgasmo antes de cada gole",key:"orgasm-simulation",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s já não tem de ter um orgasmo antes de cada gole",key:"",parent_key:"orgasm-simulation",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, escolhe alguém e olha-o(a) fixamente nos olhos. Quando for para parar, avisamos-te",key:"look-in-the-eyes",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, podes parar de olhar fixamente nos olhos do/a teu (tua) amigo(a)!",key:"",parent_key:"look-in-the-eyes",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, coloca-te de gatas, com as costas bem arqueadas. Quando for para parar, avisamos-te",key:"doggy-style-way",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s pode colocar-se novamente numa posição confortável",key:"",parent_key:"doggy-style-way",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s trabalha na PSP! Podes efetuar uma busca corporal a quem quiseres, quando quiseres; a pessoa alvo da busca pode recusar por $ goles",key:"body-search",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s já não trabalha na PSP e esta ignóbil pessoa repugnante vai ter de beber $ goles",key:"",parent_key:"body-search",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s é o Cupido! Ele/Ela escolhe quem se beija e quem se acaricia quando ele/ela quiser, caso contrário $ goles",key:"cupidon",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s já não é o Cupido",key:"",parent_key:"cupidon",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s está mesmo a precisar… ele ou ela tem de beijar uma pessoa antes de beber",key:"kiss-before-drink",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s curou a sua mania dos beijos!",key:"",parent_key:"kiss-before-drink",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s segura, de forma apaixonada, a mão de %s até nova ordem",key:"hold-hand",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s e %s podem largar-se",key:"",parent_key:"hold-hand",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s escolhe uma pessoa que terá de lhe massajar a mão! Quando for para parar, avisamos",key:"hand-massage",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s para de se fazer massajar a mão",key:"",parent_key:"hand-massage",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s é irresistível! Sempre que pedires um beijo (na boca ou noutro sítio), a pessoa eleita deve obedecer ou beber",key:"irresistible",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s é novamente feio(a)",key:"",parent_key:"irresistible",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s e %s, façam pezinho um ao outro até nova ordem",key:"naughty-feet",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s e %s podem parar de se acariciar",key:"",parent_key:"naughty-feet",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s tem de escolher alguém que ficará com a mão sob o seu rabo até nova ordem",key:"hand-under-ass",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s pode libertar o/a atrevido/a!",key:"",parent_key:"hand-under-ass",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s tem de colocar a mão sobre a coxa de um jogador até nova ordem",key:"put-your-hand-on-legs",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s pode tirar a mão!",key:"",parent_key:"put-your-hand-on-legs",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"Pequeno jogo! Sempre que %s toca num copo, %s deve mimar um orgasmo extremo. $ goles sempre que falhar!",key:"touch-glass-and-cum",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s e %s param o seu pequeno jogo divertido",key:"",parent_key:"touch-glass-and-cum",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, escolhe, a qualquer momento, 2 jogadores, um deles senta-se nos joelhos do outro. $ goles por cada recusa",key:"on-sby-knees",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, já não podes escolher quem se senta sobre quem",key:"",parent_key:"on-sby-knees",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, tens os lábios envenenados! Se conseguires dar um beijo a um jogador antes do fim do vírus sem o forçar, esse jogador terá de beber o seu copo até ao fim!",key:"kiss-poison",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, já não tens beijos envenenados! Se não conseguiste, bebe $ goles",key:"",parent_key:"kiss-poison",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, tens as mãos envenenadas! Se conseguires fazer uma carícia a um jogador antes do fim do vírus sem que este se aperceba, este jogador terá de beber o seu copo até ao fim!",key:"caddle-poison",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, já não tens carícias envenenadas! Se não conseguiste, bebe $ goles",key:"",parent_key:"caddle-poison",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"3",text:"Agora têm de acariciar o peito sempre que falarem!",key:"caress-boobs",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Podem parar as carícias para falar!",key:"",parent_key:"caress-boobs",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"É agora possível jogar novamente os seus goles ao jogo da garrafa! Em vez de beber, rodar a garrafa e beijar o jogador designado, se recusar, bebe a dobrar!",key:"spin-the-bottle",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"O jogo da garrafa chegou ao fim!",key:"",parent_key:"spin-the-bottle",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"A partir de agora, sempre que alguém disser um palavrão deve despir uma peça de roupa ou beber $ goles!",key:"cross-word-clothe",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Podem novamente dizer palavrões sem receio de perder uma peça de roupa",key:"",parent_key:"cross-word-clothe",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Agora é obrigatório chupar o dedo, ou o de outra pessoa, se ninguém falar",key:"fingers-mouth",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Podem parar de chupar o dedo",key:"",parent_key:"fingers-mouth",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"A partir de agora, sempre que uma rapariga mostrar o peito toda a gente bebe!",key:"show-your-boobs",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Miúdas, deixem de mostrar o peito",key:"",parent_key:"show-your-boobs",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Jogo do círculo! Quando quiserem, façam um círculo com o polegar e o indicador entre a cinta e o ombro, os jogadores que olharem para ele têm de despir uma peça de roupa ou beber $ goles",key:"round-game-hot",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"O jogo do círculo acabou!",key:"",parent_key:"round-game-hot",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nova regra, jogo do arroto a decorrer (alguém arrota, o último que disser Shrek perde)! A cada partida, quem perder despe uma peça de roupa ou bebe um gole",key:"gofio-game-hot",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"O jogo do arroto acabou!",key:"",parent_key:"gofio-game-hot",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nova regra: se o seu olhar cruzar o de outro jogador enquanto estiver a chupar o dedo, este último bebe",key:"suck-your-finger",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Parem de fazer gestos atrevidos uns aos outros",key:"",parent_key:"suck-your-finger",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nova regra! Sempre que acabam de beber devem acariciar os mamilos, caso contrário, voltam a beber",key:"caddle-tities",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Já não têm de acariciar os mamilos",key:"",parent_key:"caddle-tities",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"4",text:"As zonas erógenas de %s\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles. %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, pensa numa posição sexual. Os restantes jogadores vão tentar adivinhar, um de cada vez, sendo que o primeiro a adivinhar distribui $ goles. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, pensa numa prática sexual além da penetração. Os restantes jogadores vão tentar adivinhar, um de cada vez, sendo que o primeiro a adivinhar distribui $ goles. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, pensa num jogador presente que, na tua opinião, é o mais hot na cama. Os restantes jogadores vão tentar adivinhar de quem se trata, um de cada vez, sendo que o primeiro a adivinhar distribui $ goles. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, pensa num sex toy. Os restantes jogadores vão tentar adivinhar, um de cada vez, sendo que o primeiro a adivinhar distribui $ goles. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"4",text:"As partes do corpo de %s que ele ou ela gosta\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"4",text:"As roupas com as quais %s já dormiu\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"4",text:"O que vos excita no(a) vosso(a) parceiro(a)\u0022 a pessoa que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"As frases que excitam na cama\u0022 a pessoa que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Os vossos ex-parceiros sexuais, se repetires um nome que já foi dito ou se tiveres acabado, bebe $ goles. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Nova tema e $ goles em jogo: pessoas célebres que já fizeram uma sex tape\u0022. %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Jogo dos temas e $ goles em jogo: os locais onde %s já fod*u\u0022. %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Jogo dos temas e $ goles em jogo: as fantasias comuns\u0022. %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Novo tema e $ goles em jogo: as práticas sexuais\u0022 (penetração etc.). %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Um de cada vez, mostrem todas as vossas tatuagens e piercings, os que não têm nenhum bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"4",text:"Um de cada vez, mostrem um sinal de nascença e distribuem $ goles. Se não tiveres nenhum, bebe $ goles. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"As bombas sexuais que participaram num reality-show\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Os sex toys\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"As razões para ir para cama com um desconhecido\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"As coisas que é preciso fazer antes de sair à noite quando somos solteiros\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Os canais de televisão que transmitem filmes eróticos\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Os sítios onde meter as mãos durante a penetração\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Os preliminares\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"As desculpas para não ficar a dormir depois de uma queca ocasional\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Os locais frequentes nas fantasias\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Os disfarces frequentes nas fantasias\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"As profissões relacionadas com o erotismo ou o sexo\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Os perfumes de preservativos\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Os alimentos que podem despertar o desejo de ter sexo se forem comidos de uma determinada maneira\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Os sinónimos de \u0022ter um orgasmo\u0022\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Os sítios a mordiscar para excitar o/a parceiro(a) sexual\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Os objetos que servem numa relação sadomasoquista\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"As partes do corpo que são agradáveis lamber durante as relações sexuais\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"As coisas que fazemos geralmente após fazer amor\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"As coisas pelas quais podemos ser um fetichista sexual\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"As práticas sexuais que se fazem com a língua\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Os meios de dar prazer a uma mulher\u0022 o jogador que não encontrar ou repetir uma resposta bebe $ goles! %s começas tu\u0022",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, acaba o teu copo e vai abrir a braguilha da pessoa que quiseres com os dentes",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, acaba o teu copo e vai mordiscar/lamber a orelha da pessoa que te atrai mais",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, acaba o teu copo e vai beijar a pessoa que quiseres (nos lábios)",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, faz uma dança sexy à/ao %s após acabares o teu copo",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, faz um chupão à/ao %s ou, então, ambos bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s acaba o seu copo e faz como se estivesse a chupar/lamber %s",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s dá um beijo a cada jogador e acaba o copo que quiser!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, beija %s com a língua ou bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, escolha a pessoa que irá acariciar-te enquanto acabas o teu copo…",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, despe 3 peças de roupa e acaba o teu copo…",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, escolhe uma pessoa com a qual vais jogar. Vão beber um gole e, em seguida, beijar-se, até ambos acabarem os copos respetivos…",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, escolha uma pessoa que tem de pousar a mão no teu sexo enquanto acabas o teu copo. A mão dentro da roupa interior…",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, escolhe dois jogadores que vão acabar os seus copos e, em seguida, beijar-se com a língua…",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, acaba o copo do jogador com o qual eras capaz de ir para a cama esta noite…",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, vais acabar o teu copo enquanto outro jogador, à escolha, te acaricia. Se és uma rapariga, terá de te acariciar o peito, se és um homem, terá de te acariciar o pénis.",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Quem, entre %s e %s, é, na vossa opinião, o melhor parceiro no que diz respeito a preliminares? Votem todos ao mesmo tempo, quem obtiver mais votos distribui $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"14",text:"Mais vale peitorais (seios para os rapazes) ou abdominais (rabo para os rapazes)? Votem todos ao mesmo tempo, quem perder bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"14",text:"A favor ou contra o sexo ocasional? Votem todos ao mesmo tempo, pondo a mão no ar, as pessoas em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"No que toca a mamas, mais vale enormes ou pequeníssimas? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale submisso(a) ou dominado(a)? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Mais vale broche ou sodom**? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Mais vale uma aventura ou uma história séria? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Mais vale anilíng*a ou orgia? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Mais vale depilação brasileira ou sem pelos? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Mais vale fio dental ou shorty? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Mais vale bukkak* ou sodom**? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Mais vale 30 quecas num só dia ou nenhuma durante um mês? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Mais vale beijar %s ou %s? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"14",text:"Mais vale uma queca com %s ou com %s? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"14",text:"Mais vale um ménage a 3 ou uma orgia com 8? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale um cunilíngua ou um broche? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale ver através da roupa ou ficar invisível? Votem um de cada vez, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale ir para a cama com uma celebridade ou com a pessoa mais sexy que conhecem? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale Megan Fox ou Scarlett Johansson? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale uma relação perfeita mas sexualmente deprimente ou uma relação horrível mas sexualmente incrível? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale nunca encontrar o amor ou nunca mais ter relações sexuais? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale ter (ou brincar com) um pénis de 9 cm ou com um de 36 cm? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"As malandrices, mais vale de manhã ou à noite? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Para o sexo, mais vale disfarçar-se de enfermeira ou de polícia? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale beijar o seu vizinho da direita ou o da esquerda? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale uma queca com o seu/a sua vizinho(a) da direita ou o/a da esquerda? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Para o sexo, mais vale disfarçar-se de bombeiro ou de polícia? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale ter o poder de estalar os dedos para fazer desaparecer as calças ou a parte de cima? Votem todos ao mesmo tempo, os que estiverem em minoria bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale viver um sonho acordado e não ter qualquer limite durante uma semana ou ter o poder de fazer com que qualquer pessoa te deseje sexualmente durante toda a vida? Votem todos ao mesmo tempo, os que perderem bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale ter uma assinatura num clube de swing ou num salão do erotismo? Votem todos ao mesmo tempo, os que perderem bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"A favor ou contra participar num filme porno? Votem todos ao mesmo tempo, os que perderem bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"A favor ou contra o nudismo? Votem todos ao mesmo tempo, os que perderem bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"A favor ou contra a troca de casais? Votem todos ao mesmo tempo, os que perderem bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Preferes, durante o ato sexual, que a rapariga esteja por cima ou por baixo? Votem todos ao mesmo tempo, os que perderem bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale ir para a cama com alguém desta mesa ou com uma pessoa desconhecida, escolhida aleatoriamente, durante uma semana? Votem todos ao mesmo tempo, os que perderem bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Mais vale ter preliminares com um dos jogadores aqui ou ganhar 500 euros? Votem todos ao mesmo tempo, os que perderem bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Convençam o júri! %s e %s contam uma das suas fantasias, os jogadores votam pela mais tórrida! O vencedor distribui $ goles, o outro jogador bebe-os",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Designa a pessoa que mais precisa de sexo e, sem seguida, clica no ecrã",key:"horny",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"A pessoa designada distribui $ goles",key:"",parent_key:"horny",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Toda a gente bebe $ goles exceto a pessoa designada",key:"",parent_key:"horny",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"A pessoa designada pode afogar as mágoas no álcool e bebe $ goles (Esta noite não vais engatar)",key:"",parent_key:"horny",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"A duração ideal para uma queca. %s começa (o resto vem aí…)",key:"sex-duration",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Os 3 jogadores mais abaixo bebem $ goles!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Os 3 jogadores mais acima bebem $ goles!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, distribui $ goles aos jogadores que indicaram a duração maior. Se foste tu, bebe $ goles",key:"",parent_key:"sex-duration",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, distribui $ goles aos jogadores que indicaram a duração mais pequena. Se foste tu, bebe $ goles",key:"",parent_key:"sex-duration",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Quantos parceiros sexuais já tiveram? Cada um responde, o resto vem aí… %s, começas tu",key:"number-partner-sex",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s e %s distribui tantos goles quantos parceiros sexuais!",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s e %s bebem tantos goles quantos parceiros sexuais!",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"O jogador que mais parceiros teve bebe $ goles",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"O jogador que menos parceiros teve bebe $ goles",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Têm de convencer o júri! %s e %s contam um sonho de sexo bizarro que já tiveram, os outros jogadores votam pelo mais improvável! O vencedor distribui $ goles, o outro bebe-os",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"O vosso período de abstinência mais longo após a primeira relação. Cada um responde, o resto vem aí… %s, começas tu",key:"abstinence-time",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"O jogador com o período maior bebe $ goles!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"O jogador com o período maior distribui $ goles!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s e %s distribui tantos goles quantos meses de abstinência!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s e %s bebem tantos goles quantos meses de abstinência!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"O número ideal de relações sexuais por semana na vossa opinião. Cada um responde, o resto vem aí… %s, começas tu",key:"nb-sexual-rel",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"As pessoas com mais de 2 bebem $ goles, os outros bebem um pequeno gole",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"As pessoas com menos de 3 bebem $ goles, os outros bebem um pequeno gole",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s e %s distribuem tantos goles quantas relações sexuais!",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s e %s bebem tantos goles quantas relações sexuais!",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Convençam o júri! %s e %s contam uma das suas piores relações sexuais, os outros jogadores votam para escolher a pior de todas! O vencedor distribui $ goles, o outro jogador bebe-os",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Qual é a vossa posição sexual preferida? Cada um responde, os que indicarem a mesma posição bebem $ goles juntos",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Convençam o júri! %s e %s referem a coisa menos sexy de se ouvir durante o sexo, os outros jogadores votam para escolher a pior delas! O vencedor distribui $ goles, o outro jogador bebe-os",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Convençam o júri! %s e %s referem a melhor coisa a fazer para excitar o seu/a sua parceiro/a, os outros jogadores votam para escolher a mais excitante! O vencedor distribui $ goles, o outro jogador bebe-os",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Têm direito a 5 minutos de sexo antes de morrer, com qualquer pessoa, em qualquer sítio. %s e %s propõem uma escolha, os outros jogadores votam para escolher a melhor sugestão. O vencedor distribui $ goles, o outro jogador bebe-os",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Convençam o júri! %s e %s contam um dos melhores engates da sua vida, os outros jogadores votam para escolher o mais excitante! O vencedor distribui $ goles, o outro jogador bebe-os",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Convençam o júri! %s e %s referem um dos sítios insólitos onde já fod**te, os outros jogadores votam para escolher o mais improvável! O vencedor distribui $ goles, o outro jogador bebe-os",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Um de cada vez, bebam $ goles e digam com quem, nesta sala, prefeririam ir para a cama.",key:"who-u-wanna-fuck",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, se foste indicado(a), vai beijar a pessoa que te mencionou. Caso contrário, bebe $ goles",key:"",parent_key:"who-u-wanna-fuck",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Um de cada vez, vão beijar uma pessoa. Aqueles que recusarem bebem $ goles. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Um de cada vez, escolham alguém que terá de tocar-vos nas partes íntimas. Se a pessoa escolhida recusar, terá de beber $ goles. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Um de cada vez, escolham alguém que terá de despir uma peça de roupa. Se a pessoa escolhida recusar, terá de beber $ goles. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Toca a girar a garrafa! Cada jogador faz girar a garrafa e beija a pessoa designada, $ goles para quem recusar. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Concurso de boxers! As raparigas são o júri, quem perder bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Concurso de sutiã! Os rapazes são o júri, quem perder bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Kiss party! Um de cada vez, vão beijar o vizinho ou a vizinha da esquerda ou, então, bebem $ goles. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Apalpar a ratinha da vizinha! Um de cada vez, vão apalpar as partes íntimas do(a) vizinho(a) da direita ou, então, bebem $ goles. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Apalpar a ratinha da vizinha! Um de cada vez, vão apalpar as partes íntimas do(a) vizinho(a) da esquerda ou, então, bebem $ goles. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Apalpar a ratinha da vizinha! Um de cada vez, vão apalpar o peito do(a) vizinho(a) da direita ou, então, bebem $ goles. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Apalpar a ratinha da vizinha! Um de cada vez, vão apalpar o peito do(a) vizinho(a) da esquerda ou, então, bebem $ goles. %s, começas tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Concurso de rabos: rapazes, toca a desfilarem! As raparigas são o júri, o vencedor pode distribuir $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, deixa que te vendem os olhos, e 2 jogadores vão dar-te um beijo em qualquer sítio. Se adivinhares quem é um dos dois jogadores, distribui $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, deixa que te vendem os olhos, um jogador vai pôr comida em cima da sua barriga e vais ter de comer essa comida. Se adivinhares o que é, distribui $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Concurso de perfume de cabelos! As raparigas jogam, os rapazes vão ser o júri. A vencedora pode distribuir $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aqueles e aquelas que já fizeram amor num local público bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aqueles/Aquelas que já fizeram um ménage à 3 bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"As pessoas que já fizeram sexo virtual distribuem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aquelas que já pensaram noutra pessoa durante o ato distribuem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aqueles/Aquelas que gostariam de ter relações com uma pessoa presente na sala bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já foste para a cama na primeira noite",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"As pessoas que adoram felaçõ** bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aqueles/Aquelas que já se filmaram enquanto faziam amor distribuem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"As pessoas que pensam que %s deve ser bom (boa) na cama bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Aqueles/Aquelas que já praticaram anilíng*a bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aqueles/Aquelas que já foram surpreendidos enquanto se masturbavam bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"As pessoas que depilam as partes íntimas distribuem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se não visitaste nenhum site porno há já mais de 2 semanas",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aqueles/Aquelas que gostam de palavras vulgares na cama distribuem, $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"As pessoas que já encenaram personagens na cama distribuem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aqueles/Aquelas que já foram para a cama com pessoas cujo nome não se recordam bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aqueles/Aquelas que já fod** num hotel bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"As pessoas que nunca deram uma queca num carro bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que não tiveram relações sexuais esta semana bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Os jogadores que foram para a cama com uma pessoa 5 anos mais velha bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Os jogadores que foram para a cama com uma pessoa 5 anos mais nova bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"As pessoas que já enviaram ou receberam um sexting bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Os jogadores que já alguma vez murcharam em pleno ato sexual bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"As pessoas que já tiveram uma aventura sexual com outro jogador bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já foram apanhados pelos pais enquanto estavam a ter relações sexuais bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, se nunca fizeste amor mais de 4 vezes no mesmo dia, bebe $ goles, caso contrário, distribui-os",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já tiveram fantasias com o/a companheiro(a) de um(a) amigo(a) bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já enviaram fotografias eróticas bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já lamberam ou comeram comida sobre um parceiro sexual bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já gritaram o nome do parceiro ao fazer amor bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já tiveram um orgasmo em menos de 3 minutos de penetração bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já fizeram amor durante a menstruação bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"O/A melhor na cama entre %s e %s bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já experimentaram uma amizade colorida bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"As raparigas que tiveram dores durante a primeira vez bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, se já estiveste secretamente apaixonado por %s, bebe $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já introduziram objetos nos órgãos genitais do seu/da sua parceiro(a) sexual bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já se registaram num site de encontros bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquela e a queles que já engataram num site de encontros bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"A última pessoa a ter visitado um site porno distribui $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquele ou aquela que tiver engatado mais em sites de encontros distribui $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já arranharam ou já foram arranhados por um(a) parceiro(a) sexual bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já tiveram um vibrador nas mãos bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já utilizaram acessórios durante o ato sexual bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já se sentiram excitados(as) por uma massagem profissional bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já cuspiram sobre um órgão sexual bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que fizeram um broche há menos de um mês bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que fizeram um broche há menos de uma semana bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já tiveram um objeto no ânus ou na vagina bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já insultaram o seu parceiro durante o ato sexual, bebam $ goles, seu safados",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já viram um amigo ou uma amiga trair o seu companheiro bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que já curtiram com o ex de um(a) amigo(a), bebam $ goles, seus sacanas",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, se durante a tua última relação sexual usaste preservativo, distribui $ goles, caso contrário, bebe-os tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se gostas de ser observado quando fazes amor",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já fod**te enquanto vias um filme porno",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se queres fod** ou fod** novamente enquanto vês um filme porno",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se queres fod** aqui e agora mesmo",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se gostas que te acariciem o ânus quando fazes amor",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se gostas de brincar com o ânus do teu/da tua parceiro(a) sexual durante a penetração",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se gostas de palmadas",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Os safados e as safadas que já tiveram uma experiência sexual com ambos os sexos bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Para as miúdas, aquelas que já tiveram um orgasmo vaginal bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já tiveste um orgasmo anal",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Para as misturas étnicas! Se já tiveste relações sexuais com uma pessoa de outra cor distribui $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já te mascaraste para apimentar o sexo",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já viste pessoas a pinocar",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se os teus últimos 3 engates foram amizades coloridas",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já fizeste uma massagem que derrapou…",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já recebeste uma massagem que derrapou…",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se achas não vires a descobrir mais nada em termos de sexo",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, lambe uma parte do corpo (aquela que quiseres) do jogador escolhido por %s",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já fod**te à frente de outras pessoas",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já participaste numa sessão de troca de casais",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Distribui $ goles se já te masturbaste na presença do teu/da tua parceiro(a) sexual",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Distribui $ goles se já te masturbaste ao pensar num ou numa colega de trabalho",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já te masturbaste ao ver um filme que não era porno",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas e aqueles que praticaram os preliminares entre dois momentos de penetração bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas que não sabem dançar o twerk bebem $ goles!",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já tiveste fantasias sexuais com um dos jogadores",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"A última pessoa a ter tido relações sexuais despe uma peça de roupa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já pinocaste na cama de um(a) amigo(a) sem ele (ela) saber",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Distribui $ goles se já fizeste os preliminares com uma pedra de gelo",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Distribuir $ goles se já fizeste os preliminares com uma pastilha com sabor a mentol na boca…",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já te tiraram fotografias nu(a)",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se não tens roupa interior",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se preferes os preliminares à penetração",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se gostas de sexo violento",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se, para ti, os preliminares são indispensáveis",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, se a tua primeira vez foi antes dos 17 anos, distribui $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, serias capaz de ir para a cama com o teu patrão ou a tua patroa para progredires na tua carreira? Sim: bebe $ goles, Não: distribui-os",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, serias capaz de ir para a cama com um velho ou uma velha bem nojento(a) em troca de 150.000 €? Sim: distribui $ goles; Non: bebe-os tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já foste para um clube de swing ou se já tentaste entrar",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Aquelas que já simularam bebem $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"A última pessoa a ter feito um belo broche distribui $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"A última pessoa a ter feito um fantástico cunilíngua distribui $ goles",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se fizeste um cunilíngua há menos de um mês",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se fizeste um cunilíngua há menos de uma semana",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já fizeste um broche ao teu parceiro para o acordares. Para os homens, aqueles que já foram acordados com um broche",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já acariciaste um sexo com os pés",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, distribui $ goles se serias capaz de perdoar uma infidelidade ao teu/à tua parceiro(a). Caso contrário, bebe-os tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se possuis acessórios eróticos",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já beijaste, com a língua, várias pessoas na mesma noite",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se gostavas de ver o teu/a tua parceiro(a) a fazer amor com outra pessoa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se, na tua vida, fizeste mais vezes amor às escuras do que à luz do dia",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já compraste algo numa sex shop",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, distribui $ goles se te consideras atraente. Se fores feio(a), bebe-os",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já foste para a cama com alguém que nem sabia o teu nome",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, bebe $ goles se desconhecidos já te viram a fazer amor. Caso contrário, distribui-os",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já tiveste relações sexuais bêbado(a)",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, bebe $ goles se já beijaste alguém que achavas repugnante. Caso contrário, distribui-os",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se achas que serias capaz de levar a pessoa à tua direita a ter um orgasmo em menos de 10 minutos",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se achas que a pessoa à tua esquerda vai para a cama com um jogador ainda antes de amanhã",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se a tua primeira vez não foi nada de especial",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já foste engatado(a) por uma pessoa do mesmo sexo",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já tiveste um sonho erótico com uma pessoa desta mesa",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se gostas que te mordisquem os mamilos",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, se achas que és a pessoa desta mesa que mais conquistas teve, distribui $ goles. Caso contrário, bebe-os tu",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se vários jogadores desta mesa te atraem fisicamente",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ goles se já foste para a cama com uma pessoa que conheceste numa app de encontros",key:"",parent_key:"",pack_name:"hot",language:"pt",nb_players:"0"}])