var db = TAFFY([{cycle_state:"false",type:"1",text:"%s, si eres una chica, lámete el dedo de manera erótica. Si eres un hombre, simula que haces un cunnilingus con 2 dedos. Y/o bebes $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, haz como si tuvieras un orgasmo durante 10 segundos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Todas las chicas deben hacer que les sobresalga el tanga",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s y %s se tienen que dar un abrazo, y los dos beben un trago",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, deja que %s te chupe el dedo o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Los que tengan camisa, se la tienen que desabotonar y beber un trago por cada botón",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, quítale una prenda de ropa a %s o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, ¿cuántas copas necesitarías para acostarte con %s? Responde y bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, entre todas las personas de la partida, ¿quién es para ti la que mejor la chupa? Responde y bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, dale $ tragos a la persona más sexy",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, imita la postura del perrito durante 5 segundos o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, di algo sexual que nunca hayas hecho, y los que sí lo hayan hecho deberán beber $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, si nos enseñas un pezón, %s tendrá que beber $ tragos, si no, bebes tú $",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, %s, %s y %s tienen que hacer una orgía o beber todos $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"4"},
{cycle_state:"false",type:"1",text:"%s, elige entre beber $ tragos o besarle los pies a %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, si le das un beso a %s, todo el mundo tendrá que beber $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Bebe en tragos el número de orgasmos que hayas tenido esta semana. Las pajas cuentan.",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Si %s y %s se besan en la boca, cada uno repartirá $ tragos, si no lo hacen, todo el mundo tendrá que beber $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"El primer jugador que enseñe su mensaje sexual reparte $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, si no te importaría acostarte con %s, reparte $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, pellízcale los pezones a %s o tendrá que beber $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"¡%s, lámele la nariz a %s o bebe $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"¡%s, hazle un masaje en la cabeza a %s o bebe $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, deja que %s te meta mano o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, dale un beso en la nariz a %s o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, elige a dos personas que tengan que besarse o beber $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"3"},
{cycle_state:"false",type:"1",text:"%s, ¿prefieres sexo oral, anal o vaginal? Responde y bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Los que alguna vez hayan dejado que les insultaran durante el acto sexual, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, lámele la boca a uno de los jugadores o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lámele la lengua a uno de los jugadores o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Todo el mundo bebe $ tragos. Salvo %s, que tendrá que darle un beso a todos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, besa a %s o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, elige entre besar a la persona que quieras o beber $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s pásale un hielo a %s con la boca o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, empieza por beber $ tragos. Si eres un hombre, describe tu mamada ideal. Si eres una mujer, cuéntanos cómo las haces",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, empieza por beber $ tragos. Si eres una mujer, describe tu cunnilingus ideal. Si eres un hombre, cuéntanos cómo los haces",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elije a la persona que deberá lamerte una parte del cuerpo. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, tócale los pezones a un jugador, $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deja que el jugador que quieras te toque los pezones. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, bésale el torso a un jugador o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deja que el jugador que elijas te bese el torso o el pecho. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, si eres un chico, ponte detrás de una jugadora y acaríciale los pechos; si eres una chica, elige al chico que te los acaricie... $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige al jugador que quieras para te haga un lap dance, $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, acaríciale el culo a un jugador durante 5 segundos, ¡$ tragos para el que se niegue!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deja que el jugador que elijas te acaricie el culo durante 5 segundos. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, mira a los ojos a la persona con la que podrías acostarte esta noche, y esa persona se beberá $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige quién beberá mientras le acaricias sus partes",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, enseña una foto tuya en topless o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, mordisquéale la oreja a un jugador o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige a 2 personas que se tendrán que besar con lengua, el que se niegue tendrá que beberse $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige a una persona que deberá enseñar un pezón... $ tragos si se niega",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, enseña una parte íntima de tu cuerpo o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige a un jugador que deberá mostrar una parte íntima de su cuerpo. $ tragos si se niega",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, imita una postura sexual con uno de los jugadores o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige a dos jugadores que deberán imitar una postura sexual y beber al mismo tiempo $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, frótate la cabeza contra las partes de alguien. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige a alguien que deberá frotarse la cabeza contra tus partes. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige a un jugador que deberá sacudir la cabeza entre los pechos de una jugadora. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, haz una lamida a las partes íntimas de alguien. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige a alguien que tendrá que hacerte una lamida en tus partes. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, acaricia una parte íntima de alguien o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige a alguien que tendrá que acariciarte tus partes. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige a alguien que tendrá que ponerte la mano dentro de tu ropa interior. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ponle la mano dentro de la ropa interior de alguien. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, pasa un alimento a alguien con la boca. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige a dos jugadores que deberán pasarse un alimento con la boca. $ tragos para los dos si se niegan",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, tócale los pechos a una chica. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"¡Todo el mundo bebe y se quita una prenda!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, elige a la persona que deberá quitarse una ropa. $ tragos si se niega",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, reta a un jugador a desabrochar el sujetador de una jugadora. Si no consigue hacerlo en 5 segundos, tendrá que beber $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deja que el jugador que elijas te pellizque los pezones o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, pellízcale el culo al jugador que elijas. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deja que el jugador que elijas te pellizque el culo o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lámele los labios al jugador que elijas. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deja que el jugador que elijas te lama los labios o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige a un jugador que tendrá que enseñarte una parte íntima de su cuerpo. $ tragos si se niega",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lámele los pezones al jugador que elijas. $ tragos para el que se niegue",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deja que el jugador que elijas te lama los pezones o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Los chicos, quitaos una prenda o bebed $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Las chicas, quitaos una prenda o bebed $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Los chicos, quedaos sin camiseta o bebed $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Las chicas, quedaos en sujetador o bebed $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ve a quitarte la ropa interior y vuelve. Si quieres librarte, termínate tu copa",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige una letra. Todos los jugadores que se hayan acostado con una persona cuyo nombre empiece por esa letra, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, hazle un masaje en los pies al jugador que quieras durante 2 minutos, o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deja que el jugador que quieras te masajee la parte del cuerpo que elijas, durante 2 minutos. Negarse implica $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, lame alrededor del ombligo al jugador que quieras, o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deja que el jugador que quieras te lama alrededor del ombligo. Negarse implica $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, hazle un chupetón a la persona que quieras o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, deja que la persona que quieras te haga un chupetón donde quieras, y puede negarse por $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"La persona que tenga las tetas más grandes, que elija a un chico para que se las chupe o tendrá que beber $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, enseña el culo o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, elige una parte de tu cuerpo. El primer jugador que te toque esa parte repartirá $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, enseña las tetas o bebe $ tragos. Si eres un hombre, puedes repartir $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Nombrad todos juntos a la persona más flexible, que deberá demostrarlo, y beberá $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, dale un beso en el cuello a la persona que elijas o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"¡A recordar viejos tiempos! Los que alguna vez se hayan acostado, tienen que volver a besarse o beber los dos $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, deja que la persona que elijas te dé un beso en el cuello o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, envía un mensaje sexual a la persona que elija el equipo. Si te sigue el rollo, ¡puedes repartir una bebida de un trago!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, reparte $ tragos a la persona con la que %s tiene más probabilidades de acostarse",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, bebe tantos tragos como personas con las que te hayas acostado en los últimos 6 meses",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"1",text:"El primer jugador entre %s y %s que le toque sus partes a otro jugador reparte $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Si no te importaría besar a la persona de tu izquierda, levanta la mano. Los demás beben $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s y %s, tienen que leer el primer SMS que se muestra en la barra de búsqueda al escribir «sexo». Os podéis negar por $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s y %s, tienen que leer el primer SMS que se muestra en la barra de búsqueda al escribir «polla». Os podéis negar por $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s y %s, tienen que leer el primer SMS que se muestra en la barra de búsqueda al escribir «mamada». Os podéis negar por $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s ahora debe correrse antes de cada trago",key:"orgasm-simulation",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s ya no está obligado/a a correrse antes de cada trago",key:"",parent_key:"orgasm-simulation",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, elige a alguien a quien tendrás que quedarte mirando a los ojos, te diremos cuándo puedes parar",key:"look-in-the-eyes",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"¡%s, puedes dejar de mirar fijamente a tu amigo/a!",key:"",parent_key:"look-in-the-eyes",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ponte a cuatro patas bien arqueado/a, ya te diremos cuando te puedes levantar",key:"doggy-style-way",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ya puedes volver a ponerte en una posición cómoda",key:"",parent_key:"doggy-style-way",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"¡%s trabaja en la policía! Puedes cachear el cuerpo de cualquiera cuando te apetezca, la persona cacheada se podrá negar por $ tragos",key:"body-search",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s ya no es policía y esta persona ruin y cochina tiene que beber $ tragos",key:"",parent_key:"body-search",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"¡%s es Cupido! Puede elegir quién se bese y se abrace cuando quiera, $ tragos si se niegan",key:"cupidon",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s ya no es Cupido",key:"",parent_key:"cupidon",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s está muy falto/a de cariño... Está obligado/a a besar a una persona antes de beber",key:"kiss-before-drink",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"¡%s se ha curado de su besomanía!",key:"",parent_key:"kiss-before-drink",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s coge amorosamente de la mano a %s hasta nueva orden",key:"hold-hand",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s y %s ya pueden soltarse",key:"",parent_key:"hold-hand",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"2",text:"¡%s, elige a una persona para que te haga un masaje en la mano! Ya te diremos cuándo puede parar",key:"hand-massage",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ya no te tienen que masajear la mano",key:"",parent_key:"hand-massage",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"¡%s es irresistible! Cada vez que pidas un beso a alguien (en la boca o en otro lugar), la persona elegida deberá hacerlo o beber",key:"irresistible",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s vuelve a ser feo/a",key:"",parent_key:"irresistible",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s y %s, haced piececitos hasta nueva orden",key:"naughty-feet",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s y %s ya pueden dejar los toqueteos",key:"",parent_key:"naughty-feet",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, estás obligado/a a elegir a alguien que tendrá que ponerte la mano en el culo hasta nueva orden",key:"hand-under-ass",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"¡%s puede liberar al pulpo!",key:"",parent_key:"hand-under-ass",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ponle la mano en el muslo a un jugador hasta nueva orden",key:"put-your-hand-on-legs",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"¡%s puede retirar la mano!",key:"",parent_key:"put-your-hand-on-legs",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"¡Un pequeño juego! Cada vez que %s toque un vaso, %s deberá imitar un orgasmo extremo. ¡$ tragos cada vez que se olvide!",key:"touch-glass-and-cum",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s y %s ya pueden dejar ese jueguecito suyo tan simpático",key:"",parent_key:"touch-glass-and-cum",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, elige en cualquier momento a 2 jugadores, y uno tendrá que sentarse sobre las rodillas del otro. $ tragos para todos los que se nieguen",key:"on-sby-knees",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ya no puedes elegir quién se sienta sobre quién",key:"",parent_key:"on-sby-knees",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"¡%s, tienes los labios envenenados! Si consigues darle un beso a un jugador sin forzarlo antes de que termine el virus, ¡este jugador tendrá que acabarse su bebida!",key:"kiss-poison",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"¡%s, tus besos ya no son envenenados! Si no lo has logrado, bebe $ tragos",key:"",parent_key:"kiss-poison",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"¡%s, tienes las manos envenenadas! Si consigues hacerle una caricia a un jugador sin que se dé cuenta antes de que termine el virus, ¡este jugador tendrá que acabarse su bebida!",key:"caddle-poison",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"2",text:"¡%s, tus caricias ya no son envenenadas! Si no lo has logrado, bebe $ tragos",key:"",parent_key:"caddle-poison",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"3",text:"¡Ahora estamos obligados a acariciarnos el pecho al hablar!",key:"caress-boobs",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"¡Ya podemos dejar de toquetearnos al hablar!",key:"",parent_key:"caress-boobs",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"¡Ahora es posible jugarse sus tragos en el juego de la botella! En vez de beber, haz girar la botella y besa al jugador que señale, ¡si te niegas tendrás que beber el doble!",key:"spin-the-bottle",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"¡El juego de la botella ha terminado!",key:"",parent_key:"spin-the-bottle",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"¡A partir de ahora, cada vez que alguien diga una palabrota tendrá que quitarse una prenda de ropa o beber $ tragos!",key:"cross-word-clothe",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ya puedes maldecir de nuevo sin temer perder la ropa",key:"",parent_key:"cross-word-clothe",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ahora estamos obligados a chuparnos el dedo, o el de otra persona, cuando no estemos hablando",key:"fingers-mouth",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ya podéis dejar de chuparos el dedo",key:"",parent_key:"fingers-mouth",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"A partir de ahora, ¡cada vez que una chica enseñe los pechos todo el mundo tiene que beber!",key:"show-your-boobs",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Chicas, dejad de enseñar las tetas",key:"",parent_key:"show-your-boobs",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"¡Juego del círculo! Cuando quieras, haz un círculo con el pulgar y el índice entre la cintura y el hombro, los jugadores que lo miren tendrán que quitarse una prenda o beber $ tragos",key:"round-game-hot",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"¡Fin del juego del círculo!",key:"",parent_key:"round-game-hot",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nueva regla: ¡el juego del gofio (si alguien eructa, el último que diga «gofio» pierde)! El que pierda cada vez, tendrá que quitarse una prenda o beber un trago",key:"gofio-game-hot",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"¡Fin del juego del gofio!",key:"",parent_key:"gofio-game-hot",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Nueva regla: si cruzas la mirada con otro jugador mientras te chupas el dedo, este tendrá que beber",key:"suck-your-finger",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Dejad de haceros gestitos, pillines",key:"",parent_key:"suck-your-finger",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"¡Nueva regla! Cada vez que terminemos de beber, tenemos que acariciarnos los pezones. Si no, tendremos que volver a beber",key:"caddle-tities",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"3",text:"Ya no estáis obligados a acariciaros los pezones",key:"",parent_key:"caddle-tities",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"4",text:"«Zonas erógenas de %s», el jugador que no encuentre ninguna o que repita bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, piensa en una postura sexual. Todos los jugadores tendrán que decir una, el primero que lo adivine reparte $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, piensa en una práctica sexual que no sea la penetración. Todos los jugadores tendrán que decir una, el primero que lo adivine reparte $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, piensa en un jugador presente, el que para ti sea más fogoso en la cama. Todos los jugadores tendrán que decir uno, el primero que lo adivine reparte $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, piensa en un juguete sexual. Todos los jugadores tendrán que decir uno, el primero que lo adivine reparte $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"4",text:"«Partes del cuerpo de %s que le gustan», ¡el jugador que repita o que no encuentre ninguna bebe $ tragos! Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"4",text:"«Atuendos en los que %s ha dormido alguna vez», ¡el jugador que repita o que no encuentre ninguno bebe $ tragos! Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"4",text:"«Cosas que te ponen de tu pareja», ¡la persona que repita o que no encuentre ninguna bebe $ tragos! Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Frases que te ponen en la cama», ¡la persona que repita o que no encuentre ninguna bebe $ tragos! Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Vuestras ex parejas sexuales, si dices un nombre que ya se haya nombrado o si has terminado, bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Nuevo tema y $ tragos en juego: «famosos que hayan protagonizado un vídeo sexual», empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Juego de temas y $ tragos en juego: «lugares donde %s lo ha hecho», empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Juego de temas y $ tragos en juego: «fantasías comunes», empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Nuevo tema y $ tragos en juego: «prácticas sexuales» (penetración...), empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Por turnos, todos tenéis que enseñar vuestros tatuajes y piercings, los que no tengan, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"4",text:"Por turnos, mostrad una de vuestras marcas de nacimiento y repartid $ tragos. Si no tienes ninguna, bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Bombas sexuales que han participado en un reality», el jugador que repita o que no encuentre ninguna bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Juguetes sexuales», el jugador que repita o que no encuentre ninguno bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Razones por las que acostarse con una persona desconocida», el jugador que repita o que no encuentre ninguna bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Cosas que hay que hacer antes de salir de fiesta cuando se está soltero/a», el jugador que repita o que no encuentre ninguna bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Canales de televisión que difunden películas eróticas», el jugador que repita o que no encuentre ninguno bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Lugares donde poner las manos durante la penetración», el jugador que repita o que no encuentre ninguno bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Preliminares», el jugador que repita o que no encuentre ninguno bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Excusas para no quedarse a dormir después de un polvo de una noche», el jugador que repita o que no encuentre ninguna bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Lugares habituales en las fantasías», el jugador que repita o que no encuentre ninguno bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Disfraces habituales en las fantasías», el jugador que repita o que no encuentre ninguno bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Profesiones relacionadas con el erotismo o el sexo», el jugador que repita o que no encuentre ninguna bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Olores del preservativo», el jugador que repita o que no encuentre ninguno bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Alimentos que pueden dar ganas de sexo», el jugador que repita o que no encuentre ninguno bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Sinónimos de tener un orgasmo\u0022» el jugador que repita o que no encuentre ninguno bebe $ tragos. Empieza %s\u0022",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Lugares donde mordisquear para excitar a tu pareja», el jugador que repita o que no encuentre ninguno bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Objetos que sirven en una relación sadomasoquista», el jugador que repita o que no encuentre ninguno bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Partes del cuerpo que son agradables de chupar durante una relación sexual», el jugador que repita o que no encuentre ninguna bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Cosas que se hacen habitualmente justo después de haber hecho el amor», el jugador que repita o que no encuentre ninguna bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Cosas por las que se puede ser fetichista sexual», el jugador que repita o que no encuentre ninguna bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Prácticas sexuales que se hacen con la lengua», el jugador que repita o que no encuentre ninguna bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"4",text:"«Medios para hacer que una mujer se corra», el jugador que repita o que no encuentre ninguno bebe $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, termínate tu copa y bájale la bragueta a la persona que elijas con los dientes",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, termínate tu copa y mordisquéale o lámele la oreja a la persona que más te atraiga",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, termínate tu copa y besa a la persona que quieras (en los labios)",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, haz un baile sexy a %s después de terminarte tu copa",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, hazle un chupetón a %s o los dos tienen que beber $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, termínate tu copa y haz como si se la chuparas o lamieras a %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"7",text:"¡%s, dale un beso a cada jugador y termínate la copa que te guste!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, dale un morreo a %s o bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"7",text:"%s, elige a la persona que te acariciará mientras te terminas tu copa...",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, quítate 3 prendas y termínate tu copa...",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, elige a la persona con la que vas a jugar. Tenéis que beber un trago y luego besaros. Y seguir así hasta que los dos terminéis vuestras copas...",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, elige a un jugador que te pondrá la mano en tus partes mientras te terminas tu copa. La mano dentro de la ropa interior...",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, elige a dos jugadores que se tendrán que terminar sus bebidas y luego besarse con lengua...",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, termínate la copa del jugador con el que te podrías acostar esta noche...",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"7",text:"%s, termínate tu copa mientras el jugador que elijas te acaricia. Si eres una chica, será en los pechos, y si eres un chico, en tus partes.",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Entre %s y %s, ¿para ti quién es la mejor pareja para los preliminares? Votad todos juntos, el que obtenga más votos reparte $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"14",text:"¿Qué prefieres, las chicas: pectorales o abdominales; los chicos: tetas o culos? Votad todos al mismo tiempo, los que pierdan beben $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"14",text:"¿A favor o en contra del amor sin compromiso? Votad todos juntos levantando la mano, ¡los que estén en minoría beben $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Las domingas, ¿demasiado grandes o demasiado pequeñas? Votad todos al mismo tiempo, ¡la minoría se bebe $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿Sumiso/a o dominante? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"14",text:"¿Una mamada o sexo anal? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"14",text:"¿Un rollete o algo serio? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"14",text:"¿Un anulingus o una orgía? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"14",text:"¿Depilación brasileña o integral? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"14",text:"¿Tanga o culotte? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"14",text:"¿Un bukkake o sexo anal? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"14",text:"¿Hacerlo 30 veces el mismo día o no hacerlo durante un mes? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"14",text:"¿Besar a %s o a %s? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"14",text:"¿Hacerlo con %s o con %s? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"14",text:"¿Hacer un trío o hacerlo con ocho? Votad todos al mismo tiempo, ¡la minoría se bebe $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿Hacer un cunnilingus o una felación? Votad todos al mismo tiempo, ¡la minoría se bebe $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿Ver a través de la ropa o volverse invisible? Votad por turnos, ¡la minoría se bebe $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿Acostarse con un famoso o con la persona más sexy que conoces? Votad todos al mismo tiempo, ¡la minoría se bebe $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿Megan Fox o Scarlett Johansson? Votad todos al mismo tiempo, ¡la minoría se bebe $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿Tener una relación perfecta pero sexualmente pobre o una relación de mierda pero sexualmente increíble? Votad todos al mismo tiempo, ¡la minoría se bebe $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿No encontrar nunca el amor o no tener nunca una relación sexual? Votad todos al mismo tiempo, ¡la minoría se bebe $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿Tener (o tener una relación con alguien que lo tenga) un pene de 9 cm o de 36 cm? Votad todos al mismo tiempo, ¡la minoría se bebe $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Las cochinadas, ¿mejor por la mañana o por la noche? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Para el sexo, ¿disfrazarse de enfermero/a o de policía? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿Besar a la persona que está a tu derecha o a la de tu izquierda? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿Hacerlo con la persona que está a tu derecha o con la de tu izquierda? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Para el sexo, ¿disfrazarse de bombero/a o de policía? Votad todos al mismo tiempo, la minoría se bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿Poder chasquear los dedos y hacer que desaparezca un pantalón o una parte de arriba? Votad al mismo tiempo, los que pierdan beben $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿Poder vivir un sueño despierto y no tener límites durante una semana, o poder hacer cualquier cosa que desees sexualmente en la vida? Votad al mismo tiempo, los que pierdan beben $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿Tener un abono en un club de intercambio o en el salón del erotismo? Votad al mismo tiempo, los que pierdan beben $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿A favor o en contra de salir en una peli porno? Votad al mismo tiempo, los que pierdan beben $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿A favor o en contra del nudismo? Votad al mismo tiempo, los que pierdan beben $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿A favor o en contra del intercambio de parejas? Votad al mismo tiempo, los que pierdan beben $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Durante el acto sexual, ¿qué prefieres, que la chica esté arriba o abajo? Votad al mismo tiempo, los que pierdan beben $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿Acostarte con alguien de esta mesa, o con una persona desconocida aleatoria cada día durante una semana? Votad al mismo tiempo, los que pierdan beben $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"14",text:"¿Tener preliminares con uno de los jugadores presentes o ganar 500 euros? Votad al mismo tiempo, los que pierdan beben $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"¡Convenced al jurado! %s y %s tienen que contar una de sus fantasías, ¡y los demás tendrán que votar la más tórrida! El ganador reparte $ tragos, que se tendrá que beber el que pierda",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Designad a la persona que tenga más falta de sexo, y luego pulsad en la pantalla",key:"horny",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"La persona designada reparte $ tragos",key:"",parent_key:"horny",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Todo el mundo bebe $ tragos salvo la persona designada",key:"",parent_key:"horny",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"La persona designada puede ahogar sus penas en alcohol y bebe $ tragos (esta noche no vas a pillar)",key:"",parent_key:"horny",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"La duración ideal de un polvo. Empieza %s (ahora viene la continuación...)",key:"sex-duration",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"¡Los 3 jugadores más bajos beben $ tragos!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"¡Los 3 jugadores más altos beben $ tragos!",key:"",parent_key:"sex-duration",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, reparte $ tragos a los jugadores que hayan indicado una mayor duración. Si indicaste la mayor duración, bebe $ tragos",key:"",parent_key:"sex-duration",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, reparte $ tragos a los jugadores que hayan indicado una menor duración. Si indicaste la menor duración, bebe $ tragos",key:"",parent_key:"sex-duration",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"¿Cuántas parejas sexuales habéis tenido? Cada uno responde, y ahora viene la continuación... Empieza %s",key:"number-partner-sex",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"¡%s y %s reparten tantos tragos como parejas sexuales han tenido!",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"¡%s y %s beben tantos tragos como parejas sexuales han tenido!",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"El jugador que haya tenido más bebe $ tragos",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"El jugador que haya tenido menos bebe $ tragos",key:"",parent_key:"number-partner-sex",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"¡Convenced al jurado! %s y %s tienen que contar un sueño erótico extraño que hayan tenido, ¡y los demás tendrán que votar el más improbable! El ganador reparte $ tragos, que se tendrá que beber el que pierda",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Vuestro periodo de abstinencia más largo después de hacerlo por primera vez. Cada uno responde, y ahora viene la continuación... Empieza %s",key:"abstinence-time",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"¡El jugador con el periodo más largo bebe $ tragos!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"¡El jugador con el periodo más largo reparte $ tragos!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"¡%s y %s reparten tantos tragos como meses de abstinencia!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"¡%s y %s tienen que beber tantos tragos como meses de abstinencia!",key:"",parent_key:"abstinence-time",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"El número ideal de relaciones sexuales a la semana para ti. Cada uno responde, y ahora viene la continuación... Empieza %s",key:"nb-sexual-rel",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Las personas con más de 2 tendrán que beber $ tragos, los demás, beben un poquito",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Las personas con menos de 3 tendrán que beber $ tragos. Los demás, beben un poquito",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"¡%s y %s reparten tantos tragos como relaciones sexuales a la semana!",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"¡%s y %s beben tantos tragos como relaciones sexuales a la semana!",key:"",parent_key:"nb-sexual-rel",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"¡Convenced al jurado! %s y %s tienen que contar uno de sus peores encuentros sexuales, ¡y los demás tendrán que votar el más estúpido! El ganador reparte $ tragos, que se tendrá que beber el que pierda",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"¿Cuál es vuestra postura preferida? Cada uno responde, los que coincidan con la misma postura, que se beban $ tragos juntos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"¡Convenced al jurado! %s y %s tienen que decirnos lo menos sexy que se puede escuchar durante el sexo, ¡y los demás tendrán que votar qué es lo peor! El ganador reparte $ tragos, que se tendrá que beber el que pierda",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"¡Convenced al jurado! %s y %s tienen que decir lo mejor que se puede hacer para excitar a su pareja, ¡y los demás tendrán que votar lo más caliente! El ganador reparte $ tragos, que se tendrá que beber el que pierda",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Tienes derecho a 5 minutos de sexo antes de morir, con cualquier persona y en cualquier lugar. %s y %s tienen que proponer una elección, ¡y los demás tendrán que votar cuál es la mejor! El ganador reparte $ tragos, que se tendrá que beber el que pierda",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"¡Convenced al jurado! %s y %s tienen que contarnos uno de los mejores polvos de su vida, ¡y los demás tendrán que votar el más excitante! El ganador reparte $ tragos, que se tendrá que beber el que pierda",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"¡Convenced al jurado! %s y %s tienen que decirnos uno de los lugares insólitos donde lo han hecho, ¡y los demás tendrán que votar el más improbable! El ganador reparte $ tragos, que se tendrá que beber el que pierda",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"23",text:"Por turnos, bebed $ tragos y decid con quién preferiríais acostaros de esta habitación.",key:"who-u-wanna-fuck",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, si te han nombrado, dale un beso a la persona que lo ha hecho. De lo contrario, bebe $ tragos",key:"",parent_key:"who-u-wanna-fuck",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Por turnos, id a darle un beso a una persona. Los que se nieguen, que se beban $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Por turnos, elegid a alguien que tendrá que tocaros vuestras partes. Si se niega a hacerlo, ¡se llevará $ tragos! Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Por turnos, elegid a alguien que tendrá que quitarse una prenda. Si se niega a hacerlo, ¡se llevará $ tragos! Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"¡El juego de la botella! Cada jugador tiene que hacer girar la botella y besar a la persona que indique, $ tragos si se niega. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"¡Concurso de calzoncillos! Las chicas son el jurado, el que pierda se beberá $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"¡Concurso de sujetador! Los chicos son el jurado, la que pierda se beberá $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"¡Kiss party! Por turnos, besad a la persona de vuestra izquierda o bebed $ tragos, empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"¡Déjame que te acaricie el chow choooow! Por turnos, tocadle sus partes a la persona de vuestra derecha o bebed $ tragos, empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"¡Déjame que te acaricie el chow choooow! Por turnos, tocadle sus partes a la persona de vuestra izquierda o bebed $ tragos, empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"¡Déjame que te acaricie el chow choooow! Por turnos, acariciadle el pecho a la persona de vuestra derecha o bebed $ tragos, empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"¡Déjame que te acaricie el chow choooow! Por turnos, acariciadle el pecho a la persona de vuestra izquierda o bebed $ tragos, empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"¡La pregunta trampa! Por turnos, haced una pregunta picante a otra persona. Si la persona interrogada no quiere responder, tendrá que beber $ tragos. Empieza %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Concurso de culos: los chicos, ¡a desfilar! Las chicas son el jurado, el que gane podrá repartir $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"23",text:"%s, deja que te venden los ojos y 2 jugadores te tendrán que dar un beso en cualquier lugar. Si adivinas quién es uno de los dos jugadores, reparte $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, deja que te venden los ojos, y un jugador se pondrá comida en la barriga y tendrás que comértela. Si adivinas lo que es, reparte $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"23",text:"¡Concurso de olor de pelo! Las chicas juegan y los chicos son el jurado. La que gane puede repartir $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan hecho el amor en un lugar público, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan hecho un trío, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Las personas que alguna vez hayan hecho una sexcam reparten $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan pensado en otra persona mientras lo hacían, reparten $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"A los que les gustaría acostarse con una persona presente en la sala, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez te has acostado con alguien la primera noche",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"A las personas a las que les encantan las felaciones, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez se hayan grabado haciéndolo reparten $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que piensen que %s es bueno/a en la cama, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan practicado un anulingus, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"A los que alguna vez les hayan pillado masturbándose, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que se depilan sus partes íntimas reparten $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si no has visitado una página porno desde hace más de 2 semanas",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"A los que les gusta hablar sucio en la cama reparten $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Las personas que alguna vez hayan hecho juegos de rol en la cama reparten $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez se hayan acostado con alguien del que no se acuerden cómo se llamaba, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez lo hayan hecho en un hotel, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que nunca lo hayan hecho en un coche, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que no hayan tenido relaciones sexuales esta semana, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los jugadores que se hayan acostado con una persona 5 años mayor que ellos, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los jugadores que se hayan acostado con una persona 5 años más joven que ellos, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan enviado o recibido un mensaje sexual, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los jugadores que alguna vez hayan tenido un gatillazo, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Las personas que hayan tenido una aventura sexual con otro jugador, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan sido pillados por sus padres en pleno acto sexual, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, si nunca has hecho el amor más de 4 veces el mismo día, bebe $ tragos, si lo has hecho, repártelos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan fantaseado con la pareja de un/a amigo/a, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan mandado fotos eróticas, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan lamido o comido alimentos sobre una pareja, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan gritado el nombre de su pareja haciendo el amor, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan tenido un orgasmo en menos de 3 minutos de penetración, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan hecho el amor con la regla, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Entre %s y %s, el que sea más bueno en la cama tiene que beber $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Los que tuvieron su primera vez con un rollo, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Las chicas que sintieron dolor en su primera vez, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, si has estado enamorado/a en secreto de %s, bebe $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan introducido objetos en el sexo de su pareja, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez se hayan registrado en una web de citas, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan pillado en una web de citas, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"La última persona que haya visitado una página porno reparte $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"La persona que más haya pillado en web de citas reparte $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan arañado o les hayan arañado haciéndolo, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan tenido un consolador en la mano, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan utilizado juguetes para un acto sexual, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez se hayan excitado con un masaje profesional, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"¡Los que alguna vez hayan escupido sobre un sexo, que se beban $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"¡Los que hayan hecho una mamada hace menos de un mes, que se beban $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que hayan hecho una mamada hace menos de una semana, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan tenido un objeto en el ano o en la vagina, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan insultado a su pareja durante una escena de sexo, que se beban $ tragos, pillines",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan visto a un/a amigo/a serle infiel a su pareja, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan salido con el/la ex de un/a amigo/a, bebed $ tragos, malnacidos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, si tu última relación sexual fue con protección, reparte $ tragos, si no lo fue, bébetelos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si te gusta que te miren mientras haces el amor",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez te has acostado con alguien viendo una peli porno",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si no te importaría hacerlo o repetir viendo una peli porno",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si quieres hacerlo en este preciso momento",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si te gusta que te acaricien el ano cuando haces el amor",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si te gusta jugar con el ano de tu pareja durante la penetración",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si te gustan las tortas en el culo",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los pillines y pillinas que ya hayan tenido una experiencia sexual con ambos sexos, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Las chicas, las que alguna vez hayan tenido un orgasmo vaginal, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez has tenido un orgasmo anal",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"¡Por las mezclas étnicas! Si alguna vez te has acostado con una persona de otra raza, reparte $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez te has disfrazado para animar el sexo",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez has visto a otras personas echando un kiki",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si tus 3 últimas veces fueron con un rollete",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez has hecho un masaje con final feliz",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez te han hecho un masaje con final feliz",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si piensas que no vas a descubrir cosas nuevas sexualmente hablando",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, lámele una parte del cuerpo (la que quieras) al jugador que elija %s",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"2"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez lo has hecho delante de otras personas",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez has participado en un intercambio de parejas",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Reparte $ tragos si alguna vez te has masturbado delante de tu pareja",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Reparte $ tragos si alguna vez te has masturbado pensando en un/a compañero/a de trabajo",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez te has masturbado viendo una película que no fuera porno",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Los que alguna vez hayan practicado los preliminares entre dos momentos de penetración, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"¡Las que no sepan hacer twerking tienen que beber $ tragos!",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez has fantaseado con uno de los jugadores",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"La última persona en haber tenido una relación sexual, que se quite una prenda",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez lo has hecho en la cama de un/a amigo/a sin que se entere",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Reparte $ tragos si alguna vez has hecho preliminares con un cubito de hielo",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Reparte $ tragos si alguna vez has hecho preliminares con un chicle de clorofila en la boca...",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez has dejado que te hagan una foto desnudo/a",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si no llevas ropa interior",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si prefieres los preliminares a la penetración",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si te gusta el sexo salvaje en la cama",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si consideras que los preliminares son imprescindibles",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, si tu primera vez fue antes de los 17 años, reparte $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, ¿te acostarías con tu jefe/a para ascender? Si la respuesta es sí, bebe $ tragos; si es no, repártelos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"25",text:"%s, ¿te acostarías con un/a viejo/a bastante asqueroso por 150 000 €? Si la respuesta es sí, reparte $ tragos; si es no, te los puedes beber",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez has entrado en un club de intercambio, o si lo has intentado",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Las que alguna vez hayan fingido, que se beban $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"La última persona en haber hecho una buena mamada reparte $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"La última persona en haber hecho un cunnilingus apasionado reparte $ tragos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si hace menos de un mes que hiciste un cunnilingus",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si hace menos de una semana que hiciste un cunnilingus",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez se la has chupado a tu novio para despertarlo. Para los chicos, a los que alguna vez se la hayan chupado para despertarlo",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez has acariciado un sexo con los pies",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, reparte $ tragos si podrías perdonar una infidelidad a tu pareja. Si no, bébetelos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si tienes juguetes eróticos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez has besado, con lengua, a varias personas en la misma noche",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si te gustaría ver a tu pareja hacer el amor con otra persona",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si, a lo largo de tu vida, lo has hecho más a oscuras que en pleno día",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez has comprado algo en un sex shop",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, reparte $ tragos si te encuentras atractivo/a. Si eres feo/a, bébetelos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez lo has hecho sin que la otra persona conociera tu nombre",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, bebe $ tragos si alguna vez te han visto hacer el amor unos desconocidos. Si no, repártelos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez has mantenido relaciones sexuales estando borracho/a",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, bebe $ tragos si alguna vez has besado a alguien que te parecía repugnante. Si no, repártelos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si piensas que podrías hacer que la persona de tu derecha se corriera en menos de 10 minutos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si piensas que la persona de tu izquierda se va a acostar con un jugador antes de mañana",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si tu primera vez no fue para tirar cohetes",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez una persona de tu mismo sexo ha ligado contigo",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez has tenido un sueño erótico con alguien de esta mesa",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si te encanta que te mordisqueen los pezones",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"%s, si crees que eres la persona con más conquistas de esta mesa, reparte $ tragos. Si no, bébetelos",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"1"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si varios jugadores de esta mesa de atraen físicamente",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"},
{cycle_state:"false",type:"25",text:"Bebe $ tragos si alguna vez te has acostado con alguien mediante una aplicación de citas",key:"",parent_key:"",pack_name:"hot",language:"es",nb_players:"0"}])