game.stored_db.never_popular_fr = [{pack_name:"never_popular",language:"fr",text:"Je n'ai jamais 'volé' de blague."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais aimé l'école."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais appelé en masqué."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais appelé quelqu'un en inconnu en me faisant passer pour quelqu'un d'autre."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais aspiré l'encre de mon bic sans m'en rendre compte."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais aspiré un papillon de nuit avec un aspirateur."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais bien compris pourquoi tout le monde était de face sur sa photo de profil."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais bloqué les toilettes en disant que c'était quelqu'un d'autre."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais brûlé un feu rouge."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais bu d'alcool."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais bu de sirop sans eau."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais bu de vodka red bull."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais cassé du sucre sur le dos d'un diabétique."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais cassé un pare-brise en criant 'Carglass répare carglass remplace'."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais chanté avec une brosse à cheveux."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais chanté sous la douche."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais chanté tout haut dans un lieu public alors que j‘écoutais mon iPod."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais chuté en descendant d'une voiture."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais commencé l'ecole avant trois ans."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais compris comment jouer au démineur."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais compris l'utilité de faire son lit si c'est pour le déranger."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais compris le jeu Pyramide."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais compris pourquoi les artistes de la Renaissance avaient des noms de tortues ninjas."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais compris pourquoi mon chien me suit tout le temps quand je vais aux toilettes ."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais compris pourquoi tout le monde critique les blondes."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais conduit bourré."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais connu un mec qui prend des petites tomates a Mcdo."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais copié en classe."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais couché avec un inconnu."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais coupé ma viande avec un hache."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais critiqué un ami."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais crié pour engueler mon copain."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais cru au père noël."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais d'idée de 'je n'ai jamais...'."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dansé devant mon mirroir."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dansé le gangnam style."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dansé le twerk."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dansé."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais demandé de l'argent dans la rue."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais demandé le numéro de telehone à une personne que je connaissais pas."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais demandé une pause pendant l'acte."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dis pardon à un meuble en me cognant."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dis que j'avais lu un livre pour briller en société alors que je n'avais vu que le film."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dit 'j'avoue' alors qu'il n'y a rien à avouer ."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dit 'non mais allô quoi ?!'."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dit ce que je pense."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dit jamais."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dit ne plus avoir de chewing gum pour ne pas avoir à en distribuer à tout le monde."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais donné de la nourriture à quelqu'un sachant que c'était tombé par terre."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dormi dans un arbre."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dormi dans une voiture."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dormi plus de 15 heures d'affilée."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais douté de mon orientation sexuelle."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dépassé 1m70."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais désobéi a la loi."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais détesté un de mes bo parents."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais détesté un de mes exs."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais détesté une personne ici présente."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dû reprendre mon examen de conduite."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais effacé une photo de Facebook parce que je me trouvais moche dessus."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais embarquée un inconnu dans ma voiture."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais embrassé mon mirroir en me regardant."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais embrassé quelqu'un du sexe opposé."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais embrassé une affiche d'une célébrité."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais emprunté quelque chose à quelqu'un sans finir par lui rendre."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais englouti un pot (entier) de nutella à la petite cuillère."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais envoyé de nude"},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais envoyé de sexto."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais envoyé de texto saoul."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais essayé de monter les escaliers à cloche pied sans toucher la rambarde."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu d'accident de voiture où j'étais fautif."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu d'heures de colle."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu d'orgasme."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu de black out."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu de bug sous windows."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu de contravention."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu de copine / copain."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu de fou rire ultra gênant."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu envie de dire 'la ferme' à quelqu'un qui me parlait."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu envie de tuer quelqu'un."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu honte d'écouter une chanson."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu le hoquet."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu mal parce que j'avais trop mangé."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu peur de sortir dans la rue."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu peur du ridicule."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu plus peur que la fille avec qui je regardais un film d'horreur."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu un 0 sur 20."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu un coup d'un soir."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu une relation ouverte."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fais d'escalade."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fais de surf."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fais du catch mexicain avec un ours polaire."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fais pipi sous la douche."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait attention à ma ligne."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait caca sur le tapis du salon."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait croire à un patient atteint d'Alzheimer que j'étais sa fille alors que ce n'était pas vrai."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait de bordel en classe."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait de camping."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait de danse sensuelle pour quelqu'un."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait de farce téléphonique."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait de fugue."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait de manège à sensation."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait de phaute d'orthographe."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait de prank calls."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait de stop."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait du mal à une personne ici présente."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait la vaisselle en maillot de bain."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait pipi contre le vent."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait pipi dans ma culotte en public."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait pipi dans ma culotte."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait pipi dans mon lit après 20 ans."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait pipi dans une piscine publique."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait pipi dehors."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait pipi la tête en bas ."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait plus de 5 magasins en une journée."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait quelque chose de complètement fou."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait semblant d'être une personne d'un autre pays que le mien."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait une connerie et accuser quelqu'un d'autre."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais falsifié un document officiel."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais foxé un cours au secondaire."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fumé dans un transport en commun."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fumé de bédo."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fumé de cigarette."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fumé."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fêté mon anniversaire dans une tente."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais gagné aux jeux de grattage."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais imité la signature de mes parents."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais indiqué un mauvais itinéraire à quelqu'un de perdu."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais inscrit ma femme au curling pour qu'elle apprenne à balayer."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais insulté la police."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais inventé d'excuse bidon pour couvrir le fait que j'étais en retard au boulot ou en cours."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais jeté d'oeufs sur quelqu'un."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais jeté de tomates sur une voiture."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais jeté des écureuils morts devant le siège social de la Caisse d'Epargne."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais joué au jeu Je n'ai jamais."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais joué au pendu avec un salarié de France Telecom."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais joué aux agents secrets."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais joué à PES bourré."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais laché une grosse caisse dans l'ascenseur du boulot en étant seul... avant de me faire rejoindre par des collègues à l'étage suivant."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais laissé ma place dans le bus à une vieille pour faire chier le pote à coté de qui j'étais assis."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais lancé de nourriture sur la maison de quelqu'un."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais lancé quelque chose par terre en cours pour parler à quelqu'un."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais lu la saga Twilight."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais léché le sol."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais machouillé du mauvais coté un feutre permanent débouché."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mal parlé à l'un de mes professeurs."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé 3 petits beurres en moins d'une minute."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé bio."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé d'huîtres."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé d'insectes ."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé de la nourriture pour animaux."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé de la nourriture pour chien."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé de papier."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé de roses pour voir si mes pets sentiraient pareil."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé de ver de terre."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé de viande de cheval."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé des excréments de chien sechés pensant que c'était du chocolat."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé mes crottes de nez."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé pendant la nuit."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé quelque chose de dégueulasse pour de l'argent."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé quelque chose qui était tombé par terre."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé un paquet de chamallow en entier."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé un piment entier."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais manqué un avion."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais menti au 'je n'ai jamais'."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais menti pour aider un ami."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais menti à la personne sur ma droite."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais menti à mes amis."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais menti à mes parents."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais menti à quelqu'un."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mis de slip kangourou."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais montré mes fesses à la fin d'un spectacle pour un pari."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais organisé de soirée surprise pour une personne atteinte du syndrome de stress post-traumatique."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais osé crier au milieu d'une foule juste pour gagner un pari."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais osé défier Chuck Norris."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais osé m'interposer entre une femme et une paire de bottes en soldes."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais osé parler gastronomie avec un somalien."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais osé passer à un péage sans payer ."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais oublié l'anniversaire de ma copine."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais oublié les clefs de chez moi."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais oublié mes clés de maison."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais oublié mon anniversaire."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais oublié un anniversaire."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais parcouru le monde en bicyclette."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais parlé durant mon sommeil."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais passé l'aspirateur et aspiré quelque chose de vivant."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais passé une journée entière à glander devant la télé/l'ordi/la console."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais passé une journée sans facebook."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais passé une journée sans jeux vidéos."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais passé une semaine sans m'interroger sur l'heure."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pensé qu'une canicule résoudrait le problème des retraites."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pensé que je suis la plus jolie/le plus beau de ce groupe."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais perdu au jeu 'Cap's '."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais perdu mon travail parce que j'avais trop fait la fête la veille ou que j'avais trop bu."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais perdu à Pierre-Feuille-Ciseaux."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais photoshopé une photo pour être plus mince."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pissé dans la rue."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pleurer devant un(e) ami(e)."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pleuré au cinéma."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pleuré devant un film."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pleuré en lisant un livre."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pleuré pour une fille."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais porté de lunettes de vue."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais poussé la porte alors que c'était marqué 'tirer'."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pris de drogues."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pris les photos du mauvais enfant lors du spectacle de fin d'année de mon enfant."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pris mon bain dans une fontaine public ."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pris soin de moi, de mon visage, de mon corps pendant plus de 3h dans la salle de bain."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pu m'empêcher de détester les gens qui doublent dans les queues."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pété bruyamment alors que je pensais ne pas faire de bruit car j'écoutais mon mp3."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pété bruyamment pendant une réunion."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pété en classe de cours."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pété et accusé un autre à ma place."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais raté le train."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais raté mon permis."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais raté un train au dernier moment à cause d'une envie pressante."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais redoublé une année à l'école."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais regardé 5 films au cinéma dans la même journée."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais regardé friends."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais regardé un film d'horreur juste pour que la fille se blottisse de peur contre moi."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais renoncé à acheter quelque chose juste devant la caisse."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais retiré le poisson de la gammelle de mon chat en lui disant 'poisson d'avril!!'."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais reçu de baffe en public."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais rien volé."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais rien vécu de paranormal."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais rigolé en buvant."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais râté mon permis."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais réfléchi."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais répondu à une question alors que je ne l'avais pas comprise."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais réussi à aller au toilette au boulot."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais réussi à compter jusqu'à 1000."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais réussi à faire pipi à côté de quelqu'un."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais réussi à nager."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais réussi à toucher mon nez avec ma langue."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais rêver de voler dans le ciel."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais rêvé d'être agent secret."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais rêvé de quelqu'un présent ici."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais sauté à l'élastique."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais senti mes chaussettes avant de les mettre dans le linge sale."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais senti mes sous-vêtements pour vérifier qu'ils étaient propres."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais signé à la place de mes parents sur un papier de l’établissement scolaire."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais songé à offrir une dinette à ma soeur pour qu'elle intègre son rôle de femme."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais sonné à une porte en me marrant."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais sucé mon pouce."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais suivi de thérapie."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais suivi la série 'El Diablo'."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais supporté le PSG."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais supporté mon patron."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais séché un cours volontairement."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais tager quelque chose dans le train."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais tenté de lecher mon coude."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais tenu mon chat à bout de bras comme dans le Roi Lion."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais terminé le plat ou le verre de quelqu‘un après qu‘il soit partie."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais tiré une porte d'entrée alors qu'il y avait marqué 'pousser'."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais tort, c'est la vérité qui se trompe."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais trahis personne."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais traversé une salle d'alcooliques anonymes avec une bouteille de Vodka."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais trebuché dans la rue et continué comme si de rien n'était."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais trouvé ridicule le prénom des enfants de stars."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais tué un animal."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais téléchargé illégalement."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais uriné en prenant une douche."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais utilisé de faux profil sur les réseaux sociaux."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais utilisé des feuilles d'ortie comme mouchoir ."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais utilisé du papier toilette comme mouchoir."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais vendu la peau de l'ours avant de l'avoir tué."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais volé dans un magasin."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais volé de l'argent."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais volé le briquet de quelqu'un."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais volé les affaires d'un pote pour qu'il se retrouve à poil."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais volé à l'étalage."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais vomi dans le sac de quelqu'un."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais voté FN."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais voulu être mannequin."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais vu de la neige en vrai."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais vu le groeland."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais vu un de mes voeux se réaliser après une étoile filante ou après avoir soufflé mes bougies."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais vu un politicien dire la vérité."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais vu une celebrité."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais écrit sur le mur d‘une toilette publique."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais étais a l'aise alors que je regardais un film avec mes parents au moment d'une scène torride."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais éternué en cours."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été amoureuse -eux."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été amoureux virtuellement."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été au Casino."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été aussi amoureux."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été cocu."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été demoiselle d'honneur."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été en bateau."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été en cours en hélico."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été en forme le matin pour aller au boulot."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été ivre avec mes parents."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été jalouse de l'amitié entre deux de mes copines."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été malade à cause de l'alcool."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été opéré."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été parfaite."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été sur un autre continent."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été suspendu(e) de l'école."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été transporté en ambulance."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été viré."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été à l'école en meuse."},
    {pack_name:"never_popular",language:"fr",text:"Je n'aies jamais mangé un biscuit du genre barquette juste pour le chocolat au milieu."},
    {pack_name:"never_popular",language:"fr",text:"Je ne me suis jamais endormi dans le bus et j’ai dépassé ma station."},
    {pack_name:"never_popular",language:"fr",text:"Je ne me suis jamais enregistré en train de chanter."},
    {pack_name:"never_popular",language:"fr",text:"Je ne me suis jamais fait(e) arrêté(e)."},
    {pack_name:"never_popular",language:"fr",text:"Je ne me suis jamais mis le doigt dans le nez en public."},
    {pack_name:"never_popular",language:"fr",text:"Je ne me suis jamais moqué de quelqu’un."},
    {pack_name:"never_popular",language:"fr",text:"Je ne me suis jamais mordu la langue."},
    {pack_name:"never_popular",language:"fr",text:"Je ne me suis jamais rasé l'anus."},
    {pack_name:"never_popular",language:"fr",text:"Je ne me suis jamais rasé les parties intimes."},
    {pack_name:"never_popular",language:"fr",text:"Je ne me suis jamais réveillé ivre le lendemain."},
    {pack_name:"never_popular",language:"fr",text:"Je ne me suis jamais saoulé avec mes parents."},
    {pack_name:"never_popular",language:"fr",text:"Je ne ne me suis jamais pissé dessus."},
    {pack_name:"never_popular",language:"fr",text:"Je ne suis jamais allé à l'église."},
    {pack_name:"never_popular",language:"fr",text:"Je ne suis jamais allé(e) au travail bourré."},
    {pack_name:"never_popular",language:"fr",text:"Je ne suis jamais allée aux toilettes sans me laver les mains."},
    {pack_name:"never_popular",language:"fr",text:"Je ne suis jamais allée à une fête sans y avoir été invité(e)."},
    {pack_name:"never_popular",language:"fr",text:"Je ne suis jamais tombée amoureux de quelqu’un à travers le réseau."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais attrapé la main de la mauvaise personne."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais calé en voiture."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais cessé de me souvenir de mon premier amour."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais combattu dans la rue."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais compris la tektonik."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais compris pourquoi les artistes de la Renaissance avaient des noms de tortues ninjas."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais conduit ivre."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais de chewing-gum quand j’en ai le plus besoin."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais demandé à mon boss si sa fille était bonne."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dit un “je t’aime” sans le ressentir."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dit “je t’aime” juste pour baiser."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais dormi au cinéma."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais douté de mon hétérosexualité."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais embrassé mon meilleur ami."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais embrassé quelqu’un du même sexe."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais embrassé quelqu’un sans le connaître."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais espionné mes voisins."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais essayé de découvrir mon orientation sexuelle."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu de coup d’un soir."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu de relation ouverte."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais eu d’amis avec bénéfices."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait caca chez ma belle-famille."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait de photos en sous-vêtements."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait l’amour avec quelqu’un de l’université."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait pipi contre le vent."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fait quelque chose que je regrette."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais fumé de marijuana."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais harcelé le petit ami ou la petite amie d’un ex sur les réseaux sociaux."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mangé de nourriture qui tombait par terre."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais menti dans ce jeu."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais menti à mes parents sur l’endroit où je vais."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais menti à mes parents à propos de la gueule de bois."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais menti à mon/ma partenaire."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais menti à un ami pour éviter un plus grand mal."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais merdé à l’école."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais mis de chewing-gum sous un bureau."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais nagé nue dans une piscine / plage."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais parié sur quelque chose."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais participé à un concours de talents."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pensé vendre des préservatifs goût hostie au Vatican."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais pris illégalement quelque chose de l’autre côté de la frontière."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais quitté la France."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais redoublé."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais refusé un baiser."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais regardé les Anges de la télé réalité."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais reçu de sérénade."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais révélé que j’étais un super héros."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais servi du bifteck à ma nièce et dit ensuite que c’était la mère de Bambi."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais sécher les cours."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais triché à un examen."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais volé quelque chose d’une valeur supérieure à 10 €."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais voulu tomber amoureuse de l’ami de ma sœur ou de mon frère."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais voyagé en avion."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais vraiment aimé une chanson de Justin Bieber."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais vu de seins nus sur la plage."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais vu un porno de ma vie."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été amoureuse de mon professeur à I’université."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été avec l’ancien amour de mon meilleur ami."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été bourré."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été cambriolé."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été coincé dans un ascenseur."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été infidèle."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été ivre en jouant à ces jeux."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été ivre."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été menotté."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été sur Facebook enivré."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été viré d’un bar."},
    {pack_name:"never_popular",language:"fr",text:"Je n'ai jamais été à une fête en douce."}];
    game.pending_db = game.pending_db.concat(game.stored_db.never_popular_fr);