game.stored_db.never_hot_fr = [{pack_name:"never_hot",language:"fr",text:"Je n'ai jamais accepté de faire du sexe avec mon copain pour avoir la paix."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais accepté quelque chose dont je n'avais pas envie."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais acheté de preservatifs."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais acheté une tenue sexy pour faire plaisir à mon copain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais aimé faire des cunnis."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais aimé faire l'amour plus d'une fois dans la même nuit."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais aimé les cunnilingus."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais aimé me faire lécher les orteils."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais aimé me faire mordre lors d'une relation sexuelle."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais aimé quelqu'un de largement plus vieux que moi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais aimé recevoir des fessées pendant l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais aimé une photo de profil sexy dans le but de draguer la fille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais appelé mon copain par un petit surnom (bébé,  coeur, amour, chou ... )."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais appelé mon partenaire par le prénom d'un de mes exs."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais arrêté de penser à un ex."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais attaché ma copine avec des menottes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais attaché ma partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais avalé de lait précieux de mon partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais avorté."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais avoué mes sentiments à une personne dans cette piece."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais avoué à un ex que je l'avais trompé."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais baissé mon pantalon en public."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais baisé dans une baignoire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais baisé à la fac."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais bandé les yeux de ma partenaire pendant l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais bu au travail."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais bu d'alcool exprès pour aller parler à une fille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais bu un shot sur le nombril de quelqu'un."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais caché mes relations amoureuses à mes parents."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais caché mon petit copain à mes parents."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais cassé avec la même personne plus d‘une fois."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais cassé le lit en faisant l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais cassé mes talons."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais cassé un lavabo en faisant l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais cassé un meuble en faisant l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais cassé un objet en faisant l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais cassé un évier."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais chanté sous la douche."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais chatouillé ma(mon) partenair(e) avec ma moustache."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais chauffé mon partenaire par texto."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais chauffé un mec pour le planter au dernier moment."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais chuté en faisant l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais chuté parce que j'avais trop bu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais clické sur la pub en bas de cette super application :)."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais compris pourquoi les hommes aiment voir deux femmes coucher ensemble."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais compris pourquoi les hommes fantasment sur les infirmières."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais compté mon nombre de conquêtes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais connu d'étalon."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais consommé de drogue."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais continué d'aimer mon ex."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec 2 filles différentes le même jour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec 2 personnes de la même famille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec deux meilleurs amis."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec l'ex d'un(e) de mes ami(e)s."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec l'ex d'un/e meilleur/e ami/e."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec l'ex d'une amie."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec l'un de vous (autour de la table)."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec la copine de mon meilleur ami."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec la lumière allumée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec la mère d'un ami."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec la même personne que mon meilleur ami."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec la première personne venue tellement j'étais en manque."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec le partenaire d'un ami."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec le père de mon mec."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec mon boss."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec mon ex en étant avec un(e) autre."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec mon partenaire de droite."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec mon/ma voisin(e)."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec plus d'une personne dans cette pièce ."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec plus de 3 personnes dans la même semaine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec quelqu'un avant mes 17 ans."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec quelqu'un dans cette piece."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec quelqu'un dans la pièce."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec quelqu'un dans les toilettes d'une boîte de nuit."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec quelqu'un de ma classe."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec quelqu'un de Tinder."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec quelqu'un de vierge."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec quelqu'un dont était amoureuse une de mes copines."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec quelqu'un en couple."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec quelqu'un ici présent."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec quelqu'un qui avait déjà un(e) copain(ine)."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec quelqu'un qui avait un piercing génital."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec quelqu'un sur un bureau."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec quelqu'un tandis qu'il y avait quelqu'un dans la même pièce."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec un ami quand mon propre copain était en train de me chauffer par SMS."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec un blond."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec un canadien."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec un collègue de travail."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec un homme ayant des enfants."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec un homme d'origine africaine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec un homme sur une machine à laver."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec un inconnu dans un endroit insolite."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec un mec dans les vestiaires de la piscine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec un mec juste pour combler un manque."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec un voisin."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec un/une étranger/e ne parlant pas ma langue."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec une femme plus grande que moi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec une femme qui avait des enfants."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec une fille sans cervelle."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec une milf."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec une personne dans ces sept derniers jours."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec une personne du même sexe."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec une personne par simple fierté."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec une personne rousse."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché dans le lit de ma soeur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché en pleine nuit sur un parking."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché le premier soir."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché plus de 20 fois dans un week-end\n."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché à l'internat."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couru tout nu dans la rue."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couru tout nu dans les champs."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couru toute nue dans la maison."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais craché."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais crié \" je suis superman \" en faisant l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais crié au lit."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais crié durant une relation sexuelle."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais crié un autre nom que celui de mon partenaire au lit."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais cru aller aux toilettes et me suis retrouvée à l'extérieur de la boîte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais cru être enceinte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais côtoyé de petits popols."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dansé de façon sexy sur la plage."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dansé de façon vulgaire pour faire rager un ancien partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais demandé à la fille de me mettre le preservatif."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dis à ma copine de faire des cris pendant l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais disparu d'une soirée pour aller faire l'amour avec mon partenaire, puis y être retourner après l'air de rien ."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dit \"ne m'oublie pas\" après une rupture."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dit je t'aime par texto."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dit je t'aime sans le pensé."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dit je t'aime sincèrement."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dit je t'aime à mon partenaire pendant l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dit je t'aime."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dit à ma copine que je la trouvait en surpoids lors d'un dîner en amoureux."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dit à ma/mon partenaire qu'elle/il ne sentait pas bon d'en bas."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dit à mon copain qui portait un préservatif fluorescent: \"que la force soit avec toi\"."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dit à une fille que je l'aimais juste pour coucher avec elle."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dit être homosexuelle en soirée pour qu'un homme un peu trop entreprenant me lâche."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais donné une fessée pendant un rapport."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais donné à quelqu'un un faux numéro de téléphone."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais donné/obtenu une pipe au volant."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dormi dans un bar."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dormi nu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dormi pendant un rapport."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dragué avec l'application \"Je n'ai Jamais\"."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dragué la meilleure amie de ma copine sous ses yeux."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dragué la meuf d'un pote ou d'une connaissance."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dragué le/la petit(e) ami(e) d'un ami."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dragué sur un jeu vidéo."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais dragué un professeur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais désiré la soeur de ma copine..."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais désiré mon professeur..."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais effectué de position habillée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais emballé une fille avec la langue."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé 3 personnes différentes ou plus dans la même soirée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé avec la langue quelqu'un de cette piece."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé deux copines qui sont amies."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé deux filles dans la même journée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé deux garçons qui sont amis."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé deux personnes de la même famille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé deux personnes en même temps."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé plus d'une personne par soirée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé plus de 3 filles dans la même soirée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé plus de 5 gars dans une même soirée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé plus de 5 mecs à la même soirée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé quelqu un sous l eau."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé quelqu'un après avoir vomi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé quelqu'un autre que ma copine dans cette pièce."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé quelqu'un ayant un piercing à la langue."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé quelqu'un de cette pièce."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé quelqu'un du même sexe."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé quelqu'un par dépit."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé quelqu'un sur la bouche dans cette pièce."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé un americain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé un ami de mon ex."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé un mec aux yeux bleus."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé un miroir."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé un travesti."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé une brune."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé une fille aux yeux marron."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé une fille aux yeux verts."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé une fille devant son mec."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé une personne du meme sexe que moi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé une personne rousse."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé une personne âgé de 10 ans de plus que moi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais entendu baiser mon voisin pour ensuite commencer à faire l'amour de mon côté."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais entendu mon nom pendant un rapport."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais envié une autre personne ici."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais envoyé de nudes au mauvais numéro."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais envoyé de sexto."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais envoyé de sms embarassant au mauvais destinataire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais envoyé ou reçu de texto érotiques."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais envoyé une de mes photos sexy à mon boss par erreur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais envoyé une photo de moi dénudée à quelqu'un."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais envoyé/reçu une photo du sexe de mon partenaire sur mon portable."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais envoyée une photo de mes clémentines."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais espionné mes voisins."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais espionné quelqu'un en train de faire des choses coquines."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais espéré me marier (finir ma vie) avec quelqu'un ici présent."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais espéré être un homme pour pouvoir bander."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais essayé de faire l'amour a des aliments."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais essayé de jeux de rôles."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais essayé de m'auto-sucer."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais essayé de m'autosucer."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais essayé de me faire une fellation tout seul."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais essayé de sentir la taille de l'engin avec mes fesses pendant un zook."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais essayé le sexe anal."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais essayé un club echangiste."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu 2 mecs en même temps."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu d'appel coquin avec ma/mon partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu d'arrières pensées en regardant une fille manger une banane."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu d'attirance sexuelle pour une personne se trouvant dans la pièce."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu d'aventure dans un cinéma."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu d'enfant."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu d'enfants."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu d'histoire d'un soir."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu d'ITS."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu d'orgasme avec mon copain actuel."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu d'orgasme."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu d'orgasmes sans crier."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de bleu après l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de copain qui ont pleuré pour moi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de copine qui ont pleuré pour moi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de coup d un soir."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de courbature après l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de courbatures après avoir fait un peu trop l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de crampes en pleine action."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de fantasmes sur la soeur d'une de mes copines."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de fellation debout."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de flatulences à côté de ma partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de gâterie par deux femmes en même temps."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de gâterie pendant que je jouais à la console."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de massage sexuel."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de mauvaise réputation."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de mst."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de panne."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de pensée impure envers un membre de ma famille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de percing intime."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de petit coup rapide."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de petits déjeuners alcoolisés."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de photos de ma copine nue ou en sous-vêtements."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de plan coquin régulier."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de rapport avec mon mec dans le lit de mon ex."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de rapport en plein air."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de rapport sexuel non protégé."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de rapport sous l'eau."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de rapports sexuels avec un partenaire d'une autre origine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relation avec 2 hommes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relation avec 2 personnes de la même famille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relation avec un mec qui fini toujours trop tôt."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relation dans un ascenseur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relation sexuelle avec deux personnes au moins dans cette pièce."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relation sexuelle dans un aéroport."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relation sérieuse."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relations dans une cabine d’essayage."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relations sexuelles avant l'âge de mes 13 ans."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relations sexuelles avec deux femmes en même temps."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relations sexuelles avec plus d'une personne dans cette pièce."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relations sexuelles avec quelqu'un dans cette pièce."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relations sexuelles avec quelqu'un qui avait le double de mon âge."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relations sexuelles avec un ex."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relations sexuelles avec une personne de très petite taille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relations sexuelles à 3."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de rendez-vous amoureux avec quelqu'un juste pour faire souffrir quelqu'un."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de rêve érotique."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de sexfriend."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de suçon autre part que dans le cou."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de suçon."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de tache blanche sur un vêtement."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de tache de sperme sur mes habits."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de tatouage."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de trip scatophile."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu des envies sadomasochistes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu deux \"rendez-vous\" amoureux dans la même journée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envi d'embrasser quelqu'un de present aujourd'hui."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envi d'un doigt dans les fesses."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie d'aller aux toilettes pendant que je faisais l amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie d'embrasser quelqu'un d'ici lors d'une soirée où j'étais bourrée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie d'etre seul avec une personne dans cette salle."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie d'un mec au moment ou je lis \"je n'ai jamais\"."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie d'être fouetté pendant l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie de changer de partenaire juste pour une nuit (ou plus)."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie de coucher avec un ou une de mes ami(e)s."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie de faire des plans à trois."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie de faire l'acte dans une caravane."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie de la personne en face de moi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie de me faire le père, la mère d'un.e ami.e."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie de me faire sodomiser."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie de me masturber avec mon téléphone."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie de tromper mon copain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie de tromper mon/ma partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie que ça se finisse vite."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu envie quelqu'un ici présent."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu fortement envi de quelqu'un dans cette piece ."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu l'envie de me toucher."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu l'impression d avoir été naïve."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu l'intention de tromper mon copain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu l'occasion de lui dire ce que je ressentais vraiment."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu le nez de \"pinocchio\" à la piscine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu le trou interdit titillé lors d'un rapport.."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu mes petites clémentines mordues."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu peur d'avoir un enfant."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu peur d'être enceinte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu peur qu'un homme est un trop petit membre pour me donner du plaisir."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu plus d'un orgasme pendant l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu plus de 5 partenaires."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu plus de 5 plans cul en même temps."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu plus de 10 conquêtes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu plus de 20 conquêtes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu plus de 20 partenaires differents."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu plus de plaisir qu'avec ma copine ou mon copain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu un fou rire pendant l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu un manque de confiance envers mon (ma) partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu un onenight non protégé."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu une partenaire aussi sexy que mon actuelle copine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu une relation sexuelle avec des personnes dans la même pièce que nous."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu une tête de coker anglais pour coucher."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu une érection spontannée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais excité quelqu'un uniquement en dansant."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais excité un mec, sans les mains."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais exibé mon penis en public."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fais l'amour en dehors d'une maison."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fais une chute en faisant l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait aucune position du kamasutra."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait cocu ma conjointe."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait cocu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait craqué le lit en plein acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de branlette espagnole."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de cochoneries dans un cinema."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de cochonneries dans un cinéma."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de demande en mariage."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de fellation dans le coffre d'une voiture."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de gorges profondes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de jeu de \"dés sexy\" avec mon partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de jeux d'alcool."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de jeux érotiques."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de lavement anal."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de massage sensuel à un gars."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de plan à 3."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de plan à 4."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de préliminaires avec deux personnes en même temps."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de quizz sexy sur tasanté.com ou doctissimo.com."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de rêve blanc."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de sexcam."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de StreapTease à un.e inconnu.e."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de strip tease."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de strip-tease intégral."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de strip-tease sur un comptoir de bar."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de stripteases."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de suçon."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de tatouages."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de test de grossesse."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de truc à l'arrière d'une voiture alors que des personnes conduisaient."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de vidéo pendant un rapport."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de vidéo sexy."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait de voyeurisme."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait des choses avec mon partenaire sous la douche."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait des choses non catholiques au lycée.."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait des cochonneries dans une soirée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait des jeux de rôles avec mon partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait des préliminaires dans un amphi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait des réflexions à mon partenaire sur sa manière de faire l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait espérer un mec dans le but d'obtenir quelque chose."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l amour avec quelqu'un de plus âgé que moi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l amour dans un bar."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l amour à quatre pattes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte au golf."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte avec de la musique et cru être dans un clip de Booba."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte avec des gens autour de moi.."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte avec du chocolat."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte avec plusieurs couples en même temps."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte avec un militaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte avec un/une amie."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans l'eau avec mon partenaire quand mes parents étaient à côté."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans les bois."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans les toilettes d'un avion."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans les toilettes du McDonald."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans un ascenseur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans un champ."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans un endroit insolite."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans un hammam."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans un restaurants ou un fast food."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans un sac de couchage."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans un tracteur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans un train."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans une cuisine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans une douche."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans une tente."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte depuis plus de 7 jours."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte devant un film."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte devant un match de foot."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte en gardant mes chaussures."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte en pleine nature."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte les yeux bandés."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte sans me déshabiller complètement."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte sans me protéger."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte saoul."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte sur la banquette arrière d'une voiture."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte sur la plage."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte sur le plan de travail."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte sur mon lieu de travail."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte sur un lavabo."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte sur un trampoline."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte sur une banquette arrière ."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte sur une machine à laver en mode essorage."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte sur une machine à laver."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte sur une table de billard."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte à la première rencontre."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte à quelqu'un qui était tatoué ou percé."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour au bar."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour au travail."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour avec des chaussettes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour avec quelqu'un en uniforme."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour avec un copain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour contre un mur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans des catacombes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans des escaliers."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans la chambre d'un ami."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans la forêt."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans la rue."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans les bois."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans les toilettes de la fac."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans les wc d'une discothéque."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans mon jardin."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans un ascenseur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans un cinéma."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans un endroit insolite."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans un lieu public."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans un placard."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans un spa."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans une boite de nuit."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans une chapelle."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans une cuisine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans une salle de bain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans une tente."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans une toilette publique."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dans une voiture."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour dehors."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour devant des ami.es."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour devant un \"public\"."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour devant un miroir."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour défoncé."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour en restant à moitié habillé."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour en étant non protégée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour pendant mon sommeil."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour plus de 5 fois dans la même nuit."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour sauvagement."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour sur la plage."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour sur la table de cuisine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour sur la table à manger familiale."},
    {pack_name:"never_hot",language:"fr",text:"je n'ai jamais fait l'amour sur le canapé de mes parents."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour sur un balcon."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour sur un bateau."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour sur un muret."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour sur une chaise."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour à distance."},
    {pack_name:"never_hot",language:"fr",text:"je n'ai jamais fait l'amour à ma copine car elle portait des portes-jarretelles."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour à même le sol."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour à plus de 10 mètres du sol."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour à un homme très poilu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour à une femme."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait la faux-cul avec quelqu'un présent ici."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait la salope."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait le 69."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait le contorsionniste pour me faire plaisir moi-même."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait le mur pour coucher avec mon copain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait le premier pas."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait le superman."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait les préliminaires dans un lieu publique."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l‘amour dans un endroit public."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait orgasmer ma copine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait pipi dans une bouteille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait plus de 5 fois l'acte en une nuit."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait plus de 7 fois l'acte en une journée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait plus que des bisous dans un bar ou une discothèque."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait semblant d'avoir oublié ce qui s'était passé lors d'une soirée trop arrosée parce que je n'assume pas ma \"conquête\"."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait semblant d'être gay en boite ."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait semblant d'être malade pour ne pas le faire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait un clin d'oeil à un garçon inconnu qui me plaisait."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait un flop en soirée en faisant une blague nulle."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait un sextape."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait un striptease à quelqu'un."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait une branlette espagnole."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait une erreur de trou."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait une gâterie à mon copain pendant qu'il était sur l'ordinateur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait/eu de 'footjob'."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait/reçu de fellation avec un glaçon."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fanstasmé sur mon propre copain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fantasmé ou fait l'amour avec le colocataire d'un membre de ma famille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fantasmé sur la mère d'un ami."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fantasmé sur les exs des mes ami(es)."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fantasmé sur ma meilleure amie."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fantasmé sur mon beau-père."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fantasmé sur quelqu'un de + jeune."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fantasmé sur un italien."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fantasmé sur un professeur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fantasmé sur un uniforme."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fantasmé sur un(e) joueur(se) ici présent(e) après avoir entendu ses réponses aux \"je n'ai jamais\"."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fantasmé sur une autre femme en présence de ma conjointe."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fantasmé sur une femme que j'ai croisée dans la rue."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fantasmé sur une personne du même sexe."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fini lors d'une fellation."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fini trop tôt."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais flashé sur un acteur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais flashé sur un prof."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais flatulé au nez de ma copine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fleurté avec quelqu'un dans cette pièce."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fleurté voir sortir avec le meilleur ami de mon ex juste pour me venger de lui."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais flirté avec une personne que je trouvais moche pour un pari ou autre."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais forcé quelqu'un."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais frappé les fesses de ma copine en faisant l amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fréquenté de club échangiste."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fréquenté plus d'une personne en même temps."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fumé de chicha."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fumé de drogue."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fumé un mégot écrasé dans le cendrier."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fumé une cigarette pendant les préliminaires."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais galéré à ouvrir l'emballage d'un préservatif."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais goûté du sperme ou de la cyprine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais griffé mon partenaire pendant l'acte, au point qu'il en ai des marques le lendemain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais harcelé mon copain pour faire l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais ignoré un appel de ma copine même si elle est chiante."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais imaginé ma copine se battre dans la boue avec une autre fille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais imaginé mes parents en pleine action."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais initié mes potes au sexe."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais insulté mon fiancé."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais intentionnellement effleuré les Lèvres d'une femme."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais inventé de faux petit ami."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais jamais embrassé un gars sans en parler à mes amies."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais jamais eu de sex friend."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais jetté un tampon sur le terrain du voisin."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais jeté un sextoy sur un de mes partenaires."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais joui dans la bouche de quelqu'un."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais joui plusieurs fois d'affilée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais joué au Strip Poker."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais joué avec la poitrine de ma copine/partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais joué avec ma langue et l'arrière de mon partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais joué avec mon corps sous la douche."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais joué avec mon portable dans les toilettes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais joué avec une saucisse pour chauffer un mec."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais joué seul avec mon rectum."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais joué à \"je n'ai jamais\"."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais joué à action/vérité sexy avec une personne en couple."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais joué à des jeux de domination."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais joué à la maman et au papa quand j'étais petite."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais laissé traîner une capote usagée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais lancé des pieces sur une femme fontaine en faisant un voeu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais leché les testicules de mon copain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais levé ma jambe comme dans les films en embrassant un mec."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais lu de livre érotique."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais lu le Kama Sutra."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais lu le kamasoutra."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais léché le cou de mon copain ou ma copine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais léché le doigt de mon partenaire pour le \"motiver\"."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais léché les pieds de mon partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais léché les tetons de ma copine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais léché un anus."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mangé \"one cup\" avec une copine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mangé d'aliments sur le corps d'une personne."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mangé de croquettes pour animaux."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mangé de nourriture sur mon partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mangé une banane sur l'abricot d'une femme."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mangé une tranche de jambon cru sur les petites clémentines de ma copine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais marché nu sur une plage."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais matté un de mes profs."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais maté mon/ma colloque."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais maté quelqu'un autour de cette table."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti aujourd'hui à ce jeu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti concernant mes sentiments."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti dans ce jeu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti sur la longueur de mon sexe."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti sur le nombre de relation sexuelle que j'ai eu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti sur le nombre de relations à quelqu'un."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti sur les capacités de mon homme ."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti sur mes performances sexuelles à mes potes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti sur mes sorties à ma conjointe."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti sur mon âge."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti à ce jeu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti à ma copine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti à un/e partenaire en le/la complimentant sur ses performances sexuelles."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti à une fille pour coucher avec elle."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mis de nourriture sur les parties génitales de mon copain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mis de préservatif avec ma bouche."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mis de string."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mis de stérilet."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mis de tampons."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mis la main au derrière d'un inconnu en pensant que c'était mon chéri ."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mis mon doigt dans mon cul."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mis mon sexe dans un aspirateur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mis quoi que ce soit dans mon derrière."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mis un pénis entre mes seins."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mis un suppositoire à mon partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais montré un message coquin d'une fille à mes potes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mordillé ou griffé mon partenaire pendant l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mordu l'engin de mon partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mordu le sein d'une partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mordu sans le vouloir mon compagnon lors d'une felation."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais mordu un doigt."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais nagé  toute nue dans l'eau."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais nagé tout(e) nu(e)"},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais offert mon petit lait précieux à une bouche."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais osé avouer mes sentiments à quelqu'un dans cette pièce."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais osé dire à ma copine qu'elle avait (légèrement) grossi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais oublié d'aller à un rdv amoureux."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais oublié d'effacer mon historique internet."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais oublié l'anniversaire de ma copine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais oublié la fille avec qui j'ai eu ma première relation sexuelle."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais oublié le prénom d'un coup d'un soir."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais oublié ma première fois."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais oublié mon ex."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais oublié un sous vêtement chez un amant."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais parlé de mes exploits sexuels à mes potes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais parlé de sexe avec des amis."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais parlé de sexe avec mes copines."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais parlé de sexe avec mes parents."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais parlé de sexe avec mon frère/ ma soeur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais parlé plus fort que d'habitude à côté de quelqu'un pour qu'il me remarque\n."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais passé plus de 6 mois sans faire l'amour (après la première fois)."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais payé quelqu'un pour avoir une relation."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pensé coucher avec la/le partenaire d'un de mes amis."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pensé que je pourrais avoir une MST."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pensé sortir avec quelqu'un ici présent."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pensé à devenir acteur de film X."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pensé à faire de l'anal."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pensé à faire du cinéma X."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pensé à la mère d'un ami."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pensé à quelqu'un d'autre pendant l'acte.."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pensé à quelqu'un d'autre que mon partenaire quand je faisais l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pensé à un autre en couchant avec mon copain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pensé à une amie en me masturbant."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pensé à une autre personne pendant l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais perdu connaissance au cours de l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais perdu de préservatif dans le corps de quelqu'un."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais perdu un de mes sous vêtement dans un lieux public."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pleuré après avoir fait l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pleuré devant un film."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pleuré en lisant un sms."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pleuré pour un ex que je n arrive pas oublier."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pleuré pour un garçon."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais porté de lingerie sensuelle pour surprendre mon partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais porté de string pour homme."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais poussé un couple à casser."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pratiqué de 69."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pratiqué l'auto-masturbation."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pratiqué la masturbation devant un pote."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pratiqué la masturbation en pensant à une personne présente dans cette pièce."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pratiqué la sodomie."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pratiqué le sex hard."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pris avantage de quelqu'un alors qu'il avait bu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pris de bain avec une autre fille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pris de cuite."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pris de rateau."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pris de vent en demandant à mon partenaire de faire l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pris de viagra sans le dire à ma copine pour 'performer'."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pris la pilule du lendemain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pris la tension de mon engin (dédicace aux corps médical...)."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pris mon pied sous la couette."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pris toute la place dans un lit alors qu'on été deux."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pris un labello comme objet coquin."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pris un râteau par une personne ici présente."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais profité sexuellement de ma partenaire alors qu'elle avait bu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais profité sexuellement de mon partenaire alors qu'il avait bu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pété dans un jaccuzi pour faire croire qu'il fonctionnait\n."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pété en faisant l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pété en présence de ma copine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais pété en public."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais quitté ma copine parce qu'elle était loin de chez moi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais quitté un amant avant qu'il se réveille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais raconté mes exploits sexuels."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais rasé mes parties."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais rasé mon entrejambe."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais raté mon epilation."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais recouché avec un ex."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais refait mes seins."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais refusé de faire l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais refusé de pratiquer le sexe oral en raison de l'odeur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais refusé un baiser."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regardé des films coquins toute seule en attendant mon mec."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regardé la tv dans les toilettes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regardé la télé en faisant l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regardé le membre d'un autre homme aux urinoires pour comparer la taille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regardé les messages privés d'une personne que je n'aimais pas."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regardé mon corps nu dans un mirroir."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regardé un film porno."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regardé un film X alors que mon ou ma conjointe dormait."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regardé un homme se masturbé en me touchant moi aussi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regardé un match de rugby juste pour voir le derrière des joueurs."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regretté d'avoir couché avec quelqu'un."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regretté d'avoir fait ma première fois."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regretté de l avoir fait avec quelqu'un."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regretté des actes sexuels."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regretté être sorti avec quelqu'un."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais rembourré mes soutiens-gorges."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais rembouré mes soutifs."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais repris contact avec mon ex par désespoir sexuel."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais retenu un pipi pressant pour avoir plus de plaisir pendant l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais reussi à donner du plaisir avec un cunnilingus."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais revé de changer de sexe pour une journée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais revêtu de déguisement pour un jeu coquin."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais reçu de faciale."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais reçu de fessé en position de levrette."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais reçu de photos érotiques."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais reçu ou donné de fessées pendant l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais reçu une fellation dans les toilettes d'une discothèque."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais rien fait sur mon lieu de travail."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais rigolé du sexe de mon copain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais roulé de pelle à une personne autre que mon/ma partenaire autour de cette table."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais réalisé un de mes fantasmes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais réclamé après du Sexe."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais réussi à voir ma voisine d'en face en petite tenu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais réveillé mes parents en baisant."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais révé que j'avais un orgasme."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais rêvé d'une personne présente dans cette salle."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais rêvé d'être un vampire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais rêvé de coucher avec un homme célèbre."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais rêvé que je faisais l amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais saoulé une personne pour avoir plus de chance ..."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais senti mes doigts après m'être gratté l'anus ou les parties génitales."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais simulé ."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais simulé avec ma copine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais simulé."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais sniffé du popers."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais souhaité avoir de plus grosses petites clémentines."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais souhaité coucher avec un(e) ex et mon/ma copin(e) actuel(le) en même temps."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais souhaité que mon partenaire soit plus performant."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais squirté."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais su si mes voisins m'avaient vu toute nue par la fenêtre..."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais sucé le sex de 2 mecs la même soirée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais sucé une glace sensuellement devant un homme.."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais suivi quelqu'un."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais supplié mon partenaire pour une felation."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais surpris ma copine en train de se faire plaisir elle-même."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais surpris un membre de ma famille en train de se faire plaisir .."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais taché le divan ou lit d'un(e) ami(e)."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais tenté d'approcher le trou interdit de ma partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais tenu 2 sexes masculins dans mes mains en même temps."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais terminé en soutif lors d'une soirée.."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais touché de gros melons."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais touché des gros melons (sup à bonnet D)."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais touché le sterilet de ma copine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais trompé ma copine avec quelqu'un qu'elle connaissait."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais trompé mon partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais trompé personne."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais trouvé de film X dans le tiroir de mes parents."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais trouvé un de mes ex plus beau que mon copain actuel."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais téléphoné pendant des préliminaires."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais un peu trop parlé en jouant à ce jeu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais uriné dans une baignoire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais uriné en public."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utiliser le poing en entier..."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé d'anneau vibrant."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé d'objet coquin avec ma copine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé d'objet du quotidien comme objet sexuel."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé de capotes fluorescentes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé de fouet lors d'un rapport."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé de glaçons pour des préliminaires."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé de Gode."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé de jouets sexuels."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé de la nourriture sur mon corps."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé de lubrifiant."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé de plug anal."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé de popers."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé de preservatif féminin."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé de préservatif."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé des boules de geisha."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé l'engin de mon partenaire comme un micro."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé le sexe de mon copain pour chatouiller mon clitoris."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé un jouet coquin devant mon copain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé un objet/accessoire pour me faire plaisir."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé une carte routière ou tout prospectus en guise de papier toilette."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais volé la culotte d'un.e ex."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais vomi au travail."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais vomi dans un lavabo."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais vomi du fait de l'alcool."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais vomi en public."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais voulu coucher avec ma belle soeur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais voulu coucher avec quelqu'un de ma classe."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais voulu embrasser ma voisine de droite."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais voulu embrasser quelqu'un de cette pièce."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais voulu me faire un tatouage à un endroit sexy (poitrine, fesses, cou, bas du ventre, cuisse)."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais voulu passer une soirée en tête à tête avec une personne ici présente."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais voulu sortir avec quelqu'un par intérêt."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais voulu voir nu quelqu'un autour de ce cercle."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais voulu voler la copine d'un pote."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais vu de film pornographique."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais vu de sextoy."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais vu en vrai le zizi d'un autre garçon."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais vu les attributs d'une personne autour de moi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais vu mes amis faire l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais vu mes parents nus."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais vu quelqu'un nu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais vu un mec se faire plaisir seul."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais vu une fille ici présente en sous-vêtements."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais  fait l'acte dans une cabime d'essayage dans un magasin de lingerie."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais éclaté de rire lors d'un rapport."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais écouté aux murs pour entendre mes voisins faire l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais épilé mon mec."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais éteint la lumière lors d'un rapport juste pour ne pas voir le visage de mon partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais éternué les yeux ouverts."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais éternué lors d'une fellation."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais étudié le kamasutra."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été ami d'un.e ex."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été amoureuse de la personne en face de moi."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été amoureux de quelqu'un du même sexe."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été amoureux."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été attaché au lit."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été attirée par une personne de ce cercle."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été aussi célibataire qu'aujourd'hui."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été avec quelqu'un d'un autre pays."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été avec quelqu'un qui ne me plaisait pas."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été avec une célébrité."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été avec une personne de ma famille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été bourré chez des inconnus."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été cocu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été contrôlé par la police pendant un acte tard dans une voiture."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été coupé en me rasant."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été dans la même pièce que 2 personnes ou plus avec qui j'ai déjà couché."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été dans un salon érotique."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été dans un village naturiste."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été dans une piscine tout nu."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été dragué par mon patron."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été dégoûté par ma partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été déguisé en travesti."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été déçu du corps de ma copine."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été déçue en voyant pour la première fois le popol de mon partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été en boite de nuit."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été en cour pour travailler."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été en garde à vue."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été en kiff sur quelqun de cette piece."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été en manque de sex."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été en manque de sexe."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été en prison."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été en soirée échangiste."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été en sous vêtements devant mes amis."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été enceinte/faite tombé une femme enceinte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été ennuyée pendant un rapport sexuel."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été excité devant un film X."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été excité en voyant ma prof."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été fait de préliminaire en cours."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été fidèle lorsque j étais en couple."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été filmée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été frustrée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été grillé par un de mes parents entrain de se faire plaisir."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été génée par mes poils pendant un rapport."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été infidèle."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été jalouse de l'officielle en sachant que je n'étais qu'un plan cul."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été masturbé par des pieds."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été me faire plaisir dans les toilettes."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été me faire plaisir seul alors que j'étais en couple."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été menottée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été payé pour faire l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été père."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été recalée en boîte de nuit."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été recalée en boîte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été remercié après l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été réveillé par une gaterie."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été satisfait d'une partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été sodomisée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été sodomite, de manière insertive ou réceptive."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été soumis."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été supris en pleine action."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été sur chatroulette."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été sur un site X."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été surpris en pleine action par mes parents."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été surpris par autrui lorsque je faisais l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été surprise par les parents de mon copain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été surprise par mon père au lit."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été surprise par un enfant de moins de 10 ans en train de faire l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été trahie par un ex."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été trompé."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été très bruyante pendant l'acte pour emmerder les voisins."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été une fetichiste des nombrils."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été voir une prostituée."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été vraiment amoureux."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été à une soirée spéciale objets coquins."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai pas couché avec plus de 5 personnes dans ma vie."},
    {pack_name:"never_hot",language:"fr",text:"Je ne me suis jamais baigné tout.e nu.e."},
    {pack_name:"never_hot",language:"fr",text:"Je ne me suis jamais baladé nu chez ma copine."},
    {pack_name:"never_hot",language:"fr",text:"Je ne me suis jamais endormi pendant l'acte."},
    {pack_name:"never_hot",language:"fr",text:"Je ne me suis jamais fait arrêter par la police."},
    {pack_name:"never_hot",language:"fr",text:"Je ne me suis jamais fait léché les pieds pour une somme d'argent."},
    {pack_name:"never_hot",language:"fr",text:"Je ne me suis jamais masturbé dans un lieu public."},
    {pack_name:"never_hot",language:"fr",text:"Je ne me suis jamais masturbé à côté de quelqu'un, sans que cette personne ne le sache."},
    {pack_name:"never_hot",language:"fr",text:"Je ne me suis jamais masturbé(e) à l'extérieur."},
    {pack_name:"never_hot",language:"fr",text:"Je ne me suis jamais prostitué."},
    {pack_name:"never_hot",language:"fr",text:"Je ne me suis jamais stimulé la prostate."},
    {pack_name:"never_hot",language:"fr",text:"Je ne me suis jamais trompé de prénom pendant l'amour."},
    {pack_name:"never_hot",language:"fr",text:"Je ne suis jamais parti avant que la personne se réveille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais consommé de drogues."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais couché avec la mère d’un pote."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais craqué le canapé d’un copain en faisant l'acte dessus."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais embrassé quelqu’un du sexe opposé."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais envoyé une photo de moi nu(e)."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais eu de relations sexuelles à l’école/au travail."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte avec deux hommes différents la même nuit."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte dans les toilettes de la fac."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l'acte sans m’en rappeler le lendemain."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait la grosse commission chez ma belle-famille."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait le naked man."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l’amour avec deux personnes à la fois."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fait l’amour à l’extérieur."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais fantasmé sur quelqu’un dans la pièce."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais lécher un anus."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais maté en présence de ma partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais menti au je n'ai jamais (santé !)."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais regardé des gens faire l’amour."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais simulé au lit."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais tenu deux popols dans mes mains en même temps."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais trompé ma/mon partenaire."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais utilisé de sextoys."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais vu en vrai le popol d’un garçon."},
    {pack_name:"never_hot",language:"fr",text:"Je n'ai jamais été embarqué par les flics."},
    {pack_name:"never_hot",language:"fr",text:"Tout le monde boit (avec modération)."}];
    game.pending_db = game.pending_db.concat(game.stored_db.never_hot_fr);