game.stored_db.never_party_fr = [{pack_name:"never_party",language:"fr",text:"Jamais je ne me suis habillé en couple pour l'Halloween."},
    {pack_name:"never_party",language:"fr",text:"Jamais je ne suis tombé d'un lit quand j'étais ivre."},
    {pack_name:"never_party",language:"fr",text:"Jamais je ne suis tombé à cause de l'alcool."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai acheté ou vendu de drogue."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais acheté de sextoy."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais acheté un verre à quelqu'un."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais allé dans un club en étant sobre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais allée dans un bar toute seule."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais blâmé l'alcool pour quelque chose que j'ai dit."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais blâmé l'alcool pour quelque chose que j'ai fait."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu 4 shot d'affilés."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu au point de m'endormir pendant l'acte sexuel."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu au point de ne pas pouvoir me lever (bite de whisky)."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu autant que j'ai dû me faire porter à la maison."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu d'alcool au petit déjeuner."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu d'alcool au travail."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu d'alcool dans les transports publics."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu d'alcool dans une gamelle de chien."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu d'alcool pour avoir confiance en moi."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu d'alcool pour calmer mes nerfs."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu d'alcool pour gagner un pari."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu d'alcool à l'école."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu de bière."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu de l'alcool dans une assiette."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu de l'eau pendant une partie de Never Have I Ever."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu de la tequila."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu du whisky comme de l'eau."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu en appelant quelqu'un."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu l'estomac vide."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu plus de dix bières le même soir."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu seul."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu tout seul."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu une bière en moins de 10 secondes et ensuite vomi."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu une bière en moins de 10 secondes."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais bu une bouteille de vodka de 70 cl en une nuit."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais cassé un téléphone quand j'étais ivre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais chanté au karaoké en étant bourré."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais conduit sous influence."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais consommé de drogues."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais couché avec la même personne qu'un de mes amis."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais couché avec quelqu'un de ma job."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais couché avec quelqu'un ne parlant pas ma langue."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais demandé à quelqu'un de m'acheter de l'alcool quand j'étais mineur."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais demandé à quelqu'un de me payer un verre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais dit le mauvais nom pendant l'acte."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais donné d'alcool à un mineur."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais dormi dans la rue parce que j'étais trop saoul pour rentrer chez moi."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais dormi dehors quand j'étais ivre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais dépensé plus de 100£ pour une nuit dehors."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais embrassé quelqu'un du même sexe."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais enfreins la loi."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais envoyé de photos coquines."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais envoyé de sextos ou de photos coquines à la mauvaise personne."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais envoyé de sextos."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais envoyé un texto/message en état d'ébriété."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais espionné mon ex sur les réseaux sociaux."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais essayé d'entrer dans la mauvaise maison lorsque j'étais ivre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais essayé de saouler quelqu'un."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais eu d'accident en étant saoul."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais eu de fantasme sur une personne présente dans cette pièce."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais eu de rapports sexuels en état d'ivresse."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais eu de relations sexuelles avec une personne qui avait moins de 5 ans que moi."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais eu de relations sexuelles avec une personne qui avait plus de 10 ans que moi."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais eu de relations sexuelles plus de 5 fois dans une journée."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais eu la gueule de bois au point de ne pas pouvoir quitter mon lit de la journée."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais eu la gueule de bois au point de vouloir mourir."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais eu la gueule de bois."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais eu peur de vérifier mon téléphone après une soirée."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais eu un mois sans alcool depuis que j'ai commencé à boire."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais eu à boire une pinte sale."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais eu à demander à quelqu'un le matin où j'étais."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais fais de striptease."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais fait de Bondage."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais fait de cocktail."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais fait de déminage (j'ai bu les boissons à moitié vides dans la pièce)."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais fait de sport en buvant."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais fait entrer de l'alcool en cachette dans un cinéma."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais fait l'amour ailleurs que dans un lit."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais fait pipi sur quelqu'un."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais fait semblant d'être ivre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais fait une balle dans le corps ou quelqu'un m'a tiré dessus."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais faké d'avoir un orgasme."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais fantasmé sur quelqu'un dans cette pièce."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais flashé mes seins."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais flirté avec quelqu'un pour qu'il me serve un verre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais flirté avec une personne pour gagner un pari."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais jamais fait de beuverie avec ma bière."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais joué au beer pong."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais joué à un jeu d'alcool."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais joué à un jeu vidéo en étant ivre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais mesuré mon pénis ou celui de mon partenaire."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais mis d'alcool dans mes céréales."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais mis de fruits dans un verre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais ouvert une bouteille avec mes dents."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais ouvert une bouteille avec mes seins."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais ouvert une bouteille avec une autre bouteille."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais parlé à quelqu'un d'ivre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais payé une dette avec de l'alcool."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais perdu connaissance dans les toilettes."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais perdu connaissance à cause de l'alcool."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais perdu quelque chose quand j'étais saoul."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais perdu un téléphone quand j'étais ivre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais pleuré pendant une soirée."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais pratiqué le BDSM."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais pris d'héroïne."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais pris un coup de feu."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais pris un jour de congé de maladie au travail ou à l'école à cause de l'alcool."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais pris un selfie avec une boisson alcoolisée."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais promené un chien ivre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais regretté d'avoir bu."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais renversé un verre sur un étranger."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais révélé un secret quand j'étais ivre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais tué d'animaux."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais utilisé de préservatif en état d'ébriété."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais utilisé l'alcool pour diminuer mes propres inhibitions ou celles de quelqu'un d'autre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais voler dans un magasin."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais volé de l'alcool à mes parents."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais volé l'alcool de quelqu'un."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais vomi parce que j'avais trop bu."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais vomi sur le sol parce que je ne trouvais pas la salle de bain."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais vomi sur quelqu'un alors que j'étais ivre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais vomi sur quelqu'un."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été arrêté alors que j'étais ivre."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été attiré ou dessiné sur quelqu'un qui s'est évanoui."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été embarqué par la police/gendarmerie."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été gêné par ce qu'un ami m'a dit qu'il s'était passé un soir de sortie."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été incapable de boire un type d'alcool après une mauvaise nuit."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été ivre avant le déjeuner."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été ivre avec moins de trois verres."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été ivre dans un pays étranger."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été ivre en sous-vêtements."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été ivre à un enterrement."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été malade dans un taxi."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été malade à cause de l'alcool."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été mis au lit par mes amis."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été si saoul que j'ai pissé dans mon lit."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été tout.e nu.e dans la rue."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été trop soûl pour me rappeler où j'étais."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été trop soûl pour me souvenir d'une soirée."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été trop soûle pour me rappeler où j'habite."},
    {pack_name:"never_party",language:"fr",text:"Je n'ai jamais été viré d'un club."},
    {pack_name:"never_party",language:"fr",text:"Je ne me suis jamais endormi dans les toilettes."},
    {pack_name:"never_party",language:"fr",text:"Je ne me suis jamais fais dessus car j'avais trop peur."},
    {pack_name:"never_party",language:"fr",text:"Je ne me suis jamais fait prendre par mes parents."},
    {pack_name:"never_party",language:"fr",text:"Je ne me suis jamais fait virer d'une boîte de nuit."},
    {pack_name:"never_party",language:"fr",text:"Je ne me suis jamais masturbé l'anus."},
    {pack_name:"never_party",language:"fr",text:"Je ne me suis jamais masturbé plus de 5 fois en une journée."},
    {pack_name:"never_party",language:"fr",text:"Je ne me suis jamais masturbé."},
    {pack_name:"never_party",language:"fr",text:"Je ne me suis jamais perdu en étant bourré."},
    {pack_name:"never_party",language:"fr",text:"Je ne me suis jamais réveillé ivre."},
    {pack_name:"never_party",language:"fr",text:"Je ne me suis jamais réveillé malade après avoir bu."},
    {pack_name:"never_party",language:"fr",text:"Je ne me suis jamais saoulé avec mes parents."},
    {pack_name:"never_party",language:"fr",text:"Je ne me suis jamais saoulée en sous-vêtements."},
    {pack_name:"never_party",language:"fr",text:"Je ne suis jamais allé au travail avec une gueule de bois."},
    {pack_name:"never_party",language:"fr",text:"Je ne suis jamais allé dans un club tout seul."},
    {pack_name:"never_party",language:"fr",text:"Je ne suis jamais allé dans un club échangiste."},
    {pack_name:"never_party",language:"fr",text:"Je ne suis jamais allé à l'école avec une gueule de bois."},
    {pack_name:"never_party",language:"fr",text:"Je ne suis jamais rentré chez moi avec quelqu'un juste parce que j'étais ivre."},
    {pack_name:"never_party",language:"fr",text:"Je ne suis jamais rentré chez moi avec quelqu'un parce qu'il m'avait acheté de l'alcool."},
    {pack_name:"never_party",language:"fr",text:"Je ne suis jamais rentré chez moi dans la mauvaise maison alors que j'étais ivre."},
    {pack_name:"never_party",language:"fr",text:"Je ne suis jamais retrouvé à l’hôpital à cause du sexe."},
    {pack_name:"never_party",language:"fr",text:"Je ne suis jamais réveillé dans mon vomi."},
    {pack_name:"never_party",language:"fr",text:"Je ne suis jamais sorti de chez moi sans sous-vêtement."},
    {pack_name:"never_party",language:"fr",text:"Je ne suis jamais tombé d'un canapé quand j'avais bu."}];
    game.pending_db = game.pending_db.concat(game.stored_db.never_party_fr);