game.stored_db.never_party_fr = [{pack_name:"never_party",language:"en",text:"Never have I ever asked someone to buy me a drink."},
{pack_name:"never_party",language:"en",text:"Never have I ever asked someone to buy me alcohol when underage."},
{pack_name:"never_party",language:"en",text:"Never have I ever been arrested while drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever been asked to leave a party."},
{pack_name:"never_party",language:"en",text:"Never have I ever been drawn on or drawn on someone passed out."},
{pack_name:"never_party",language:"en",text:"Never have I ever been drunk at a funeral."},
{pack_name:"never_party",language:"en",text:"Never have I ever been drunk before lunchtime."},
{pack_name:"never_party",language:"en",text:"Never have I ever been drunk in a foreign country."},
{pack_name:"never_party",language:"en",text:"Never have I ever been drunk on less than three drinks."},
{pack_name:"never_party",language:"en",text:"Never have I ever been embarrassed about what a friend told me happened on a night out."},
{pack_name:"never_party",language:"en",text:"Never have I ever been put to bed by my friends."},
{pack_name:"never_party",language:"en",text:"Never have I ever been scared to check my phone after a night out."},
{pack_name:"never_party",language:"en",text:"Never have I ever been sick from drinking."},
{pack_name:"never_party",language:"en",text:"Never have I ever been sick in a taxi."},
{pack_name:"never_party",language:"en",text:"Never have I ever been so drunk I peed in my bed."},
{pack_name:"never_party",language:"en",text:"Never have I ever been to a bar on my own."},
{pack_name:"never_party",language:"en",text:"Never have I ever been to a club sober."},
{pack_name:"never_party",language:"en",text:"Never have I ever been too drunk to remember a night out."},
{pack_name:"never_party",language:"en",text:"Never have I ever been too drunk to remember where I live."},
{pack_name:"never_party",language:"en",text:"Never have I ever been too drunk to remember where I was."},
{pack_name:"never_party",language:"en",text:"Never have I ever been unable to drink a type of alcohol after a bad night."},
{pack_name:"never_party",language:"en",text:"Never have I ever blamed alcohol for something I did."},
{pack_name:"never_party",language:"en",text:"Never have I ever blamed alcohol for something I said."},
{pack_name:"never_party",language:"en",text:"Never have I ever boofed my beer."},
{pack_name:"never_party",language:"en",text:"Never have I ever bought someone a drink."},
{pack_name:"never_party",language:"en",text:"Never have I ever chugged a beer in less than 10 seconds and then puked."},
{pack_name:"never_party",language:"en",text:"Never have I ever chugged a beer in less than 10 seconds."},
{pack_name:"never_party",language:"en",text:"Never have I ever cried on a night out."},
{pack_name:"never_party",language:"en",text:"Never have I ever didn't use a condom while drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever done a body shot or had someone do a body shot off of me."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank a 70cl bottle of vodka in one night."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank alcohol at school."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank alcohol at work."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank alcohol during breakfast."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank alcohol off of a plate."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank alcohol on public transport."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank alcohol out of a dog bowl."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank alcohol to calm my nerves."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank alcohol to gain confidence."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank alcohol to win a bet."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank any kind of spirit."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank beer."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank on an empty stomach."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank on my own."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank over ten beers on the same night."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank so much I couldn't get it up (whiskey dick)."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank so much I had to get carried home."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank so much that I fell asleep while having sex."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank tequila."},
{pack_name:"never_party",language:"en",text:"Never have I ever drank water during a game of Never Have I Ever."},
{pack_name:"never_party",language:"en",text:"Never have I ever dressed as a couple for Halloween."},
{pack_name:"never_party",language:"en",text:"Never have I ever Drink alone."},
{pack_name:"never_party",language:"en",text:"Never have I ever drink whiskey like water."},
{pack_name:"never_party",language:"en",text:"Never have I ever driven under the influence."},
{pack_name:"never_party",language:"en",text:"Never have I ever drunk called someone."},
{pack_name:"never_party",language:"en",text:"Never have I ever fallen over due to drinking."},
{pack_name:"never_party",language:"en",text:"Never have I ever fell off a bed when drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever fell off a sofa when drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever flirted with someone so they would get me a drink."},
{pack_name:"never_party",language:"en",text:"Never have I ever given alcohol to someone underage."},
{pack_name:"never_party",language:"en",text:"Never have I ever given away a secret while drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever gone home to the wrong house while drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever gone home with someone because they bought me alcohol."},
{pack_name:"never_party",language:"en",text:"Never have I ever gone home with someone just because I was drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever gone out to a club on my own."},
{pack_name:"never_party",language:"en",text:"Never have I ever gone to school with a hangover."},
{pack_name:"never_party",language:"en",text:"Never have I ever gone to work with a hangover."},
{pack_name:"never_party",language:"en",text:"Never have I ever gotten drunk in my underwear."},
{pack_name:"never_party",language:"en",text:"Never have I ever gotten drunk while underage."},
{pack_name:"never_party",language:"en",text:"Never have I ever gotten drunk with my parents."},
{pack_name:"never_party",language:"en",text:"Never have I ever gotten kicked out of a club."},
{pack_name:"never_party",language:"en",text:"Never have I ever gotten lost while drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever had a hangover so bad I couldn't leave bed all day."},
{pack_name:"never_party",language:"en",text:"Never have I ever had a hangover so bad I wanted to be dead."},
{pack_name:"never_party",language:"en",text:"Never have I ever had a hangover."},
{pack_name:"never_party",language:"en",text:"Never have I ever had a month without alcohol since I started drinking."},
{pack_name:"never_party",language:"en",text:"Never have I ever had an accident while drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever had drunken sex."},
{pack_name:"never_party",language:"en",text:"Never have I ever had to ask someone in the morning where I was."},
{pack_name:"never_party",language:"en",text:"Never have I ever had to drink a dirty pint."},
{pack_name:"never_party",language:"en",text:"Never have I ever lost a phone while drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever lost something while drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever made a cocktail."},
{pack_name:"never_party",language:"en",text:"Never have I ever minesweeped (drank the half-empty drinks around the room)."},
{pack_name:"never_party",language:"en",text:"Never have I ever opened a bottle with another bottle."},
{pack_name:"never_party",language:"en",text:"Never have I ever opened a bottle with my boobs."},
{pack_name:"never_party",language:"en",text:"Never have I ever opened a bottle with my teeth."},
{pack_name:"never_party",language:"en",text:"Never have I ever paid a debt with alcohol."},
{pack_name:"never_party",language:"en",text:"Never have I ever passed out from drinking."},
{pack_name:"never_party",language:"en",text:"Never have I ever passed out on a toilet."},
{pack_name:"never_party",language:"en",text:"Never have I ever played a drinking game."},
{pack_name:"never_party",language:"en",text:"Never have I ever played a sport while drinking."},
{pack_name:"never_party",language:"en",text:"Never have I ever played a video game drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever played beer pong."},
{pack_name:"never_party",language:"en",text:"Never have I ever pretended to be drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever put alcohol in my cereal."},
{pack_name:"never_party",language:"en",text:"Never have I ever put fruit in a drink."},
{pack_name:"never_party",language:"en",text:"Never have I ever regretted drinking."},
{pack_name:"never_party",language:"en",text:"Never have I ever sang karaoke while drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever sent a drunk text/message."},
{pack_name:"never_party",language:"en",text:"Never have I ever slept outside while drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever smashed a phone while drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever sneaked alcohol into a cinema."},
{pack_name:"never_party",language:"en",text:"Never have I ever spent over £100 on a night out."},
{pack_name:"never_party",language:"en",text:"Never have I ever spilled a drink on a stranger."},
{pack_name:"never_party",language:"en",text:"Never have I ever stolen alcohol from my parents."},
{pack_name:"never_party",language:"en",text:"Never have I ever stolen someone's drink."},
{pack_name:"never_party",language:"en",text:"Never have I ever taken a selfie with an alcoholic drink."},
{pack_name:"never_party",language:"en",text:"Never have I ever taken a shot."},
{pack_name:"never_party",language:"en",text:"Never have I ever taken a sick day from work/school due to drinking."},
{pack_name:"never_party",language:"en",text:"Never have I ever Talked to anyone drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever thrown up on someone while drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever thrown up on the floor because I couldn't find the bathroom."},
{pack_name:"never_party",language:"en",text:"Never have I ever tried to enter the wrong house when drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever tried to get someone drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever used alcohol to lower my own or someone else's inhibitions."},
{pack_name:"never_party",language:"en",text:"Never have I ever walked a dog drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever woken up drunk."},
{pack_name:"never_party",language:"en",text:"Never have I ever woken up sick after drinking."}];
game.pending_db = game.pending_db.concat(game.stored_db.never_party_fr);