var db = TAFFY([{cycle_state:"false",type:"1",text:"%s, изобрази, будто у тебя запор или сделай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, спусти штаны или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Последний, кто прокричит дерьмо\u0022 допивает свой бокал\u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s устрой армреслинг с %s, тот, кто проиграет, делает $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Последний, кто прокричит %s, отс*си мне\u0022 делает $ глотка(ов) \u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Первый, кто рыгнет, решает, кто сделает $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Тот, кто начал заниматься сексом раньше всех, делает $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Тот, кто начал мастурбировать раньше всех, делает $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, поковыряйся в носу или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, если у тебя меньше двух сосков, решай, кому делать $ глотка(ов) или пей сам(а)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, покажи свой лобковые волосы или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Тот, кто до конца игры сможет пукнуть так, что бы все услышали, тот решит, кому делать 10 глотков",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Дуэль между %s и %s, тот(та), у кого больше мускулов, делает $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, тот(та), кто пойдет в туалет первым(первой), делает $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, если ты когда-нибудь делал(а) куннилингус, пей $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, если ты когда-нибудь делал(а) минет, пей $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, лизни пол или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s и %s, начинайте отжиматься! Тот, кто устанет первым, делает $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Тот(та), кому сегодня делали минет или куни, решают, кому делать $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, засунь свою голову между ног %s или сделай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, отлей из своего бокала по чуть-чуть каждому из игроков",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Все игроки отливают немного из своего бокала в бокал %s",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s , лизни ухо %s или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s снимают свои штаны",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, допей свой бокал и наполни его до краев ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, возьми бокал игрока слева и напои его из этого бокала",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Первый, кто назовет год рождения Иисуса Христа, решает, кому делать $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, положи кубик льда себе в трусы/лифчик на 5 минут",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ущипни за соски %s или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, покажи свою красивую попку всем игрокам или допивай свой бокал ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, встань на руки и сделай $ глотка(ов). %s и %s помогут тебе сохранить равновесие",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"3"},
{cycle_state:"false",type:"1",text:"Те, кто бы с радостью занялся сексом с игроком справа, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто бы с радостью занялся сексом с игроком слева, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь поднимал еду с пола и ел ее, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, если ты когда-нибудь мастурбировал(а), представляя свою(его) дальнюю(него) родственницу(ка), делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, у кого был секс больше недели назад, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, если ты в детстве снимал(а) штанишки перед противоположным полом, делай $ глотка(ов)  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, если ты занимался(лась) сексом в носках, делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s засунь палец в нос %s или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, сделай столько глотков, сколько мужских чл*нов ты отссал(а)\u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Как скоро вы достигаете оргазма? Все отвечают по очереди. Скорострел решает, кому делать $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Тот, кто спал на одной неделе с двумя разными партнерами, делает $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Тот, кто в течение одного дня переспал в двумя разными партнерами, делает $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, потрогай %s между ног или все игроки делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Те, у кого был анальный секс, поднимите свои бокалы в воздух и скажите да здравствует анал\u0022 и выпейте до дна \u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Тот, кто планирует заняться сексом сегодня вечером, делайте $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь изменял своей супруге(своему супругу), решайте, кому делать $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, сделай 10 отжиманий на 1 руке или пей $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, сымитируй оргазм или делай 10 глотков",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, покажи, как ты мастурбируешь или делай 10 глотков",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты когда-нибудь отправлял(а) фото своего пениса или своей груди в смс сообщении ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s сделай $ глотка(ов), не касаясь губами бокала",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, положи что-нибудь съестное в бокал %s, он(она) должен(должна) допить до дна, что бы достать это ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, кто быстрее выпьет свой бокал до дна, у того иммунитет на 8 минут ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Те, кто в детстве рассматривал картинки голых женщин на последней странице новостных газет, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, выщипни волосок со своего живота или допивай свой бокал",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь засовывал палец в попу, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, делай столько глотков, сколько раз ты мастурбировал(а) за последние 7 дней ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь снимал проститутку, решают, кому делать $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, сделай $ глотка(ов), не касаясь до бокала руками",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь мастурбировал во время просмотра мультфильма, делают $ глотка(ов)  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, или ты позволишь %s поменять аватарку на твоей страничке в соц. сети до конца вечера или ты допиваешь свой бокал ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, произнеси имя %s\u0022 наоборот или делай $ глотка(ов)  \u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, выбирай : или добавляешь крепкого алкоголя себе в бокал или делаешь $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, делай $ глотка(ов), %s и %s должны сделать вдвое больше",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"3"},
{cycle_state:"false",type:"1",text:"Следующий игрок, который будет пить, должен выпить в три раза больше",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Следующий игрок, который будет пить, должен выпить в четыре раза больше",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Девушки: та, у кого недавно были месячные, делает $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто пукнул или рыгнул на сегодняшней вечеринке, делают $ глотка(ов)  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, пусть кто-нибудь из игроков сфотографирует тебя без трусов или пей $ глотка(ов)  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Последний, кто засунет руку себе в трусы, делает $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, у кого первый секс был с проституткой, решают, кому делать $ глотка(ов)  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, у кого серьезных отношений было больше, чем секса на одну ночь, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, у кого член меньше 24 см, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто сегодня уже покакал, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, выбирай: выпить $ глотка(ов) или поцеловать ступни %s",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, если ты сможешь отжаться 15 раз, %s сделает $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, сделай $ глотка(ов), держа бокал между ног",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Игроки выбирают, кому делать $ глотка(ов):%s или %s ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, если не успеешь сделать 10 кругов вокруг своей оси, пока %s считает до 50, допивай свой бокал ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, если тебя когда-либо стошнило на кого-нибудь, делай $ глотка(ов), если нет - выбирай, кому пить ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь мастурбировал, представляя своего друга(свою подругу), делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Первый, кто выложит в соц. сеть фотографию своего пьяного лица, решает, кому делать $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, если ты когда-нибудь ломал кому-нибудь голову, делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, если ты когда-нибудь ломал кому-нибудь голову, выбирай, кому делать $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь какал в душе, делают $ глотка(ов)  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь глотал сперму, делают $ глотка(ов) (алкоголя)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь давал денег бомжу, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь подсматривал за своими соседями, в надежде увидеть их голыми, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Первый, кто покажет свой половой орган, решает, кому делать $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если вчера ты смотрел(а) порно ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь писался в штаны, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь писал в раковину, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь писал в лифте, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кого когда-нибудь рвало(тошнило) в общественном транспорте, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь представлял в эротических фантазиях героя мультфильма, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь смотрел на свой анус в зеркало, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто бреют или эпилируют волосы в попе, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, понюхай подмышку %s или сделай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, оцарапай спину %s или сделай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, выбирай: сделать по одному глотку из бокала каждого игрока или сделать 5 глотков из своего бокала",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Игроки должны решить, у кого из %s и %s бицепс больше. Кто проиграет, делает $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"3"},
{cycle_state:"false",type:"1",text:"%s, понюхай трусы %s или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Тот, кому когда-нибудь вставляли палец в попу, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, сделай 5 кругов вокруг своей оси и делай глоток, каждый раз наткнувшись на другого игрока, делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь пробовал на вкус естественную смазку своего партнера, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s и %s, кто из вас сильнее даст другому пощечину, выиграл! Проигравший делает $ глотка(ов)!",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, кто из вас сильнее шлепнет по попе другого, выиграл! Проигравший делает $ глотка(ов)!",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, кто из вас дольше продержит руки поднятыми над головой, победил. Проигравший делает $ глотка(ов)!",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, кто из вас дольше продержится, стоя на одной ноге, тот выиграл! Проигравший делает $ глотка(ов)! ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, кто из вас сможет прокрутиться на месте дольше, тот победил ! Проигравший делает $ глотка(ов)! ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, кто из вас сделает больше приседаний, тот победил. Проигравший делает $ глотка(ов)! ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, кто из вас сможет как можно дольше повторять люблю анал\u0022 победил. Проигравший делает $ глотка(ов)!  \u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, кто из вас сможет как можно дольше повторять я урод\u0022 победил. Проигравший делает $ глотка(ов)!  \u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, кто из вас сможет как можно дольше повторять я тупица\u0022 победил. Проигравший делает $ глотка(ов)!  \u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, кто из вас сможет как можно дольше простоять в планке на локтях, победил. Проигравший делает $ глотка(ов)!  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, кто из вас отправит как можно больше смс разным людям в течении минуты, тот победил. Проигравший делает $ глотка(ов)!  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s и %s, надо держать свой язык двумя пальцами, кто из вас продержится дольше, тот победил. Проигравший делает $ глотка(ов)!  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, ударь между ног любого из игроков или делай $ глотка(ов)!",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь пукал во время секса, делают $ глотка(ов)! ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Парни, кто из вас последний покажет свой голый торс, делает $ глотка(ов)! ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, скажи, что %s должен сделать. Если он(она) откажется, делает $ глотка(ов)! ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Все, у кого есть борода, делают $ глотка(ов)! ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь какал в океан, делает $ глотка(ов)! ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь какал на улице, делают $ глотка(ов)! ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, напиши статус в соц. сети одного из игроков. Если он наберет 15 лайков до конца вечера, ты решаешь, кому пить до дна, если нет, то тебе пить столько глотков, сколько лайков собрал статус ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, изобрази лающую собаку и сделай $ глотка(ов)!  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, сделай $ глотка(ов), пока %s дует на лицо %s!",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"3"},
{cycle_state:"false",type:"1",text:"%s, выбирай, или ты затыкаешь уши на 5 минут или ты делаешь $ глотка(ов) каждые 5 минут",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, досчитай вслух до 200 или делай $ глотка(ов)! ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, ты должен продержаться 10 секунд на %s, который изображает бешенного быка на родео, или сделать $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, сломай кусочек льда об лоб или делай $ глотка!",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, сломай кусочек льда об лоб %s или делай $ глотка!",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Ваня пукнул на ромашку и упал лицом в какашку\u0022 первый кто засмеется тот пьет до дна!\u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, какую вещь в последний раз ты засовывал в попу? Отвечай и делай $ глотка(ов)!",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь специально громко пукал(а) в присутствии незнакомого человека ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь ел(а) корм для животных",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь занимался(лась) любовью в присутствие своей собаки или кошки",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь занимался(лась) любовью в общественном транспорте",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты хранишь обнаженные фотографии своих бывших",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если у тебя есть сексуальные обнаженные фотографии твоей девушки(парня)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь покупал(а) порно журналы",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь делал(а) золотой дождь\u0022\u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь занимался(лась) сексом с бабулей или дедулей",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, покажи свою голую попу или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь занимался(лась) сексом с человеком, не зная его имени",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто не занимался анальным сексом, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s и %s, возьмите друг друга за руку, тот, кто первый отпустит руку, пьет до дна (игра должна продолжаться)  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Первый, кто покажет свои яйца, делает $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Реши, кому делать $ глотка(ов), если ты когда-нибудь плевал в бокал перед тем, как отдать его кому-то ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Реши, кому делать $ глотка(ов), если ты когда-нибудь ел фрукты с тела своего партнера ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, у кого бокал наполнен меньше, чем на половину, доливайте до краев и пейте до дна ! ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто на этой неделе стриг ногти на ногах, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Все храпуны должны сделать $ глотка(ов), и храпеть в это время, конечно же",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты когда-нибудь писал на кого-нибудь",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты когда-нибудь издевался над насекомыми",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты когда-нибудь поджигал муху зажигалкой ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь отрывал крылья насекомым ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты никогда не какал вне дома",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты никогда не писал вне дома",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь вбивал в поисковике секс позиции\u0022 \u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь вбивал в поисковике что делать если не стоит\u0022 \u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь вбивал в поисковике что делать если у нее болит голова\u0022 \u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь смотрел азиатское порно или групповушку, в которой было более 14 человек ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Все игроки делают $ глотка(ов). Кроме %s, который(ая) танцует танец маленьких утят ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Те, кто любит часок-другой посидеть в туалете, делайте $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто любит рассматривать свои козявки, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s. засунь кусочек льда в трусы или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, сделай столько глотков, сколько кисок ты удовлетворил своим языком ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, позвони в дверь соседа или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, вылей немного из своего бокала себе в трусы или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, отправь смс с текстом я опять обкакался\u0022 или делай $ глотка(ов)\u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, пописай в раковину или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, окуни свое лицо в туалет или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, вылей немного из своего бокала себе на голову или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, надень халат, сходи к соседям и попроси у них льда для твоего бокала или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, нанеси тонким слоем на все свое лицо зубную пасту или делай $ глотка(ов)  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Тот или та, у кого самая большая грудь, решает, кому делать $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, съешь козявку или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, сделай глоток из каждой бутылки, которая стоит на столе",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, отправь фотографию своих гениталий трем людям или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, продержись 5 секунд, стоя на руках со спущенными штанами или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, сделай колесо или пей $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, лизни ниже копчика %s или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты когда-нибудь покупал клизму",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты когда-нибудь достигал оргазма находясь под струей воды",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s наполни рот алкоголем и вылей его в бокал %s",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты когда-нибудь кликал(а) на ссылку в интернете как увеличить член/грудь\u0022\u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь не мог достать из себя тампон, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, объясни всем, как лучше всего какать и делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, съешь кубик льда или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, выбери очкарика и оставь на его очках отпечатки своих пальцев, $ глотка(ов) в случае отказа. Если никто из игроков не носит очки, реши, кому делать $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, если у тебя есть клитор, делай $ глотка(ов), если нет - решай, кому пить",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, если у тебя есть член и яички, делай $ глотка(ов), если нет - решай, кому пить",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, съешь волос одного из игроков или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь пихал свой член в пластиковую вагину, или если ты засовывала секс игрушку себе в вагину",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, поставь статус в социальной сети, что у тебя отношения со своей рукой или допивай до дна ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s и %s кричат aaaaaaaaa, тот кто продержится дольше, решает, кому делать $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Те, у кого был когда-нибудь был грибок стопы (или другой части тела...), делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Все игроки меняются пачками сигарет между собой",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s засовывает себе тампон в попу или делает $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, приклей себе на лоб крышку от пива, если через 30 секунд она не слетит, решай, кому делать $ глотка(ов). Если слетит - пей сам(а)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если твоя грудь меньше первого размера",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если твоя грудь больше третьего размера",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, ущипни за бока того, кто должен будет сделать $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Если ты когда-нибудь смеялся над тем, как кто-то пукал, делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты когда-нибудь засовывал(а) свою руку в штаны, что бы проверить не обкакался(лась) ли ты, пока пукал(а)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Все игроки должны потрогать гениталии %s. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты не любишь анальный секс",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, сделай по глотку из каждого бокала",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Если вы когда-нибудь нюхали свои пальцы после того, как потрогали свои гениталии, делайте $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь смотрел порно с друзьями/девушкой/парнем и т.п.",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Делай $ глотка(ов), если ты когда-нибудь застукивал своих родителей за сексом",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, добавь немного молока в свой бокал. Если нет молока, добавь масло/соус",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, Добавь немного соли в свой бокал. Или перца, или приправ, все что угодно, что придаст вкуса твоему напитку ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, задай вопрос любому игроку. Игрок должен ответить или допить свой бокал до дна",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, посмотри сколько времени и распредели цифры между игроками. Например, 23:32 => 2, 3, 3 и 2 глотка игрокам",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, расскажи грязную шуточку. Если у тебя таких нет, или никто не смеется над твоей шуткой, делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, отправь селфи тому человеку, которого выберет %s или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если по тебе можно сказать, что ты иностранец",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если по тебе можно сказать, что ты пьян",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Лысеешь? Все, у кого выпадают волосы, делают $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь масту*бировал на Сашу Грей, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Те, кто когда-нибудь преодолевал 50 км, ради того, что бы заняться сексом, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, приклей козявку себе на лоб или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, дай пощечину %s. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, ударь в плечо %s. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, пописай на стол или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, плюнь на стол или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, плюнь себе в бокал или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, плюнь в бокал %s. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, допей свой бокал или пусть %s окунет туда свой член. Если это девушка...что ж, пей до дна ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, окуни свой член в свой бокал и допивай до дна. Если ты девушка, не повезло тебе...",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, допей свой бокал или пусть %s окунет туда свои яички. Если это девушка...что ж, пей до дна...",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, окуни свои яички в свой бокал и допивай до дна. Если ты девушка, не повезло тебе...",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, позвони кому-нибудь и наори на него. Или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, оскорби кого-нибудь по смс. Или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, крикни с полным ртом или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, любой игрок может написать тебе что-нибудь на руке. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, любой игрок может написать тебе что-нибудь на лбу. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, любой игрок может написать тебе что-нибудь на щеке. $ глотка(ов) в случае отказа",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, просвисти какую-нибудь мелодию с набитым ртом. Тот, кто ее угадает, решает, кому делать $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, засунь палец себе в трусы и окуни его в свой бокал. Пей до на в случае отказа",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, пусть %s засунет свой палец себе в трусы и потом окунет его в твой бокал. В случае отказа, пей до дна",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, если ты засунешь палец себе в попу, %s допивает свой бокал",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"%s, если твои гениталии побриты, решай, кому делать $ глотка(ов). Если нет - пей сам",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, сними свою обувь или делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, пусть %s разорвет что-либо из твоей одежды. Допивай до дна в случае отказа ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"1",text:"Те, кто весят меньше 57 кг, пьют до дна и выбирают одного игрока, который с ними чокнется и сделает $ глотка(ов)  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, расскажи ситуацию, когда тебе было очень стыдно или пей до дна ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если в этом году ты занимался(лась) сексом больше, чем с одним партнером ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Парни, которые прямо сейчас сделают вертолетик своим членом, не будут пить $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, сделай столько глотков, какое количество идиотов сидит в этой комнате",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, сделай столько глотков, какое количество мебели находится в этой комнате",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Если ты когда-нибудь включал свой компьютер/телефон в публичном месте, а там открывалось порно, делай $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Если кто-нибудь видел, что в истории твоих запросов в интернете есть порно сайты, делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Если тебя когда-нибудь застукивали со стояком в общественных местах, делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Если тебе случается маскировать свою эрекцию, делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Если ты когда-нибудь танцевала с парнем и чувствовала его эрекцию, делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Реши, кому делать $ глотка(ов), если у тебя на лице есть жировик ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если за 50 тысяч ты переспишь с игроком справа от тебя",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты любишь пукать в кровати и зарываться головой под одеяло",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если у тебя был приступ смеха во время секса ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Реши, кому делать $ глотка(ов), если у тебя было больше 20 сексуальных партнеров",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"Сделай $ глотка(ов), если ты пукал(а) при своем партнере, что бы посмеяться ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, надень штаны задом наперед или делай $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"%s, сделай $ глотка(ов), если ты когда-нибудь засовывал(а) что-либо себе в попу",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Сколько лет было вашему самому взрослому партнеру? Тот, у кого партнер был старше, решает, кому делать $ глотка(ов) ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"1",text:"%s, должен понюхать ноги каждого игрока или допить свой бокал",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"1",text:"Каждый игрок дает пощечину %s. Или он делает 10 глотков",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, засунь в нос два пальца, пока не будет задания прекратить",key:"finger-nose",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты можешь убрать пальцы из носа",key:"",parent_key:"finger-nose",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, разденься и останься с голым торсом/в лифчике",key:"topless",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, можешь одеться",key:"",parent_key:"topless",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, должен заканчивать каждую фразу, говоря  чееее\u0022\u0022",key:"gneee",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, можешь прекратить говорить чееее\u0022\u0022",key:"",parent_key:"gneee",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, можешь выдергивать по волоску с любой части тела %s каждый раз, когда кто-то из игроков пьет ",key:"pull-hair",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, прекрати выдергивать волосы у %s",key:"",parent_key:"pull-hair",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, ляг на пол, тебе скажут, когда можно будет встать",key:"lying-floor",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, можешь встать с пола",key:"",parent_key:"lying-floor",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"Все игроки должны вытащить свои языки, как собаки, и сидеть так, пока не будет новой команды ",key:"tongue-out",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Все могут убрать языки и закрыть рты",key:"",parent_key:"tongue-out",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Отныне, все должны говорить, положа два пальца в рот ",key:"fingers-mouth",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Можете убрать пальцы изо рта ",key:"",parent_key:"fingers-mouth",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Отныне все должны постоянно держать руку между ног ",key:"hand-sex",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Можете убрать руки из паховой области",key:"",parent_key:"hand-sex",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Приклонитесь перед, %s, нашим Божеством ! В любой момент он(она) может указать на того, кто будет делать 3 глотка",key:"god",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты больше не Божество! Сделай $ глотка(ов)",key:"",parent_key:"god",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты Цезарь! Подымешь большой палец руки вверх и укажешь на игрока, он не пьет. Опустишь большой палец вниз - пьет двойную порцию",key:"ceasar",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты больше не Цезарь!",key:"",parent_key:"ceasar",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, натяни свою кофту на голову, что бы другие не видели твоего пьяного лица!  ",key:"hide-your-face",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, можешь опустить кофту",key:"",parent_key:"hide-your-face",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, бомж вечера! Делаешь 2 глотка каждый раз, когда игроки тебе будут давать 10 копеек!",key:"hobo-of-the-night",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты больше не бомж!",key:"",parent_key:"hobo-of-the-night",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты богач!Ты можешь покупать игроков, давая им 10 копеек. Они должны сделать 3 глотка!",key:"cresus",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s. ты больше не богач!",key:"",parent_key:"cresus",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, директор зоопарка! Любой игрок должен изобразить того животного, какого ты пожелаешь!",key:"zoo-director",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты больше не директор зоопарка!",key:"",parent_key:"zoo-director",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты Волан де Морт!  Скажешь Авада Кедабра\u0022 и игрок должен сделать 5 глотков!\u0022",key:"voldemort",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты больше не Волан де Морт!",key:"",parent_key:"voldemort",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, в любой момент ты можешь сказать але оп\u0022. Последний кто прокричит \u0022оп оп\u0022 делает $ глотка(ов)!\u0022",key:"to-the-bus",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, можешь больше не кричать але оп\u0022\u0022",key:"",parent_key:"to-the-bus",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, должен каждый раз облизывать дно своего бокала, перед тем как пить ",key:"lick-glass",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, прекрати облизывать свой бокал",key:"",parent_key:"lick-glass",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, дергай за уши %s, пока не будет задания прекратить",key:"hold-ear",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, перестань дергать за уши %s ",key:"",parent_key:"hold-ear",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, щелкай пальцами и говори да сучка\u0022 каждый раз когда кто-нибудь пьет \u0022",key:"clac-fingers",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, перестань щелкать пальцами ",key:"",parent_key:"clac-fingers",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты Пикачу! Ты  должен говорить как Пикачу до того момента, пока тебе не скажут прекратить. Забудешь - делаешь $ глотка(ов)",key:"pikachu",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты больше не Пикачу",key:"",parent_key:"pikachu",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s и %s, поменяйтесь своими носками ",key:"trade-socks",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s и %s, можете поменяться обратно носками",key:"",parent_key:"trade-socks",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s и %s, отныне, вы должны говорить одновременно. Не получилось - делаете $ глотка(ов) ",key:"speak-at-the-same-time",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s и %s, можете больше не говорить одновременно",key:"",parent_key:"speak-at-the-same-time",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"2",text:"Все игроки должны издавать как можно больше звуков своим ртом, каждый раз, когда пьют",key:"mouth-noise",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Можете спокойно пить, без звуков",key:"",parent_key:"mouth-noise",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Все игроки должны использовать отрицание (не, никогда и тд.), когда разговаривают",key:"only-negative",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Можете больше не использовать отрицание",key:"",parent_key:"only-negative",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"%s, отныне, когда ты пьешь, должен до этого рыгнуть. Забудешь - делаешь $ глотка(ов)",key:"mongolito",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, перестань рыгать",key:"",parent_key:"mongolito",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"Все игроки должны говорить высоким, пронзителным голосом, как-будто вам отрезали яйца",key:"speak-high-pitched",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Вам снова пришили яйца, можете говорить нормально",key:"",parent_key:"speak-high-pitched",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"%s, у тебя нервный тик! Моргай как можно чаще",key:"epileptical-mescouilles",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты излечился(лась) от тика!",key:"",parent_key:"epileptical-mescouilles",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты должен/должна причмокивать каждый раз, когда кто-нибудь из игроков пьет ",key:"glouglou-mania",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, можешь больше не причмокивать каждый раз, когда кто-нибудь пьет",key:"",parent_key:"glouglou-mania",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты должен/должна говорить и одновременно рыгать. Иначе делаешь $ глотка(ов)",key:"must-spurb",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, перестань рыгать, это мерзко!!!",key:"",parent_key:"must-spurb",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s и %s, вы должны говорить как Тарзан ! $ глотка(ов), кто облажается",key:"tarzan-like",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"2",text:"Вернитесь к цивилизации, %s и %s! Не нужно больше говорить, как Тарзан",key:"",parent_key:"tarzan-like",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"2",text:"%s, у тебя полно вшей! Чешись, пока не будет команды прекратить",key:"full-of-lice",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты избавился(лась) от паразитов, можешь больше не чесаться",key:"",parent_key:"full-of-lice",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, отныне тебе нельзя произносить согласные!",key:"no-consonne-sa-mere",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, можешь снова произносить согласные",key:"",parent_key:"no-consonne-sa-mere",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты должен/должна надеть задом наперед минимум два элементы одежды",key:"inside-out",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты можешь надеть нормально свою одежду",key:"",parent_key:"inside-out",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s диктатор! В любой момент он/она может дать задание для любого из игроков. $ глотка(ов) в случае отказа",key:"dictator",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты больше не диктатор! И допивай свой бокал до дна!",key:"",parent_key:"dictator",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты больше не диктатор!",key:"",parent_key:"dictator",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, от тебя пахнет... Отойди от всех игроков на 3 метра ",key:"man-you-stink",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты наконец-то принял(а) душ! Можешь подойти к игрокам",key:"",parent_key:"man-you-stink",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты не можешь дотрагиваться ногами до пола! Если твои ноги коснулись пола, делай $ глотка(ов)",key:"floor-lava",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты можешь поставить свои ноги на пол",key:"",parent_key:"floor-lava",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты милый котенок! Облизывай тыльную часть ладони и умывайся как кошечка ",key:"kitty",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты больше не милый котенок. Ты вообще даже не милый ",key:"",parent_key:"kitty",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты химик! Химичь над напитками игроков, когда захочешь",key:"chemister",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты больше не химик",key:"",parent_key:"chemister",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты динозавр Рекс! Твои локти должны быть постоянно прижаты к телу, пока не будет команды прекратить",key:"t-rex",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты больше не динозавр Рекс!",key:"",parent_key:"t-rex",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты должен говорить и корчить гримасы, $ глотка(ов), если облажаешься",key:"squint-eyes",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, прекрати гримасничать",key:"",parent_key:"squint-eyes",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты должен/должна мяукать после каждый фразы. $ глотка(ов), если облажаешься ",key:"meow-end-of-sentence",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, прекращай мяукать",key:"",parent_key:"meow-end-of-sentence",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, ты должен/должна гавкать, как собака, после каждый фразы. $ глотка(ов), если облажаешься ",key:"bark-end-of-sentence",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"%s, прекращай гавкать",key:"",parent_key:"bark-end-of-sentence",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"Играем в ладушки! В любой момент каждый игрок может начать играть в ладушки со своим соседом. Тот, кто откажется, делает $ глотка(ов)",key:"round-game",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Игра в ладушки закончилась!",key:"",parent_key:"round-game",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Никому нельзя смеяться! Тот, кто засмеется, делает $ глотка(ов)",key:"gofio-game",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Расслабьтесь, можно смеяться",key:"",parent_key:"gofio-game",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Поставьте пустой бокал посередине стола. Каждый игрок может добавить в него все, что захочет, %s начинает (имя игрока, который все это выпьет вы скоро узнаете)",key:"kings-rule",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"Игрок справа от %s выпивает бокал, который стоит посередине стола…",key:"",parent_key:"kings-rule",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"2",text:"Отныне, если игрок сказал матерное слово, это слово надо написать на его теле",key:"swear-words-on-body",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Перестаньте писать матерные слова друг на друге",key:"",parent_key:"swear-words-on-body",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Отныне, обращаясь друг к другу, надо показывать средний палец",key:"middle-finger",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Перестаньте показывать средний палец",key:"",parent_key:"middle-finger",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Отныне никому нельзя выходить в туалет!",key:"no-toilet",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"2",text:"Можно снова ходить в туалет",key:"",parent_key:"no-toilet",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"4",text:"Назовите по очереди цифры от 2 до 5 включительно. Тот, кто не сможет дать ответ или повторится, делает $ глотка(ов)! %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Назовите по очереди названия порно сайтов. Тот, кто не сможет дать ответ или повторится, делает $ глотка(ов)! %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Назовите предмет, который можно использовать во время секса, который начинается с буквы, с которой начинается имя игрока справа. Тот, кто не сможет дать ответ или повторится, делает $ глотка(ов)! %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Назовите цвета радуги. Тот, кто не сможет дать ответ или повторится, делает $ глотка(ов)! %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Назовите по очереди порно актрис. Тот, кто не сможет дать ответ или повторится, делает $ глотка(ов)! %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Назовите по очерези то, что ужасно воняет. Тот, кто не сможет дать ответ или повторится, делает $ глотка(ов)! %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Какие буквы составляют слово изподвыподверта\u0022. Тот кто не сможет дать ответ или повторится делает $ глотка(ов)! %s начинает\u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Назовите по очереди место, где нельзя снять проститутку. Тот, кто не сможет дать ответ или повторится, делает $ глотка(ов)! %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Назовите по очереди фрукты, которые поместятся в вагину стандартного размера. Тот, кто не сможет дать ответ или повторится, делает $ глотка(ов)! %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Назовите по очереди маленьких животных, которые могут поместиться в анусе стандартного размера. Тот, кто не сможет дать ответ или повторится, делает $ глотка(ов)! %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Назовите по очереди злых, но сексуальных героев Диснея. Тот, кто не сможет дать ответ или повторится, делает $ глотка(ов)! %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Назовите по очереди места, где %s занимался(лась) сексом. Тот, кто не сможет дать ответ или повторится, делает $ глотка(ов)! %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Назовите по очереди места, где %s какал. Тот, кто не сможет дать ответ или повторится, делает $ глотка(ов)! %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Овощи которые поместятся в вагину порно звезды\u0022. Тот кто не сможет дать ответ или повторится делает $ глотка(ов)! %s начинает\u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Цвета российского флага\u0022. Тот кто не сможет дать ответ или повторится делает $ глотка(ов)! %s начинает\u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Преимущества 13-и метровых рук\u0022. Тот кто не сможет дать ответ или повторится делает $ глотка(ов)! %s начинает\u0022",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Каждый по очереди должен назвать предмет, который может поместиться в анусе. Слово должно начинаться на первую букву имени игрока, сидящего слева. Тот, кто не сможет ответить или повторится, делает $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Кого из общих знакомых вы считаете глупее %s? Все игроки отвечают по очереди. Тот, кто не сможет ответить или повторится, делает $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"4",text:"Каждый игрок по очереди должен назвать ругательства, в которых присутствует слово член. Тот, кто не сможет ответить или повторится, делает $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Каждый игрок по очереди должен назвать ругательства, в которых присутствует слово пи*да. Тот, кто не сможет ответить или повторится, делает $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Каждый игрок по очереди должен сказать шутку, которая начинается со слов: твоя мама... Тот, кто не сможет ответить или повторится, делает $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"Каждый игрок по очереди должен сказать ругательство, которое можно применить только к девушке. Тот, кто не сможет ответить или повторится, делает $ глотка(ов). %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, назови про себя порно актрису. Все игроки по очереди должны угадать, кто это. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, назови про себя отстойный фильм. Все игроки по очереди должны угадать, что это за фильм. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, подумай про себя, кого из игроков ты считаешь круглым дураком. Все игроки по очереди должны угадать, кто это. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, вспомни, какую глупость сегодня сделал %s (не озвучивай ее вслух). Все игроки по очереди должны угадать, что это было. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"4",text:"%s, подумай про себя, где бы ты хотел(а) отдохнуть. Все игроки по очереди должны угадать, что это за место. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, подумай про себя, где бы ты хотел(а) оторваться по полной. Все игроки по очереди должны угадать, что это за место. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, назови про себя болезнь, передающуюся половым путем. Все игроки по очереди должны угадать, что это за болезнь. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, назови про себя секс игрушку (не говори вслух). Все игроки по очереди должны угадать, что это за игрушка. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, назови про себя сексуальную американскую актрису (не говори вслух). Все игроки по очереди должны угадать, кто это. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, назови про себя сексуальную русскую актрису (не говори вслух). Все игроки по очереди должны угадать, кто это. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, назови про себя мазохистскую позицию в сексе (не говори вслух). Все игроки по очереди должны угадать, что это за позиция. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, назови про себя нечто отвратительное, что может выйти из человеческого тела (не говори вслух). Все игроки по очереди должны угадать, что это. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, назови про себя самого глупого человека, которого знают все присутствующие. Все игроки по очереди должны угадать, кто это. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"4",text:"%s, назови про себя самую сексуальную девушку, которую знают все присутствующие. Все игроки по очереди должны угадать, кто это. Те, кто не угадают, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"6",text:"%s, встань, что бы %s смог(ла) тебя шлёпнуть 2 раза, и допивай свой бокал  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"6",text:"%s, допивай свой бокал под всеобщие оскорбления! ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"6",text:"%s, ты должен допить свой бокал, в то время как %s тебя щиплет за нос и %s шлепает тебя по попе",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"3"},
{cycle_state:"false",type:"6",text:"%s и %s, встаньте на четвереньки, выгните спину и в такой позе допейте свой бокал  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"6",text:"%s, допей свой бокал и рыгни на всю комнату ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"6",text:"%s, допивай свой бокал делая вид, что ты масту*бируешь или сделай вид, что ты масту*бируешь %s, пока он(она) допивает свой бокал",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"6",text:"%s, сделай один глоток, надев на бокал свой носок или пей до дна ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"6",text:"%s, сядь голой попой на пол и осуши свой бокал ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"6",text:"%s, понюхай носки одного из игроков и допей свой бокал ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"6",text:"%s, вылей свой бокал себе на штаны или допивай до дна ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"6",text:"%s, все игроки дают тебе щелбан и ты допиваешь свой бокал",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Ты бы предпочел застрять в лифте с 3 мокрыми собаками или с 3 пердунами? Все голосуют одновременно, те, кто в меньшинстве, делают $ глотка(ов) !",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что бы ты предпочел(чла): cделать минет или съесть какашку? Голосуйте одновременно, те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Вы за или против увеличения груди? Голосуйте одновременно, те, кто окажется в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: какать бабочками или тошнить конфетти? Голосуйте одновременно, те, кто окажется в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: поцеловать паука или съесть земляного червя? Голосуйте одновременно, те, кто окажется в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: пукать каждые три минуты или рыгать каждые 30 секунд? Голосуйте одновременно, те, кто окажется в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: облизать ноги бомжа или проглотить сперму? Голосуйте одновременно, те, кто окажется в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: быть слепым или иметь член как у слона? Голосуйте одновременно, те, кто окажется в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: диарею на всю жизнь или лай собаки вместо человеческого голоса? Голосуйте одновременно, те, кто окажется в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: выпить шот спермы или женской природной смазки? Голосуйте одновременно, те, кто окажется в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: выпить флакон духов или банку шампуня? Голосуйте одновременно, те, кто окажется в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: работать в табачном ларьке всю жизнь или проституткой 5 дней? Голосуйте одновременно, те, кто окажется в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: на протяжении 3 дней питаться листьями растений и цветов или 3 дня ходить в водолазном костюме? Голосуйте одновременно, те, кто окажется в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"За или против какать бананами 4 дня в день? Голосуйте одновременно, те, кто окажется в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: выпить шот мочи или слюней? Голосуйте одновременно, те, кто окажется в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: лизнуть ан*с собаки или отс*сать ей? Голосуйте одновременно, те, кто окажется в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: сесть на член и съесть пирог или сесть на пирог и сделать минет? Голосуйте одновременно. Те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: лишиться своих гениталий или набрать 150 кг? Голосуйте одновременно. Те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: лизнуть попу соседа справа или слева? Голосуйте одновременно. Те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: иметь ножи вместо пальцев или леденцы? Голосуйте одновременно. Те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: что бы воняло от вас, но вы этого не чувствовали, или, что бы воняло от всех вокруг? Голосуйте одновременно. Те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: писаться на публике раз в неделю или раз в неделю обкакаться, пока никто не видит? Голосуйте одновременно. Те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Что бы вы выбрали: носить чужое грязное белье или пользоваться чужой зубной щеткой? Голосуйте одновременно. Те, кто в меньшинстве, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"14",text:"Те, кто когда-нибудь оставлял презерватив внутри своей партнерши, делают $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"У каждого игрока есть винтовка с тремя пулями. Когда вы стреляете в другого игрока, он делает 1 глоток. Играем до конца вечера ",key:"beretta",parent_key:"",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s ты получил еще $ пули!",key:"",parent_key:"beretta",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s украл все пули у %s!",key:"",parent_key:"beretta",pack_name:"silly",language:"ru",nb_players:"2"},
{cycle_state:"false",type:"23",text:"%s, ты получил еще одну полностью заряженную пушку! ",key:"",parent_key:"beretta",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Каждый игрок должен рыгнуть. Тот, ко не сможет, делает $ глотка(ов), %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Каждый игрок должен назвать цифру от 1 до 10. Продолжение следует... %s начинает",key:"gold-number",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Те, кто выбрал четную цифру, делают $ глотка(ов)",key:"",parent_key:"gold-number",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Все игроки должны сделать столько глотков, какую цифру они выбрали ",key:"",parent_key:"gold-number",pack_name:"silly",language:"ru",nb_players:"0"},
{cycle_state:"false",type:"23",text:"Каждый игрок решает, кому пить то количество глотков, которое он выбрал. %s начинает",key:"",parent_key:"gold-number",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s встает на четвереньки, и каждый игрок должен его шлепнуть  ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Каждый делает по 2 глотка и описывают самую ужасную сцену из порно фильма, которую он когда-либо видел. %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s делает 1 глоток, игрок справа от него делает 2 глотка, следующий игрок справа делает 3 глотка и т.д., пока очередь не дойдет до %s ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"4"},
{cycle_state:"false",type:"23",text:"Каждый делает столько глотков, сколько раз он писал сегодня. %s начинает",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Каждый игрок по очереди должен назвать количество гласных букв в своем имени. %s начинает. Тот, кто не сможет ответить, делает $ глотка(ов). ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, начинай пить. Игрок слева от тебя тоже должен начать пить, и так дальше по очереди. Нельзя останавливаться, пока не остановится игрок справа от тебя",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"Выберете вместе прозвище для %s. До конца игры все обращаются к нему/ней по придуманному прозвищу",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, скажи любую фразу с набитым ртом. Первый, кто угадает, решит, кому делать $ глотка(ов)",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"},
{cycle_state:"false",type:"23",text:"%s, закрой глаза. Игроки делают для тебя коктейль, если ты угадаешь, из чего он состоит, ты решаешь, кому делать $ глотка(ов). Если не угадаешь, делаешь $ ",key:"",parent_key:"",pack_name:"silly",language:"ru",nb_players:"1"}]);
retrieveDB();