game.stored_db.weakest_link_fr = [
    {type:"1",text:"De quel bonnet? Quoi fait-on? Autrefois la tête des mauvais élèves ?",answer:"Le bonnet d'âne",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel mot commençant par la lettre k désigne un avertisseur sonore sur une automobile?",answer:"Le klaxon",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Sur quel célèbre avenue de Paris défile traditionnellement les militaire le jour du 14 juillet?",answer:"Les champs-élysées?",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Dans le film de Yves Robert, un éléphant ça trompe un peu, énormément ou pas du tout?",answer:"Énormément",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel mot désigne à la fois une plante de la famille des malvacées et un violet pâle ?",answer:"Mauve",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Compléter le titre de cette chanson créé par le grand orchestre du Splendid : La salsa...",answer:"... du démon",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Les pronom personnel. Quelle est la troisième personne du pluriel?",answer:"Ils",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Qu'elle est donnée le nom de la terre appartenant à la seigneurie du vicomte ?",answer:"Une vicomté",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Chez l'homme le foie est-il normalement situé à droite ou à gauche dans l'abdomen?",answer:"À droite",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel mot commençant par un C désigner un voyage d'agrément sur un paquebot?",answer:"Une croisière",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Dans le calendrier laïque occidentale combien de mois compte au moins 30 jours?",answer:"11",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle est la spécialité culinaire on déguste en raclant un morceau de fromage ramolli par la chaleur ?",answer:"La raclette",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Selon l'expression familière devant quel endroit faut-il balayer avant de critiquer les autres?",answer:"Sa porte",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Le caribou est un animal voisin du hibou vrai ou faux?",answer:"Faux",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Lors de la finale de la coupe du monde de football de 1998, qui inscrivit le premier but pour l'équipe de France?",answer:"Zinédine Zidane",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel mot commençant par la lettre i et le contraire du mot barbu?",answer:"Imberbe",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"À quel roi de France attribue-t-on la phrase : « l'état c'est moi » Louis XIII, Louis XIV ou Louis XV?",answer:"Louis XIV",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle est la langue officielle de l'autriche ?",answer:"L'allemand",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle pâte alimentaire d'origine italienne dont le nom commence par T a une forme de ruban plat ?",answer:"La tagliatelle",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel adjectif qualifie une randonnée qui se pratique à cheval ?",answer:"Équestre",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Si la mère de Toto à trois fils et pas de fille. Combien Toto a-t-il de frère?",answer:"2",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"On l'a parfois bien pendu et on la tire en ouvrant la bouche pour narguer quelqu'un, de quoi s'agit-il?",answer:"La langue",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Lors de la campagne 2000-2001, combien de bénévoles ont travaillé pour les restos du cœur en France ? 4000 ou 40000?",answer:"40000",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"En en formule 1, quel mot français désigne l'ensemble personne travaillant dans une même équipe?",answer:"Une écurie",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel accessoire pointu utiliser généralement par paire est indispensable pour tricoter?",answer:"Des aiguilles",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est le nom de l'ensemble constitué par les populations francophone dans le monde?",answer:"La francophonie",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Dans les aventures de Lucky Luck: Joe, Jack, Williams et Avrel sont cousins ou frères?",answer:"Frères",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Sylvie, quelle sorte de pain dont le nom commence par un b est devenu un des symboles de la France ?",answer:"La baguette",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est le nom des habitants de Montpellier chef-lieu de l'Hérault ? Les Montpelliérains",answer:"",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel mot composé emprunter à l'anglais désigne le ballon dans le rugby dans lequel les boxeurs frappent pour s'entraîner?",answer:"Le Punching-ball",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel verbe désigne l'action de dépouiller un fil électrique d'une partie de son isolant ?",answer:"Dénuder",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Le tapir est un animal qui se nourrit de fourmis?",answer:"Faux (herbivore)",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Si 4 enfants se partagent équitablement 44 bonbons combien chacun en aura-t-il?",answer:"11",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Traditionnellement, les taxis de New York sont connus pour leur couleur bien visible, laquelle ?",answer:"Jaune",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"À quel héros de roman feuilleton fais ton référence lorsqu'on évoque une aventure rocambolesque?",answer:"Rocambol",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"En 1980, Francis Cabrel chante l'encre de...",answer:"...Tes yeux",pack_name:"weakest_link",language:"fr"},
    // {type:"1",text:"Quel type de carburant utilise-t-on pour faire fonctionner un moteur diesel, du diesel ou du GPL?",answer:"Du gazole",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Comment se nomme le professionnel charger de la projection des films dans un cinéma ?",answer:"Un projectionniste",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est le plus grand continent du monde ?",answer:"L'Asie",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle est la capitale de l'Espagne ?",answer:"Madrid",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Qui a écrit \"Romeo et Juliette\" ?",answer:"William Shakespeare",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle est la planète la plus proche du soleil ?",answer:"Mercure",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Combien de joueurs y a-t-il dans une équipe de football ?",answer:"11",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est le symbole chimique de l'oxygène ?",answer:"O",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Qui a peint la Joconde ?",answer:"Leonardo da Vinci",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle est la monnaie du Japon ?",answer:"Le yen",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est le plus long fleuve du monde ?",answer:"Le Nil",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est le nom du satellite naturel de la Terre ?",answer:"La Lune",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est le gaz le plus abondant dans l'atmosphère terrestre ?",answer:"L'azote",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Qui a écrit \"Les Misérables\" ?",answer:"Victor Hugo",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est l'élément chimique le plus léger ?",answer:"L'hydrogène",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle est la première lettre de l'alphabet ?",answer:"A",pack_name:"weakest_link",language:"fr"},
    // {type:"1",text:"Quelle est la couleur du drapeau français ?",answer:"Bleu, blanc, rouge",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est le pays le plus peuplé du monde ?",answer:"La Chine",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Qui a découvert la gravité en observant une pomme tomber d'un arbre ?",answer:"Isaac Newton",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle est la distance approximative entre la Terre et la Lune ?",answer:"Environ 384 400 kilomètres",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est le plus haut sommet du monde ?",answer:"L'Everest",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle est la date de la fête de Noël ?",answer:"Le 25 décembre",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Qui a écrit \"Hamlet\" ?",answer:"William Shakespeare",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle est la capitale de la France ?",answer:"Paris",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle est la plus grande planète du système solaire ?",answer:"Jupiter",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle est la deuxième planète du système solaire à partir du soleil ?",answer:"Vénus",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est le symbole chimique de l'or ?",answer:"Au",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Qui a peint \"La Nuit étoilée\" ?",answer:"Vincent van Gogh",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle est la monnaie des États-Unis ?",answer:"Le dollar",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est le désert le plus grand du monde ?",answer:"Le Sahara",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle est la distance approximative entre la Terre et le soleil ?",answer:"Environ 149,6 millions de kilomètres",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est le gaz responsable du réchauffement climatique ?",answer:"Le dioxyde de carbone (CO2)",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Qui a écrit \"Don Quichotte\" ?",answer:"Miguel de Cervantes",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est l'élément chimique le plus abondant dans l'univers ?",answer:"L'hydrogène",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle est la dernière lettre de l'alphabet ?",answer:"Z",pack_name:"weakest_link",language:"fr"},
    // {type:"1",text:"Quelle est la couleur du drapeau américain ?",answer:"Rouge, blanc, bleu",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est le pays le moins peuplé du monde ?",answer:"Le Vatican",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Dans blanche neige, quel nain porte un nom décrivant sa bonne humeur?",answer:"Joyeux",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel est le point culminant de la France?",answer:"Le Mont Blanc",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle épée est l'un des deux symboles de la justice?",answer:"Le glaive",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle heure de l'après-midi à donner son nom au traditionnel goûter des enfants?",answer:"4 heure",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Dans les horoscopes, quel signe du zodiaque débute l'année astrologique?",answer:"Bélier",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"A combien de litres correspondent 1m³ d'eau?",answer:"1000L",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel chauffeur de taxi au foulard à pois rouge vit au pays des jouets?",answer:"Oui-Oui",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Sur un distributeur de confiserie en panne que signifie le signe \"HS\"?",answer:"Hors service",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel nom enfantin du cheval désigne aussi un passe-temps?",answer:"Dada",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Sous quel nom le roi Louis IX apparaît sur le calendrier?",answer:"Saint Louis",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Complétez ce slogan: \"Métro, Boulot, ...\"",answer:"Dodo",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quelle chanteuse est la mère de Thomas Dutronc?",answer:"Françoise Hardy",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Au cinéma quel petit héros africain de dessin animé n'est pas grand mais vaillant?",answer:"Kirikou",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"En géométrie quel mot de 4 lettres désigne la superficie d'un carrée?",answer:"L'aire",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Dans une fête d'anniversaire pour enfants, qu'est-ce qui peut être de baudruche?",answer:"Un ballon",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"D'après son nom, quelle est la durée du contrat de travail appelé CDI",answer:"Indéterminé",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel célèbre musée Parisiens est considéré comme le plus grand musée du monde?",answer:"Le Louvre",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"En 1978, quel insecte de dessin animé est Maya?",answer:"Une abeille",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel adjectif qualifie l'acier résistant à la rouille?",answer:"Inoxydable",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel nom évoquant Noël désigne une garderie?",answer:"Une crèche",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Combien 5 Km font-ils de mètres?",answer:"5000",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel mot désigne à la fois la rétribution d'un artiste et l'emprunte posé sur un timbre par la poste?",answer:"Un cachet",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel mot anglais désigne couramment le commandant de bord d'un yacht ou le barreur d'un voilier de course?",answer:"Skipper",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Le recensement est une opération qui consiste à dénombrer la population d'un pays, vrai ou faux?",answer:"Vrai",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel mot commençant par \"H\" désigne l'appareil qui permet de payer le stationnement sur la voie publique?",answer:"Un horodateur",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Dans l'enseignement professionnel francais, quel établissement est désigné par les lettres \"LP\"?",answer:"Lycée professionnel",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"EN 1995 quel province du Canada vote non à sa propre indépendance pour la deuxième fois de son histoire?",answer:"Le Québec",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"A quelle période associe-t-on le mouvement hippie? 1930, 1950 ou 1970?",answer:"1970",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Compléter en un mot les paroles de cette chanson de Charles Trenet: \"Douce France, cher pays de mon...",answer:"... enfance\"",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"En anglais quel pièce du logement est désigné par le mot \"bedroom\"?",answer:"La chambre",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Selon le proverbe: \"Qui aime bien...",answer:"... châtie bien.\"",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Au scrabble français combien de jeton porte la lettre \"Y\"",answer:"1",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"En France, le président de la république à le droit de parler à la tribune de l'assemblée nationale vrai ou faux?",answer:"Faux",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"En 1967, selon le titre du film, sur quel planète est retenu Charlton Heston?",answer:"La planète des singes",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel nom désignant autrefois un commerce d'épice est aujourd'hui un magasin d'alimentation",answer:"Une épicerie",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"En mythologie, quelle divinité romaine est assimilée à la déesse grec Aphrodite?",answer:"Vénus",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"En Provence, comment s'appelle les gorges qui vont de Castellane au lac de Sainte Croix?",answer:"Gorges du Verdon",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Le liège est un matière imperméable vrai ou faux?",answer:"Vrai",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Dans le langage familier quand vous faites la tambouille s'agit-il du ménage, de la cuisine ou du repassage?",answer:"La cuisine",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Au judo, après la ceinture blanche, accède-t-on à la ceinture jaune ou à la verte?",answer:"Jaune",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Dans la version française de \"Chicken Run\" quel est le nom du coq ancien combattant dans l'armée de l'air?",answer:"\"Colonel\"",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Quel instrument de musique peut-être de coeur dans une église ou de barbarie dans la rue?",answer:"Un orgue",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"Le cacatoes est-il un singe ou un perroquet?",answer:"un perroquet",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"L'agent du trésor chargé du recouvrement des impôts est un précepteur vrai ou faux?",answer:"Faux (percepteur)",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"En 1978, sous quel nom Roger JOURE se fait-il connaître avec le tube \"Ça plane pour moi\"?",answer:"Plastic Bertrand",pack_name:"weakest_link",language:"fr"},
    {type:"1",text:"De quel hormone associé au stress dit-on que l'ont subie une poussé quand l'on s'emporte?",answer:"Adrénaline",pack_name:"weakest_link",language:"fr"}];
game.pending_db = game.pending_db.concat(game.stored_db.weakest_link_fr);